SET DEFINE OFF;
CREATE OR REPLACE FUNCTION fn_check_qtty_1414(p_CRPHYSAGREEID varchar2) return number is
  v_Result number;
begin
  select nvl(hd.qtty - nvl(nh.QTTY_NHAP,0) + nvl(RUT.QTTY_RUT,0)   + nvl(b.QTTY_BAN,0) - nvl(NHl.QTTY_NHAPLAI,0),0) into v_Result
    from
            CRPHYSAGREE hd,
            (SELECT CRPHYSAGREEID,SUM(QTTY)QTTY_NHAP FROM CRPHYSAGREE_LOG WHERE TYPE ='R'  GROUP BY CRPHYSAGREEID)NH ,
            (SELECT CRPHYSAGREEID,SUM(ICQTTY)QTTY_NHAPLAI FROM CRPHYSAGREE_WITHDRAW_LOG where type = 'IC'  GROUP BY CRPHYSAGREEID)NHl,
            (SELECT CRPHYSAGREEID,SUM(WDQTTY)QTTY_RUT FROM CRPHYSAGREE_WITHDRAW_LOG where type = 'WD'  GROUP BY CRPHYSAGREEID)RUT,
            (SELECT CRPHYSAGREEID,nvl(sum(qtty),0) QTTY_BAN fROM CRPHYSAGREE_LOG_ALL WHERE TLTXCD = '1403' GROUP BY CRPHYSAGREEID)B
    where   hd.CRPHYSAGREEID = nh.CRPHYSAGREEID(+)
        and hd.CRPHYSAGREEID = NHl.CRPHYSAGREEID(+)
        and hd.CRPHYSAGREEID = b.CRPHYSAGREEID(+)
        and hd.CRPHYSAGREEID = RUT.CRPHYSAGREEID(+)
        and hd.CRPHYSAGREEID = p_CRPHYSAGREEID
    ;
  return(v_Result);
end fn_check_qtty_1414;



-- End of DDL Script for Function HOSTSHVTEST.FN_CHECK_QTTY_1414
/
