SET DEFINE OFF;
CREATE OR REPLACE FUNCTION fn_cidatedepofeeacr(strCLOSETYPE in varchar2,strCUSTODYCD IN varchar2, strAFACCTNO in varchar2, strNumDATE IN  NUMBER)
  RETURN  number
  IS

  v_Result  number(20);
BEGIN

    if strCLOSETYPE = '001' then
        SELECT nvl(sum(nvl(FEEACR,0)),0)
        INTO v_Result
        FROM CFMAST CF, AFMAST AF,
            (SELECT A2.AFACCTNO,
                SUM(DECODE(A2.FORP,'P',A2.FEEAMT/100,A2.FEEAMT)*A2.SEBAL*strNumDATE/(A2.LOTDAY*A2.LOTVAL)) FEEACR
                FROM (SELECT T.ACCTNO, MIN(T.ODRNUM) RFNUM FROM VW_SEMAST_VSDDEP_FEETERM T GROUP BY T.ACCTNO) A1,
                VW_SEMAST_VSDDEP_FEETERM A2 WHERE A1.ACCTNO=A2.ACCTNO AND A1.RFNUM=A2.ODRNUM GROUP BY A2.AFACCTNO) T2
        WHERE CF.custid = af.custid and af.acctno = T2.AFACCTNO AND CF.CUSTODYCD = strCUSTODYCD;
    else
        SELECT nvl(sum(nvl(FEEACR,0)),0)
        INTO v_Result
        FROM (SELECT A2.AFACCTNO,
                SUM(DECODE(A2.FORP,'P',A2.FEEAMT/100,A2.FEEAMT)*A2.SEBAL*strNumDATE/(A2.LOTDAY*A2.LOTVAL)) FEEACR
                FROM (SELECT T.ACCTNO, MIN(T.ODRNUM) RFNUM FROM VW_SEMAST_VSDDEP_FEETERM T GROUP BY T.ACCTNO) A1,
                VW_SEMAST_VSDDEP_FEETERM A2 WHERE A1.ACCTNO=A2.ACCTNO AND A1.RFNUM=A2.ODRNUM GROUP BY A2.AFACCTNO) T2
        WHERE T2.AFACCTNO = strAFACCTNO;
    end if;

    RETURN v_result;
EXCEPTION
WHEN OTHERS
   THEN

      RETURN 0;
END fn_cidatedepofeeacr;

/
