SET DEFINE OFF;
CREATE OR REPLACE FUNCTION FN_CHECK_DEVIDENTRATE_CA024(P_CATYPE VARCHAR2, P_TYPERATE VARCHAR2, P_DEVIDENTRATE NUMBER) RETURN VARCHAR2 IS

BEGIN
    IF TRIM(P_CATYPE) = '024' AND P_TYPERATE = 'R' AND P_DEVIDENTRATE <= 0 THEN
        RETURN 'FALSE';
    END IF;

    RETURN 'TRUE';
EXCEPTION WHEN OTHERS THEN
    RETURN 'FALSE';
END FN_CHECK_DEVIDENTRATE_CA024;
/
