SET DEFINE OFF;
CREATE OR REPLACE FUNCTION fn_check_custodycd_ddmast(P_CUSTID VARCHAR2) RETURN VARCHAR2 IS
    L_CUSTODYCD VARCHAR2(100);
BEGIN
    SELECT CUSTODYCD INTO L_CUSTODYCD FROM CFMAST WHERE CUSTID = P_CUSTID;
    IF L_CUSTODYCD IS NULL OR L_CUSTODYCD = '' THEN
        RETURN 'FALSE';
    END IF;
    RETURN 'TRUE';
EXCEPTION WHEN OTHERS THEN
    RETURN 'FALSE';
END FN_CHECK_CUSTODYCD_DDMAST;
/
