SET DEFINE OFF;
CREATE OR REPLACE FUNCTION FN_CHECKRATE_A_B(P_RATE VARCHAR2) RETURN VARCHAR2 IS
    L_LEFT VARCHAR(10);
    L_RIGHT VARCHAR(10);
BEGIN
    L_LEFT := SUBSTR(P_RATE, 1, INSTR(P_RATE,'/') - 1);
    L_RIGHT := SUBSTR(P_RATE, INSTR(P_RATE,'/') + 1);

    IF (TO_NUMBER(L_LEFT)/TO_NUMBER(L_RIGHT)) > 0 THEN
        RETURN 'TRUE';
    END IF;

    RETURN 'FALSE';
EXCEPTION WHEN OTHERS THEN
    RETURN 'FALSE';
END FN_CHECKRATE_A_B;
/
