SET DEFINE OFF;
CREATE OR REPLACE FUNCTION FN_EXECUTESQL2JSON (P_SQL VARCHAR2, P_LANGUAGE IN VARCHAR2) RETURN VARCHAR2
AS
    TYPE V_CURTYP IS REF CURSOR;
    C0 V_CURTYP;
    V_VALUE VARCHAR2(4000);
    V_SQL VARCHAR2(4000);
BEGIN
    V_VALUE := '';
    IF UPPER(NVL(P_LANGUAGE, 'VIE')) = 'VIE' THEN
        V_SQL := REPLACE(P_SQL,'<@CDCONTENT>','CDCONTENT');
        V_SQL := REPLACE(V_SQL,'<@TXDESC>','TXDESC');
    ELSE
        V_SQL := REPLACE(P_SQL,'<@CDCONTENT>','EN_CDCONTENT');
        V_SQL := REPLACE(V_SQL,'<@TXDESC>','EN_TXDESC');
    END IF;

    IF LENGTH(V_SQL) > 0 THEN

        OPEN C0 FOR UPPER(V_SQL);
        FETCH C0 INTO V_VALUE;
        CLOSE C0;

        V_VALUE := REPLACE(V_VALUE, 'LABEL":', 'label":');
        V_VALUE := REPLACE(V_VALUE, 'VALUE":', 'value":');
    END IF;
    RETURN V_VALUE;
EXCEPTION WHEN OTHERS THEN
    PLOG.ERROR('FN_EXECUTESQL2JSON ERR: ' || SQLERRM || ' TRACE: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE );
    RETURN '';
END;
/
