SET DEFINE OFF;
CREATE OR REPLACE FUNCTION fn_feecal_6639( PV_TRANSFERTYPE VARCHAR2,PV_CUSTODYCD IN VARCHAR2, PV_AMT NUMBER,PV_FEETYPE VARCHAR2)
RETURN NUMBER IS

     V_FEECD   VARCHAR2(30);
     V_FEEAMT NUMBER(20,4);
     V_NOTHING NUMBER;
     V_FEERATE NUMBER;
     V_CCYCD VARCHAR2(10);
     V_TAXAMT NUMBER(20,4);
     V_TAXRATE NUMBER;
     V_SUPEBANK VARCHAR2(10);
     V_SB VARCHAR2(10);
     V_VATRATE NUMBER;
BEGIN
    V_FEEAMT:=0;
    V_TAXAMT:=0;
    IF PV_TRANSFERTYPE = 'D' THEN
        BEGIN
            SELECT NVL(SUPEBANK,'N'), NVL(SBCHECK,'N') INTO V_SUPEBANK, V_SB FROM CFMAST WHERE CUSTODYCD = PV_CUSTODYCD AND STATUS NOT IN ('C');
        EXCEPTION WHEN OTHERS THEN
            V_SUPEBANK := 'N';
            V_SB := 'N';
        END;

        IF V_SUPEBANK = 'N' AND V_SB = 'N' THEN
            V_NOTHING := CSPKS_FEECALC.FN_CB_CITAD_CALC(PV_CUSTODYCD, PV_AMT, 0, V_FEECD, V_FEEAMT, V_FEERATE, V_CCYCD);
            V_NOTHING := CSPKS_FEECALC.FN_TAX_CALC(PV_CUSTODYCD, V_FEEAMT, V_CCYCD, V_FEECD, 2, V_TAXAMT, V_VATRATE);
        ELSE
            V_NOTHING:=CSPKS_FEECALC.FN_TRANSFER_CALC(PV_CUSTODYCD, PV_AMT,0, V_FEECD, V_FEEAMT , V_FEERATE, V_CCYCD);
            BEGIN
                SELECT ROUND(TO_NUMBER(VATRATE)*V_FEEAMT/100) INTO V_TAXAMT
                FROM FEEMASTER WHERE REFCODE='OTHER' AND SUBTYPE='004' AND CCYCD = 'VND';
            EXCEPTION WHEN OTHERS THEN
                V_TAXAMT:=0;
            END;
        END IF;

        IF PV_FEETYPE = '3' THEN
            RETURN V_FEEAMT + V_TAXAMT;
        ELSIF PV_FEETYPE = '1' THEN --1: PHI NGOAI
            RETURN V_FEEAMT + V_TAXAMT;
        ELSE
            RETURN 0;
        END IF;
    ELSE
        RETURN 0;
    END IF;


EXCEPTION WHEN OTHERS THEN
    PLOG.ERROR ('FN_FEECAL_6639: ' || SQLERRM || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    RETURN 0;
END;
/
