SET DEFINE OFF;
CREATE OR REPLACE
FUNCTION fn_get_flmsgmap_subval(PV_REQID NUMBER, PV_REFAUTOID NUMBER, PV_ISSUBHEADER VARCHAR2) RETURN VARCHAR2 IS
    CONST_FORMATDATE CONSTANT VARCHAR2(10) := 'RRRR-MM-DD';
    V_JSON VARCHAR2(4000);
BEGIN

    V_JSON := '{';
    FOR REC_FLMSGMAP IN (
        SELECT M.*, NVL(CRB.CVAL, CRB.NVAL) VALUE
        FROM
        (
            SELECT * FROM FLMSGMAP WHERE REFAUTOID = PV_REFAUTOID AND ISSUBHEADER = PV_ISSUBHEADER ORDER BY AUTOID
        ) M
        LEFT JOIN (
            SELECT REQID, FLDNAME, CVAL, NULL NVAL
            FROM (
                SELECT REQID,OBJTYPE,OBJNAME,TRFCODE,REQCODE,
                       OBJKEY,TO_CHAR(TXDATE,CONST_FORMATDATE) TXDATE,BANKCODE,BANKACCT,AFACCTNO,
                       TO_CHAR(TXAMT) TXAMT,NOTES,STATUS,REFTXNUM,TO_CHAR(REFTXDATE,CONST_FORMATDATE) REFTXDATE,
                       REFVAL,TO_CHAR(AFFECTDATE,CONST_FORMATDATE) AFFECTDATE,ERRORCODE,TO_CHAR(CREATEDATE,CONST_FORMATDATE) CREATEDATE,GRPREQID,
                       VIA,RBANKACCOUNT,RBANKNAME,RBANKCITAD,RBANKACCNAME,
                       TRNREF,ERRORDESC,PSTATUS,UNHOLD,REPVAL,
                       CURRENCY,REQTXNUM,DORC,TO_CHAR(FEEAMT) FEEAMT,TO_CHAR(TAXAMT) TAXAMT,
                       FEECODE,FEETYPE,TO_CHAR(EXCHANGERATE) EXCHANGERATE,TO_CHAR(EXCHANGEVALUE) EXCHANGEVALUE,TOCURRENCY,
                       FEENAME,BRANCH,TO_CHAR(BUSDATE,CONST_FORMATDATE) BUSDATE,DESBANKACCOUNT,TRN_DT
                FROM CRBTXREQ
            )
            UNPIVOT (
              CVAL FOR FLDNAME IN (
                    OBJTYPE,OBJNAME,TRFCODE,REQCODE,OBJKEY,
                    TXDATE,BANKCODE,BANKACCT,AFACCTNO,TXAMT,
                    NOTES,STATUS,REFTXNUM,REFTXDATE,REFVAL,
                    AFFECTDATE,ERRORCODE,CREATEDATE,GRPREQID,VIA,
                    RBANKACCOUNT,RBANKNAME,RBANKCITAD,RBANKACCNAME,TRNREF,
                    ERRORDESC,PSTATUS,UNHOLD,REPVAL,CURRENCY,
                    REQTXNUM,DORC,FEEAMT,TAXAMT,FEECODE,
                    FEETYPE,EXCHANGERATE,EXCHANGEVALUE,TOCURRENCY,FEENAME,
                    BRANCH,BUSDATE,DESBANKACCOUNT,TRN_DT
                )
            ) U
            WHERE REQID = PV_REQID

            UNION ALL

            SELECT REQID, FLDNAME, CVAL, NVAL FROM CRBTXREQDTL WHERE REQID = PV_REQID
        ) CRB ON CRB.FLDNAME = M.FRFIELD)
    LOOP
        IF REC_FLMSGMAP.ISSUBVAL = 'N' THEN
            IF REC_FLMSGMAP.VALUE IS NOT NULL
            THEN
                IF REC_FLMSGMAP.VALUETYPE = 'C'
                THEN
                    V_JSON := V_JSON || '"' || REC_FLMSGMAP.TOFIELD || '":' || '"' || TRANSFORM_PARAMETER_JSON(REC_FLMSGMAP.VALUE) ||'",';
                ELSE
                    V_JSON := V_JSON || '"' || REC_FLMSGMAP.TOFIELD || '":' || TRANSFORM_PARAMETER_JSON(REC_FLMSGMAP.VALUE) ||',';
                END IF;
            ELSE
                V_JSON := V_JSON || '"' || REC_FLMSGMAP.TOFIELD || '":"' || REC_FLMSGMAP.DEFAULTVALUE ||'",';
            END IF;
        ELSE
            V_JSON := V_JSON || '"' || REC_FLMSGMAP.TOFIELD || '":' || FN_GET_FLMSGMAP_SUBVAL(PV_REQID, PV_REFAUTOID, REC_FLMSGMAP.TOFIELD) || ',';
        END IF;
    END LOOP;

    V_JSON := V_JSON || '}';
    V_JSON := REPLACE(V_JSON,',}','}');
    V_JSON := TRANSFORM_JSON(V_JSON);


    RETURN V_JSON;

EXCEPTION WHEN OTHERS THEN
    RETURN '{}';
END;
/
