SET DEFINE OFF;
CREATE OR REPLACE FUNCTION FN_GET0088ACCOUNT(P_CLOSETYPE IN VARCHAR2,P_CUSTODYCD IN VARCHAR2,P_AFACCTNO IN VARCHAR2)
    RETURN VARCHAR2 IS

    V_RESULT VARCHAR2(200);

BEGIN

IF P_CLOSETYPE = '001' THEN
    V_RESULT:= '|ALL' ;
ELSE
    SELECT  P_AFACCTNO INTO V_RESULT FROM dual;
END IF;


RETURN V_RESULT;
EXCEPTION
   WHEN OTHERS THEN
    RETURN '';
END;
/
