SET DEFINE OFF;
CREATE OR REPLACE FUNCTION FN_GET_MAXVALUEOFISSUE (PV_ISSUESID IN VARCHAR2, PV_AUTOID IN VARCHAR2)
RETURN NUMBER
IS
    V_VALUEOFISSUE_MAX NUMBER:=0;
    V_VALUEOFISSUE_OLD NUMBER:=0;
    V_RESULT NUMBER:=0;
    V_VALUEOFISSUE_EDIT   NUMBER;
    V_BONDISSUE_AUTOID    VARCHAR2(10):=NULL;
BEGIN
    --LAY VALUEOFISSUE CUA DOT PHAT HANH TRAI PHIEU
    SELECT VALUEOFISSUE INTO V_VALUEOFISSUE_MAX
    FROM ISSUES
    WHERE AUTOID = PV_ISSUESID;
    --TINH TONG VALUEOFISSUE HIEN TAI CUA ISSUECODE
    SELECT SUM(VALUEOFISSUE) INTO V_VALUEOFISSUE_OLD
    FROM (
          SELECT AUTOID ISSUESID,0 VALUEOFISSUE FROM ISSUES
          UNION ALL
          SELECT ISSUESID,VALUEOFISSUE FROM BONDISSUE
         )
    WHERE ISSUESID = PV_ISSUESID
    GROUP BY ISSUESID;
    --VALUEOFISSUE TOI DA CO THE PHAT HANH
    V_BONDISSUE_AUTOID := PV_AUTOID;
    IF V_BONDISSUE_AUTOID IS NULL THEN --TRUONG HOP: THEM MOI
        V_RESULT := (V_VALUEOFISSUE_MAX - V_VALUEOFISSUE_OLD);
    ELSE
            --TINH VALUEOFISSUE DA GAN VOI AUTOID
            SELECT VALUEOFISSUE INTO V_VALUEOFISSUE_EDIT
            FROM BONDISSUE
            WHERE AUTOID = TO_NUMBER(V_BONDISSUE_AUTOID);
            V_RESULT := (V_VALUEOFISSUE_MAX + V_VALUEOFISSUE_EDIT - V_VALUEOFISSUE_OLD);
    END IF;
    RETURN V_RESULT;
    EXCEPTION
    WHEN OTHERS THEN
    RETURN 0;
END;
/
