SET DEFINE OFF;
CREATE OR REPLACE FUNCTION FN_GET_TLLOGFLD_VALUE(PV_TXNUM VARCHAR2, PV_TXDATE DATE, PV_FLDCD VARCHAR2, PV_FLDTYPE CHAR DEFAULT 'N')
RETURN VARCHAR2
IS
V_VALUE VARCHAR2(1000);
BEGIN
    IF PV_FLDTYPE='N' THEN
        SELECT nvl(NVALUE,'0') INTO V_VALUE FROM vw_tllogfld_all WHERE TXNUM = PV_TXNUM AND TXDATE = PV_TXDATE AND FLDCD =PV_FLDCD;
        RETURN nvl(V_VALUE,'0');
    ELSE
        SELECT CVALUE INTO V_VALUE FROM vw_tllogfld_all WHERE TXNUM = PV_TXNUM AND TXDATE = PV_TXDATE AND FLDCD =PV_FLDCD;
        RETURN V_VALUE;
    END IF;

EXCEPTION WHEN OTHERS THEN
    IF PV_FLDTYPE='N' THEN
        RETURN '0';
    else
        return '';
    end if;
END;

 
 
 
 
 
 
 
 
 
 
 
 
/
