SET DEFINE OFF;
CREATE OR REPLACE FUNCTION fn_get_ccycd_1293(PV_FEEINPUT IN VARCHAR2,  PV_FEENAMEPRIVATE IN VARCHAR2)
RETURN varchar2
IS
  V_RESULT varchar2(250);
BEGIN

    V_RESULT:='VND';
    IF PV_FEEINPUT = '003' THEN
        SELECT CCYCD INTO V_RESULT  fROM CFFEEEXP WHERE AUTOID = PV_FEENAMEPRIVATE;
    END IF;

    RETURN V_RESULT;
    EXCEPTION WHEN OTHERS THEN RETURN 'VND';
END;
/
