SET DEFINE OFF;
CREATE OR REPLACE FUNCTION fn_get_feeamt_1293(PV_FEEINPUT IN VARCHAR2, PV_FEENAME IN VARCHAR2, PV_FEENAMEPRIVATE IN VARCHAR2,pv_feeamt varchar2)
RETURN NUMBER
IS
  V_RESULT NUMBER;
BEGIN

    V_RESULT:=0;
    if PV_FEEINPUT ='001' then
        V_RESULT:= pv_feeamt;
    end if;
    IF PV_FEEINPUT ='002' THEN
        SELECT FEEAMT INTO V_RESULT fROM FEEMASTER WHERE FEECD =PV_FEENAME;
    END IF;
    IF PV_FEEINPUT ='003' then
        SELECT feeval INTO V_RESULT fROM CFFEEEXP WHERE AUTOID =PV_FEENAMEPRIVATE;
    END IF;
    RETURN V_RESULT;
    EXCEPTION WHEN OTHERS THEN RETURN 0;
END;
/
