SET DEFINE OFF;
CREATE OR REPLACE FUNCTION fn_get_info_fr_custodycd(P_CUSTODYCD IN VARCHAR2,P_KEYVALUE IN VARCHAR2)
    RETURN varchar2 IS
    V_RESULT varchar2(4000);
    V_CUSTODYCD varchar2(50);
BEGIN
    SELECT fn_get_custodycd_fr_childfund(P_CUSTODYCD) into V_CUSTODYCD from dual;
    IF P_KEYVALUE ='STC' THEN
        SELECT (CASE WHEN COUNTRY ='234' THEN SUBSTR(CUSTODYCD,5,6) ELSE TRADINGCODE END) STC INTO V_RESULT
        FROM CFMAST WHERE CUSTODYCD=V_CUSTODYCD;
    ELSE
        SELECT FULLNAME INTO V_RESULT
        FROM CFMAST WHERE CUSTODYCD=V_CUSTODYCD;
    END IF;
RETURN TRIM(V_RESULT);
EXCEPTION
   WHEN OTHERS THEN
    RETURN '';
END;
/
