SET DEFINE OFF;
CREATE OR REPLACE FUNCTION fn_getfeeclose0088
    RETURN NUMBER IS

    V_RESULT NUMBER;
    P_FEETYPE VARCHAR2(100);

BEGIN
    V_RESULT:=0;
    SELECT FE.FEECD into P_FEETYPE
        FROM FEEMASTER FE, FEEMAP FM WHERE FE.FEECD = FM.FEECD AND FM.TLTXCD ='0088';

    select feeamt into V_RESULT
    from feemaster where feecd= P_FEETYPE;


RETURN V_RESULT;
EXCEPTION
   WHEN OTHERS THEN
    RETURN 0;
END;
/
