SET DEFINE OFF;
CREATE OR REPLACE FUNCTION fn_get_feecode(P_REFCODE IN VARCHAR2, P_SUBTYPE IN VARCHAR2)
RETURN VARCHAR2
IS --NAM.LY 20/03/2020
  V_FEECODE VARCHAR2(20);
BEGIN
     SELECT CDCONTENT
     INTO V_FEECODE
     FROM ALLCODE
     WHERE CDTYPE ='SA' AND
           CDNAME ='FEECODE' AND
           CDVAL = (SELECT EN_CDCONTENT FROM ALLCODE WHERE CDNAME = P_REFCODE AND CDVAL = P_SUBTYPE AND CDTYPE ='SA');
    RETURN V_FEECODE;
    EXCEPTION WHEN OTHERS THEN RETURN NULL;
END;
/
