SET DEFINE OFF;
CREATE OR REPLACE FUNCTION fn_getTRFACINV (PV_BR IN VARCHAR2)RETURN VARCHAR2
IS
   l_Return VARCHAR2(10) := '1';
BEGIN

    SELECT  NVL(MAX(ODR)+1,1) AUTOINV
    INTO l_Return
    FROM
        (SELECT ROWNUM ODR, INVACCT
        FROM (SELECT AUTOID INVACCT FROM CRBTRFACCTSRC ORDER BY AUTOID) DAT
        WHERE TO_NUMBER(INVACCT)=ROWNUM) INVTAB;
    RETURN LPAD(l_Return,4,'0');
EXCEPTION
  WHEN OTHERS THEN
       RAISE_APPLICATION_ERROR(-20001,SQLERRM);
END;

 
 
 
 
 
 
 
 
 
 
 
 
/
