SET DEFINE OFF;
CREATE OR REPLACE FUNCTION fn_get_feename(P_REFCODE IN VARCHAR2, P_SUBTYPE IN VARCHAR2)
RETURN VARCHAR2
IS
/*========================================================*/ 
--CREATER                               DATETIME
--THUNT                                 26/03/2020
/*========================================================*/ 
  V_FEECODE VARCHAR2(20);
  V_FEECSTD VARCHAR2(1000);
BEGIN
     SELECT CDCONTENT
     INTO V_FEECODE
     FROM ALLCODE
     WHERE CDTYPE ='SA' AND
           CDNAME ='FEECODE' AND
           CDVAL = (SELECT EN_CDCONTENT FROM ALLCODE WHERE CDNAME = P_REFCODE AND CDVAL = P_SUBTYPE AND CDTYPE ='SA');
           
    SELECT CDCONTENT INTO V_FEECSTD FROM ALLCODE WHERE CDNAME='FEECODES' AND CDTYPE='SA' AND CDVAL=V_FEECODE;       
    RETURN V_FEECSTD;
EXCEPTION 
WHEN OTHERS THEN 
RETURN NULL;
END;
/
