SET DEFINE OFF;
CREATE OR REPLACE FUNCTION fn_get_netamount_1400(P_TAXABLEPARTY VARCHAR2, P_SALEVALUE NUMBER, P_VAT NUMBER) 
RETURN NUMBER IS
    V_RESULT       NUMBER;
BEGIN
    IF (P_TAXABLEPARTY = '001') THEN --BEN MUA CHIU THUE -> SO TIEN TT = GIA TRI BAN, HACH TOAN THUE CHO BEN MUA
        V_RESULT := P_SALEVALUE;
    ELSIF (P_TAXABLEPARTY = '002') THEN --BEN BAN CHIU THUE -> SO TIEN TT = GIA TRI BAN + THUE, HACH TOAN THUE CHO BEN BAN
        V_RESULT := P_SALEVALUE + P_VAT;
    END IF;
    RETURN V_RESULT;
END FN_GET_NETAMOUNT_1400;
/
