SET DEFINE OFF;
CREATE OR REPLACE FUNCTION fn_net_amount(PV_FEETYPE VARCHAR2, PV_AMT NUMBER, PV_FEEAMT NUMBER)
RETURN NUMBER IS
    V_NETAMT NUMBER(20,4);
BEGIN
    V_NETAMT := 0;

    IF PV_FEETYPE = '3' THEN --3: PHI TRONG
        V_NETAMT := PV_AMT - PV_FEEAMT;
    ELSIF PV_FEETYPE = '1' THEN --1: PHI NGOAI
        V_NETAMT := PV_AMT;
    ELSE
        V_NETAMT := PV_AMT;
    END IF;
    RETURN V_NETAMT;

EXCEPTION WHEN OTHERS THEN
    PLOG.ERROR ('FN_NET_AMOUNT: ' || SQLERRM || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    RETURN 0;
END;
/
