SET DEFINE OFF;
CREATE OR REPLACE FUNCTION TRANSFORM_JSON(PV_DATA IN VARCHAR2) RETURN  VARCHAR2 IS
    L_JSON VARCHAR2(4000);
BEGIN
    L_JSON := REPLACE(PV_DATA, '\', '\\');
    RETURN L_JSON;
EXCEPTION WHEN OTHERS THEN
    PLOG.ERROR ('TRANSFORM_JSON ERROR' || SQLERRM || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    RETURN PV_DATA;
END;
/
