SET DEFINE OFF;DELETE FROM VSDTXMAPEXT WHERE 1 = 1 AND NVL(OBJNAME,'NULL') = NVL('3358','NULL');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3358', '542.NEWM.CLAS//CORP.STCO//DLWM', 'TXDATE', 'D', '<$BUSDATE>', NULL, 'Ngày tạo yêu cầu', 'Preparation Date', NULL, 'N', 0);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3358', '542.NEWM.CLAS//CORP.STCO//DLWM', 'CUSTODYCD', 'C', '$81', 'SELECT CUSTODYCD FROM VW_CFMAST_M WHERE CUSTODYCD_ORG = ''<$FILTERID>''', 'Tài khoản lưu ký', 'Custody code', NULL, 'N', 1);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3358', '542.NEWM.CLAS//CORP.STCO//DLWM', 'FULLNAME', 'C', '$81', 'select fullname from cfmast where custodycd IN (SELECT CUSTODYCD FROM VW_CFMAST_M WHERE CUSTODYCD_ORG = ''<$FILTERID>'')', 'Tên đầy đủ nhà đầu tư', 'Full name', 'C', 'N', 2);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3358', '542.NEWM.CLAS//CORP.STCO//DLWM', 'CAMASTID', 'C', '$02', 'select nvl(vsdid,0) CAMASTID from camast where camastid = ''<$FILTERID>''', 'Số hiệu THQ tham chiếu', 'Reference corporate action code', NULL, 'N', 2);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3358', '542.NEWM.CLAS//CORP.STCO//DLWM', 'SETTLEMENTDATE', 'D', '$01', 'select to_char(tl.busdate,''DD/MM/RRRR'') from catransfer ca, vw_tllog_all tl where ca.txdate = tl.txdate and ca.txnum=tl.txnum and ca.autoid = ''<$FILTERID>''', 'Ngày hạch toán', 'Settlement date', NULL, 'N', 3);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3358', '542.NEWM.CLAS//CORP.STCO//DLWM', 'UNIT', 'C', '$04', 'SELECT (CASE WHEN SECTYPE = ''006'' or SECTYPE = ''003'' THEN ''FAMT'' ELSE ''UNIT'' END) UNIT FROM SBSECURITIES WHERE SYMBOL=''<$FILTERID>''', 'Cổ phiếu/ Trái phiếu', 'Shares/ Bonds', NULL, 'N', 4);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3358', '542.NEWM.CLAS//CORP.STCO//DLWM', 'SYMBOL', 'C', '$04', NULL, 'Mã chứng khoán', 'Securities code', NULL, 'N', 4);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3358', '542.NEWM.CLAS//CORP.STCO//DLWM', 'IDCODE', 'C', '$81', 'select (case when idtype = ''009'' then tradingcode
            else idcode end) idcode
from cfmast where custodycd IN (SELECT CUSTODYCD FROM VW_CFMAST_M WHERE CUSTODYCD_ORG = ''<$FILTERID>'')', 'Loại giấy tờ', 'ID number', 'C', 'N', 5);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3358', '542.NEWM.CLAS//CORP.STCO//DLWM', 'VSDSTOCKTYPE', 'C', '$01', 'select vsdstocktype from catransfer where autoid = ''<$FILTERID>''', 'Loại chứng khoán', 'Type of securities', NULL, 'N', 5);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3358', '542.NEWM.CLAS//CORP.STCO//DLWM', 'QTTY', 'C', '$10', NULL, 'Số lượng', 'Quantity', NULL, 'N', 6);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3358', '542.NEWM.CLAS//CORP.STCO//DLWM', 'IDDATE', 'D', '$81', 'select (case when idtype = ''009'' then to_char(TRADINGCODEDT,''DD/MM/RRRR'')
            else to_char(IDDATE,''DD/MM/RRRR'') end) idcode
from cfmast where custodycd IN (SELECT CUSTODYCD FROM VW_CFMAST_M WHERE CUSTODYCD_ORG = ''<$FILTERID>'')', 'Ngày cấp', 'Issue date', 'C', 'N', 6);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3358', '542.NEWM.CLAS//CORP.STCO//DLWM', 'RECCODE', 'C', '$34', 'select biccode from deposit_member where depositid = ''<$FILTERID>''', 'TVLK bên nhận', 'The transferee DM', NULL, 'N', 7);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3358', '542.NEWM.CLAS//CORP.STCO//DLWM', 'RECCUSTODY', 'C', '$82', NULL, 'Số tài khoản bên nhận', 'Account of the transferee DM', NULL, 'N', 10);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3358', '542.NEWM.CLAS//CORP.STCO//DLWM', 'VSDCODE', 'C', '$04', 'select b.vsdbiccode
from sbsecurities sb, issuers i , vsdbiccode b
where sb.issuerid = i.issuerid
and i.vsdplace = b.vsdplace
and sb.symbol = ''<$FILTERID>''', 'VSD BICCODE', 'VSD BICCODE', 'C', 'N', 12);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3358', '542.NEWM.CLAS//CORP.STCO//DLWM', 'VSDBICCODE', 'C', '$01', 'SELECT d.biccode
from deposit_member d, sysvar s
where d.shortname = s.varvalue and s.varname = ''COMPANYSHORTNAME''', 'TVLK bên chuyển', 'The transferor DM', 'C', 'N', 12);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3358', '542.NEWM.CLAS//CORP.STCO//DLWM', 'TVLK', 'C', '$09', 'select (case when ''<$FILTERID>'' = ''Y'' then ''OWNI'' else ''OWNE'' end) TVLK from dual', 'Loại điện gửi lên VSD', 'Vsd message', 'C', 'N', 13);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3358', '542.NEWM.CLAS//CORP.STCO//DLWM', 'ALTERNATEID', 'C', '$81', 'select ( case when cf.idtype = ''001'' then ''IDNO''
         when cf.idtype = ''002'' then ''CCPT''
         when cf.idtype = ''005'' then ''CORP''
         when cf.idtype = ''009'' and cf.custtype = ''B'' then ''FIIN''
         when cf.idtype = ''009'' and cf.custtype = ''I'' then ''ARNU''
         else ''OTHR''
    end) ALTERNATEID
from cfmast cf
where cf.custodycd IN (SELECT CUSTODYCD FROM VW_CFMAST_M WHERE CUSTODYCD_ORG = ''<$FILTERID>'')', 'Loại hình cổ đông', 'Type of investor', 'C', 'N', 15);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3358', '542.NEWM.CLAS//CORP.STCO//DLWM', 'AUTONUMBER', 'C', '$01', 'SELECT LPAD(SEQ_VSDREQAUTOID.NEXTVAL,6,''0'') AUTONUMBER FROM DUAL', 'Số thứ tự của điện gửi trong phiên', 'EN:Số thứ tự của điện gửi trong phiên', 'C', 'N', 16);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3358', '542.NEWM.CLAS//CORP.STCO//DLWM', 'DESC', 'C', '$30', NULL, 'Diễn giải', 'Description', NULL, 'N', 30);COMMIT;