SET DEFINE OFF;DELETE FROM VSDTXMAPEXT WHERE 1 = 1 AND NVL(OBJNAME,'NULL') = NVL('3300','NULL');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3300', '567.NEWM.CAEV//RHTS/CANCEL', 'REF35B', 'C', 'SWIFTMSGMAPLOGDTL|USECU.35B.ISIN', '', 'Isin code', 'ISIN code', 'C', 'N', 3);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3300', '567.NEWM.CAEV//RHTS/CANCEL', 'REF36B', 'C', 'SWIFTMSGMAPLOGDTL|CAINST.36B.QINS', 'SELECT SUBSTR(''<$FILTERID>'',0,INSTR(''<$FILTERID>'',''/'')) || REPLACE(TO_CHAR(REPLACE(SUBSTR(''<$FILTERID>'',INSTR(''<$FILTERID>'',''/'') + 1),'','',''.''),''FM999999999999990.999999''),''.'','','') FROM DUAL', 'Số lượng chứng khoán đăng kí', 'Quantity', 'C', 'N', 3);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3300', '567.NEWM.CAEV//RHTS/CANCEL', 'REF97A', 'C', 'SWIFTMSGMAPLOGDTL|USECU.97A.SAFE', '', 'Mã KH tại ngân hàng', 'CIF ID', 'C', 'N', 3);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3300', '567.NEWM.CAEV//RHTS/CANCEL', 'REFELID', 'C', 'SWIFTMSGMAPLOGDTL|ACCTINFO.93B.ELIG', 'SELECT SUBSTR(''<$FILTERID>'',0,INSTR(''<$FILTERID>'',''/'')) || REPLACE(TO_CHAR(REPLACE(SUBSTR(''<$FILTERID>'',INSTR(''<$FILTERID>'',''/'') + 1),'','',''.''),''FM999999999999990.999999''),''.'','','') FROM DUAL', 'Tổng số lượng ', 'Balance', 'C', 'N', 3);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3300', '567.NEWM.CAEV//RHTS/CANCEL', 'REFID', 'C', 'SWIFTMSGMAPLOG|MSGID', '', 'Số hiện điện tham chiếu', 'Reference ID', 'C', 'N', 3);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3300', '567.NEWM.CAEV//RHTS/CANCEL', 'TRAD_DATA', 'C', 'SWIFTMSGMAPLOGDTL|TRADDET.98A.TRAD', '', 'Ngày giao dịch', 'Trade Date', 'C', 'N', 3);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3300', '567.NEWM.CAEV//RHTS/CANCEL', 'INBA', 'C', '<$TXNUM>', 'SELECT (CASE WHEN SB.SECTYPE IN (''001'',''002'',''008'',''011'') THEN ''UNIT/'' ELSE ''FAMT/'' END) || REPLACE(TO_CHAR(CS.QTTY,''FM999999999999990.999999''),''.'','','') INBA
FROM CAMAST CA, SBSECURITIES SB,
(
    SELECT TMP.CAMASTID, TMP.CUSTODYCD, SUM(TMP.QTTY) QTTY
    FROM
    (
        SELECT CAMASTID, CUSTODYCD, SUM(QTTY) QTTY FROM CACANCEL WHERE STATUS = ''P'' GROUP BY CAMASTID, CUSTODYCD
        UNION ALL
        SELECT CA.CAMASTID, CF.CUSTODYCD, SUM(BALANCE) QTTY
        FROM CASCHD CA, CFMAST CF, AFMAST AF
        WHERE CF.CUSTID = AF.CUSTID
        AND AF.ACCTNO = CA.AFACCTNO
        GROUP BY CA.CAMASTID, CF.CUSTODYCD
    )TMP
    GROUP BY TMP.CAMASTID, TMP.CUSTODYCD
) CS,
(
    SELECT MAX(CASE WHEN FLDCD = ''03'' THEN CVALUE ELSE '''' END) CAMASTID, MAX(CASE WHEN FLDCD = ''88'' THEN CVALUE ELSE '''' END)  CUSTODYCD
    FROM TLLOGFLD WHERE TXNUM =''<$FILTERID>''
) TL
WHERE CS.CAMASTID = TL.CAMASTID
AND CS.CUSTODYCD = TL.CUSTODYCD
AND CS.CAMASTID = CA.CAMASTID
AND CA.CODEID = SB.CODEID', 'Tổng số lượng ', 'Balance', 'C', 'N', 3);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3300', '567.NEWM.CAEV//RHTS/CANCEL', 'UNBA', 'C', '<$TXNUM>', 'SELECT (CASE WHEN SB.SECTYPE IN (''001'',''002'',''008'',''011'') THEN ''UNIT/'' ELSE ''FAMT/'' END) || REPLACE(TO_CHAR(CS.PBALANCE - NVL(CAN.QTTY,0),''FM999999999999990.999999''),''.'','','') INBA
FROM CAMAST CA, CASCHD CS, CFMAST CF, AFMAST AF, SBSECURITIES SB,
(
    SELECT CAMASTID, CUSTODYCD, SUM(QTTY) QTTY FROM CACANCEL WHERE STATUS = ''P'' GROUP BY CAMASTID, CUSTODYCD
) CAN,
(
    SELECT MAX(CASE WHEN FLDCD = ''03'' THEN CVALUE ELSE '''' END) CAMASTID, MAX(CASE WHEN FLDCD = ''88'' THEN CVALUE ELSE '''' END)  CUSTODYCD
    FROM TLLOGFLD WHERE TXNUM =''<$FILTERID>''
) TL
WHERE CS.AFACCTNO = AF.ACCTNO
AND AF.CUSTID = CF.CUSTID
AND CS.CAMASTID = TL.CAMASTID
AND CF.CUSTODYCD = TL.CUSTODYCD
AND CS.CAMASTID = CA.CAMASTID
AND CA.CODEID = SB.CODEID
AND TL.CAMASTID = CAN.CAMASTID(+)
AND TL.CUSTODYCD = CAN.CUSTODYCD(+) ', 'Tổng số lượng ', 'Balance', 'C', 'N', 3);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3300', '567.NEWM.CAEV//RHTS/CANCEL', 'DESCRIPTION', 'C', '<$TXNUM>', 'select max(case when fldcd = ''30'' then cvalue else '''' end)
       from tllogfld where txnum =''<$FILTERID>''', 'Diễn giải', 'Balance', 'C', 'N', 3);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3300', '567.NEWM.CAEV//RHTS/CANCEL', 'REF22F', 'C', '@LAPS', '', 'CAOP', 'CAOP', 'C', 'N', 3);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3300', '567.NEWM.CAEV//RHTS/CANCEL', 'CAEV', 'C', '@RHTS', '', 'CAEV', 'CAEV', 'C', 'N', 2);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3300', '567.NEWM.CAEV//RHTS/CANCEL', 'CAID', 'C', '$03', '', 'Mã sự kiện quyền', 'CA id', 'C', 'N', 2);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3300', '567.NEWM.CAEV//RHTS/CANCEL', 'CFNSTATUS', 'C', '<$TXNUM>', 'select case when txstatus = 1 then ''PACK'' else ''REJT'' end
from tllog where txnum =''<$FILTERID>''', 'CFNSTATUS', 'CFNSTATUS', 'C', 'N', 2);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3300', '567.NEWM.CAEV//RHTS/CANCEL', 'CICCODE', 'C', '<$TXNUM>', 'select cf.swiftcode
       from tllogfld f,cfmast cf
       where    f.txnum =''<$FILTERID>''
            and f.cvalue = cf.custodycd', 'CICCODE', 'CICCODE', 'C', 'N', 2);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '3300', '567.NEWM.CAEV//RHTS/CANCEL', 'CURDATA', 'C', '<$BUSDATE>', 'select to_char(to_date(''<$FILTERID>'',''DD/MM/YYYY''),''RRRRMMDD'') FROM DUAL', 'Ngày giao dịch', 'Trade Date', 'C', 'N', 2);COMMIT;