SET DEFINE OFF;DELETE FROM VSDTXMAPEXT WHERE 1 = 1 AND NVL(OBJNAME,'NULL') = NVL('9017','NULL');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9017', '564.CORP.NOTF.ANN', 'PLIS_INFO', 'C', '<$TXNUM>', 'SELECT (CASE WHEN TRADEPLACE=''001'' THEN ''HOSE''
            WHEN TRADEPLACE=''002'' THEN ''HNX''
            WHEN TRADEPLACE=''003'' THEN ''DCCNY''
            WHEN TRADEPLACE=''005'' THEN ''UPCOM''
            WHEN TRADEPLACE=''010'' THEN ''BOND'' END) PLIS
FROM SBSECURITIES
WHERE CODEID IN (SELECT CODEID FROM <$REFOBJ> WHERE AUTOID =''<$FILTERID>'')', 'Nơi niêm yết', 'Place Information', 'C', 'Y', 9);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9017', '564.CORP.NOTF.ANN', 'CICCODE', 'C', '<$TXNUM>', 'SELECT CF.SWIFTCODE
FROM CFMAST CF, AFMAST AF WHERE CF.CUSTID=AF.CUSTID AND AF.ACCTNO IN (SELECT AFACCTNO  FROM <$REFOBJ> WHERE AUTOID = ''<$FILTERID>'')', 'CICCODE Client', 'CICCODE Client', 'C', 'N', 1);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9017', '564.CORP.NOTF.ANN', 'CAMV_IND', 'C', '<$TXNUM>', 'SELECT CASE WHEN INSTR(''010,015,016,027,024,021,011,017,029,031,032,003,019'',CATYPE) >0 THEN ''MAND'' ELSE ''VOLU'' END
FROM CAMAST WHERE CAMASTID IN (SELECT CAMASTID  FROM <$REFOBJ> WHERE AUTOID = ''<$FILTERID>'')', 'CAMV_IND', 'CAMV_IND', 'C', 'N', 6);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9017', '564.CORP.NOTF.ANN', 'CAEP_IND', 'C', '<$TXNUM>', 'SELECT CASE WHEN INSTR(''010,015,016,027,024,021,011,017,020,014,023'',CATYPE) >0 THEN ''DISN''
            WHEN INSTR(''005,028,006,029,031,032,003,030,019'',CATYPE) >0 THEN ''GENL'' END
FROM CAMAST WHERE CAMASTID IN (SELECT CAMASTID  FROM <$REFOBJ> WHERE AUTOID = ''<$FILTERID>'')', 'Loại thông báo thực hiện quyền', 'Type of Notification', 'C', 'N', 4);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9017', '564.CORP.NOTF.ANN', 'CIF_NO', 'C', '<$TXNUM>', 'SELECT CF.CIFID FROM AFMAST AF, CFMAST CF
WHERE AF.CUSTID =CF.CUSTID AND AF.ACCTNO IN (SELECT AFACCTNO FROM <$REFOBJ> WHERE AUTOID = ''<$FILTERID>'')', 'Số CIF của khách hàng', 'Customer Number', 'C', 'Y', 10);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9017', '564.CORP.NOTF.ANN', 'STOCK_INFO', 'C', '<$TXNUM>', 'SELECT ISINCODE FROM SBSECURITIES WHERE CODEID IN (SELECT CODEID FROM <$REFOBJ> WHERE AUTOID =''<$FILTERID>'' )', 'Thông tin chứng khoán', 'Stock Information', 'C', 'Y', 8);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9017', '564.CORP.NOTF.ANN', 'PROC_STATUS', 'C', '<$TXNUM>', 'SELECT CASE WHEN INSTR(''030'',CATYPE) >0 AND INSTR(''001,002'',CASUBTYPE) >0 THEN ''PREC''
            ELSE ''COMP''  END
FROM CAMAST WHERE CAMASTID IN (SELECT CAMASTID  FROM <$REFOBJ> WHERE AUTOID = ''<$FILTERID>'')', 'Trạng thái thông tin', 'Processing Status', 'C', 'N', 7);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9017', '564.CORP.NOTF.ANN', 'CAID', 'C', '<$TXNUM>', 'SELECT CAMASTID FROM <$REFOBJ> WHERE AUTOID = ''<$FILTERID>''', 'CAMV_IND', 'CAMV_IND', 'C', 'N', 6);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9017', '564.CORP.NOTF.ANN', 'CAEV_IND', 'C', '<$TXNUM>', 'SELECT CASE WHEN INSTR(''010,024'',CATYPE) >0 THEN ''DVCA''
            WHEN INSTR(''011'',CATYPE) >0 THEN ''DVSE''
            WHEN INSTR(''014'',CATYPE) >0 THEN ''RHTS''
            WHEN INSTR(''021'',CATYPE) >0 THEN ''BONU''
            WHEN INSTR(''005'',CATYPE) >0 THEN ''MEET''
            WHEN INSTR(''028,006'',CATYPE) >0 THEN ''XMET''
            WHEN INSTR(''015'',CATYPE) >0 THEN ''INTR''
            WHEN INSTR(''027'',CATYPE) >0 THEN ''LIQU''
            WHEN INSTR(''017,020,023'',CATYPE) >0 THEN ''CONV''
            WHEN INSTR(''019'',CATYPE) >0 THEN ''CHAN''
            WHEN INSTR(''030'',CATYPE) >0 AND INSTR(''001,003'',CASUBTYPE) >0 THEN ''TEND''
            WHEN INSTR(''030'',CATYPE) >0 AND CASUBTYPE=''002'' THEN ''OTHR''
            WHEN INSTR(''031,032'',CATYPE) >0 THEN ''OTHR''
            WHEN INSTR(''003'',CATYPE) >0 THEN ''DLST''
            WHEN INSTR(''016'',CATYPE) >0 THEN ''REDM''
            WHEN INSTR(''029'',CATYPE) >0 THEN ''CHAN''    END
FROM CAMAST WHERE CAMASTID IN (SELECT CAMASTID  FROM <$REFOBJ> WHERE AUTOID = ''<$FILTERID>'')', 'Loại sự kiện quyền', 'Corporate Action Event Indicator', 'C', 'N', 5);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9017', '564.CORP.NOTF.ANN', 'CRLFPAYD_DT1', 'C', '<$TXNUM>', 'SELECT  CASE WHEN INSTR(''031,032,019,029'',CATYPE) >0  THEN ''||:98A::EFFD//''||TO_CHAR(ACTIONDATE,''RRRRMMDD'')
             WHEN INSTR(''003'',CATYPE) >0  THEN ''||:98A::EFFD//''||TO_CHAR(ACTIONDATE,''RRRRMMDD'')
             else '''' END
FROM CAMAST WHERE CAMASTID IN (SELECT CAMASTID  FROM <$REFOBJ> WHERE AUTOID = ''<$FILTERID>'')', 'Ngày thanh toán', 'Payment Date', 'C', 'N', 16);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9017', '564.CORP.NOTF.ANN', 'CRLFPAYD_DT2', 'C', '<$TXNUM>', 'SELECT  CASE WHEN INSTR(''003'',CATYPE) >0  THEN ''||:98A::TSDT//''||TO_CHAR(STOPTRANDATE,''RRRRMMDD'') else '''' END
FROM CAMAST WHERE CAMASTID IN (SELECT CAMASTID  FROM <$REFOBJ> WHERE AUTOID = ''<$FILTERID>'')', 'Ngày thanh toán', 'Payment Date', 'C', 'N', 16);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9017', '564.CORP.NOTF.ANN', 'DESCRIPTION', 'C', '<$TXNUM>', 'SELECT CASE WHEN INSTR(''003,031,032'',CATYPE) >0  THEN CA.CONTENT
            WHEN INSTR(''029,030'',CATYPE) >0  THEN CA.CHANGECONTENT
            WHEN INSTR(''005,006,028'',CATYPE) >0  THEN CA.DESCRIPTION ||
                    (CASE WHEN CA.MEETINGPLACE IS NULL THEN '''' ELSE ''||'' || CA.MEETINGPLACE END) ||
                    (CASE WHEN CA.MEETINGDATETIME IS NULL THEN '''' ELSE ''||'' || CA.MEETINGDATETIME END) ||
                    (CASE WHEN V.VOTE IS NULL THEN '''' ELSE ''||'' || V.VOTE END)
            ELSE CA.DESCRIPTION
            END
FROM CAMAST CA,
(
    SELECT CAMASTID, LISTAGG(VOTING, ''||'') WITHIN GROUP (ORDER BY CAMASTID) VOTE
    FROM CAVOTING
    GROUP BY CAMASTID
) V
WHERE CA.CAMASTID IN (SELECT CAMASTID FROM <$REFOBJ> WHERE AUTOID = ''<$FILTERID>'')
AND CA.CAMASTID=V.CAMASTID(+)', 'Thông tin chứng khoán', 'Stock Information', 'C', 'N', 8);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9017', '564.CORP.NOTF.ANN', 'PAYD_DT', 'C', '<$TXNUM>', 'SELECT  CASE WHEN INSTR(''005,028,006'',CATYPE) >0
THEN ''MEET//''||TO_CHAR(actiondate,''RRRRMMDD'')||''||:98A::XDTE//''||TO_CHAR(GETPREVDATE(REPORTDATE,1),''RRRRMMDD'')||''||:98A::RDTE//''||TO_CHAR(REPORTDATE,''RRRRMMDD'')
            WHEN INSTR(''030'',CATYPE) >0  THEN ''ANOU//''||TO_CHAR(SYSDATE,''RRRRMMDD'')
            WHEN INSTR(''031,032,019,029'',CATYPE) >0  THEN ''ANOU//''||TO_CHAR(SYSDATE,''RRRRMMDD'')
            WHEN INSTR(''003'',CATYPE) >0  THEN ''ANOU//''||TO_CHAR(SYSDATE,''RRRRMMDD'')
            END
FROM CAMAST WHERE CAMASTID IN (SELECT CAMASTID  FROM <$REFOBJ> WHERE AUTOID = ''<$FILTERID>'')', 'Ngày thanh toán', 'Payment Date', 'C', 'N', 16);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9017', '564.CORP.NOTF.ANN', 'STOCK_DESTINATION', 'C', '<$TXNUM>', 'SELECT SB.ISINCODE FROM SBSECURITIES SB WHERE SB.CODEID IN (
SELECT CA.EXCODEID
FROM <$REFOBJ> L, CAMAST CA WHERE L.AUTOID =''<$FILTERID>'' AND CA.CAMASTID =L.CAMASTID)', 'Thông tin chứng khoán', 'Stock Information', 'C', 'Y', 8);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9017', '564.CORP.NOTF.ANN', 'STOCK_OPTION', 'C', '<$TXNUM>', 'SELECT CA.OPTSYMBOL FROM <$REFOBJ> L, CAMAST CA WHERE L.AUTOID =''<$FILTERID>'' AND CA.CAMASTID =L.CAMASTID', 'Thông tin chứng khoán', 'Stock Information', 'C', 'Y', 8);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9017', '564.CORP.NOTF.ANN', 'CONTENT', 'C', '<$TXNUM>', 'SELECT CA.PURPOSEDESC
FROM <$REFOBJ> L, CAMAST CA WHERE L.AUTOID =''<$FILTERID>'' AND CA.CAMASTID =L.CAMASTID', 'Thông tin chứng khoán', 'Stock Information', 'C', 'Y', 8);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9017', '564.CORP.NOTF.ANN', 'EVENT_TP', 'C', '<$TXNUM>', 'SELECT CASE WHEN SWIFTCLIENT=''N'' THEN ''NEWM'' WHEN SWIFTCLIENT=''U'' THEN ''REPL''
            WHEN SWIFTCLIENT=''D'' THEN ''CANC'' WHEN SWIFTCLIENT=''M'' THEN ''RMDR'' END  FROM <$REFOBJ> WHERE AUTOID = ''<$FILTERID>''', 'Loại sự kiện doanh nghiệp', 'Corporate Action Event', 'C', 'N', 3);COMMIT;