SET DEFINE OFF;DELETE FROM VSDTXMAPEXT WHERE 1 = 1 AND NVL(OBJNAME,'NULL') = NVL('9018','NULL');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9018', '564.CORP.REPE.TIEN', 'PLIS_SOURCE_TICKET', 'C', '<$TXNUM>', 'SELECT (CASE WHEN TRADEPLACE=''001'' THEN ''HOSE''
            WHEN TRADEPLACE=''002'' THEN ''HNX''
            WHEN TRADEPLACE=''003'' THEN ''DCCNY''
            WHEN TRADEPLACE=''005'' THEN ''UPCOM''
            WHEN TRADEPLACE=''010'' THEN ''BOND'' END) PLIS
FROM SBSECURITIES
WHERE CODEID IN (SELECT CODEID FROM CASCHD WHERE AUTOID =''<$FILTERID>'')', 'Nơi niêm yết', 'Place Listing Underlying Stock', 'C', 'Y', 9);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9018', '564.CORP.REPE.TIEN', 'PAYD_DT', 'C', '<$TXNUM>', 'select  case when instr(''005,028,006'',catype) >0  then ''RDTE//''||to_char(reportdate,''RRRRMMDD'')
            when instr(''005,028,006'',catype) <= 0  then ''XDTE//''||to_char(GETPREVDATE(REPORTDATE,1),''RRRRMMDD'')
            else  '':98A://UKWN'' end
from camast where camastid in (select camastid  from CASCHD where autoid = ''<$FILTERID>'')', NULL, NULL, NULL, NULL, NULL);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9018', '564.CORP.REPE.TIEN', 'DESCRIPTION', 'C', '@VSD confirmed', NULL, 'Diễn giải', 'Description', 'C', NULL, NULL);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9018', '564.CORP.REPE.TIEN', 'CICCODE', 'C', '<$TXNUM>', 'SELECT CF.SWIFTCODE
FROM CFMAST CF, AFMAST AF WHERE CF.CUSTID=AF.CUSTID AND AF.ACCTNO IN (SELECT AFACCTNO  FROM <$REFOBJ> WHERE AUTOID = ''<$FILTERID>'')', 'CICCODE Client', 'CICCODE Client', 'C', 'N', 1);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9018', '564.CORP.REPE.TIEN', 'CAMV_IND', 'C', '<$TXNUM>', 'select case when instr(''010,015,016,027,024,021,011,017,029,031,032,003,019'',catype) >0 then ''MAND'' else ''VOLU'' END
from camast where camastid in (select camastid  from CASCHD where autoid = ''<$FILTERID>'')', 'CAMV_IND', 'CAMV_IND', 'C', 'N', 6);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9018', '564.CORP.REPE.TIEN', 'CAEP_IND', 'C', '<$TXNUM>', 'select case when instr(''010,015,016,027,024,021,011,017,020,014,023'',catype) >0 then ''DISN''
            when instr(''005,028,006,029,031,032,003,030,019'',catype) >0 then ''GENL'' END
from camast where camastid in (select camastid  from CASCHD where autoid = ''<$FILTERID>'')', 'Loại thông báo thực hiện quyền', 'Type of Notification', 'C', 'N', 4);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9018', '564.CORP.REPE.TIEN', 'SEME_ID', 'C', '<$TXNUM>', 'select camastid  from CASCHD where autoid = ''<$FILTERID>''', 'Số hiệu yêu cầu', 'Reference identitication', 'C', 'N', 2);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9018', '564.CORP.REPE.TIEN', 'SOURCE_TICKET', 'C', '<$TXNUM>', 'select isincode from sbsecurities where codeid in (select codeid from caschd where autoid =''<$FILTERID>'' )', 'Chứng khoán gốc', 'Underlying stock', 'C', 'Y', 8);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9018', '564.CORP.REPE.TIEN', 'CORP_STOCK_CODE', 'C', '<$TXNUM>', 'select camastid from caschd where autoid = ''<$FILTERID>''', 'Mã thực hiện quyền', 'The corporate action reference number', 'C', 'Y', 7);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9018', '564.CORP.REPE.TIEN', 'GRSS_AMT', 'C', '<$TXNUM>', 'SELECT REPLACE(TO_CHAR(NVL(AMT,0),''FM999999999999990.999999''),''.'','','') GRSS_AMT FROM CASCHD WHERE AUTOID = ''<$FILTERID>''', 'Số tiền cổ tức ', 'Entitled Amount ', 'C', NULL, NULL);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9018', '564.CORP.REPE.TIEN', 'ENTL_AMT', 'C', '<$TXNUM>', 'SELECT REPLACE(TO_CHAR(NVL(AMT,0),''FM999999999999990.999999''),''.'','','') ENTL_AMT FROM CASCHD WHERE AUTOID = ''<$FILTERID>''', 'Số tiền cổ tức ', 'Entitled Amount ', 'C', NULL, NULL);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9018', '564.CORP.REPE.TIEN', 'NETT_AMT', 'C', '<$TXNUM>', 'SELECT REPLACE(TO_CHAR((
    CASE WHEN VAT <> ''Y'' THEN AMT
    ELSE (
        CASE WHEN CATYPE = ''010'' THEN (CASE WHEN CUSTTYPE = ''B'' THEN AMT ELSE NETT1 END)
        WHEN CATYPE = ''024'' THEN NETT2
        WHEN CATYPE = ''027'' THEN NETT1
        ELSE AMT END --015,016
    )
    END)
    ,''FM999999999999990.999999''),''.'','','') NETT
FROM (
    SELECT CF.VAT, CF.CUSTTYPE, CA.CATYPE, CAS.AMT,
           GREATEST(0, CAS.AMT - ROUND(CAS.AMT * CA.PITRATE/100)) NETT1,
           GREATEST(0, CAS.AMT - ROUND(CAS.BALANCE * CA.PITRATE/100 * CA.EXPRICE / CA.EXRATE)) NETT2
    FROM CASCHD CAS, CFMAST CF, AFMAST AF,
    (
        SELECT CAMASTID, CATYPE, PITRATE, EXPRICE,
               NVL(CASE WHEN INSTR(EXRATE, ''/'') = 0 THEN TO_NUMBER(EXRATE) ELSE TO_NUMBER(SUBSTR(EXRATE, 0, INSTR(EXRATE, ''/'') - 1)) / TO_NUMBER(SUBSTR(EXRATE, INSTR(EXRATE,''/'') + 1, LENGTH(EXRATE))) END,1) EXRATE
        FROM CAMAST
    ) CA
    WHERE CAS.AUTOID = ''<$FILTERID>''
    AND CAS.CAMASTID = CA.CAMASTID
    AND CF.CUSTID = AF.CUSTID
    AND AF.ACCTNO = CAS.AFACCTNO
)', 'Số tiền đã trừ thuế cổ tức', 'Net amount', 'C', 'N', 13);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9018', '564.CORP.REPE.TIEN', 'CST_BANK_ACCT', 'C', '<$TXNUM>', 'select NVL(refcasaacct,'''')REFCA from ddmast where  accounttype = ''IICA'' and status <> ''C'' and afacctno in (select afacctno from caschd where autoid = ''<$FILTERID>'')', 'TK nhận tiền cổ tức ', 'Account number', 'C', NULL, NULL);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9018', '564.CORP.REPE.TIEN', 'ACT_DT', 'C', '<$TXNUM>', 'select TO_CHAR(actiondate,''RRRRMMDD'') from CAMAST WHERE CAMASTID IN (SELECT CAMASTID FROM caschd WHERE AUTOID = ''<$FILTERID>'')', 'Ngày thanh toán', 'Payment date', NULL, NULL, NULL);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9018', '564.CORP.REPE.TIEN', 'CRLFPAYD_DT', 'C', '<$TXNUM>', 'select  case when instr(''005,028,006'',catype) >0  then ''||:98A::MEET//''||to_char(actiondate,''RRRRMMDD'')
            when instr(''005,028,006'',catype) <= 0  then ''||:98A::RDTE//''||to_char(reportdate,''RRRRMMDD'')
             else  '''' end
from camast where camastid in (select camastid  from CASCHD where autoid = ''<$FILTERID>'')', NULL, NULL, NULL, NULL, NULL);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9018', '564.CORP.REPE.TIEN', 'ELIG_TYPE', 'C', '<$TXNUM>', 'SELECT (CASE WHEN INSTR(''001,002,008,011'',SB.SECTYPE)>0 THEN ''UNIT/''|| REPLACE(TO_CHAR(NVL(CAS.TRADE,0),''FM999999999999990.999999''),''.'','','')
             ELSE ''FAMT/''|| REPLACE(TO_CHAR(NVL(CAS.TRADE,0) * CA.PARVALUE,''FM999999999999990.999999''),''.'','','')
        END) ELIG
FROM CASCHD CAS, SBSECURITIES SB, CAMAST CA
WHERE CAS.AUTOID = ''<$FILTERID>''
AND CAS.CODEID = SB.CODEID
AND CAS.CAMASTID = CA.CAMASTID', 'Số CK chốt quyền', 'The balance of the stock', 'C', 'N', 11);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9018', '564.CORP.REPE.TIEN', 'CIF_NO', 'C', '<$TXNUM>', 'select cf.cifid from afmast af, cfmast cf
where af.custid =cf.custid and af.acctno in (select afacctno from caschd where autoid = ''<$FILTERID>'')', 'Số CIF của khách hàng', 'Customer Number', 'C', 'Y', 10);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9018', '564.CORP.REPE.TIEN', 'XDTE_DT', 'C', '<$TXNUM>', 'SELECT TO_CHAR(GETPREVDATE(REPORTDATE,1),''RRRRMMDD'') FROM CAMAST
WHERE CAMASTID  IN (SELECT CAMASTID FROM <$REFOBJ> WHERE AUTOID = ''<$FILTERID>'')', 'Ngày giao dịch không hưởng quyền', 'XDTE_DT', 'C', 'N', 11);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9018', '564.CORP.REPE.TIEN', 'WAPA_92D', 'C', '<$TXNUM>', 'SELECT CASE WHEN TMP.CATYPE = ''024'' THEN '':92D::WAPA//'' || (CASE WHEN TMP.DR = ''0,'' THEN TMP.DL ELSE TMP.DL || ''/'' || TMP.DR END) || ''||'' ELSE '''' END
FROM(
    SELECT CATYPE,
           REPLACE(TO_CHAR((CASE WHEN INSTR(EXRATE, ''/'') > 0 THEN SUBSTR(EXRATE,0,INSTR(EXRATE, ''/'') - 1) ELSE EXRATE END),''FM999999999999990.999999''),''.'','','') DL,
           REPLACE(TO_CHAR((CASE WHEN INSTR(EXRATE, ''/'') > 0 THEN SUBSTR(EXRATE,INSTR(EXRATE, ''/'') + 1) ELSE ''0'' END),''FM999999999999990.999999''),''.'','','') DR
    FROM CAMAST
    WHERE CAMASTID IN (SELECT CAMASTID FROM <$REFOBJ> WHERE AUTOID = ''<$FILTERID>'')
) TMP', 'Tỷ lệ thực hiện', 'Conversion ratio', 'C', 'N', 18);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9018', '564.CORP.REPE.TIEN', 'BOND_AMOUNT', 'C', '<$TXNUM>', 'SELECT (CASE WHEN CATYPE=''016'' THEN ''||:90B::OFFR//ACTU/VND'' || REPLACE(TO_CHAR(PARVALUE*INTERESTRATE/100+PARVALUE,''FM999999999999990.999999''),''.'','','')
             WHEN CATYPE=''024'' THEN ''||:90B::OFFR//ACTU/VND'' || REPLACE(TO_CHAR(DECODE(TYPERATE,''R'',PARVALUE*DEVIDENTRATE/100,DEVIDENTVALUE),''FM999999999999990.999999''),''.'','','')
             WHEN CATYPE=''027'' THEN ''||:90B::OFFR//ACTU/VND'' || REPLACE(TO_CHAR(DECODE(TYPERATE,''R'',PARVALUE*DEVIDENTRATE/100,DEVIDENTVALUE),''FM999999999999990.999999''),''.'','','')
             ELSE ''''
       END) VAL
FROM CAMAST
WHERE CAMASTID IN (SELECT CAMASTID  FROM CASCHD WHERE AUTOID = ''<$FILTERID>'')', 'Số tiền trả cho 1 TP', NULL, 'C', 'N', 17);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9018', '564.CORP.REPE.TIEN', 'CRLFPAYMENT_PERCENT', 'C', '<$TXNUM>', 'SELECT REPLACE(
       CASE WHEN CATYPE=''010'' THEN ''||:92F::GRSS//VND''||TO_CHAR(DECODE(TYPERATE,''R'',PARVALUE*DEVIDENTRATE/100,DEVIDENTVALUE),''FM999999999999990.999999'')
            WHEN CATYPE=''015'' THEN ''||:92F::INTP//VND''||TO_CHAR(INTERESTRATE/100*PARVALUE,''FM999999999999990.999999'')
       ELSE '''' END
       ,''.'','','') VAL
FROM CAMAST WHERE CAMASTID IN (SELECT CAMASTID  FROM CASCHD WHERE AUTOID = ''<$FILTERID>'')', NULL, NULL, 'C', 'N', 16);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '9018', '564.CORP.REPE.TIEN', 'CAEV_IND', 'C', '<$TXNUM>', 'SELECT CASE WHEN INSTR(''010'',CATYPE) >0 THEN ''DVCA''
            WHEN INSTR(''011'',CATYPE) >0 THEN ''DVSE''
            WHEN INSTR(''024'',CATYPE) >0 THEN ''EXWA''
            WHEN INSTR(''014'',CATYPE) >0 THEN ''RHTS''
            WHEN INSTR(''021'',CATYPE) >0 THEN ''BONU''
            WHEN INSTR(''005'',CATYPE) >0 THEN ''MEET''
            WHEN INSTR(''028,006'',CATYPE) >0 THEN ''XMET''
            WHEN INSTR(''015'',CATYPE) >0 THEN ''INTR''
            WHEN INSTR(''027'',CATYPE) >0 THEN ''LIQU''
            WHEN INSTR(''017,020,023'',CATYPE) >0 THEN ''CONV''
            WHEN INSTR(''019'',CATYPE) >0 THEN ''CHAN''
            WHEN INSTR(''030'',CATYPE) >0 AND INSTR(''001,003'',CASUBTYPE) >0 THEN ''TEND''
            WHEN INSTR(''030'',CATYPE) >0 AND CASUBTYPE=''002'' THEN ''OTHR''
            WHEN INSTR(''031,032'',CATYPE) >0 THEN ''OTHR''
            WHEN INSTR(''003'',CATYPE) >0 THEN ''DLST''
            WHEN INSTR(''016'',CATYPE) >0 THEN ''REDM''
            WHEN INSTR(''029'',CATYPE) >0 THEN ''INFO''    END
FROM CAMAST WHERE CAMASTID IN (SELECT CAMASTID  FROM CASCHD WHERE AUTOID = ''<$FILTERID>'')', 'Loại sự kiện quyền', 'Corporate Action Event Indicator', 'C', 'N', 5);COMMIT;