SET DEFINE OFF;DELETE FROM VSDTXMAPEXT WHERE 1 = 1 AND NVL(OBJNAME,'NULL') = NVL('0167','NULL');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'IDCODE', 'C', '$03', 'select (case when idtype = ''009'' then tradingcode
            else idcode end) idcode
from cfmast where custodycd = ''<$FILTERID>''', 'Loại giấy tờ', 'ID number', 'C', 'N', 5);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'IDDATE', 'D', '$07', '', 'Ngày cấp', 'Issue date', 'C', 'N', 6);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'PHONE', 'C', '$21', '', 'Số điện thoại', 'Telephone number', 'C', 'N', 8);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'PROVINCE', 'C', '$01', 'SELECT PROVINCE FROM CFMAST WHERE CUSTID=''<$FILTERID>''', 'Mã tỉnh/thành phố', 'Province', 'C', 'N', 11);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'TXDATE', 'D', '<$BUSDATE>', '', 'Ngày tạo yêu cầu', 'Preparation Date', 'C', 'N', 13);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'VSDCODE', 'C', '@VSDSVN01', '', 'VSD BICCODE', 'VSD BICCODE', 'C', 'N', 12);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'ADDRESS', 'C', '$08', 'SELECT ADDRESS FROM CFMAST WHERE CUSTID=''<$FILTERID>''', 'Địa chỉ', 'Address', 'C', 'N', 10);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'FULLNAME', 'C', '$04', 'SELECT FULLNAME FROM CFMAST WHERE CUSTID=''<$FILTERID>''', 'Tên đầy đủ nhà đầu tư', 'Full name', 'C', 'N', 2);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'IDPLACE', 'C', '$29', 'SELECT IDPLACE FROM CFMAST WHERE CUSTID=''<$FILTERID>''', 'Nơi cấp', 'Issue place', 'C', 'N', 7);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'EMAIL', 'C', '$01', 'SELECT EMAIL FROM CFMAST WHERE CUSTID=''<$FILTERID>''', 'Email', 'Email', 'C', 'N', 9);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'ALTERNATEID', 'C', '$01', 'select (''VISD/'' ||
    case when cf.idtype = ''001'' then ''IDNO''
         when cf.idtype = ''002'' then ''CCPT''
         when cf.idtype = ''005'' then ''CORP''
         when cf.idtype = ''009'' and cf.custtype = ''B'' then ''FIIN''
         when cf.idtype = ''009'' and cf.custtype = ''I'' then ''ARNU''
         else ''OTHR''
    end) ALTERNATEID
from cfmast cf
where custid = ''<$FILTERID>''', 'Loại hình cổ đông', 'Type of investor', 'C', 'N', 15);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'AUTONUMBER', 'C', '$01', 'SELECT LPAD(SEQ_VSDREQAUTOID.NEXTVAL,6,''0'') AUTONUMBER FROM DUAL', 'Số thứ tự của điện gửi trong phiên', 'EN:Số thứ tự của điện gửi trong phiên', 'C', 'N', 16);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'COUNTRY', 'C', '$12', '', 'Mã quốc gia', 'Country codes', 'C', 'N', 12);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'CUSTODYCD', 'C', '$03', '', 'Tài khoản nhà đầu tư', 'Custody code', 'C', 'N', 1);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'DESC', 'C', '$30', '', 'Diễn giải', 'Description', 'C', 'N', 14);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'DOBDATE', 'D', '$01', 'SELECT to_char(DATEOFBIRTH,''DD/MM/RRRR'') FROM CFMAST WHERE CUSTID=''<$FILTERID>''', 'Ngày sinh', 'Date of birth', 'C', 'N', 3);COMMIT;