SET DEFINE OFF;DELETE FROM VSDTXMAPEXT WHERE 1 = 1 AND NVL(OBJNAME,'NULL') = NVL('0059','NULL');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0059', '598.NEWM/ACLS', 'ADDRESS', 'C', '$03', 'SELECT ADDRESS FROM CFMAST WHERE CUSTID=''<$FILTERID>''', 'Địa chỉ', 'Address', 'C', 'N', 10);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0059', '598.NEWM/ACLS', 'ALTERNATEID', 'C', '$03', 'select (''VISD/'' ||
    case when cf.idtype = ''001'' then ''IDNO''
         when cf.idtype = ''002'' then ''CCPT''
         when cf.idtype = ''005'' then ''CORP''
         when cf.idtype = ''009'' and cf.custtype = ''B'' then ''FIIN''
         when cf.idtype = ''009'' and cf.custtype = ''I'' then ''ARNU''
         else ''OTHR''
    end) ALTERNATEID
from cfmast cf
where custid = ''<$FILTERID>''', 'Loại hình cổ đông', 'Type of investor', 'C', 'N', 16);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0059', '598.NEWM/ACLS', 'AUTONUMBER', 'C', '$03', 'SELECT LPAD(SEQ_VSDREQAUTOID.NEXTVAL,6,''0'') AUTONUMBER FROM DUAL', 'Số thứ tự của điện gửi trong phiên', 'EN:Số thứ tự của điện gửi trong phiên', 'C', 'N', 17);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0059', '598.NEWM/ACLS', 'COUNTRY', 'C', '$03', 'SELECT A.Cdcontent FROM CFMAST CF, ALLCODE A WHERE CF.CUSTID=''<$FILTERID>''
AND CF.country=A.CDVAL AND A.Cdname=''NATIONAL'' ', 'Mã quốc gia', 'Country codes', 'C', 'N', 12);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0059', '598.NEWM/ACLS', 'COUNTRY_FULL', 'C', '$03', 'SELECT A.en_Cdcontent FROM CFMAST CF, ALLCODE A WHERE CF.CUSTID=''<$FILTERID>''
AND CF.country=A.CDVAL AND A.Cdname=''NATIONAL'' ', 'Quốc gia', 'Country', 'C', 'N', 13);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0059', '598.NEWM/ACLS', 'CUSTODYCD', 'C', '$88', NULL, 'Tài khoản nhà đầu tư', 'Custody code', 'C', 'N', 1);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0059', '598.NEWM/ACLS', 'DESC', 'C', '$30', NULL, 'Diễn giải', 'Description', 'C', 'N', 15);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0059', '598.NEWM/ACLS', 'DOBDATE', 'D', '$03', 'SELECT to_char(DATEOFBIRTH,''DD/MM/RRRR'') FROM CFMAST WHERE CUSTID=''<$FILTERID>''', 'Ngày sinh', 'Date of birth', 'C', 'N', 3);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0059', '598.NEWM/ACLS', 'EMAIL', 'C', '$03', 'SELECT EMAIL FROM CFMAST WHERE CUSTID=''<$FILTERID>''', 'Email', 'Email', 'C', 'N', 9);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0059', '598.NEWM/ACLS', 'FULLNAME', 'C', '$03', 'SELECT FULLNAME FROM CFMAST WHERE CUSTID=''<$FILTERID>''', 'Tên đầy đủ nhà đầu tư', 'Full name', 'C', 'N', 2);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0059', '598.NEWM/ACLS', 'IDCODE', 'C', '$03', 'select (case when idtype = ''009'' then tradingcode
            else idcode end) idcode
from cfmast where custid= ''<$FILTERID>''', 'Loại giấy tờ', 'ID number', 'C', 'N', 5);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0059', '598.NEWM/ACLS', 'IDDATE', 'D', '$03', 'select (case when idtype = ''009'' then to_char(TRADINGCODEDT,''DD/MM/RRRR'')
            else to_char(IDDATE,''DD/MM/RRRR'') end) idcode
from cfmast where custid = ''<$FILTERID>''', 'Ngày cấp', 'Issue date', 'C', 'N', 6);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0059', '598.NEWM/ACLS', 'IDPLACE', 'C', '$03', 'SELECT IDPLACE FROM CFMAST WHERE CUSTID=''<$FILTERID>''', 'Nơi cấp', 'Issue place', 'C', 'N', 7);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0059', '598.NEWM/ACLS', 'PHONE', 'C', '$03', 'SELECT MOBILESMS FROM CFMAST WHERE CUSTID=''<$FILTERID>''', 'Số điện thoại', 'Telephone number', 'C', 'N', 8);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0059', '598.NEWM/ACLS', 'PROVINCE', 'C', '$03', 'SELECT PROVINCE FROM CFMAST WHERE CUSTID=''<$FILTERID>''', 'Mã tỉnh/thành phố', 'Province', 'C', 'N', 11);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0059', '598.NEWM/ACLS', 'TXDATE', 'D', '<$BUSDATE>', NULL, 'Ngày tạo yêu cầu', 'Preparation Date', 'C', 'N', 14);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, EN_CAPTION, CHSTATUS, SPLIT, ODRNUM) Values   ('T', '0059', '598.NEWM/ACLS', 'VSDCODE', 'C', '@VSDSVN01', NULL, 'VSD BICCODE', 'VSD BICCODE', 'C', 'N', 12);COMMIT;