SET DEFINE OFF;DELETE FROM SEARCHFLD WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('POSTMAPEXT','NULL');Insert into SEARCHFLD   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD) Values   (1, 'AUTOID', 'Số tự tăng', 'C', 'POSTMAPEXT', 100, '', 'LIKE,=', '', 'N', 'N', 'Y', 100, '', 'Contract number', 'N', '', '', 'N', '', '', '', 'N', 'Y', '', '');Insert into SEARCHFLD   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD) Values   (2, 'ACNAME', 'Tên nghiệp vụ định khoản', 'C', 'POSTMAPEXT', 150, '', 'LIKE,=', '', 'Y', 'Y', 'N', 250, '', 'Name', 'N', '', '', 'N', '', '', '', 'N', 'Y', '', '');Insert into SEARCHFLD   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD) Values   (3, 'ACTYPE_DESC', 'Loại', 'C', 'POSTMAPEXT', 100, '', 'LIKE,=', '', 'Y', 'Y', 'N', 100, 'select cdval value, cdval cdvalue, cdcontent display, 
en_cdcontent en_display, '''' description
from allcode where cdname=''TRADETYPE''  and cdtype = ''GL'' 
and cduser = ''Y'' order by lstodr', 'Type', 'N', '', '', 'N', '', '', '', 'N', 'Y', '', '');Insert into SEARCHFLD   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD) Values   (4, 'CFTYPE_DESC', 'Loại khách hàng', 'C', 'POSTMAPEXT', 100, '', 'LIKE,=', '', 'Y', 'Y', 'N', 100, 'select cdval value, cdval cdvalue, cdcontent display, 
en_cdcontent en_display, '''' description
from allcode where cdname=''DORC''  and cdtype = ''GL'' 
and cduser = ''Y'' order by lstodr', 'Customer type', 'N', '', '', 'N', '', '', '', 'N', 'Y', '', '');Insert into SEARCHFLD   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD) Values   (5, 'DORC_DESC', 'Loại phát sinh', 'C', 'POSTMAPEXT', 100, '', 'LIKE,=', '', 'Y', 'Y', 'N', 100, 'select cdval value, cdval cdvalue, cdcontent display, 
en_cdcontent en_display, '''' description
from allcode where cdname=''DORC''  and cdtype = ''GL'' 
and cduser = ''Y'' order by lstodr', 'Debit/Credit', 'N', '', '', 'N', '', '', '', 'N', 'Y', '', '');Insert into SEARCHFLD   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD) Values   (6, 'SHORTCD', 'Loại tiền tệ', 'C', 'POSTMAPEXT', 100, '', 'LIKE,=', '', 'Y', 'Y', 'N', 100, 'select ccycd value, ccycd cdvalue, shortcd display, shortcd en_display, '''' description from sbcurrency  order by ccycd', 'Currency', 'N', '', '', 'N', '', '', '', 'N', 'Y', '', '');Insert into SEARCHFLD   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD) Values   (7, 'TRADEPLACE_DESC', 'Sàn giao dịch', 'C', 'POSTMAPEXT', 100, '', 'LIKE,=', '', 'Y', 'Y', 'N', 100, 'select cdval value, cdval cdvalue, cdcontent display, 
en_cdcontent en_display, '''' description
from allcode where cdname=''TRADEPLACE''  and cdtype = ''GL'' 
and cduser = ''Y'' order by lstodr', 'Trade place', 'N', '', '', 'N', '', '', '', 'N', 'Y', '', '');Insert into SEARCHFLD   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD) Values   (9, 'DEBITACCOUNT', 'Tài khoản ghi Nợ', 'C', 'POSTMAPEXT', 100, 'ccccccc.cccc.cccc.ccc', 'LIKE,=', 'ccccccc.cccc.cccc.ccc', 'Y', 'Y', 'N', 130, '', 'Debit account', 'N', '', '', 'N', '', '', '', 'N', 'Y', '', '');Insert into SEARCHFLD   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD) Values   (10, 'CREBITACCOUNT', 'Tài khoản ghi Có', 'C', 'POSTMAPEXT', 100, 'ccccccc.cccc.cccc.ccc', 'LIKE,=', 'ccccccc.cccc.cccc.ccc', 'Y', 'Y', 'N', 130, '', 'Credit account', 'N', '', '', 'N', '', '', '', 'N', 'Y', '', '');Insert into SEARCHFLD   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD) Values   (12, 'CREATEDDT', 'Ngày tạo', 'C', 'POSTMAPEXT', 100, '', 'LIKE,=', '', 'Y', 'Y', 'N', 150, '', 'Create date', 'N', '', '', 'N', '', '', '', 'N', 'Y', '', '');Insert into SEARCHFLD   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD) Values   (99, 'DESC_STATUS', 'Trạng thái', 'C', 'POSTMAPEXT', 100, '', 'LIKE,=', '', 'Y', 'Y', 'N', 100, 'select cdval value, cdval cdvalue, cdcontent display, 
en_cdcontent en_display, '''' description
from allcode where cdname=''APPRV_STS''  and cdtype = ''SY'' 
and cduser = ''Y'' order by lstodr', 'Status', 'N', '', '', 'N', '', '', '', 'N', 'Y', '', '');Insert into SEARCHFLD   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD) Values   (203, 'APRALLOW', 'APRALLOW', 'C', 'POSTMAPEXT', 100, '', 'LIKE,=', '', 'N', 'Y', 'N', 100, '', 'APRALLOW', 'N', '', '', 'N', '', '', '', 'N', 'Y', '', '');COMMIT;