SET DEFINE OFF;

DELETE FROM SEARCHFLD WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CF1044','NULL');

Insert into SEARCHFLD
   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD)
 Values
   (0, 'TXNUM', 'Số chứng từ', 'C', 'CF1044', 100, NULL, 'LIKE,=', NULL, 'Y', 'Y', 'N', 100, NULL, 'TXNUM', 'N', '05', NULL, 'N', NULL, NULL, NULL, 'N', 'Y', NULL, NULL);
Insert into SEARCHFLD
   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD)
 Values
   (1, 'TXDATE', 'Ngày chứng từ', 'D', 'CF1044', 100, NULL, 'LIKE,=', NULL, 'Y', 'Y', 'N', 100, NULL, 'TXNUM', 'N', '04', NULL, 'N', NULL, NULL, NULL, 'N', 'Y', NULL, NULL);
Insert into SEARCHFLD
   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD)
 Values
   (2, 'CUSTID', 'Mã Khách hàng', 'C', 'CF1044', 100, NULL, 'LIKE,=', NULL, 'Y', 'Y', 'N', 100, NULL, 'CUSTID', 'N', '03', NULL, 'N', NULL, NULL, NULL, 'N', 'Y', NULL, NULL);
Insert into SEARCHFLD
   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD)
 Values
   (3, 'CUSTODYCD', 'Số TK lưu ký', 'C', 'CF1044', 100, NULL, 'LIKE,=', NULL, 'Y', 'Y', 'N', 100, NULL, 'CUSTODYCD', 'N', '88', NULL, 'N', NULL, NULL, NULL, 'N', 'Y', NULL, NULL);
Insert into SEARCHFLD
   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD)
 Values
   (4, 'OFULLNAME', 'Tên Khách hàng cũ', 'C', 'CF1044', 200, NULL, 'LIKE,=', NULL, 'Y', 'Y', 'N', 200, NULL, 'FULLNAME', 'N', '28', NULL, 'N', NULL, NULL, NULL, 'N', 'Y', NULL, NULL);
Insert into SEARCHFLD
   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD)
 Values
   (5, 'NFULLNAME', 'Tên Khách hàng mới', 'C', 'CF1044', 200, NULL, 'LIKE,=', NULL, 'Y', 'Y', 'N', 200, NULL, 'FULLNAME', 'N', '38', NULL, 'N', NULL, NULL, NULL, 'N', 'Y', NULL, NULL);
Insert into SEARCHFLD
   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD)
 Values
   (6, 'OIDCODE', 'Số CMND/DKKD/Passport cũ', 'C', 'CF1044', 200, NULL, 'LIKE,=', NULL, 'Y', 'Y', 'N', 200, NULL, 'IDCODE', 'N', '21', NULL, 'N', NULL, NULL, NULL, 'N', 'Y', NULL, NULL);
Insert into SEARCHFLD
   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD)
 Values
   (7, 'NIDCODE', 'Số CMND/DKKD/Passport mới', 'C', 'CF1044', 200, NULL, 'LIKE,=', NULL, 'Y', 'Y', 'N', 200, NULL, 'IDCODE', 'N', '31', NULL, 'N', NULL, NULL, NULL, 'N', 'Y', NULL, NULL);
Insert into SEARCHFLD
   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD)
 Values
   (8, 'OIDDATE', 'Ngày cấp cũ', 'D', 'CF1044', 200, NULL, 'LIKE,=', NULL, 'Y', 'Y', 'N', 200, NULL, 'IDDATE', 'N', '22', NULL, 'N', NULL, NULL, NULL, 'N', 'Y', NULL, NULL);
Insert into SEARCHFLD
   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD)
 Values
   (9, 'NIDDATE', 'Ngày cấp mới', 'D', 'CF1044', 200, NULL, 'LIKE,=', NULL, 'Y', 'Y', 'N', 200, NULL, 'IDDATE', 'N', '32', NULL, 'N', NULL, NULL, NULL, 'N', 'Y', NULL, NULL);
Insert into SEARCHFLD
   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD)
 Values
   (10, 'OIDEXPIRED', 'Ngày hết hạn cũ', 'D', 'CF1044', 200, NULL, 'LIKE,=', NULL, 'Y', 'Y', 'N', 200, NULL, 'IDEXPIRED', 'N', '23', NULL, 'N', NULL, NULL, NULL, 'N', 'Y', NULL, NULL);
Insert into SEARCHFLD
   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD)
 Values
   (11, 'NIDEXPIRED', 'Ngày hết hạn mới', 'D', 'CF1044', 200, NULL, 'LIKE,=', NULL, 'Y', 'Y', 'N', 200, NULL, 'IDEXPIRED', 'N', '33', NULL, 'N', NULL, NULL, NULL, 'N', 'Y', NULL, NULL);
Insert into SEARCHFLD
   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD)
 Values
   (12, 'OIDPLACE', 'Nơi cấp cũ', 'C', 'CF1044', 200, NULL, 'LIKE,=', NULL, 'Y', 'Y', 'N', 200, NULL, 'IDPLACE', 'N', '24', NULL, 'N', NULL, NULL, NULL, 'N', 'Y', NULL, NULL);
Insert into SEARCHFLD
   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD)
 Values
   (13, 'NIDPLACE', 'Nơi cấp mới', 'C', 'CF1044', 200, NULL, 'LIKE,=', NULL, 'Y', 'Y', 'N', 200, NULL, 'IDPLACE', 'N', '34', NULL, 'N', NULL, NULL, NULL, 'N', 'Y', NULL, NULL);
Insert into SEARCHFLD
   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD)
 Values
   (14, 'OTRADINGCODE', 'Trading code cũ', 'C', 'CF1044', 200, NULL, 'LIKE,=', NULL, 'Y', 'Y', 'N', 200, NULL, 'TRADINGCODE', 'N', '25', NULL, 'N', NULL, NULL, NULL, 'N', 'Y', NULL, NULL);
Insert into SEARCHFLD
   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD)
 Values
   (15, 'NTRADINGCODE', 'Trading code mới', 'C', 'CF1044', 200, NULL, 'LIKE,=', NULL, 'Y', 'Y', 'N', 200, NULL, 'TRADINGCODE', 'N', '35', NULL, 'N', NULL, NULL, NULL, 'N', 'Y', NULL, NULL);
Insert into SEARCHFLD
   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD)
 Values
   (16, 'OTRADINGCODEDT', 'Ngày cấp Trading code cũ', 'D', 'CF1044', 200, NULL, 'LIKE,=', NULL, 'Y', 'Y', 'N', 200, NULL, 'TRADINGCODEDT', 'N', '26', NULL, 'N', NULL, NULL, NULL, 'N', 'Y', NULL, NULL);
Insert into SEARCHFLD
   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD)
 Values
   (17, 'NTRADINGCODEDT', 'Ngày cấp Trading code mới', 'D', 'CF1044', 200, NULL, 'LIKE,=', NULL, 'Y', 'Y', 'N', 200, NULL, 'TRADINGCODEDT', 'N', '36', NULL, 'N', NULL, NULL, NULL, 'N', 'Y', NULL, NULL);
Insert into SEARCHFLD
   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD)
 Values
   (18, 'OADDRESS', 'Địa chỉ cũ', 'C', 'CF1044', 200, NULL, 'LIKE,=', NULL, 'Y', 'Y', 'N', 200, NULL, 'ADDRESS', 'N', '27', NULL, 'N', NULL, NULL, NULL, 'N', 'Y', NULL, NULL);
Insert into SEARCHFLD
   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD)
 Values
   (19, 'NADDRESS', 'Địa chỉ mới', 'C', 'CF1044', 200, NULL, 'LIKE,=', NULL, 'Y', 'Y', 'N', 200, NULL, 'ADDRESS', 'N', '37', NULL, 'N', NULL, NULL, NULL, 'N', 'Y', NULL, NULL);
Insert into SEARCHFLD
   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD)
 Values
   (20, 'OCUSTTYPE', 'Phân loại KH cũ', 'C', 'CF1044', 200, NULL, 'LIKE,=', NULL, 'Y', 'Y', 'N', 200, NULL, 'CUSTTYPE', 'N', '45', NULL, 'N', NULL, NULL, NULL, 'N', 'Y', NULL, NULL);
Insert into SEARCHFLD
   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD)
 Values
   (21, 'NCUSTTYPE', 'Phân loại KH mới', 'C', 'CF1044', 200, NULL, 'LIKE,=', NULL, 'Y', 'Y', 'N', 200, NULL, 'CUSTTYPE', 'N', '46', NULL, 'N', NULL, NULL, NULL, 'N', 'Y', NULL, NULL);
Insert into SEARCHFLD
   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD)
 Values
   (23, 'OCOUNTRY', 'Quốc tịch cũ', 'C', 'CF1044', 200, NULL, 'LIKE,=', NULL, 'Y', 'Y', 'N', 200, NULL, 'COUNTRY', 'N', '87', NULL, 'N', NULL, NULL, NULL, 'N', 'Y', NULL, NULL);
Insert into SEARCHFLD
   (POSITION, FIELDCODE, FIELDNAME, FIELDTYPE, SEARCHCODE, FIELDSIZE, MASK, OPERATOR, FORMAT, DISPLAY, SRCH, KEY, WIDTH, LOOKUPCMDSQL, EN_FIELDNAME, REFVALUE, FLDCD, DEFVALUE, MULTILANG, ACDTYPE, ACDNAME, FIELDCMP, FIELDCMPKEY, ISPROCESS, QUICKSRCH, SUMMARYCD)
 Values
   (24, 'NCOUNTRY', 'Quốc tịch mới', 'C', 'CF1044', 200, NULL, 'LIKE,=', NULL, 'Y', 'Y', 'N', 200, NULL, 'COUNTRY', 'N', '89', NULL, 'N', NULL, NULL, NULL, 'N', 'Y', NULL, NULL);
COMMIT;
