SET DEFINE OFF;

DELETE FROM SYSVAR WHERE 1 = 1 AND NVL(VARNAME,'NULL') = NVL('WEBSITE','NULL');

Insert into SYSVAR
   (GRNAME, VARNAME, VARVALUE, VARDESC, EN_VARDESC, EDITALLOW, DATATYPE)
 Values
   ('SYSTEM', 'WEBSITE', 'Website: www.acb.com.vn', 'Website: www.acb.com.vn', NULL, 'Y', 'C');
COMMIT;
