SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE AP6001 (
   PV_REFCURSOR   IN OUT   PKG_REPORT.REF_CURSOR,
   OPT            IN       VARCHAR2,
   BRID           IN       VARCHAR2,
   F_TXDATE         IN       VARCHAR2,
   T_TXDATE         IN       VARCHAR2,
   P_CONTRACTNO   IN       VARCHAR2,
   P_CUSTODYCD    IN       VARCHAR2
)
IS
    v_FromDate     DATE;
    v_ToDate       DATE;
    V_CONTRACTNO   VARCHAR2 (10);
    V_CUSTODYCD    VARCHAR2 (50);
    V_STROPTION    VARCHAR2 (5);       -- A: ALL; B: BRANCH; S: SUB-BRANCH
    V_STRBRID      VARCHAR2 (4);       -- USED WHEN V_NUMOPTION > 0
BEGIN
    V_STROPTION := OPT;
    IF V_STROPTION = 'A' THEN
        V_STRBRID := '%';
    ELSIF V_STROPTION = 'B' THEN
        V_STRBRID := SUBSTR(BRID,1,2) || '__' ;
    ELSE
        V_STRBRID:= BRID;
    END IF;
    --v_FromDate := TO_DATE(F_DATE, SYSTEMNUMS.C_DATE_FORMAT);
    --v_ToDate := TO_DATE(T_DATE, SYSTEMNUMS.C_DATE_FORMAT);
    -----
    IF P_CONTRACTNO IS NULL OR P_CONTRACTNO ='ALL'
    THEN
        V_CONTRACTNO := '%';
    ELSE
        V_CONTRACTNO := P_CONTRACTNO;
    END IF;
    -----
    IF P_CUSTODYCD IS NULL OR P_CUSTODYCD ='ALL'
    THEN
        V_CUSTODYCD := '%';
    ELSE
        V_CUSTODYCD := P_CUSTODYCD;
    END IF;
    -----
    v_FromDate := F_TXDATE;
    v_ToDate   := T_TXDATE;
    SELECT (CASE WHEN v_FromDate IS NULL THEN MIN(DT.OPNDATE) ELSE v_FromDate END),
           (CASE WHEN v_ToDate IS NULL THEN MAX(DT.OPNDATE) ELSE v_ToDate END)
    INTO v_FromDate, v_ToDate
    FROM CRPHYSAGREE CR JOIN DOCSTRANSFER DT ON CR.CRPHYSAGREEID = DT.CRPHYSAGREEID
    WHERE CR.STATUS='A' AND
          DT.CRPHYSAGREEID LIKE V_CONTRACTNO AND
          DT.CUSTODYCD LIKE V_CUSTODYCD;
--==============MAIN QUERY================
 OPEN PV_REFCURSOR
 FOR
        SELECT v_FromDate FROM_DATE
             , v_ToDate TO_DATE
             , GETCURRDATE() CREATED_DATE --NGAY XUAT BAO CAO
             , DT.OPNDATE --NGAY NHAP KHO
             , DT.CRPHYSAGREEID
             , CR.NO --SO HOP DONG
             , MAX(NVL(AP.APQTTY,0)) APQTTY--SO LUONG PHU LUC HOP DONG
             , MAX(CR.QTTY) CRQTTY--SO LUONG CHUNG KHOAN TREN HOP DONG
             , MAX(CR.REQTTY) REQTTY --SO LUONG CHUNG KHOAN DA BAN
             , SUM(DT.QTTY) DTQTTY--SO LUONG CHUNG KHOAN HIEN DANG DUOC NHAP KHO
             , DT.SYMBOL --MA CHUNG KHOAN
        FROM CRPHYSAGREE CR JOIN DOCSTRANSFER DT ON CR.CRPHYSAGREEID = DT.CRPHYSAGREEID
                            JOIN SBSECURITIES SB ON SB.CODEID = CR.CODEID
                            JOIN ISSUERS ISS ON CR.ISSUERID = ISS.ISSUERID
                            LEFT JOIN (SELECT CRPHYSAGREEID, COUNT(1) APQTTY FROM APPENDIX GROUP BY CRPHYSAGREEID) AP ON AP.CRPHYSAGREEID = CR.CRPHYSAGREEID
        WHERE CR.STATUS='A' AND
              DT.OPNDATE BETWEEN v_FromDate AND v_ToDate AND
              DT.CRPHYSAGREEID LIKE V_CONTRACTNO AND
              DT.CUSTODYCD LIKE V_CUSTODYCD
        GROUP BY DT.OPNDATE , DT.CRPHYSAGREEID, CR.NO, DT.SYMBOL;
EXCEPTION
  WHEN OTHERS
   THEN
      PLOG.ERROR ('AP6001: ' || SQLERRM || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
      RETURN;
END;
/
