SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE BA0017(
   PV_REFCURSOR           IN OUT   PKG_REPORT.REF_CURSOR,
   OPT                    IN       VARCHAR2,
   BRID                   IN       VARCHAR2,
   PV_ISSUERS             IN       VARCHAR2,
   PV_ISSUECODE           IN       VARCHAR2,
   P_CONTRACT             IN       VARCHAR2
   )
IS
    -- BOND 17: CONG VAN THONG BAO DINH GIA LAI TSCC
    -- PERSON      DATE                 COMMENTS
    -- ---------   ------               -------------------------------------------
    -- THOAI.TRAN    19-11-2019           CREATED
    V_STROPTION    VARCHAR2 (5);       -- A: ALL; B: BRANCH; S: SUB-BRANCH
    V_STRBRID      VARCHAR2 (4);       -- USED WHEN V_NUMOPTION > 0

    V_CURRDATE      DATE;
    V_ISSUER        VARCHAR(100);
    V_CONTRACTNO    VARCHAR(100);
    V_ISSUECODE     VARCHAR(100);
BEGIN
     V_STROPTION := OPT;
     IF V_STROPTION = 'A' THEN
        V_STRBRID := '%';
     ELSIF V_STROPTION = 'B' THEN
        V_STRBRID := SUBSTR(BRID,1,2) || '__' ;
     ELSE
        V_STRBRID:=BRID;
     END IF;

    V_CURRDATE := GETCURRDATE;
    V_ISSUECODE:=PV_ISSUECODE;
    V_ISSUER:= PV_ISSUERS;
    V_CONTRACTNO:=P_CONTRACT;
OPEN PV_REFCURSOR FOR
    SELECT DISTINCT
        TO_CHAR(V_CURRDATE,'DD/MM/YYYY') CURRDATE
        ,ISS.FULLNAME FULLNAME
        ,ISE.CONTRACTNO CONTRACTNO
        ,TO_CHAR(ISE.CONTRACTDATE,'DD/MM/YYYY') CONTRACTDATE
        ,NVL(SB.THIRDPARTNER,'SASDASD') TCPH_4
        ,SB.SYMBOL SYMBOL
        ,TO_CHAR(SB.ISSUEDATE,'DD/MM/YYYY')     ISSUEDATE           --NGAY PHAT HANH
        ,TO_CHAR(SB.EXPDATE,'DD/MM/YYYY')       EXPDATE             --NGAY DAO HAN
        ,TO_CHAR(UTILS.SO_THANH_CHU(NVL(SB.VALUEOFISSUE,0)))   VALUEOFISSUE     --GIA TRI PHAT HANH
        ,TO_CHAR(SB.INTCOUPON) RATE                           --LAI SUAT
        ,TO_CHAR(GETPREVDATE(V_CURRDATE,5),'DD/MM/YYYY') EXPDATE5
        ,ISE.TYPERATE
        FROM ISSUERS ISS,SBSECURITIES SB,(SELECT DISTINCT MST.AUTOID,
 MST.ISSUESID,ISS.ISSUERID, ISS.ISSUECODE,ISS.TYPERATE, MST.CONTRACTNO, MST.CONTRACTDATE
FROM ISSUER_CONTRACTNO MST, ISSUES ISS
WHERE   ISS.AUTOID = MST.ISSUESID) ISE
        WHERE ISS.ISSUERID=SB.ISSUERID AND ISE.ISSUERID=SB.ISSUERID
        AND SB.CONTRACTNO IS NOT NULL
        AND SB.CONTRACTDATE IS NOT NULL
        AND ISS.SHORTNAME LIKE V_ISSUER
        AND ISE.ISSUECODE LIKE V_ISSUECODE
        AND ISE.AUTOID LIKE V_CONTRACTNO;
EXCEPTION
  WHEN OTHERS
   THEN
      PLOG.ERROR ('BA0017: ' || SQLERRM || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
      RETURN;
END;
/
