SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE BA601601 (
   PV_REFCURSOR           IN OUT   PKG_REPORT.REF_CURSOR,
   OPT                    IN       VARCHAR2,
   BRID                   IN       VARCHAR2,

   P_FDATE_PREVIOUS         IN       VARCHAR2,
   P_TDATE_PREVIOUS         IN       VARCHAR2,
   F_DATE                   IN       VARCHAR2,
   T_DATE                   IN       VARCHAR2,
   Report_No      IN       VARCHAR2 -- So chung tu
)
IS

    V_FDATE_PREVIOUS     DATE;
    V_TDATE_PREVIOUS       DATE;
    V_FROMDATE     DATE;
    V_TODATE       DATE;
    V_CURRDATE       DATE;

    V_STROPTION         VARCHAR2 (5);       -- A: ALL; B: BRANCH; S: SUB-BRANCH
    V_STRBRID           VARCHAR2 (4);       -- USED WHEN V_NUMOPTION > 0

BEGIN

    V_STROPTION := OPT;
    IF V_STROPTION = 'A' THEN
        V_STRBRID := '%';
    ELSIF V_STROPTION = 'B' THEN
        V_STRBRID := SUBSTR(BRID,1,2) || '__' ;
    ELSE
        V_STRBRID:= BRID;
    END IF;

    V_FDATE_PREVIOUS := TO_DATE(P_FDATE_PREVIOUS, SYSTEMNUMS.C_DATE_FORMAT);
    V_TDATE_PREVIOUS := TO_DATE(P_TDATE_PREVIOUS, SYSTEMNUMS.C_DATE_FORMAT);
    V_FROMDATE := TO_DATE(F_DATE, SYSTEMNUMS.C_DATE_FORMAT);
    V_TODATE := TO_DATE(T_DATE, SYSTEMNUMS.C_DATE_FORMAT);
    SELECT GETCURRDATE INTO V_CURRDATE FROM DUAL;

 OPEN PV_REFCURSOR
 FOR
        SELECT -- DISTINCT
                RS.FULLNAME AS NAME_TCPH,    --TEN CUA TCPH
                SB.SYMBOL,      -- MA TP
                TO_CHAR(SB.ISSUEDATE,'DD/MM/RRRR')ISSUEDATE,   --NGAY PHAT HANH TRAI PHIEU
                TO_CHAR(SB.EXPDATE,'DD/MM/RRRR')EXPDATE,     --NGAY DAO HAN TP
                TO_CHAR(UTILS.SO_THANH_CHU(NVL(SB.PARVALUE,0))) AS PARVALUE_CHU,
                ISS.VALUEOFISSUE,  --GIA TRI PHAT HANH CUA MA TP
                TO_CHAR(UTILS.SO_THANH_CHU(NVL(ISS.VALUEOFISSUE,0))) AS VALUEOFISSUE_CHU,
                SB.INTCOUPON     --LAI XUAT
        FROM SBSECURITIES SB, SEMAST SE, CFMAST CF, ISSUERS RS,BONDISSUE BI,ISSUES ISS
        WHERE SB.SECTYPE IN ('003','006')
              AND SB.ROLEOFSHV IN ('002','003','004')
              AND SB.CODEID = SE.CODEID
              AND SB.CODEID= BI.BONDCODE
              AND BI.ISSUESID = ISS.AUTOID
              AND ISS.ISSUERID = RS.ISSUERID
              AND SE.TRADE  > 0
              AND SE.CUSTID = CF.CUSTID
              AND SB.EXPDATE > v_ToDate --GETCURRDATE
        GROUP BY
                    RS.FULLNAME,
                    SB.SYMBOL,      -- MA TP
                    SB.ISSUEDATE,   --NGAY PHAT HANH TRAI PHIEU
                    SB.EXPDATE,     --NGAY DAO HAN TP
                    SB.PARVALUE,    --MENH GIA TP
                    ISS.VALUEOFISSUE,  --GIA TRI PHAT HANH CUA MA TP
                    SB.INTCOUPON     --LAI XUAT
      ;
EXCEPTION
  WHEN OTHERS
   THEN
   DBMS_OUTPUT.PUT_LINE('BA601601 ERROR');
   PLOG.ERROR('BA60160101: - ' ||DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
      RETURN;
END;
/
