SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE ba600601(
   PV_REFCURSOR           IN OUT   PKG_REPORT.REF_CURSOR,
   OPT                    IN       VARCHAR2,
   BRID                   IN       VARCHAR2,
   PV_ISSUERS             IN       VARCHAR2,
   PV_ISSUECODE           IN       VARCHAR2,
   PV_CONTRACTNO          IN       VARCHAR2,
   I_DATE                 IN       VARCHAR2
   )
IS
    -- BA600601: CONG VAN THONG BAO LAI TRAI PHIEU
    -- PERSON      DATE                 COMMENTS
    -- ---------   ------               -------------------------------------------
    -- THOAI.TRAN  22-11-2019           CREATED
    -- TRI.BUI     17-12-2019           EDDITED
    -- NAM.LY      11-03-2020           MODIFIED
    V_STROPTION    VARCHAR2 (5);       -- A: ALL; B: BRANCH; S: SUB-BRANCH
    V_STRBRID      VARCHAR2 (4);       -- USED WHEN V_NUMOPTION > 0
    V_PAYMENTDATE        DATE;
    V_CUSTODYCD          VARCHAR(20);
    V_ISSUECODE          VARCHAR(50);
    V_CURRDATE           DATE;
    V_ISSNAME            VARCHAR(20);
    V_CONTRACTNO         VARCHAR(100);
BEGIN
     V_STROPTION := OPT;
     IF V_STROPTION = 'A' THEN
        V_STRBRID := '%';
     ELSIF V_STROPTION = 'B' THEN
        V_STRBRID := SUBSTR(BRID,1,2) || '__' ;
     ELSE
        V_STRBRID:=BRID;
     END IF;
    V_PAYMENTDATE  := TO_DATE(I_DATE, SYSTEMNUMS.C_DATE_FORMAT);
    V_ISSNAME      := PV_ISSUERS;
    V_CURRDATE     := GETCURRDATE();
    V_ISSUECODE    := PV_ISSUECODE;
    V_CONTRACTNO   := PV_CONTRACTNO;
OPEN PV_REFCURSOR FOR
      SELECT
          CF.FULLNAME FUNDNAME
        , SB.SYMBOL
        , (CASE WHEN CF.IDTYPE='009' THEN CF.TRADINGCODE ELSE NVL(CF.IDCODE ,'') END) IDCODE
        , TO_CHAR(UTILS.SO_THANH_CHU(SUM(BCA.QUANTITY)))   TRADE     -- SL TP SO HUU
        , CUR.SHORTCD CCYCD
        , TO_CHAR(BT.BEGINDATE,'DD/MM/YYYY') BEGINDATE
        , TO_CHAR(V_PAYMENTDATE,'DD/MM/YYYY') PAYMENTDATE
        , TO_CHAR(V_PAYMENTDATE-BT.BEGINDATE)      NUMDATE
        , TO_CHAR(SB.INTCOUPON)||'%'   INTCOUPON--LAI SUAT
        , TO_CHAR(UTILS.SO_THANH_CHU(NVL(SB.PARVALUE,0)))    PARVALUE
        , TO_CHAR(UTILS.SO_THANH_CHU(SUM(BCA.QUANTITY) *SB.PARVALUE))    TOTAL
        , SUM(BCA.AMOUNT) AMOUNT   --LAI DUOC HUONG CHUA TRU TAX
      FROM  SBCURRENCY CUR, SBSECURITIES SB,BONDTYPEPAY BT,BONDCASCHD BCA,CFMAST CF,ISSUERS ISR,CAMAST CA, ISSUES ISS, BONDISSUE BI,
             (
                SELECT ISSUESID, CONTRACTNO, CONTRACTDATE, '%' BONDCODE
                FROM ISSUER_CONTRACTNO
                UNION ALL
                SELECT I1.AUTOID ISSUESID, SB1.CONTRACTNO, SB1.CONTRACTDATE, BI1.BONDCODE
                FROM ISSUES I1, BONDISSUE BI1, SBSECURITIES SB1
                WHERE I1.AUTOID = BI1.ISSUESID AND BI1.BONDCODE = SB1.CODEID
             ) IC
      WHERE BCA.CAMASTID = CA.CAMASTID
            AND BCA.CUSTODYCD = CF.CUSTODYCD
            AND CA.CODEID = SB.CODEID
            AND CA.CODEID = BT.BONDCODE (+)
            AND CA.CODEID = BI.BONDCODE
            AND SB.CCYCD = CUR.CCYCD
            AND BI.ISSUESID = ISS.AUTOID
            AND ISS.ISSUERID = ISR.ISSUERID
            AND IC.CONTRACTNO LIKE V_CONTRACTNO
            AND ISS.ISSUECODE LIKE V_ISSUECODE
            AND BT.PAYMENTDATE = V_PAYMENTDATE  -- LAY DU LIEU THEO PAYMENTDATE (KHI CUNG SYMBOL/CODEID KHAC DATE)
            AND ISR.SHORTNAME LIKE  V_ISSNAME
      GROUP BY SB.SYMBOL,CF.FULLNAME,CF.IDTYPE,CF.TRADINGCODE,CF.IDCODE,CUR.SHORTCD,BT.BEGINDATE,SB.INTCOUPON,SB.PARVALUE,BI.BONDSYMBOL ;
EXCEPTION
  WHEN OTHERS
   THEN
      PLOG.ERROR ('BA600601: ' || SQLERRM || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
      RETURN;
END;
/
