SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE ba6006(
   PV_REFCURSOR           IN OUT   PKG_REPORT.REF_CURSOR,
   OPT                    IN       VARCHAR2,
   BRID                   IN       VARCHAR2,
   PV_ISSUERS             IN       VARCHAR2,
   PV_ISSUECODE           IN       VARCHAR2,
   PV_CONTRACTNO          IN       VARCHAR2,
   I_DATE                 IN       VARCHAR2
   )
IS
    -- BA6006: CONG VAN THONG BAO LAI TRAI PHIEU
    -- PERSON      DATE                 COMMENTS
    -- ---------   ------               -------------------------------------------
    -- THOAI.TRAN    22-11-2019           CREATED
    -- NAM.LY        05-02-2020           EDIT
    V_STROPTION    VARCHAR2 (5);       -- A: ALL; B: BRANCH; S: SUB-BRANCH
    V_STRBRID      VARCHAR2 (4);       -- USED WHEN V_NUMOPTION > 0
    V_ISSUECODE          VARCHAR(50);
    V_PAYMENTDATE        DATE;
    V_CURRDATE           DATE;
    V_ISSNAME            VARCHAR(20);
    V_CONTRACTNO         VARCHAR(100);
BEGIN
    V_STROPTION := OPT;
    IF V_STROPTION = 'A' THEN
        V_STRBRID := '%';
    ELSIF V_STROPTION = 'B' THEN
        V_STRBRID := SUBSTR(BRID,1,2) || '__' ;
    ELSE
        V_STRBRID:=BRID;
    END IF;
     --
    V_PAYMENTDATE  := TO_DATE(I_DATE, SYSTEMNUMS.C_DATE_FORMAT);
    V_ISSNAME      := PV_ISSUERS;
    V_CURRDATE     := GETCURRDATE();
    V_CONTRACTNO   := PV_CONTRACTNO;
    V_ISSUECODE    := PV_ISSUECODE;
OPEN PV_REFCURSOR FOR
        SELECT DISTINCT
              TO_CHAR(V_CURRDATE,'DD/MM/YYYY') CURRDATE
             , ISR.FULLNAME
             , IC.CONTRACTNO
             , TO_CHAR(IC.CONTRACTDATE,'DD/MM/YYYY') CONTRACTDATE
             , NVL(SB.THIRDPARTNER,'THIRDPARTNER')  THIRDPARTNER
             , SB.SYMBOL
             , TO_CHAR(SB.ISSUEDATE,'DD/MM/YYYY')  ISSUEDATE
             , TO_CHAR(SB.EXPDATE,'DD/MM/YYYY')    EXPDATE
             , TO_CHAR(UTILS.SO_THANH_CHU(NVL(BI.VALUEOFISSUE,0))) VALUEOFISSUE --GIA TRI PHAT HANGH 'VND 54,545,324'
             , TO_CHAR(SB.INTCOUPON)   INTCOUPON--LAI SUAT
             --, AL.CDCONTENT PERIODINTEREST --DINH KY TRA LAI
             , TO_CHAR(BT.BEGINDATE,'DD/MM/YYYY') BEGINDATE
             , TO_CHAR(BT.PAYMENTDATE,'DD/MM/YYYY') PAYMENTDATE
             , TO_CHAR(GETPREVDATE(V_PAYMENTDATE, 2),'DD/MM/YYYY') PREVDATE2
             , BT.BONDEVENT
             , TO_CHAR(ABS(FLOOR(MONTHS_BETWEEN(BT.BEGINDATE, BT.PAYMENTDATE)))) PERIODINTEREST
        FROM SBSECURITIES SB, ISSUERS ISR, BONDTYPEPAY BT, ISSUES ISS, BONDISSUE BI, ALLCODE AL,
             (
                SELECT ISSUESID, CONTRACTNO, CONTRACTDATE, '%' BONDCODE
                FROM ISSUER_CONTRACTNO
                UNION ALL
                SELECT I1.AUTOID ISSUESID, SB1.CONTRACTNO, SB1.CONTRACTDATE, BI1.BONDCODE
                FROM ISSUES I1, BONDISSUE BI1, SBSECURITIES SB1
                WHERE I1.AUTOID = BI1.ISSUESID AND BI1.BONDCODE = SB1.CODEID
             ) IC
        WHERE ISS.ISSUERID = ISR.ISSUERID AND
              ISS.AUTOID = BI.ISSUESID AND
              ISS.AUTOID = IC.ISSUESID(+) AND
              BI.BONDCODE LIKE IC.BONDCODE AND
              BI.BONDCODE = BT.BONDCODE(+) AND
              BI.BONDCODE = SB.CODEID AND
              AL.CDNAME = 'PERIODINTEREST' AND AL.CDVAL(+) = SB.PERIODINTEREST AND AL.CDTYPE = 'CB' AND
              ISR.SHORTNAME LIKE  V_ISSNAME AND
              ISS.ISSUECODE LIKE V_ISSUECODE AND
              IC.CONTRACTNO LIKE V_CONTRACTNO AND
              BT.PAYMENTDATE = V_PAYMENTDATE
        GROUP BY ISR.FULLNAME, IC.CONTRACTNO, IC.CONTRACTDATE, SB.THIRDPARTNER, SB.SYMBOL, SB.ISSUEDATE,
                 SB.EXPDATE, BI.VALUEOFISSUE, SB.INTCOUPON, AL.CDCONTENT, BT.BEGINDATE, BT.PAYMENTDATE, BT.BONDEVENT;
EXCEPTION
  WHEN OTHERS
   THEN
      PLOG.ERROR ('BA6006: ' || SQLERRM || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
      RETURN;
END;
/
