SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE bo1001 (
   PV_REFCURSOR   IN OUT   PKG_REPORT.REF_CURSOR,
   OPT            IN       VARCHAR2,
   BRID           IN       VARCHAR2,
   F_DATE         IN       VARCHAR2,
   T_DATE         IN       VARCHAR2,
   PV_CUSTODYCD   IN       VARCHAR2,
   EXECTYPE       IN       VARCHAR2
)
IS
--
-- PURPOSE: BRIEFLY EXPLAIN THE FUNCTIONALITY OF THE PROCEDURE
-- DANH SACH NGUOI SO HUU CHUNG KHOAN  LUU KY
-- MODIFICATION HISTORY
-- PERSON      DATE    COMMENTS
-- NAMNT   20-DEC-06  CREATED
-- ---------   ------  -------------------------------------------
   V_STROPTION     VARCHAR2 (5);            -- A: ALL; B: BRANCH; S: SUB-BRANCH
   V_STRBRID       VARCHAR2 (4);                   -- USED WHEN V_NUMOPTION > 0
   V_STRAFACCTNO   VARCHAR2 (20);
   V_STRSYMBOL     VARCHAR2 (20);

   V_TDATE            DATE;
   V_FDATE           DATE;
    V_CUSTODYCD VARCHAR2 (20);
    V_EXECTYPE VARCHAR2 (20);
BEGIN

   V_STROPTION := OPT;

  IF V_STROPTION = 'A' then
      V_STRBRID := '%';
  ELSIF V_STROPTION = 'B' then
      V_STRBRID := substr(BRID,1,2) || '__' ;
  else
      V_STRBRID:=BRID;
  END IF;

IF UPPER(PV_CUSTODYCD) = 'ALL' THEN
    V_CUSTODYCD:='%';
ELSE
    V_CUSTODYCD:=PV_CUSTODYCD;
END IF;


IF UPPER(EXECTYPE) = 'ALL' THEN
    V_EXECTYPE:= '%';
ELSE
    V_EXECTYPE:= EXECTYPE;
END IF;

 -- GET REPORT'S PARAMETERS
    V_TDATE := TO_DATE(T_DATE,'DD/MM/RRRR');
    V_FDATE := TO_DATE(F_DATE,'DD/MM/RRRR');
 -- END OF GETTING REPORT'S PARAMETERS

  -- GET REPORT'S DATA

OPEN PV_REFCURSOR
     FOR
SELECT to_char(MST.TRANSDATE,'MM') ismonth, MST.AUTOID, A0.CDCONTENT STATUS,
    (CASE WHEN MST.DEALTYPE='S' THEN A1.CDCONTENT ELSE A1.CDCONTENT || ': ' || A2.CDCONTENT END) DEALTYPE,
    MST.CUSTID, MST.TRANSDATE, SB.SYMBOL, iss.fullname iss_fullname, a3.CDCONTENT BONDTYPE,
    MST.QTTY, MST.QTTY*MST.PRICE AMT, mst.feebrk feerate, mst.feeexc feevsd, mst.feecomm feehh,
    mst.feersv TL_KHTH, MST.NOTES, CF.FULLNAME, MST.PRICE, A4.CDCONTENT SHAREUNIT
FROM BONDDEAL MST, CFMAST CF, SBSECURITIES SB, ALLCODE A0, ALLCODE A1, ALLCODE A2,
    (SELECT CUSTID, FULLNAME FROM CFMAST UNION ALL SELECT 'NULL' CUSTID, '---' FULLNAME FROM DUAL) RCF,
    ISSUERS iss, ALLCODE A3, ALLCODE A4
WHERE MST.CUSTID=CF.CUSTID AND MST.CODEID=SB.CODEID AND NVL(MST.PCUSTID,'NULL') = RCF.CUSTID
    AND A0.CDTYPE='SY' AND A0.CDNAME='TYPESTS' AND A0.CDVAL=MST.STATUS
    AND A1.CDTYPE='SA' AND A1.CDNAME='DEALTYPE' AND A1.CDVAL=MST.DEALTYPE
    AND A2.CDTYPE='SA' AND A2.CDNAME='BONDBORS' AND A2.CDVAL=MST.BORS
    AND A4.CDTYPE='SA' AND A4.CDNAME='SHAREUNIT' AND A4.CDVAL=MST.SHAREUNIT
    AND MST.DEALTYPE='P' and sb.issuerid=iss.issuerid
    and A3.CDTYPE = 'SA' AND A3.CDNAME = 'BONDTYPE' AND A3.CDUSER='Y'
    and sb.bondtype = A3.cdval
    AND CF.CUSTODYCD LIKE V_CUSTODYCD
    AND MST.BORS LIKE V_EXECTYPE
    AND NVL(MST.TRANSDATE,TO_DATE('01/01/2009','DD/MM/RRRR')) <= V_TDATE
    AND NVL(MST.TRANSDATE,TO_DATE('01/01/2009','DD/MM/RRRR')) >= V_FDATE
    ;

EXCEPTION
   WHEN OTHERS
   THEN
      RETURN;
END;                                                              -- PROCEDURE

 
 
 
 
 
/
