SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE ca0033 (
   PV_REFCURSOR   IN OUT   PKG_REPORT.REF_CURSOR,
   OPT            IN       VARCHAR2,
   BRID           IN       VARCHAR2,
   PV_CAMASTID        IN       VARCHAR2
)
IS
    L_CAMASTID VARCHAR2(100);
BEGIN
    L_CAMASTID := REPLACE(PV_CAMASTID, '.', '');

    OPEN PV_REFCURSOR FOR
    SELECT DEM.FULLNAME DEPOSITNAME, DEM.DEPOSITID, SB.SYMBOL, SB.BONDNAME, CAS.*,
       (CAS.P_TRADE + CAS.C_TRADE + CAS.F_TRADE) TOTAL_TRADE,
       (CAS.P_AQTTY + CAS.C_AQTTY + CAS.F_AQTTY) TOTAL_AQTTY,
       (CAS.P_QTTY + CAS.C_QTTY + CAS.F_QTTY) TOTAL_QTTY,
       (CAS.P_REMAIN_QTTY + CAS.C_REMAIN_QTTY + CAS.F_REMAIN_QTTY) TOTAL_REMAIN_QTTY
    FROM CAMAST CA, DEPOSIT_MEMBER DEM,
    (SELECT * FROM SYSVAR WHERE VARNAME = 'DEPOSITID') DEP,
    (SELECT * FROM SBSECURITIES WHERE TRADEPLACE = '099') SB,
    (
        SELECT CAS.CAMASTID,
            SUM(CASE WHEN CF.CFTYPE = 'P' THEN CAS.TRADE ELSE 0 END) P_TRADE,
            SUM(CASE WHEN CF.CFTYPE = 'P' THEN CAS.AQTTY ELSE 0 END) P_AQTTY,
            SUM(CASE WHEN CF.CFTYPE = 'P' THEN CAS.QTTY ELSE 0 END) P_QTTY,
            SUM(CASE WHEN CF.CFTYPE = 'P' THEN CAS.TRADE - CAS.QTTY ELSE 0 END) P_REMAIN_QTTY,

            SUM(CASE WHEN CF.CFTYPE = 'C' THEN CAS.TRADE ELSE 0 END) C_TRADE,
            SUM(CASE WHEN CF.CFTYPE = 'C' THEN CAS.AQTTY ELSE 0 END) C_AQTTY,
            SUM(CASE WHEN CF.CFTYPE = 'C' THEN CAS.QTTY ELSE 0 END) C_QTTY,
            SUM(CASE WHEN CF.CFTYPE = 'C' THEN CAS.TRADE - CAS.QTTY ELSE 0 END) C_REMAIN_QTTY,

            SUM(CASE WHEN CF.CFTYPE = 'F' THEN CAS.TRADE ELSE 0 END) F_TRADE,
            SUM(CASE WHEN CF.CFTYPE = 'F' THEN CAS.AQTTY ELSE 0 END) F_AQTTY,
            SUM(CASE WHEN CF.CFTYPE = 'F' THEN CAS.QTTY ELSE 0 END) F_QTTY,
            SUM(CASE WHEN CF.CFTYPE = 'F' THEN CAS.TRADE - CAS.QTTY ELSE 0 END) F_REMAIN_QTTY
        FROM CASCHD CAS, AFMAST AF,
        (
            SELECT CF.*, (CASE WHEN SUBSTR(CUSTODYCD,1,4) = SYS.VARVALUE THEN 'P' ELSE DECODE(CF.COUNTRY, '234', 'C', 'F') END) CFTYPE
            FROM CFMAST CF,
            (SELECT VARVALUE FROM SYSVAR WHERE VARNAME = 'DEALINGCUSTODYCD') SYS
            WHERE CF.STATUS NOT IN ('C')
        ) CF
        WHERE CF.CUSTID = AF.CUSTID
        AND AF.ACCTNO = CAS.AFACCTNO
        AND CAS.STATUS NOT IN ('C')
        AND CAS.DELTD = 'N'
        GROUP BY CAS.CAMASTID
    ) CAS
    WHERE DEM.DEPOSITID = DEP.VARVALUE
    AND CA.CODEID = SB.CODEID
    AND CA.CATYPE = '040'
    AND CA.CAMASTID = CAS.CAMASTID
    AND CA.CAMASTID = L_CAMASTID;


EXCEPTION WHEN OTHERS THEN
    PLOG.ERROR ('CA0033: ' || SQLERRM || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    RETURN;
END;
/
