SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE ca6015 (
   PV_REFCURSOR   IN OUT   PKG_REPORT.REF_CURSOR,
   OPT            IN       VARCHAR2,
   PV_BRID        IN       VARCHAR2,
   CACODE         IN       VARCHAR2, --MA SU KIEN
   P_NUMBER      IN  VARCHAR2,
   PLSENT         IN       VARCHAR2 -- NOI GUI
   )
IS
    -- THONG BAO XAC NHAN PHONG TOA TRAI PHIEU DANG KY CHUYEN DOI (MAU 32A-THQ)
    -- person      date                 comments
    -- ---------   ------               -------------------------------------------
    -- NAM.LY    12-11-2019           created
    V_STROPTION    VARCHAR2 (5);       -- A: ALL; B: BRANCH; S: SUB-BRANCH
    V_STRBRID      VARCHAR2 (4);       -- USED WHEN V_NUMOPTION > 0
-----------------------------------------------

    V_STRCACODE   VARCHAR2 (20);
    V_NUMBER   VARCHAR2 (20);
BEGIN
    V_STRCACODE :=  CACODE;
    V_NUMBER :=P_NUMBER;


-- GET REPORT'S PARAMETERS
OPEN PV_REFCURSOR
   FOR
       SELECT PLSENT PLSENT
            ,V_NUMBER as PNUMBER
            ,EXTRACT(YEAR FROM  getcurrdate) year
            , SB1.FULLNAME BOND_NAME --TEN TRAI PHIEU
            , SB1.SYMBOL BOND_CODE --MA TRAI PHIEU
            , Replace(utils.so_thanh_chu(CA.PARVALUE),',','.') BOND_PARVALUE --MENH GIA
            , SB2.FULLNAME STOCK_NAME --TEN CO PHIEU DA DUOC CHUYEN DOI
            , SB2.SYMBOL STOCK_CODE --MA CO PHIEU DA DUOC CHUYEN DOI
            , TO_CHAR(CA.REPORTDATE,'DD/MM/RRRR') REPORTDATE  --NGAY DANG KY CUOI CUNG
            , REPLACE(CA.EXRATE,'/',':') EXRATE --TY LE CHUYEN DOI TRAI PHIEU THANH CO PHIEU
            , TO_NUMBER(CA.INTERESTRATE)INTERESTRATE --TY LE THANH TOAN TRAI PHIEU BANG TIEN
            --, CA.EXPRICE --GIA QUY DOI CO PHIEU LE
            , Replace(utils.so_thanh_chu(CASE WHEN CA.CATYPE IN ('023') THEN TO_NUMBER(NVL(CA.FRACTIONALSHARE,0)) ELSE CA.EXPRICE END),',','.') EXPRICE-- GIA QUY DOI CO PHIEU LE = MENH GIA CO PHIEU (GIANG.PHAM TESTED)
            , Replace(utils.so_thanh_chu(SB2.PARVALUE),',','.') STOCK_PARVALUE--MENH GIA CO PHIEU
            , AL1.CDCONTENT NATIONALITY --QUOC TICH
            , CF.FULLNAME --HO TEN
            , (CASE WHEN CF.IDTYPE='009' THEN NVL(CF.TRADINGCODE ,'') ELSE NVL(CF.IDCODE ,'') END) IDCODE --SO DANG KY SO HUU
            , TO_CHAR((CASE WHEN CF.IDTYPE='009' THEN NVL(CF.TRADINGCODEDT ,'') ELSE NVL(CF.IDDATE ,'') END),'DD/MM/RRRR')  IDDATE --NGAY CAP
            , CF.CUSTODYCD --SO TAI KHOAN GIAO DICH
            , CA.CAMASTID
            , SUM(CAS.TRADE)  TRADE--SO LUONG TRAI PHIEU SO HUU
            , SUM((CAS.TRADE - CAS.BALANCE)) EXQTTY --SO LUONG TRAI PHIEU DANG KY THUC HIEN CHUYEN DOI THANH CO PHIEU
            , SUM(CAS.BALANCE) BALANCE --SO LUONG TRAI PHIEU DANG KY THUC HIEN THANH TOAN BANG TIEN
            , CASE WHEN SUBSTR (CF.CUSTODYCD,4,1) IN ('C','B') THEN 'C' ELSE
              CASE WHEN SUBSTR (CF.CUSTODYCD,4,1) = 'F' THEN 'F' ELSE
              CASE WHEN SUBSTR (CF.CUSTODYCD,4,1) IN ('P','A') THEN 'P' END END END CUSTODYCD_TYPE --TRONG NUOC/NUOC NGOAI/TU DOANH
            , CASE WHEN SUBSTR (CF.CUSTODYCD,4,1) IN ('C','B') THEN 'I' ELSE
              CASE WHEN SUBSTR (CF.CUSTODYCD,4,1) = 'F' THEN 'II' ELSE
              CASE WHEN SUBSTR (CF.CUSTODYCD,4,1) IN ('P','A') THEN 'III' END END END GROUP_ID1 --STT NHOM 1
            , UPPER(AL3.CDCONTENT) GROUP_NAME1 --TEN NHOM 1: TRONG NUOC/NUOC NGOAI/TU DOANH
            , CASE WHEN SUBSTR (CF.CUSTODYCD,4,1) IN ('P','A') THEN '' ELSE
                   (CASE CF.CUSTTYPE
                         WHEN 'I' THEN '1'
                         WHEN 'B' THEN '2'
                         ELSE '0' END) END GROUP_ID2 --STT NHOM 2
            , CASE WHEN SUBSTR (CF.CUSTODYCD,4,1) IN ('P','A') THEN '' ELSE AL2.CDCONTENT END GROUP_NAME2 --TEN NHOM 2: LOAI KHACH HANG
       FROM CAMAST CA
            LEFT JOIN CASCHD CAS ON CA.CAMASTID = CAS.CAMASTID
            LEFT JOIN (SELECT ISSUERS.FULLNAME, SB.* FROM SBSECURITIES SB, ISSUERS WHERE SB.ISSUERID = ISSUERS.ISSUERID) SB1 ON CA.CODEID = SB1.CODEID
            LEFT JOIN (SELECT ISSUERS.FULLNAME, SB.* FROM SBSECURITIES SB, ISSUERS WHERE SB.ISSUERID = ISSUERS.ISSUERID) SB2 ON CA.TOCODEID = SB2.CODEID
            LEFT JOIN AFMAST AF ON CAS.AFACCTNO = AF.ACCTNO
            LEFT JOIN VW_CFMAST_M CF ON AF.CUSTID = CF.CUSTID
            LEFT JOIN ALLCODE AL1 ON CF.COUNTRY = AL1.CDVAL AND AL1.CDNAME ='COUNTRY' AND AL1.CDTYPE ='CF'
            LEFT JOIN ALLCODE AL2 ON CF.CUSTTYPE = AL2.CDVAL AND AL2.CDNAME ='CUSTTYPE' AND AL2.CDTYPE ='CF'
            LEFT JOIN ALLCODE AL3 ON (CASE WHEN SUBSTR (CF.CUSTODYCD,4,1) IN ('C','B') THEN 'B' ELSE
                                      CASE WHEN SUBSTR (CF.CUSTODYCD,4,1) = 'F' THEN 'F' ELSE
                                      CASE WHEN SUBSTR (CF.CUSTODYCD,4,1) IN ('P','A') THEN 'P' END END END) = AL3.CDVAL
                                      AND AL3.CDNAME ='TYPELG' AND AL3.CDTYPE ='CF'
       WHERE CF.CUSTTYPE IN ('I','B') AND
             CA.CAMASTID = V_STRCACODE AND
             CA.CATYPE IN ('023') AND
             cas.deltd <> 'Y' and
             CA.STATUS IN ('V')
        GROUP BY SB1.FULLNAME
            , SB1.SYMBOL
            , CA.PARVALUE
            , SB2.FULLNAME
            , SB2.SYMBOL
            , CA.REPORTDATE
            , CA.EXRATE
            , CA.INTERESTRATE
            , SB2.PARVALUE
            , AL1.CDCONTENT
            , CF.FULLNAME
            , CF.IDTYPE
            , CF.TRADINGCODE
            , CF.IDCODE
            , CF.TRADINGCODEDT
            , CF.IDDATE
            , CF.CUSTTYPE
            , AL3.CDCONTENT
            , AL2.CDCONTENT
            , CF.CUSTODYCD --SO TAI KHOAN GIAO DICH
            , CA.CAMASTID
            , (CASE WHEN CA.CATYPE IN ('023') THEN TO_NUMBER(NVL(CA.FRACTIONALSHARE,0)) ELSE CA.EXPRICE END);
EXCEPTION
  WHEN OTHERS
   THEN

      PLOG.ERROR ('CA6015: ' || SQLERRM || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
      RETURN;
END;
/
