SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE ca6017 (
    PV_REFCURSOR          IN OUT   PKG_REPORT.REF_CURSOR,
    OPT                   IN       VARCHAR2,
    BRID                  IN       VARCHAR2,
    CACODE                IN       VARCHAR2, --MA SU KIEN
    PLSENT                IN       VARCHAR2 -- NOI GUI
   )
IS
    -- GIAY ÐE NGHI PHONG TOA VÀ ÐANG KY CHUYEN ÐOI TRAI PHIEU CHUYEN ÐOI (MAU 33B-THQ)
    -- PERSON      DATE                 COMMENTS
    -- ---------   ------               -------------------------------------------
    -- THOAI.TRAN    15-11-2019           CREATED
    V_STROPTION    VARCHAR2 (5);       -- A: ALL; B: BRANCH; S: SUB-BRANCH
    V_STRBRID      VARCHAR2 (4);       -- USED WHEN V_NUMOPTION > 0
-----------------------------------------------

    V_STRCACODE     VARCHAR2 (20);
    V_PLSENT        VARCHAR(200);
    V_OFFICE        VARCHAR(200);
    V_COMPANYCD     VARCHAR(200);
BEGIN
     V_STROPTION := OPT;
         IF V_STROPTION = 'A' THEN
            V_STRBRID := '%';
         ELSIF V_STROPTION = 'B' THEN
            V_STRBRID := SUBSTR(BRID,1,2) || '__' ;
         ELSE
            V_STRBRID:=BRID;
         END IF;
    V_STRCACODE :=  CACODE;
    -- LAY THONG TIN CUA SHV
     SELECT MAX(CASE WHEN  VARNAME='HEADOFFICE' THEN VARVALUE ELSE '' END),
           MAX(CASE WHEN  VARNAME='DEPOSITID' THEN VARVALUE ELSE '' END)
            INTO  V_OFFICE, V_COMPANYCD
        FROM SYSVAR WHERE VARNAME IN ('DEPOSITID','HEADOFFICE');
     V_PLSENT := PLSENT;
-- GET REPORT'S PARAMETERS
OPEN PV_REFCURSOR FOR
        SELECT
            V_OFFICE OFFICE,
            V_COMPANYCD COMPANYCD,
            FULLNAME,
            V_PLSENT PLSENT,
            SYMBOL,
            -- SO HUU
            SUM(TRADE_TN) TRADE_TN,
            SUM(TRADE_NN) TRADE_NN,
            SUM(TRADE_TD) TRADE_TD,
            SUM(TRADE_TN)+SUM(TRADE_NN)+SUM(TRADE_TD) TOTAL_TRADE,
            --
            SUM(AQTTY_TN) AQTTY_TN,
            SUM(AQTTY_NN) AQTTY_NN,
            SUM(AQTTY_TD) AQTTY_TD,
             SUM(AQTTY_TN)+SUM(AQTTY_NN)+SUM(AQTTY_TD) TOTAL_AQTTY,
            --
            SUM(EXQTTY_TN) EXQTTY_TN,
            SUM(EXQTTY_NN) EXQTTY_NN,
            SUM(EXQTTY_TD) EXQTTY_TD,
            SUM(EXQTTY_TN)+SUM(EXQTTY_NN)+SUM(EXQTTY_TD) TOTAL_EXQTTY,
            --
            SUM(BALANCE_TN) BALANCE_TN,
            SUM(BALANCE_NN) BALANCE_NN,
            SUM(BALANCE_TD) BALANCE_TD,
            SUM(BALANCE_TN)+SUM(BALANCE_NN)+SUM(BALANCE_TD) TOTAL_BALANCE
        FROM
        (
            SELECT ISS.FULLNAME, SB.SYMBOL,
                --TRAI PHIEU SO HUU
                (CASE WHEN SUBSTR (CF.CUSTODYCD,4,1) IN ('C','B') THEN SUM(CS.TRADE) ELSE 0 END) TRADE_TN,
                (CASE WHEN SUBSTR (CF.CUSTODYCD,4,1) = 'F' THEN SUM(CS.TRADE) ELSE 0 END) TRADE_NN,
                (CASE WHEN SUBSTR (CF.CUSTODYCD,4,1)IN ('P','A','E') THEN SUM(CS.TRADE) ELSE 0 END) TRADE_TD,
                -- TRAI PHIEU DUOC CHUYEN DOI
                (CASE WHEN SUBSTR (CF.CUSTODYCD,4,1) IN ('C','B') THEN SUM(CS.AQTTY) ELSE 0 END) AQTTY_TN, --CHECK LAI
                (CASE WHEN SUBSTR (CF.CUSTODYCD,4,1) = 'F'  THEN SUM(CS.AQTTY) ELSE 0 END) AQTTY_NN,
                (CASE WHEN SUBSTR (CF.CUSTODYCD,4,1)IN ('P','A','E') THEN SUM(CS.AQTTY) ELSE 0 END)  AQTTY_TD, --CHECK LAI
                -- TRAI PHIEU DANG KY CHUYEN DOI THANH CO PHIEU
                (CASE WHEN SUBSTR (CF.CUSTODYCD,4,1) IN ('C','B')THEN SUM(CS.AQTTY - CS.BALANCE) ELSE 0 END) EXQTTY_TN,
                (CASE WHEN SUBSTR (CF.CUSTODYCD,4,1) = 'F' THEN SUM(CS.AQTTY - CS.BALANCE) ELSE 0 END) EXQTTY_NN,
                (CASE WHEN SUBSTR (CF.CUSTODYCD,4,1)IN ('P','A','E') THEN SUM(CS.AQTTY - CS.BALANCE) ELSE 0 END)  EXQTTY_TD,
                -- TRAI PHIEU THANH TOAN BANG TIEN MAT
                (CASE WHEN SUBSTR (CF.CUSTODYCD,4,1) IN ('C','B') THEN SUM(CS.BALANCE) ELSE 0 END) BALANCE_TN,
                (CASE WHEN SUBSTR (CF.CUSTODYCD,4,1) = 'F' THEN SUM(CS.BALANCE) ELSE 0 END) BALANCE_NN,
                (CASE WHEN SUBSTR (CF.CUSTODYCD,4,1)IN ('P','A','E') THEN SUM(CS.BALANCE) ELSE 0 END)   BALANCE_TD
            FROM CAMAST CA, CASCHD CS, SBSECURITIES SB, ISSUERS ISS,CFMAST CF, AFMAST AF
            WHERE CF.CUSTID=AF.CUSTID AND CS.AFACCTNO=AF.ACCTNO
            AND CA.CAMASTID=CS.CAMASTID
            AND SB.ISSUERID =ISS.ISSUERID
            AND CA.CODEID=SB.CODEID
            AND CA.CATYPE ='023'
            AND CA.DELTD = 'N'
            AND CS.DELTD = 'N'
            AND CA.CAMASTID LIKE V_STRCACODE
            GROUP BY CF.COUNTRY,ISS.FULLNAME, SB.SYMBOL,CF.CUSTODYCD
        ) MST
        GROUP BY FULLNAME,SYMBOL;
EXCEPTION
  WHEN OTHERS
   THEN
      PLOG.ERROR ('CA6017: ' || SQLERRM || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
      RETURN;
END;
/
