SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE cf0012(
   PV_REFCURSOR   IN OUT   PKG_REPORT.REF_CURSOR,
   OPT            IN       VARCHAR2,
   BRID           IN       VARCHAR2,
   F_DATE         IN       VARCHAR2,
   T_DATE         IN       VARCHAR2,
   CIACCTNO       IN       VARCHAR2
)
IS
--
-- PURPOSE: BRIEFLY EXPLAIN THE FUNCTIONALITY OF THE PROCEDURE
--
-- MODIFICATION HISTORY
-- PERSON      DATE    COMMENTS
-- NAMNT  08-OCT-07  CREATED
-- ---------   ------  -------------------------------------------
   V_STROPTION        VARCHAR2 (5);       -- A: ALL; B: BRANCH; S: SUB-BRANCH
   V_STRBRID          VARCHAR2 (4);              -- USED WHEN V_NUMOPTION > 0
   V_CIACCTNO           VARCHAR2 (20);
-- DECLARE PROGRAM VARIABLES AS SHOWN ABOVE
BEGIN
-- INSERT INTO TEMP_BUG(TEXT) VALUES('CF0001');COMMIT;
   V_STROPTION := OPT;

   IF (V_STROPTION <> 'A') AND (BRID <> 'ALL')
   THEN
      V_STRBRID := BRID;
   ELSE
      V_STRBRID := '%%';
   END IF;

   -- GET REPORT'S PARAMETERS
   IF (CIACCTNO <> 'ALL')
   THEN
      V_CIACCTNO := CIACCTNO;
   ELSE
      V_CIACCTNO := '%%';
   END IF;


   -- END OF GETTING REPORT'S PARAMETERS
   -- GET REPORT'S DATA

      OPEN PV_REFCURSOR
       FOR
         SELECT CIIN.ACCTNO,INTAMT,FRDATE,TODATE,INTBAL, IRRATE, CF.FULLNAME,TO_CHAR (TODATE,'MM/YYYY') MM
         FROM DDINTTRAN CIIN,
         (SELECT * FROM AFMAST WHERE ACCTNO LIKE V_CIACCTNO )AF,
         (SELECT * FROM CFMAST ) CF
         WHERE TODATE <= TO_DATE(T_DATE ,'DD/MM/YYYY')
         AND TODATE>= TO_DATE(F_DATE ,'DD/MM/YYYY')
         AND AF.ACCTNO =CIIN.ACCTNO
         AND AF.CUSTID=CF.CUSTID
         AND CIIN.INTTYPE ='OD'
                  UNION ALL
           SELECT CIIN.ACCTNO,INTAMT,FRDATE,TODATE,INTBAL, IRRATE, CF.FULLNAME,TO_CHAR (TODATE,'MM/YYYY') MM
         FROM DDINTTRANA CIIN,
         (SELECT * FROM AFMAST WHERE ACCTNO LIKE V_CIACCTNO )AF,
         (SELECT * FROM CFMAST ) CF
         WHERE TODATE <= TO_DATE(T_DATE ,'DD/MM/YYYY')
         AND TODATE>= TO_DATE(F_DATE ,'DD/MM/YYYY')
         AND AF.ACCTNO =CIIN.ACCTNO
         AND AF.CUSTID=CF.CUSTID
         AND CIIN.INTTYPE ='OD'
         ORDER BY TODATE



         ;
 EXCEPTION
   WHEN OTHERS
   THEN
    --INSERT INTO TEMP_BUG(TEXT) VALUES('CF0001');COMMIT;
      RETURN;
END;                                                              -- PROCEDURE
/
