SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE cf2001 (
   PV_REFCURSOR   IN OUT   PKG_REPORT.REF_CURSOR,
   OPT            IN       VARCHAR2,
   PV_BRID           IN       VARCHAR2,
   I_DATE         IN       VARCHAR2,
   PV_CUSTODYCD   IN       VARCHAR2,
   I_BRIDGD       IN       VARCHAR2,
   I_FULLNAME     IN       VARCHAR2,
   I_IDCODE       IN       VARCHAR2,
   I_IDDATE       IN       VARCHAR2,
   I_ADDRESS      IN       VARCHAR2,
   I_CUSTTYPE     IN       VARCHAR2,
   I_COUNTRY      IN       VARCHAR2
 )
IS
--
-- BAO CAO THAY DOI THONG TIN KHACH HANG
-- MODIFICATION HISTORY
-- PERSON      DATE    COMMENTS
-- NGOCVTT   22/04/15  CREATED
-- ---------   ------  -------------------------------------------
   V_STROPTION        VARCHAR2 (5);       -- A: ALL; B: BRANCH; S: SUB-BRANCH
   V_STRBRID          VARCHAR2 (4);        -- USED WHEN V_NUMOPTION > 0
   V_busdate             DATE;
   v_inBRID          VARCHAR2 (4);
   V_STRCUSTODYCD    VARCHAR2 (20);
   V_BRNAME          VARCHAR2(500);
   V_I_BRID          VARCHAR2 (20);
   V_FULLNAME         VARCHAR2 (20);
   V_IDCODE           VARCHAR2 (20);
   V_IDDATE           VARCHAR2 (20);
   V_ADDRESS          VARCHAR2 (20);
   V_CUSTTYPE         VARCHAR2 (20);

   V_COUNTRY          VARCHAR2 (20);
   v_BRNAME1          VARCHAR2 (200);
BEGIN

   V_STROPTION := OPT;

   IF (V_STROPTION <> 'A') AND (PV_BRID <> 'ALL')
   THEN
      V_STRBRID := PV_BRID;
   ELSE
      V_STRBRID := '%%';
   END IF;

   v_inBRID := PV_BRID;

   if(PV_CUSTODYCD is null or upper(PV_CUSTODYCD) = 'ALL')
   then
        V_STRCUSTODYCD := '%';
   else
        V_STRCUSTODYCD := upper(PV_CUSTODYCD);
   end if;

      if(I_BRIDGD is null or upper(I_BRIDGD) = 'ALL')
   then
        V_I_BRID := '%';
   else
        V_I_BRID := upper(I_BRIDGD);
   end if;

      if(I_FULLNAME is null or upper(I_FULLNAME) = 'ALL')
   then
        V_FULLNAME := '%';
   else
        V_FULLNAME := upper(I_FULLNAME);
   end if;

         if(I_IDCODE is null or upper(I_IDCODE) = 'ALL')
   then
        V_IDCODE := '%';
   else
        V_IDCODE := upper(I_IDCODE);
   end if;

         if(I_IDDATE is null or upper(I_IDDATE) = 'ALL')
   then
        V_IDDATE := '%';
   else
        V_IDDATE := upper(I_IDDATE);
   end if;

         if(I_ADDRESS is null or upper(I_ADDRESS) = 'ALL')
   then
        V_ADDRESS := '%';
   else
        V_ADDRESS := upper(I_ADDRESS);
   end if;

         if(I_CUSTTYPE is null or upper(I_CUSTTYPE) = 'ALL')
   then
        V_CUSTTYPE := '%';
   else
        V_CUSTTYPE := upper(I_CUSTTYPE);
   end if;


         if(I_COUNTRY is null or upper(I_COUNTRY) = 'ALL')
   then
        V_COUNTRY := '%';
   else
        V_COUNTRY := upper(I_COUNTRY);
   end if;

   SELECT BRNAME INTO V_BRNAME FROM BRGRP WHERE BRID=v_inBRID;

      Select max(case when  varname='BRNAME' then varvalue else '' end)
       into v_BRNAME1
   from sysvar WHERE varname IN ('BRNAME');

OPEN PV_REFCURSOR
  FOR

SELECT ---TO_DATE(I_DATE,'DD/MM/RRRR') INDATE,v_inBRID inBRID,V_BRNAME BRNAME,v_BRNAME1 BRNAME1,
'NEW' TYPE,A.TXDATE||A.TXNUM TXTYPE, A.TXDATE, A.TXNUM, A.CUSTID,
       (CASE WHEN A.NFULLNAME<>OFULLNAME THEN A.NFULLNAME ELSE '' END) FULLNAME,
       (CASE WHEN A.NADDRESS<>A.OADDRESS THEN A.NADDRESS ELSE '' END) ADDRESS,
       (CASE WHEN  A.NIDCODE<>A.OIDCODE THEN A.NIDCODE ELSE '' END) IDCODE,
       (CASE WHEN A.NIDDATE<> A.OIDDATE THEN A.NIDDATE ELSE TO_DATE('','DD/MM/RRRR') END) IDDATE,
      (CASE WHEN A.OCUSTTYPE<>A.NCUSTTYPE THEN (CASE WHEN A.NCUSTTYPE = 'I' AND CF.COUNTRY = '234' THEN '3'
          WHEN A.NCUSTTYPE = 'I' AND CF.COUNTRY <> '234' THEN '4'
          WHEN A.NCUSTTYPE = 'B' AND CF.COUNTRY = '234' THEN '5'
          WHEN A.NCUSTTYPE = 'B' AND CF.COUNTRY <> '234' THEN '6' ELSE '7' END) ELSE '' END) IDTYPE,
          '' COUNTRY, '' CUSTODYCD, '' TXDESC
FROM CFVSDLOG A, CFMAST CF, vw_tllog_all TL,ALLCODE A1
    ---(SELECT MAX(TXDATE) TXDATE, MAX(TXNUM) TXNUM FROM CFVSDLOG WHERE TXDATE = TO_DATE(I_DATE,'DD/MM/RRRR')  group by txdate, txnum  ORDER BY TXDATE, TXNUM) B
WHERE ---A.TXDATE = B.TXDATE AND A.TXNUM = B.TXNUM
       ---AND
       A.CUSTID = CF.CUSTID  AND A.TXDATE = TL.TXDATE
       AND A.TXNUM = TL.TXNUM
       AND A1.CDNAME = 'COUNTRY' AND A1.CDVAL = CF.COUNTRY
       ---AND CF.CUSTODYCD LIKE V_STRCUSTODYCD
       ---AND CF.BRID LIKE V_I_BRID
       ---AND (CASE WHEN A.NFULLNAME IS NULL THEN 'N' WHEN A.NFULLNAME=A.OFULLNAME THEN 'N' ELSE 'Y' END) LIKE V_FULLNAME
       ---AND (CASE WHEN A.NIDCODE IS NULL THEN 'N' WHEN A.NIDCODE=A.OIDCODE THEN 'N' ELSE 'Y' END) LIKE V_IDCODE
       ---AND (CASE WHEN A.NIDDATE IS NULL THEN 'N' WHEN A.NIDDATE=A.OIDDATE THEN 'N'  ELSE 'Y' END) LIKE V_IDDATE
       ---AND (CASE WHEN A.NADDRESS IS NULL THEN 'N' WHEN A.NADDRESS=A.OADDRESS THEN 'N' ELSE 'Y' END) LIKE V_ADDRESS
       ---AND (CASE WHEN A.NCUSTTYPE <> A.OCUSTTYPE THEN 'Y' ELSE 'N' END) LIKE V_CUSTTYPE
       --AND (CASE WHEN A.NCOUNTRY <> A.OCOUNTRY THEN 'Y' ELSE 'N' END) LIKE V_COUNTRY

 UNION ALL

SELECT ---TO_DATE(I_DATE,'DD/MM/RRRR') INDATE,v_inBRID inBRID,V_BRNAME BRNAME, v_BRNAME1 BRNAME1,
'OLD' TYPE,A.TXDATE||A.TXNUM TXTYPE, A.TXDATE, A.TXNUM, A.CUSTID,
        OFULLNAME FULLNAME ,OADDRESS ADDRESS, OIDCODE IDCODE, OIDDATE IDDATE,
        (CASE WHEN A.OCUSTTYPE = 'I' AND CF.COUNTRY = '234' THEN '3'
        WHEN A.OCUSTTYPE = 'I' AND CF.COUNTRY <> '234' THEN '4'
        WHEN A.OCUSTTYPE = 'B' AND CF.COUNTRY = '234' THEN '5'
        WHEN A.OCUSTTYPE = 'B' AND CF.COUNTRY <> '234' THEN '6'  ELSE '7' END) IDTYPE,
        cf.COUNTRY, CF.CUSTODYCD,  (CASE WHEN SUBSTR(A.TXNUM,1,2)='68' THEN 'Thay d?i d?a ch? m?i' ELSE TL.txdesc END )txdesc
FROM CFVSDLOG A, CFMAST CF, vw_tllog_all TL,ALLCODE A1
   --- (SELECT MAX(TXDATE) TXDATE, MAX(TXNUM) TXNUM FROM CFVSDLOG WHERE TXDATE = TO_DATE(I_DATE,'DD/MM/RRRR') group by txdate, txnum ORDER BY TXDATE, TXNUM ) B
WHERE ---A.TXDATE = B.TXDATE AND A.TXNUM = B.TXNUM
     --- AND
     A.CUSTID = CF.CUSTID AND A.TXDATE = TL.TXDATE
      AND A.TXNUM = TL.TXNUM
      AND A1.CDNAME = 'COUNTRY' AND A1.CDVAL = CF.COUNTRY
      ---AND CF.CUSTODYCD LIKE V_STRCUSTODYCD
      ---AND CF.BRID LIKE V_I_BRID
      ---AND (CASE WHEN A.NFULLNAME IS NULL THEN 'N' WHEN A.NFULLNAME=A.OFULLNAME THEN 'N' ELSE 'Y' END) LIKE V_FULLNAME
       --AND (CASE WHEN A.NIDCODE IS NULL THEN 'N' WHEN A.NIDCODE=A.OIDCODE THEN 'N' ELSE 'Y' END) LIKE V_IDCODE
       --AND (CASE WHEN A.NIDDATE IS NULL THEN 'N' WHEN A.NIDDATE=A.OIDDATE THEN 'N'  ELSE 'Y' END) LIKE V_IDDATE
      -- AND (CASE WHEN A.NADDRESS IS NULL THEN 'N' WHEN A.NADDRESS=A.OADDRESS THEN 'N' ELSE 'Y' END) LIKE V_ADDRESS
       --AND (CASE WHEN A.NCUSTTYPE <> A.OCUSTTYPE THEN 'Y' ELSE 'N' END) LIKE V_CUSTTYPE
       --AND (CASE WHEN A.NCOUNTRY <> A.OCOUNTRY THEN 'Y' ELSE 'N' END) LIKE V_COUNTRY
ORDER BY TXDATE, TXNUM,TYPE
;

EXCEPTION
   WHEN OTHERS
   THEN
      RETURN;

End;
/
