SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE CF601801 (
   PV_REFCURSOR           IN OUT   PKG_REPORT.REF_CURSOR,
   OPT                    IN       VARCHAR2,
   BRID                   IN       VARCHAR2,
   I_DATE                 IN VARCHAR2, /*NGAY TAO BAO CAO*/
   PV_CUSTODYCD           IN       VARCHAR2 /*SO TK LUU KY */

   )
IS
    -- BANK CONFIRMATION - CASH
    -- PERSON      DATE                 COMMENTS
    -- ---------   ------               -------------------------------------------
    -- LAMGK    22-10-2019           CREATED
    V_STROPTION    VARCHAR2 (5);
    V_STRBRID      VARCHAR2 (4);

    V_CUSTODYCD    VARCHAR2(20);
    V_REPORT_DATE DATE;
BEGIN

    V_STROPTION := OPT;

    V_REPORT_DATE  :=  TO_DATE(I_DATE, SYSTEMNUMS.C_DATE_FORMAT);
    IF V_STROPTION = 'A' THEN
        V_STRBRID := '%';
    ELSIF V_STROPTION = 'B' THEN
        V_STRBRID := SUBSTR(BRID,1,2) || '__' ;
    ELSE
        V_STRBRID:=BRID;
    END IF;

    V_CUSTODYCD := REPLACE(PV_CUSTODYCD,'.','');

OPEN PV_REFCURSOR FOR
      SELECT CF.FULLNAME ACCOUNT_NAME
         , CF.BANKATADDRESS RECEIVERADDRESS
         --, DD.REFCASAACCT ACCOUNT_NUMBER
         ,SUBSTR(DD.REFCASAACCT,1,3) || '-' || SUBSTR(DD.REFCASAACCT,4,3) || SUBSTR(DD.REFCASAACCT,7,6) ACCOUNT_NUMBER
         , DD.CCYCD --LOAI TIEN
         , DD.BALANCE + DD.PENDINGHOLD + DD.HOLDBALANCE CURRENT_BALANCE
         , DD.BALANCE AVAILABLE_BALANCE --CHECK LAI VOI DIEM CACH LAY
         , ACC_TP.CDVAL ACCOUNT_TYPE --ACCOUNT_TYPE
     FROM CFMAST CF
         JOIN DDMAST DD ON DD.CUSTID = CF.CUSTID
         -- PHAT SINH TU NGAY DEN NGAY HIEN TAI
         LEFT JOIN
         (
            SELECT CUSTODYCD, ACCTNO, SUM(CASE WHEN TXTYPE='C' THEN NAMT ELSE -NAMT END) NAMT
            FROM VW_DDTRAN_GEN WHERE FIELD ='BALANCE' AND TXDATE > V_REPORT_DATE
            GROUP BY CUSTODYCD, ACCTNO
         ) TR ON TR.ACCTNO = DD.ACCTNO
         JOIN (
                  SELECT CDCONTENT, CDVAL
                  FROM ALLCODE
                  WHERE CDNAME ='ACCOUNTTYPE' AND CDTYPE='DD'
              )ACC_TP ON ACC_TP.CDVAL = DD.ACCOUNTTYPE
     WHERE CF.CUSTODYCD = V_CUSTODYCD; --FILTER;

EXCEPTION
  WHEN OTHERS
   THEN
      PLOG.ERROR ('CF601801: ' || SQLERRM || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
      RETURN;
END;
/
