SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE cf6025(
   PV_REFCURSOR           IN OUT   PKG_REPORT.REF_CURSOR,
   OPT                    IN       VARCHAR2,
   BRID                   IN       VARCHAR2,
   P_CUSTODYCD            IN       VARCHAR2, /*SO TK LUU KY */
   P_CONTRACT             IN       VARCHAR2, /*SO HOP DONG*/
   --P_CFAUTH               IN       VARCHAR2, /*NGUOI NHAN */
   P_SIGNTYPE             IN       VARCHAR2 /*NGUOI KY */
   )
IS
    -- REPORT ON THE DAY BECOME/IS NO LONGER MAJOR SHAREHOLDER, INVESTORS HOLDING 5% OR MORE OF SHARES
    -- PERSON      DATE                 COMMENTS
    -- ---------   ------               -------------------------------------------
    -- DU.PHAN    23-10-2019           CREATED
    V_STROPTION    VARCHAR2 (5);       -- A: ALL; B: BRANCH; S: SUB-BRANCH
    V_STRBRID      VARCHAR2 (4);       -- USED WHEN V_NUMOPTION > 0

    V_FROMDATE          DATE;
    V_TODATE            DATE;
    V_CURRDATE          DATE;
    V_ISSUEDATE         DATE;
    V_EXPDATE           DATE;
    V_CUSTODYCD         VARCHAR2(20);
    V_SYMBOL            VARCHAR2(50);
    V_IDCODE           VARCHAR2(200);
    V_OFFICE           VARCHAR2(200);
    V_REFNAME          VARCHAR2(200);
    V_SHVSTC           VARCHAR2(200);
    V_SHVCUSTODYCD     VARCHAR2(200);
    V_SHVCIFID         VARCHAR2(200);

    V_TLTITLE          VARCHAR2(200);
    V_TLFULLNAME       VARCHAR2(200);
BEGIN
     V_STROPTION := OPT;
     V_CURRDATE   := GETCURRDATE;
     IF V_STROPTION = 'A' THEN
        V_STRBRID := '%';
     ELSIF V_STROPTION = 'B' THEN
        V_STRBRID := SUBSTR(BRID,1,2) || '__' ;
     ELSE
        V_STRBRID:=BRID;
     END IF;

    V_CUSTODYCD := REPLACE(P_CUSTODYCD,'.','');
    IF P_SIGNTYPE = '002' THEN
        SELECT MAX(CASE WHEN  VARNAME='1IDCODE' THEN EN_VARDESC ELSE '' END),
           MAX(CASE WHEN  VARNAME='1OFFICE' THEN EN_VARDESC ELSE '' END),
           MAX(CASE WHEN  VARNAME='1REFNAME' THEN EN_VARDESC ELSE '' END)
            INTO V_IDCODE, V_OFFICE, V_REFNAME
        FROM SYSVAR WHERE VARNAME IN ('1IDCODE','1OFFICE','1REFNAME');
    ELSE
        SELECT
           MAX(CASE WHEN  VARNAME='2IDCODE' THEN EN_VARDESC ELSE '' END),
           MAX(CASE WHEN  VARNAME='2OFFICE' THEN EN_VARDESC ELSE '' END),
           MAX(CASE WHEN  VARNAME='2REFNAME' THEN EN_VARDESC ELSE '' END)
            INTO V_IDCODE, V_OFFICE, V_REFNAME
        FROM SYSVAR WHERE VARNAME IN ('2IDCODE','2OFFICE','2REFNAME');
    END IF;

-- LAY THONG TIN CUA SHV

    BEGIN
        SELECT MAX((CASE WHEN VARNAME ='TRANDINGCODE' THEN VARVALUE ELSE '' END))
        , MAX((CASE WHEN VARNAME ='CUSTODYCD' THEN VARVALUE ELSE '' END))
        , MAX((CASE WHEN VARNAME ='CIFID' THEN VARVALUE ELSE '' END))
        INTO V_SHVSTC, V_SHVCUSTODYCD,V_SHVCIFID
        FROM   SYSVAR
        WHERE VARNAME IN ('TRANDINGCODE','CUSTODYCD','CIFID');  --DATA TAM THOI
    EXCEPTION
        WHEN OTHERS  THEN
            V_SHVSTC := '';
            V_SHVCUSTODYCD := '';
            V_SHVCIFID :='';
    END;
-- LAY THONG TIN NGUOI UY QUYEN
/*    BEGIN
        SELECT TLFULLNAME, TLTITLE
        INTO V_TLFULLNAME, V_TLTITLE
        FROM   TLPROFILES
        WHERE TLNAME = P_CFAUTH;
    EXCEPTION
        WHEN OTHERS  THEN
            V_TLFULLNAME := '';
            V_TLTITLE := '';

    END;*/


OPEN PV_REFCURSOR FOR
    SELECT V_IDCODE SIGN_IDCODE, V_OFFICE SIGN_OFFICE, V_REFNAME SIGN_REFNAME,
    --V_TLFULLNAME TLFULLNAME, V_TLTITLE TLTITLE,
    V_SHVSTC SHVSTC, V_SHVCUSTODYCD SHVCUSTODYCD,V_SHVCIFID SHVCIFID
    ,MST.*, UTILS.FNC_NUMBER2WORK(MST.AMOUNT,'VIETNAM DONG') STR_AMOUNT
    FROM
    (
        SELECT ISS.FULLNAME,
               CRP.SYMBOL CODEID,
               SB.ISSUEDATE,
               SB.EXPDATE,
              SUM( DOC.QTTY) TOTAL_QTTY,
              SUM(DOC.QTTY* SB.PARVALUE) AMOUNT
        FROM CRPHYSAGREE CRP,DOCSTRANSFER DOC,SBSECURITIES SB,ISSUERS ISS,(SELECT DISTINCT A.CRPHYSAGREEID
        FROM CRPHYSAGREE_LOG_ALL A, CRPHYSAGREE B
        WHERE A.TLTXCD='1405') MST
        WHERE CRP.ISSUERID = ISS.ISSUERID
         AND DOC.CRPHYSAGREEID=CRP.CRPHYSAGREEID
         AND CRP.CRPHYSAGREEID=MST.CRPHYSAGREEID
        AND CRP.CODEID = SB.CODEID
         AND CRP.CRPHYSAGREEID = P_CONTRACT
        AND CRP.CUSTODYCD LIKE V_CUSTODYCD
        GROUP BY ISS.FULLNAME, CRP.SYMBOL, SB.ISSUEDATE, SB.EXPDATE
    )MST;

EXCEPTION
  WHEN OTHERS
   THEN
      PLOG.ERROR ('CF6025: ' || SQLERRM || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
      RETURN;
END;
/
