SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE CF6018 (
   PV_REFCURSOR           IN OUT   PKG_REPORT.REF_CURSOR,
   OPT                    IN       VARCHAR2,
   BRID                   IN       VARCHAR2,
   I_DATE                 IN       VARCHAR2,
   PV_CUSTODYCD           IN       VARCHAR2 /*SO TK LUU KY */
--   PV_REPORT_DT    IN VARCHAR2 /*NGAY TAO BAO CAO*/
   )
IS
    -- BANK CONFIRMATION
    -- PERSON      DATE                 COMMENTS
    -- ---------   ------               -------------------------------------------
    -- LAMGK    22-10-2019           CREATED
    V_STROPTION    VARCHAR2 (5);
    V_STRBRID      VARCHAR2 (4);

    V_CUSTODYCD    VARCHAR2(20);
    V_REPORT_DATE DATE;
BEGIN

    V_STROPTION := OPT;
    V_REPORT_DATE  := TO_DATE(I_DATE, SYSTEMNUMS.C_DATE_FORMAT);
    IF V_STROPTION = 'A' THEN
        V_STRBRID := '%';
    ELSIF V_STROPTION = 'B' THEN
        V_STRBRID := SUBSTR(BRID,1,2) || '__' ;
    ELSE
        V_STRBRID:=BRID;
    END IF;

    V_CUSTODYCD := REPLACE(PV_CUSTODYCD,'.','');

OPEN PV_REFCURSOR FOR
     SELECT V_REPORT_DATE VALUE_DATE --NGAY TAO
        , FULLNAME --TEN KHACH HANG
        , CIFID --MA KHACH HANG TAI NGAN HANG
        , (CASE WHEN COUNTRY ='234' THEN SUBSTR(CUSTODYCD,5,6) ELSE TRADINGCODE END) TRADINGCODE --MA GIAO DICH CK
     FROM CFMAST
     WHERE CUSTODYCD = V_CUSTODYCD; --FILTER;

EXCEPTION
  WHEN OTHERS
   THEN
      PLOG.ERROR ('CF6018: ' || SQLERRM || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
      RETURN;
END;
/
