SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE CF7007
(
PV_REFCURSOR   IN OUT   PKG_REPORT.REF_CURSOR,
   OPT            IN       VARCHAR2,
   BRID           IN       VARCHAR2,
   PV_I_DATE         IN       VARCHAR2,
   PV_CUSTODYCD      IN       VARCHAR2,
   PV_GCB            IN       VARCHAR2,
   PV_SYMBOL         IN       VARCHAR2,
   PV_OPTION         IN       VARCHAR2
   )
is
V_DATE DATE;
V_PREDATE DATE;
V_CUSTODYCD VARCHAR2(10);
V_GCB VARCHAR2(10);
V_SYMBOL VARCHAR2(10);

begin

V_DATE := TO_DATE(PV_I_DATE, SYSTEMNUMS.C_DATE_FORMAT);
V_PREDATE := get_t_date (V_DATE,1);

IF  (PV_CUSTODYCD <> 'ALL' or PV_CUSTODYCD <> '') THEN
         V_CUSTODYCD := PV_CUSTODYCD;
ELSE
        V_CUSTODYCD := '%';
END IF;

IF  (PV_GCB <> 'ALL' or PV_GCB <> '') THEN
         V_GCB := PV_GCB;
ELSE
        V_GCB := '%';
END IF;

IF  (PV_SYMBOL <> 'ALL' or PV_SYMBOL <> '') THEN
         V_SYMBOL := PV_SYMBOL;
ELSE
        V_SYMBOL := '%';
END IF;

OPEN PV_REFCURSOR  FOR
SELECT
      ROW_NUMBER() OVER (ORDER BY CF.CUSTODYCD) AS NO, V_DATE REPORTDATE,
      CF.FULLNAME FUNNAME,
      SE.AFACCTNO, SE.ACCTNO, SEB.CODEID, SEB.SYMBOL, SEB.ISINCODE, FAM.SHORTNAME GC, ISS.FULLNAME DESCRIPTION,
      (CASE WHEN SUBSTR(CF.CUSTODYCD,4,1)='F' OR SUBSTR(CF.CUSTODYCD,4,1)='E' THEN CF.TRADINGCODE
            ELSE substr('SHVB999999',5) END) STC,
      SE.TRADE - NVL(TR.TRADE,0)+ SE.RECEIVING- NVL(TR.RECEIVING,0)- SE.NETTING + NVL(TR.NETTING,0) QTTY_T,
      SE.TRADE - NVL(PRETR.TRADE,0)+ SE.RECEIVING- NVL(PRETR.RECEIVING,0)- SE.NETTING + NVL(PRETR.NETTING,0) QTTY_PRET,
      SEC.CIRCULATINGQTTY_T,
      PRESEC.CIRCULATINGQTTY_PRET,
      CAST((SE.TRADE - NVL(TR.TRADE,0)+ SE.RECEIVING- NVL(TR.RECEIVING,0)- SE.NETTING + NVL(TR.NETTING,0))/ SEC.CIRCULATINGQTTY_T * 100 as numeric(38,2)) RATE_T,
      CAST((SE.TRADE - NVL(PRETR.TRADE,0)+ SE.RECEIVING- NVL(PRETR.RECEIVING,0)- SE.NETTING + NVL(PRETR.NETTING,0))/ PRESEC.CIRCULATINGQTTY_PRET * 100 as numeric(38,2)) RATE_PRET,
      CAST((SE.TRADE - NVL(TR.TRADE,0)+ SE.RECEIVING- NVL(TR.RECEIVING,0)- SE.NETTING + NVL(TR.NETTING,0))/ SEC.CIRCULATINGQTTY_T * 100 as numeric(38,2)) - CAST((SE.TRADE - NVL(PRETR.TRADE,0)+ SE.RECEIVING- NVL(PRETR.RECEIVING,0)- SE.NETTING + NVL(PRETR.NETTING,0))/ PRESEC.CIRCULATINGQTTY_PRET * 100 as numeric(38,2)) DELTA_CHANGE
FROM CFMAST CF, AFMAST AF, FAACCTMAIN FAA, FAMEMBERS FAM, SBSECURITIES SEB, SEMAST SE, ISSUERS ISS,
     (SELECT ACCTNO ,SUM(CASE WHEN FIELD ='TRADE' AND TXTYPE ='C' THEN NAMT WHEN FIELD ='TRADE' AND TXTYPE ='D' THEN - NAMT ELSE 0 END) TRADE ,
             SUM(CASE WHEN FIELD ='RECEIVING' AND TXTYPE ='C' THEN NAMT WHEN FIELD ='RECEIVING' AND TXTYPE ='D' THEN - NAMT ELSE 0 END) RECEIVING,
             SUM(CASE WHEN FIELD ='NETTING' AND TXTYPE ='C' THEN NAMT WHEN FIELD ='NETTING' AND TXTYPE ='D' THEN - NAMT ELSE 0 END) NETTING
      FROM VW_SETRAN_GEN
      WHERE BUSDATE > V_DATE
      GROUP BY ACCTNO
      ) TR ,
      (SELECT ACCTNO ,SUM(CASE WHEN FIELD ='TRADE' AND TXTYPE ='C' THEN NAMT WHEN FIELD ='TRADE' AND TXTYPE ='D' THEN - NAMT ELSE 0 END) TRADE ,
              SUM(CASE WHEN FIELD ='RECEIVING' AND TXTYPE ='C' THEN NAMT WHEN FIELD ='RECEIVING' AND TXTYPE ='D' THEN - NAMT ELSE 0 END) RECEIVING,
              SUM(CASE WHEN FIELD ='NETTING' AND TXTYPE ='C' THEN NAMT WHEN FIELD ='NETTING' AND TXTYPE ='D' THEN - NAMT ELSE 0 END) NETTING
       FROM VW_SETRAN_GEN
       WHERE BUSDATE > V_PREDATE
       GROUP BY ACCTNO
      ) PRETR,
      (SELECT CODEID, (CASE WHEN PV_OPTION='OLD' THEN OLDCIRCULATINGQTTY ELSE NEWCIRCULATINGQTTY END) CIRCULATINGQTTY_T  FROM vw_securities_info_hist WHERE HISTDATE = V_DATE) SEC,
      (SELECT CODEID, (CASE WHEN PV_OPTION='OLD' THEN OLDCIRCULATINGQTTY ELSE NEWCIRCULATINGQTTY END) CIRCULATINGQTTY_PRET FROM vw_securities_info_hist WHERE HISTDATE = V_PREDATE) PRESEC
WHERE CF.CUSTODYCD = FAA.CUSTODYCD (+)
  AND FAA.GCBID = FAM.AUTOID
  AND CF.CUSTID=AF.CUSTID
  AND AF.ACCTNO=SE.AFACCTNO
  AND SE.CODEID=SEB.CODEID
  AND SEB.ISSUERID=ISS.ISSUERID
  AND SE.ACCTNO = TR.ACCTNO (+)
  AND SE.ACCTNO = PRETR.ACCTNO (+)
  AND SE.CODEID=SEC.CODEID
  AND SE.CODEID=PRESEC.CODEID
  AND CF.CUSTODYCD LIKE V_CUSTODYCD
  AND FAM.SHORTNAME LIKE V_GCB
  AND SEB.SYMBOL LIKE V_SYMBOL
  AND SE.TRADE - NVL(TR.TRADE,0)+ SE.RECEIVING- NVL(TR.RECEIVING,0)- SE.NETTING + NVL(TR.NETTING,0) <> 0;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN;
end;
/
