SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE dd600701 (
   PV_REFCURSOR   IN OUT   PKG_REPORT.REF_CURSOR,
   OPT            IN       VARCHAR2,
   BRID           IN       VARCHAR2,
   PV_CUSTODYCD   IN       VARCHAR2,
   DATE_T         IN       VARCHAR2
)
IS

------------------------------------------------------------
   V_STROPTION        VARCHAR2 (200);       -- A: ALL; B: BRANCH; S: SUB-BRANCH
   V_STRBRID          VARCHAR2 (200);        -- USED WHEN V_NUMOPTION > 0
   V_INBRID           VARCHAR2 (200);
   V_BILL_MONTH        VARCHAR2(200);
   V_CUSTODYCD    VARCHAR2(200);
   V_CCYCD  VARCHAR2(3);
   V_MCIFID VARCHAR2(250);
-- DECLARE PROGRAM VARIABLES AS SHOWN ABOVE
BEGIN

    V_STROPTION := OPT;
    IF V_STROPTION = 'A' THEN
        V_STRBRID := '%';
    ELSIF V_STROPTION = 'B' THEN
        V_STRBRID := SUBSTR(BRID,1,2) || '__' ;
    ELSE
        V_STRBRID:=BRID;
    END IF;
------------------
   V_CUSTODYCD := REPLACE(PV_CUSTODYCD,'.','');
-------------------
   V_BILL_MONTH :=  DATE_T;
   ----------------CCYCD-------------
BEGIN
   SELECT CCYCD INTO V_CCYCD
   FROM
   (
        SELECT DISTINCT (CASE WHEN OD.SETLDATE IS NULL THEN FE.TXDATE ELSE OD.SETLDATE END) TXDATE, FE.CUSTODYCD, FEEAMT, FE.ORDERID, CCYCD
        FROM (
            SELECT TXDATE,CUSTODYCD,FEEAMT,ORDERID,CCYCD FROM FEETRANDETAIL WHERE FORP ='F' AND CUSTODYCD =V_CUSTODYCD AND REFID NOT IN(SELECT AUTOID FROM FEETRAN WHERE DELTD ='Y') --TRUNG.LUU: SHBVNEX-1540 XOA GD 1293
            UNION ALL
            SELECT TXDATE,CUSTODYCD,FEEAMT,ORDERID,CCYCD FROM FEETRANDETAILHIST WHERE FORP ='F'  AND CUSTODYCD =V_CUSTODYCD AND REFID NOT IN(SELECT AUTOID FROM FEETRANA WHERE DELTD ='Y') --TRUNG.LUU: SHBVNEX-1540 XOA GD 1293
            UNION ALL
            SELECT TXDATE,CUSTODYCD,FEEAMT,ORDERID,CCYCD FROM VW_FEETRAN_ALL  WHERE DELTD <>'Y'  AND CUSTODYCD =V_CUSTODYCD
        )FE LEFT JOIN VW_ODMAST_IMPORT OD ON OD.ORDERID=FE.ORDERID
        WHERE TO_CHAR(CASE WHEN OD.SETLDATE IS NULL THEN FE.TXDATE ELSE OD.SETLDATE END,'MMRRRR') = V_BILL_MONTH ORDER BY TXDATE
    )
    WHERE ROWNUM=1;
EXCEPTION WHEN OTHERS THEN
     V_CCYCD:='USD';
END;
--------------------------------------------
--TRUNG.LUU: 19-02-2021 SHBVNEX-2067 LAY CIFID cua tai khoan me

--trung.luu: 18-03-2021 SHBVNEX-2161 khong dung tai khoan me, dung master cifid
BEGIN
    --SELECT CIFID INTO V_MCIFID FROM CFMAST WHERE CUSTODYCD IN (SELECT MCUSTODYCD FROM CFMAST WHERE CUSTODYCD = V_CUSTODYCD);
    --trung.luu: 28-04-2021 SHBVNEX-2161 khong co mastercif thi de null
    SELECT MCIFID INTO V_MCIFID FROM CFMAST WHERE CUSTODYCD = V_CUSTODYCD;
EXCEPTION WHEN OTHERS THEN
    V_MCIFID:= '';
END;
-- GET REPORT'S DATA
OPEN PV_REFCURSOR FOR

SELECT (CASE WHEN nvl(FEE_TRAN,0) = 0 and nvl(FEE_RE,0) = 0 then '' else FULLNAME_TRAN end ) FULLNAME_TRAN
,(CASE WHEN nvl(FEE_TRAN,0) = 0 and nvl(FEE_RE,0) = 0 then '' else CIFID_TRAN end ) CIFID_TRAN,V_MCIFID MCIFID
,STT,TXNUM_TRAN,TRANSACTION_TYPE_TRAN,SYMBOL_TRAN,TXDATE_TRAN,CLEARDATE_TRAN
,FEE_TRAN,FEE_RE,CUSTODYCD
FROM (
    SELECT
             CF.FULLNAME AS FULLNAME_TRAN
            ,CF.CIFID AS CIFID_TRAN --CIFID PROXY
            ,CF.CUSTODYCD
            ,ROW_NUMBER() OVER(ORDER BY FE.CUSTODYCD DESC) STT
            ---------------------Transaction and repair charge----------------------
            ,FE.TXNUM AS TXNUM_TRAN --MA CHUNG TU GIAO DICH
            ,CASE WHEN FET.ORDERID = '2266' THEN 'Odd-lot shares' --TRUNG.LUU: 05-05-2021 SHBVNEX-1996 Phi phat sinh tu gd 2266 thi gan tyep = 'Odd-lot shares'
                  WHEN FET.EXECTYPE ='NS' THEN 'Selling'
                  WHEN FET.EXECTYPE ='NB' THEN 'Buying'
                  ELSE NULL
                  END TRANSACTION_TYPE_TRAN   --LENH MUA BAN
            ,FET.SYMBOL AS SYMBOL_TRAN  -- MA CK
            ,(CASE WHEN OD.TXDATE IS NULL THEN FE.TXDATE ELSE OD.TXDATE END) AS TXDATE_TRAN --NGAY GIAO DICH
            ,FET.CLEARDATE AS CLEARDATE_TRAN --NGAY THANH TOAN
            ,CASE WHEN FE.SUBTYPE ='001'THEN (CASE WHEN FT.CCYCD  = 'VND' THEN ROUND(FE.FEEAMT + FT.VATAMT/(FT.FEEAMT/FE.FEEAMT),0) ELSE ROUND(FE.FEEAMT + FT.VATAMT/(FT.FEEAMT/FE.FEEAMT),2)END)
                  ELSE 0
                  END AS FEE_TRAN       --PHI GIAO DICH
            ,CASE WHEN FE.SUBTYPE ='002'THEN (CASE WHEN FT.CCYCD  = 'VND' THEN ROUND(FE.FEEAMT + FT.VATAMT/(FT.FEEAMT/FE.FEEAMT),0) ELSE ROUND(FE.FEEAMT + FT.VATAMT/(FT.FEEAMT/FE.FEEAMT),2)END)
                  ELSE 0
                  END AS FEE_RE         --PHI SUA LOI

    FROM (
        SELECT * FROM FEETRANDETAIL where refid not in(select autoid from feetran where deltd ='Y')
        UNION
        SELECT * FROM FEETRANDETAILHIST where refid not in(select autoid from feetrana where deltd ='Y')
    ) FE
    LEFT JOIN CFMAST CF ON CF.CUSTODYCD= FE.CUSTODYCD
    LEFT JOIN (select *from VW_FEETRAN_ALL where deltd <>'Y') FT ON FT.AUTOID=FE.REFID
    LEFT JOIN (
        SELECT SB.CODEID,FET.*
        FROM
        (
            SELECT * FROM FEETRANREPAIR WHERE DELTD <> 'Y'
            UNION
            SELECT * FROM FEETRANREPAIRHIST WHERE DELTD <> 'Y'
        )FET, SBSECURITIES SB
        WHERE FET.SYMBOL=SB.SYMBOL
    )FET
    ON FET.ORDERID= FE.ORDERID AND FE.TXDATE=FET.TXDATE AND FE.CODEID=FET.CODEID
    LEFT JOIN VW_ODMAST_IMPORT OD ON OD.ORDERID=FE.ORDERID
    WHERE FE.FEETYPES ='TRANREPAIR'
    --AND FE.CCYCD=V_CCYCD
    AND FE.FORP ='F'
    AND FE.TXNUM IS NOT NULL
    AND TO_CHAR(CASE WHEN OD.SETLDATE IS NULL THEN FE.TXDATE ELSE OD.SETLDATE END,'MMRRRR') = V_BILL_MONTH
    AND CF.CUSTODYCD = V_CUSTODYCD

    UNION --------SHOW WHEN NO DATA-----------------------------

    SELECT
             '' FULLNAME_TRAN
            ,'' CIFID_TRAN --CIFID PROXY
            ,'' CUSTODYCD
            ,1 AS STT
            ,'' AS TXNUM_TRAN --MA CHUNG TU GIAO DICH
            ,'' TRANSACTION_TYPE_TRAN   --LENH MUA BAN
            ,'' AS SYMBOL_TRAN  -- MA CK
            ,TO_DATE('') AS TXDATE_TRAN --NGAY GIAO DICH
            ,TO_DATE('') AS CLEARDATE_TRAN --NGAY THANH TOAN
            ,0 FEE_TRAN       --PHI GIAO DICH
            ,0 FEE_RE         --PHI SUA LOI
    FROM DUAL
    WHERE NOT EXISTS (
        SELECT 1
        FROM (
            SELECT*FROM FEETRANDETAIL WHERE REFID NOT IN(SELECT AUTOID FROM FEETRAN WHERE DELTD ='Y')
            UNION ALL
            SELECT*FROM FEETRANDETAILHIST WHERE REFID NOT IN(SELECT AUTOID FROM FEETRANA WHERE DELTD ='Y')
        ) FE
        LEFT JOIN CFMAST CF ON CF.CUSTODYCD= FE.CUSTODYCD
        LEFT JOIN VW_ODMAST_IMPORT OD ON OD.ORDERID=FE.ORDERID
        WHERE FE.FEETYPES ='TRANREPAIR'
        --AND FE.CCYCD=V_CCYCD
        AND FE.FORP ='F'
        AND FE.TXNUM IS NOT NULL
        AND TO_CHAR(CASE WHEN OD.SETLDATE IS NULL THEN FE.TXDATE ELSE OD.SETLDATE END,'MMRRRR') = V_BILL_MONTH
        AND CF.CUSTODYCD = V_CUSTODYCD
    )
) A /*WHERE  EXISTS (
    SELECT 1
    FROM (
        SELECT TXDATE,CUSTODYCD,FEEAMT,ORDERID,CCYCD FROM FEETRANDETAIL WHERE FORP ='F' and refid not in(select autoid from feetran where deltd = 'Y') --trung.luu: SHBVNEX-1540 xoa gd 1293
        UNION ALL
        SELECT TXDATE,CUSTODYCD,FEEAMT,ORDERID,CCYCD FROM FEETRANDETAILHIST WHERE FORP ='F' and refid not in(select autoid from feetrana where deltd = 'Y') --trung.luu: SHBVNEX-1540 xoa gd 1293
        UNION ALL
        SELECT TXDATE,CUSTODYCD,FEEAMT,ORDERID,CCYCD FROM VW_FEETRAN_ALL  WHERE FEETYPES ='OTHER' AND FEEAMT > 0 AND SUBTYPE IN ('014','015','003','016') and deltd <> 'Y' --trung.luu: SHBVNEX-1540 xoa gd 1293
    )FE
    LEFT JOIN VW_ODMAST_IMPORT OD ON OD.ORDERID=FE.ORDERID
    WHERE FE.CUSTODYCD =V_CUSTODYCD
    --AND FE.CCYCD=V_CCYCD
    AND TO_CHAR(CASE WHEN OD.SETLDATE IS NULL THEN FE.TXDATE ELSE OD.SETLDATE END,'MMYYYY')=V_BILL_MONTH
    GROUP BY FE.CUSTODYCD,FE.TXDATE
    HAVING SUM(FE.FEEAMT) >0
)*/
;
 EXCEPTION
   WHEN OTHERS
   THEN  plog.error ('DD600701: ' || SQLERRM || dbms_utility.format_error_backtrace);
      RETURN;
END;
/
