SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE gen_market_info_req
IS
    L_REQBODY VARCHAR2(4000);
    L_TXDARE DATE;
BEGIN
    L_TXDARE := GETCURRDATE;
    FOR REC IN (
        SELECT INF.*
        FROM MARKET_INFO INF
        WHERE INF.REQSTATUS = 'P'
    )LOOP
        L_REQBODY := '';
        L_REQBODY := L_REQBODY || 'INDEXCODE:' || REC.INDEXCODE || CHR(13) || CHR(10);
        L_REQBODY := L_REQBODY || 'TRADINGDATE:' || TO_CHAR(REC.TRADINGDATE, 'RRRRMMDD') || CHR(13) || CHR(10);
        L_REQBODY := L_REQBODY || 'CLOSEINDEX:' || TO_CHAR(REC.CLOSEINDEX, 'FM999999999999990.90');

        INSERT INTO SYN_AITHER_REQ(AUTOID, TYPEREQ, OBJECTREQKEY, OBJECTKEY, TXDATE, BODYREQ)
        VALUES (SEQ_SYN_AITHER_REQ.NEXTVAL, 'MARKETINFO', REC.INDEXCODE || '-' || TO_CHAR(REC.TRADINGDATE, 'RRRRMMDD'), REC.AUTOID, REC.TRADINGDATE, L_REQBODY);

        UPDATE MARKET_INFO SET REQSTATUS = 'Q' WHERE AUTOID = REC.AUTOID;
    END LOOP;
EXCEPTION WHEN OTHERS THEN
  PLOG.ERROR ('GEN_MARKET_INFO_REQ: ' || SQLERRM || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END;
/
