SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE GEN_MT564 (P_CAMASTID VARCHAR2, P_FILENAME VARCHAR2)
IS
    V_CATYPE VARCHAR2(10);
    V_CATYPE_VSD VARCHAR2(10);
    V_SYMBOL VARCHAR2(50);
    V_VSDID VARCHAR(50);
BEGIN
    SELECT CA.CATYPE, SB.SYMBOL, CA.VSDID INTO V_CATYPE, V_SYMBOL, V_VSDID
    FROM CAMAST CA, SBSECURITIES SB
    WHERE CA.CODEID = SB.CODEID
    AND CA.CAMASTID = P_CAMASTID;

    SELECT CASE WHEN V_CATYPE = '010' THEN 'DVCA'
                WHEN V_CATYPE = '011' THEN 'DVSE'
                WHEN V_CATYPE = '005' THEN 'MEET'
                --WHEN V_CATYPE = '005' THEN 'XMET'
                WHEN V_CATYPE = '014' THEN 'RHTS'
                WHEN V_CATYPE = '023' THEN 'CONV'
                WHEN V_CATYPE = '020' THEN 'OTHR'
                WHEN V_CATYPE = '021' THEN 'BONU'
                WHEN V_CATYPE = '015' THEN 'INTR'
                WHEN V_CATYPE = '016' THEN 'PRII'
                --WHEN V_CATYPE = '016' THEN 'REDM'
                WHEN V_CATYPE = '024' THEN 'DETI'
            ELSE '' END
    INTO V_CATYPE_VSD
    FROM DUAL;

    IF V_CATYPE_VSD IS NOT NULL THEN
        INSERT INTO VSD_MT564_INF(AUTOID,VSDMSGID,VSDPROMSG,VSDPROMSG_VALUE,SYMBOL,REFSYMBOL,VSDMSGDATE,VSDMSGTYPE,ISGEN,VSDREFERENCE,MSGSTATUS)
        VALUES (seq_vsd_mt564_inf.nextval, V_VSDID, '564.CAEV//' || V_CATYPE_VSD, 'NEWM', V_SYMBOL, V_SYMBOL, GETCURRDATE, V_CATYPE_VSD, 'Y', V_VSDID, 'C');

        INSERT INTO VSD_PARCONTENT_LOG(AUTOID,FILENAME,TIMECREATED,TIMEPROCESS,STATUS,TXDATE,VSDID,CSVFILENAME)
        VALUES (seq_vsd_parcontent_log.nextval, REPLACE(P_FILENAME,'.csv','.par'), TO_DATE(TO_CHAR(SYSTIMESTAMP,systemnums.C_DATE_FORMAT),systemnums.C_DATE_FORMAT),TO_CHAR(systimestamp,systemnums.C_TIME_FORMAT),'P', GETCURRDATE, V_VSDID, REPLACE(P_FILENAME,'.par','.csv'));

        COMMIT;
    END IF;

EXCEPTION WHEN OTHERS THEN
    PLOG.ERROR ('GEN_MT564: ' || SQLERRM || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    RETURN;
END;
/
