SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE INQUIRY_ACCOUNT(
        PV_REFCURSOR IN OUT PKG_REPORT.REF_CURSOR,
        TABLENAME IN VARCHAR2,
        AFACCTNO IN VARCHAR2,
        CASEBY IN VARCHAR2,
        FRDATE in varchar2,
        TODATE in varchar2,
            FPAGENUMBER in NUMBER,
        TPAGENUMBER in NUMBER
        )
  IS

  V_ACCTNO VARCHAR2(30);
  V_CASEBY VARCHAR2(30);
  V_TABLENAME VARCHAR2(30);
  v_FRDATE date;
  v_TODATE date;
  v_FPAGENUMBER NUMBER;
  v_TPAGENUMBER NUMBER;

  -- AUTHOER : TRUONGLD
  -- DATE : 11/04/2010
  -- PURPOSE : LAY DANH SACH GD DICH TU NGAY ... DEN NGAY ....

BEGIN

    V_ACCTNO:=AFACCTNO;
    V_CASEBY:=CASEBY;
    V_TABLENAME:=TABLENAME;
    v_FRDATE:=to_date(FRDATE,'DD/MM/YYYY');
    v_TODATE:=to_date(TODATE,'DD/MM/YYYY');
    v_FPAGENUMBER:=FPAGENUMBER;
    v_TPAGENUMBER:=TPAGENUMBER;

if V_TABLENAME = 'CIMAST' THEN
   OPEN PV_REFCURSOR FOR
   SELECT T1.* FROM (
          SELECT LOGDATA.* FROM
               (
                   SELECT LF.TXDATE, LF.TXNUM, LF.BUSDATE, LF.TLTXCD, LF.TXDESC, (CASE WHEN SUBSTR(LF.TLTXCD,1,2)='33'THEN TRF.NAMT ELSE LF.MSGAMT END )AMT  ,TX.TXDESC TLTXDESC,TX.EN_TXDESC TLTXEN_DESC,LF.DELTD
                   FROM (SELECT  TO_CHAR(TXDATE,'DD/MM/RRRR') || TXNUM VOUCHERCD  , MAX(NAMT) NAMT
                   FROM DDTRAN WHERE ACCTNO=V_ACCTNO
                   AND TXDATE>=v_FRDATE
                   AND TXDATE<=v_TODATE GROUP BY TXDATE ,TXNUM) TRF, TLLOG LF, TLTX TX
                   WHERE TRF.VOUCHERCD=TO_CHAR(TXDATE,'DD/MM/RRRR') || TXNUM AND DELTD<>'Y' AND LF.TLTXCD=TX.TLTXCD
                   UNION ALL
                   SELECT LF.TXDATE, LF.TXNUM, LF.BUSDATE, LF.TLTXCD, LF.TXDESC, (CASE WHEN SUBSTR(LF.TLTXCD,1,2)='33'THEN TRF.NAMT ELSE LF.MSGAMT END )AMT ,TX.TXDESC TLTXDESC,TX.EN_TXDESC TLTXEN_DESC,LF.DELTD
                   FROM (SELECT  TO_CHAR(TXDATE,'DD/MM/RRRR') || TXNUM VOUCHERCD ,TXDATE, TXNUM , MAX(NAMT) NAMT
                   FROM DDTRANA WHERE ACCTNO=V_ACCTNO
                   AND TXDATE>=v_FRDATE
                   AND TXDATE<=v_TODATE GROUP BY TXDATE ,TXNUM) TRF, TLLOGALL LF, TLTX TX
                   WHERE TRF.TXNUM=LF.TXNUM AND TRF.TXDATE =LF.TXDATE  AND DELTD<>'Y' AND LF.TLTXCD=TX.TLTXCD
               ) LOGDATA ORDER BY TXDATE, TXNUM
        ) T1
        WHERE ROWNUM BETWEEN v_FPAGENUMBER  AND v_TPAGENUMBER
        ORDER BY TXDATE, TXNUM;
end if;
   EXCEPTION
    WHEN others THEN
        return;
END;
/
