SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE INSERT_SIGNATURE(V_CUSTID varchar2,V_SIGNATURE VARCHAR2,V_VALDATE Varchar2,V_EXPDATE Varchar2,v_DESCRIPTION VARCHAR2) IS
    LONGLITERAL VARCHAR2(32767);
    V_AUTOID NUMBER;
    BEGIN
       --plog.error ('INSERT_SIGNATURE: Begin V_CUSTID='||V_CUSTID||', V_VALDATE='||V_VALDATE||', V_EXPDATE='||V_EXPDATE);
       INSERT INTO log_err
                  (id,date_log, POSITION, text)
           VALUES ( seq_log_err.NEXTVAL,SYSDATE, ' INSERT_SIGNATURE ', 'Begin V_CUSTID='||V_CUSTID);
       LONGLITERAL:=V_SIGNATURE;
       SELECT SEQ_CFSIGN.NEXTVAL INTO V_AUTOID FROM DUAL;
       INSERT INTO CFSIGN(AUTOID,CUSTID,SIGNATURE,VALDATE,EXPDATE,DESCRIPTION)
       VALUES(V_AUTOID,V_CUSTID,LONGLITERAL,TO_DATE(V_VALDATE,'DD/MM/YYYY'),TO_DATE(V_EXPDATE,'DD/MM/RRRR'),v_DESCRIPTION);
        --plog.error ('INSERT_SIGNATURE: End V_CUSTID='||V_CUSTID);
         INSERT INTO log_err
                  (id,date_log, POSITION, text)
           VALUES ( seq_log_err.NEXTVAL,SYSDATE, ' INSERT_SIGNATURE ', 'End V_CUSTID='||V_CUSTID);

    EXCEPTION
    WHEN OTHERS
       THEN

          plog.error ('INSERT_SIGNATURE: '|| SQLERRM || dbms_utility.format_error_backtrace);
    END ;
 
 
/
