SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE OD6030(
   PV_REFCURSOR           IN OUT   PKG_REPORT.REF_CURSOR,
   OPT                    IN       VARCHAR2,
   BRID                   IN       VARCHAR2,

   F_DATE         IN       VARCHAR2,
   T_DATE         IN       VARCHAR2,
   PV_CUSTODYCD         IN       VARCHAR2
   )
IS

    V_STROPTION    VARCHAR2 (5);
    V_STRBRID      VARCHAR2 (4);

    V_FROMDATE           DATE;
    V_TODATE           DATE;
    V_CUSTODYCD    varchar2(20);
    V_ONE NUMBER;
    V_ONE_ONE NUMBER;
    V_ONE_TWO NUMBER;
    V_ONE_THREE NUMBER;
    V_ONE_FOUR NUMBER;
    V_TWO NUMBER;
    V_TWO_ONE NUMBER;
    V_TWO_TWO NUMBER;
    V_TWO_THREE NUMBER;
   BEGIN
     V_STROPTION := OPT;
     IF V_STROPTION = 'A' THEN
        V_STRBRID := '%';
     ELSIF V_STROPTION = 'B' THEN
        V_STRBRID := SUBSTR(BRID,1,2) || '__' ;
     ELSE
        V_STRBRID:=BRID;
     END IF;
     ------------------------------------
     V_CUSTODYCD := UPPER(REPLACE(PV_CUSTODYCD,'.',''));
     IF (V_CUSTODYCD = 'ALL') THEN
        V_CUSTODYCD := '%';
     ELSE
        V_CUSTODYCD:= V_CUSTODYCD;
     END IF;
     ------------------------------------
     V_FROMDATE := to_date(F_DATE,SYSTEMNUMS.C_DATE_FORMAT);
     V_TODATE := to_date(T_DATE,SYSTEMNUMS.C_DATE_FORMAT);
 ---------------------------------1.2--------------------------------------------
BEGIN
    SELECT
    NVL(SUM(
            CASE
                WHEN DDTRAN.TXTYPE = 'C' THEN NAMT
                ELSE -NAMT
            END
            ),0) AMOUNT
    INTO  V_ONE_TWO
    FROM VW_DDTRAN_GEN DDTRAN, DDMAST DD,CFMAST CF,
        (
            SELECT DISTINCT TL.TLTXCD AS TLTXCD_REF,CQ.TXDATE, CR.REFTXNUM
            FROM
                (SELECT * FROM CRBBANKREQUEST UNION ALL SELECT * FROM CRBBANKREQUESTHIST) CR,
                (SELECT * FROM CRBTXREQ UNION ALL SELECT * FROM CRBTXREQHIST) CQ,
                (SELECT * FROM TLLOG UNION ALL  SELECT DISTINCT * FROM TLLOGALL) TL
            WHERE CR.TRNREF=CQ.REPVAL
                AND TL.TXNUM = SUBSTR(CQ.REQTXNUM,INSTR (CQ.REQTXNUM,'.',1,2) +1)
                AND TO_CHAR(TL.TXDATE,'RRRRMMDD') = SUBSTR(CQ.REQTXNUM,INSTR (CQ.REQTXNUM,'.',1,1) +1,INSTR(CQ.REQTXNUM,'.',1,2) -4)
                --AND CR.CBOBJ IN ('6674')
        ) TL
    WHERE DDTRAN.FIELD ='BALANCE'
    AND DDTRAN.TXNUM = TL.REFTXNUM(+) AND DDTRAN.TXDATE =TL.TXDATE (+)
    AND DDTRAN.TXTYPE IN ('D','C')
    AND ((DDTRAN.TLTXCD  IN ('6626') AND TL.TLTXCD_REF IN ('2211')) OR (DDTRAN.TLTXCD  IN ('6674') AND TL.TLTXCD_REF IN ('8820','8880')))--GD8820,8880 SINH 6674/ GD2211,1401 SINH 6626(BAN)
    AND DDTRAN.ACCTNO=DD.ACCTNO
    AND DDTRAN.CUSTODYCD = CF.CUSTODYCD
    AND DD.CCYCD='VND'
    AND DD.ACCOUNTTYPE='IICA'
    AND CF.CUSTATCOM ='Y'
    AND DDTRAN.BUSDATE BETWEEN V_FROMDATE AND V_TODATE
    AND DDTRAN.CUSTODYCD LIKE V_CUSTODYCD;
EXCEPTION WHEN NO_DATA_FOUND THEN V_ONE_TWO:=0;
END;
---------------------------------1.3--------------------------------------------
BEGIN
    SELECT
        NVL(SUM(
               CASE WHEN DDTRAN.TLTXCD IN ('3350','3354') THEN
                     CASE
                        WHEN DDTRAN.TXTYPE = 'D' THEN NAMT
                        ELSE -NAMT
                     END
               ELSE
                    CASE
                        WHEN DDTRAN.TXTYPE = 'C' THEN NAMT
                        ELSE -NAMT
                    END
               END
            ),0) AMOUNT
    INTO  V_ONE_THREE
    FROM VW_DDTRAN_GEN DDTRAN, DDMAST DD,CFMAST CF,
        (
            SELECT DISTINCT TL.TLTXCD AS TLTXCD_REF,CQ.TXDATE, CR.REFTXNUM
            FROM
                (SELECT * FROM CRBBANKREQUEST UNION ALL SELECT * FROM CRBBANKREQUESTHIST) CR,
                (SELECT * FROM CRBTXREQ UNION ALL SELECT * FROM CRBTXREQHIST) CQ,
                (SELECT * FROM TLLOG UNION ALL  SELECT DISTINCT * FROM TLLOGALL) TL
            WHERE CR.TRNREF=CQ.REPVAL
                AND TL.TXNUM = SUBSTR(CQ.REQTXNUM,INSTR (CQ.REQTXNUM,'.',1,2) +1)
                AND TO_CHAR(TL.TXDATE,'RRRRMMDD') = SUBSTR(CQ.REQTXNUM,INSTR (CQ.REQTXNUM,'.',1,1) +1,INSTR(CQ.REQTXNUM,'.',1,2) -4)
                AND CR.CBOBJ IN ('6674')
        ) TL
    WHERE DDTRAN.FIELD IN (CASE WHEN DDTRAN.TLTXCD IN ('3350','3354') THEN 'RECEIVING' ELSE 'BALANCE' END)
    AND DDTRAN.TXNUM = TL.REFTXNUM(+) AND DDTRAN.TXDATE =TL.TXDATE (+)
    AND DDTRAN.TXTYPE IN ('D','C')
    AND ((DDTRAN.TLTXCD = '6674' AND TL.TLTXCD_REF IN ('3350','3354')) OR  DDTRAN.TLTXCD IN ('3350','3354'))
    AND DDTRAN.ACCTNO=DD.ACCTNO
    AND DDTRAN.CUSTODYCD = CF.CUSTODYCD
    AND DD.CCYCD='VND'
    AND DD.ACCOUNTTYPE='IICA'
    AND CF.CUSTATCOM ='Y'
    AND DDTRAN.BUSDATE BETWEEN V_FROMDATE AND V_TODATE
    AND DDTRAN.CUSTODYCD LIKE V_CUSTODYCD;
EXCEPTION WHEN NO_DATA_FOUND THEN V_ONE_THREE:=0;
END;
---------------------------------2.1--------------------------------------------
BEGIN
    SELECT
      NVL(SUM(
            CASE
                WHEN DDTRAN.TXTYPE = 'C' THEN -NAMT
                ELSE NAMT
            END
            ),0) AMOUNT
    INTO  V_TWO_ONE
    FROM VW_DDTRAN_GEN DDTRAN, DDMAST DD,CFMAST CF
    WHERE DDTRAN.FIELD ='BALANCE'
    AND DDTRAN.TXTYPE IN ('D','C')
    AND DDTRAN.TLTXCD  IN ('6673','6651','6620','6621','6650')--8818: 6673/ 8869: 6651,6673 /2211:6620 MUA /1401:6620,6621 MUA/3339: 6650
    AND DDTRAN.ACCTNO=DD.ACCTNO
    AND DDTRAN.CUSTODYCD = CF.CUSTODYCD
    AND DD.CCYCD='VND'
    AND DD.ACCOUNTTYPE='IICA'
    AND CF.CUSTATCOM ='Y'
    AND DDTRAN.BUSDATE BETWEEN V_FROMDATE AND V_TODATE
    AND DDTRAN.CUSTODYCD LIKE V_CUSTODYCD;
EXCEPTION WHEN NO_DATA_FOUND THEN V_TWO_ONE:=0;
END;
---------------------------------2.3--------------------------------------------
BEGIN
    SELECT NVL(SUM(TB.VATAMOUNT),0)
        INTO V_TWO_THREE
    FROM TAX_BOOKING_RESULT TB,DDMAST DD,CFMAST CF
    WHERE  TB.CIFID = CF.CIFID
            AND CF.CUSTODYCD =DD.CUSTODYCD
            AND DD.ISDEFAULT ='Y' AND DD.ACCOUNTTYPE ='IICA'
            AND DD.CUSTODYCD LIKE V_CUSTODYCD
            AND TB.PAYMENTDATE BETWEEN V_FROMDATE AND V_TODATE;
EXCEPTION WHEN NO_DATA_FOUND THEN V_TWO_THREE:=0;
END;
---------------------------------SUM--------------------------------------------
V_ONE_ONE:=0;
V_ONE_FOUR:=0;
V_TWO_TWO:=0;
V_ONE:= V_ONE_ONE + V_ONE_TWO +V_ONE_THREE+V_ONE_FOUR;
V_TWO:= V_TWO_ONE + V_TWO_TWO +V_TWO_THREE;
OPEN PV_REFCURSOR FOR

SELECT
        V_ONE AS SUM_ONE,
        V_ONE_TWO AS ONE_TWO,
        V_ONE_THREE AS ONE_THREE,

        V_TWO AS SUM_TWO,
        V_TWO_ONE AS TWO_ONE,
        V_TWO_THREE AS TWO_THREE
FROM DUAL;

EXCEPTION
  WHEN OTHERS
   THEN
      PLOG.ERROR ('OD6030: ' || SQLERRM || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
      RETURN;
END;
/
