SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE PR_LOG_USERNAME(P_TXMSG IN TX.MSG_RECTYPE, P_USERNAME VARCHAR2, P_MODE VARCHAR2) IS

BEGIN
    IF P_MODE = 'C' THEN
        INSERT INTO ONLREQUESTLOG_USER(TXDATE, TXNUM, USER_CREATED, TIME_CREATED)
        VALUES(TO_DATE(P_TXMSG.TXDATE, SYSTEMNUMS.C_DATE_FORMAT), P_TXMSG.TXNUM, P_USERNAME, SYSDATE);
    ELSIF P_MODE = 'A' THEN
        UPDATE ONLREQUESTLOG_USER SET USER_APPR = P_USERNAME, TIME_APPR = SYSDATE WHERE TXDATE = TO_DATE(P_TXMSG.TXDATE, SYSTEMNUMS.C_DATE_FORMAT) AND TXNUM = P_TXMSG.TXNUM;
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        PLOG.ERROR('PR_LOG_USERNAME: ' || SQLERRM || ' TRACE: ' ||DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END; -- Procedure
/
