SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE pr_vstp_settle_hold
IS
    P_ERR_CODE VARCHAR2(250);
    L_HOLDBALACE NUMBER;
    L_COUNT NUMBER;
    L_ERRMSG VARCHAR2(500);
    L_REQUESTKEY VARCHAR2(100);
BEGIN
    FOR REC IN (
        SELECT VLOG.CUSTODYCD, VLOG.DDACCTNO, VLOG.MEMBERID, DD.REFCASAACCT, VERSION, (MIN(BEFOR_HOLD) - SUM(AMT)) AMOUNT
        FROM VSTP_SETTLE_LOG VLOG, DDMAST DD
        WHERE VLOG.STATUS = '2.1'
        AND VLOG.DDACCTNO = DD.ACCTNO
        AND VLOG.PROCESS <= 3
        GROUP BY VLOG.CUSTODYCD, VLOG.DDACCTNO, VLOG.MEMBERID, DD.REFCASAACCT, VERSION
        ORDER BY MIN(VLOG.AUTOID)
    )
    LOOP

        IF REC.AMOUNT <= 0 THEN
            UPDATE VSTP_SETTLE_LOG
            SET STATUS = '3.1', PSTATUS = STATUS, LASTCHANGE = SYSTIMESTAMP
            WHERE VERSION = REC.VERSION
            AND STATUS = '2.1';
            CONTINUE;
        END IF;

        --co xu ly dang unhold, dang cat tien, dang hold thi khong hold
        SELECT COUNT(1) INTO L_COUNT FROM VSTP_SETTLE_LOG WHERE CUSTODYCD = REC.CUSTODYCD AND DDACCTNO = REC.DDACCTNO AND MEMBERID = REC.MEMBERID AND STATUS IN ('1','2','2.2','3');
        IF L_COUNT > 0 THEN
            CONTINUE;
        END IF;

        L_REQUESTKEY := 'VSTP.' || REC.VERSION;
        PCK_BANKAPI.BANK_HOLDBALANCE(REC.DDACCTNO, REC.MEMBERID, '', '', REC.AMOUNT, 'BANKHOLDEDBYBROKERTPRL', L_REQUESTKEY, 'PPBs - Hold back unused money', SYSTEMNUMS.C_SYSTEM_USERID, P_ERR_CODE);
        IF P_ERR_CODE <> SYSTEMNUMS.C_SUCCESS THEN
            PLOG.ERROR ('PR_VSTP_SETTLE_HOLD: VERSION = ' || REC.VERSION || '-' || SQLERRM || ' ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
            L_ERRMSG := 'PR_VSTP_SETTLE_HOLD: VERSION = ' || REC.VERSION || '-' || SQLERRM || ' ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;

            UPDATE VSTP_SETTLE_LOG
            SET PROCESS = PROCESS + 1,
                ERRMSG = SUBSTR(L_ERRMSG, 1, 500)
            WHERE VERSION = REC.VERSION;

            CONTINUE;
        END IF;

        UPDATE VSTP_SETTLE_LOG
        SET STATUS = '3', PSTATUS = STATUS, LASTCHANGE = SYSTIMESTAMP
        WHERE VERSION = REC.VERSION
        AND STATUS = '2.1';
    END LOOP;
EXCEPTION WHEN OTHERS THEN
    RETURN;
END;
/
