SET DEFINE OFF;
CREATE OR REPLACE
PROCEDURE prc_update_synctoredis(P_AUTOID NUMBER, P_STATUS VARCHAR2, P_ERROR_MSG VARCHAR2, P_ERR_CODE IN OUT VARCHAR2, P_ERR_PARAM IN OUT VARCHAR2)
IS

BEGIN
    P_ERR_CODE  := SYSTEMNUMS.C_SUCCESS;

    UPDATE SYNC_TO_REDIS
    SET STATUS = P_STATUS,
        ERROR_MSG = P_ERROR_MSG
    WHERE AUTOID = P_AUTOID;

EXCEPTION WHEN OTHERS THEN
    P_ERR_CODE := ERRNUMS.C_SYSTEM_ERROR;
    PLOG.ERROR('PRC_UPDATE_SYNCTOREDIS ERR: ' || SQLERRM || ' TRACE: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE );
END;
/
