SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE PRC_MANUAL_CAL
IS
    L_MSG VARCHAR2(1000);
BEGIN
    FOR REC IN (
        SELECT * FROM MANUAL_CAL_JOB
        WHERE STATUS = 'P'
        AND ROWNUM < 5
        ORDER BY CTYPE, TXDATE
    )
    LOOP
        UPDATE MANUAL_CAL_JOB SET STATUS = 'Q' WHERE CTYPE = REC.CTYPE AND TXDATE = REC.TXDATE;
        BEGIN
            IF REC.CTYPE = 'LTVCAL' THEN
                PROC_LTVCAL(REC.TXDATE, NULL);
                UPDATE MANUAL_CAL_JOB SET STATUS = 'C', ENDDT = SYSTIMESTAMP WHERE CTYPE = REC.CTYPE AND TXDATE = REC.TXDATE;
            ELSIF REC.CTYPE = 'STOCK_INFO' THEN
                PRC_SYN_STOCKINFO_FROM_FINN();
                UPDATE MANUAL_CAL_JOB SET STATUS = 'C', ENDDT = SYSTIMESTAMP WHERE CTYPE = REC.CTYPE AND TXDATE = REC.TXDATE;
            END IF;
        EXCEPTION WHEN OTHERS THEN
            L_MSG := SQLERRM || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
            PLOG.ERROR('PRC_MANUAL_CAL - CTYPE: ' || REC.CTYPE || ' - ' || SQLERRM || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
            UPDATE MANUAL_CAL_JOB SET STATUS = 'E', ENDDT = SYSTIMESTAMP, MSG = L_MSG WHERE CTYPE = REC.CTYPE AND TXDATE = REC.TXDATE;
        END;
    END LOOP;
EXCEPTION WHEN OTHERS THEN
  PLOG.ERROR(SQLERRM || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END;



-- END OF DDL SCRIPT FOR PROCEDURE HOSTCB.SP_SYNC_FIIN
/
