SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE PRC_UPDATE_SEARCHCODE_TLTXCD
IS
       V_COUNT_S       NUMBER;
       V_COUNT_SFLD    NUMBER;
       V_COUNT_RMST    NUMBER;
BEGIN

      BEGIN
        FOR REC IN
        (
            -- LAY RA CAC GD CO 4 KI TU SAU CUA SEARCHCODE KHAC VOI MA GD
            SELECT SEARCHCODE, TLTXCD, SUBSTR(TRIM(SEARCHCODE), 1, 2) || TRIM(TLTXCD) NEWSEARCHCODE FROM SEARCH 
            WHERE TRIM(TLTXCD) IS NOT NULL AND SUBSTR(TRIM(SEARCHCODE), 3, 4) <> TRIM(TLTXCD) AND TRIM(TLTXCD) <> 'EXEC' AND TRIM(SEARCHCODE) <> 'PAYMENTORDER'
        )
        LOOP
            -- XEM NEWSEARCHCODE DA TON TAI TRONG SEARCH CHUA
            SELECT COUNT(1)
            INTO V_COUNT_S
            FROM SEARCH WHERE SEARCHCODE =  REC.NEWSEARCHCODE;
            
            -- XEM NEWSEARCHCODE DA TON TAI TRONG SEARCHFLD CHUA
            SELECT COUNT(1)
            INTO V_COUNT_SFLD
            FROM SEARCHFLD WHERE SEARCHCODE =  REC.NEWSEARCHCODE;
            
            -- XEM NEWSEARCHCODE DA TON TAI TRONG RPTMASTER CHUA
            SELECT COUNT(1)
            INTO V_COUNT_RMST
            FROM RPTMASTER WHERE RPTID = REC.NEWSEARCHCODE;
            
            -- NEU KHONG TRUNG THUC HIEN CAP NHAT
            IF (V_COUNT_S = 0 AND V_COUNT_SFLD = 0 AND V_COUNT_RMST = 0) THEN
               -- CAP NHAT RPTMASTER
                UPDATE RPTMASTER SET RPTID = REC.NEWSEARCHCODE WHERE RPTID = REC.SEARCHCODE;

                -- CAP NHAT SEARCH
                UPDATE SEARCH SET SEARCHCODE = REC.NEWSEARCHCODE WHERE SEARCHCODE = REC.SEARCHCODE;

                -- CAP NHAT SEARCHFLD
                UPDATE SEARCHFLD SET SEARCHCODE = REC.NEWSEARCHCODE WHERE SEARCHCODE = REC.SEARCHCODE;
                
                -- LOG VAO BANG LOGCSC
                INSERT INTO LOGCSC (OLDSEARCHCODE, NEWSEARCHCODE, TLTXCD)
                VALUES (REC.SEARCHCODE, REC.NEWSEARCHCODE, REC.TLTXCD);

                COMMIT;
            END IF;
        
        END LOOP;
      END;
     
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN;
END;

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
/
