SET DEFINE OFF;
CREATE OR REPLACE
PROCEDURE prc_get_crbtxreq(P_REFCURSOR IN OUT PKG_REPORT.REF_CURSOR, P_ERR_CODE IN OUT VARCHAR2, P_ERR_PARAM IN OUT VARCHAR2)
IS
    L_REQID NUMBER;
BEGIN
    P_ERR_CODE  := SYSTEMNUMS.C_SUCCESS;
    BEGIN
        SELECT DT.REQID INTO L_REQID
        FROM
        (
            SELECT CRB.REQID
            FROM FLMSGJSON FLM, CRBTXREQ CRB
            WHERE FLM.REQID = CRB.REQID
            AND FLM.STATUS = 'P'
            AND CRB.STATUS = 'W'
            ORDER BY CRB.REQID ASC
        ) DT
        WHERE ROWNUM = 1;
    EXCEPTION WHEN OTHERS THEN
        L_REQID := NULL;
    END;

    OPEN P_REFCURSOR FOR
    SELECT * FROM FLMSGJSON WHERE STATUS = 'P' AND REQID = L_REQID;

    UPDATE FLMSGJSON SET STATUS = 'S' WHERE STATUS = 'P' AND REQID = L_REQID;
    UPDATE CRBTXREQ SET STATUS = 'S' WHERE STATUS = 'W' AND REQID = L_REQID;

EXCEPTION WHEN OTHERS THEN
    P_ERR_CODE := ERRNUMS.C_SYSTEM_ERROR;
    PLOG.ERROR('PRC_GET_CRBTXREQ ERR: ' || SQLERRM || ' TRACE: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE );
END;
/
