SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE sa0001 (
   PV_REFCURSOR   IN OUT   PKG_REPORT.REF_CURSOR,
   OPT            IN       VARCHAR2,
   BRID           IN       VARCHAR2,
   GRPID          IN       VARCHAR2
 )
IS
--
-- PURPOSE: BRIEFLY EXPLAIN THE FUNCTIONALITY OF THE PROCEDURE
--
-- MODIFICATION HISTORY
-- PERSON      DATE    COMMENTS
-- MINHTK   21-NOV-06  CREATED
-- ---------   ------  -------------------------------------------
   V_STROPTION        VARCHAR2 (5);       -- A: ALL; B: BRANCH; S: SUB-BRANCH
   V_STRBRID          VARCHAR2 (4);        -- USED WHEN V_NUMOPTION > 0
   V_STRGRPID              VARCHAR2 (6);
   V_STRGRPNAME            VARCHAR2 (50);
   V_STRACTIVE             VARCHAR2 (6);
   V_STRDESCRIPTION        VARCHAR2 (50);
   V_STRCOU                VARCHAR2 (6);
   V_STRGRPTYPE           VARCHAR2 (50);


   PV_CUR      PKG_REPORT.REF_CURSOR;
-- DECLARE PROGRAM VARIABLES AS SHOWN ABOVE
BEGIN
-- INSERT INTO TEMP_BUG(TEXT) VALUES('CF0001');COMMIT;
   V_STROPTION := OPT;

   IF (V_STROPTION <> 'A') AND (BRID <> 'ALL')
   THEN
      V_STRBRID := BRID;
   ELSE
      V_STRBRID := '%%';
   END IF;
V_STRGRPID:=GRPID;

OPEN PV_CUR
    FOR
SELECT TLGR.GRPID,TLGR.GRPNAME ,TLGR.ACTIVE ,TLGR.DESCRIPTION,COU.COU,AL.CDCONTENT
FROM TLGROUPS TLGR,(SELECT COUNT(ROWNUM) COU FROM TLGRPUSERS WHERE  GRPID like V_STRGRPID )COU,ALLCODE AL
WHERE AL.CDNAME='GRPTYPE' AND  AL.CDTYPE='SA' AND  AL.CDVAL =TLGR.GRPTYPE
and TLGR.grpid like V_STRGRPID
 ;

LOOP
FETCH PV_CUR
   INTO V_STRGRPID,V_STRGRPNAME,V_STRACTIVE,V_STRDESCRIPTION ,V_STRCOU,V_STRGRPTYPE;

  EXIT WHEN PV_CUR%NOTFOUND;

END LOOP;



OPEN PV_REFCURSOR
  FOR
SELECT  V_STRGRPID GRPID,V_STRGRPNAME GRPNAME,V_STRACTIVE ACTIVE,V_STRDESCRIPTION DESCRIPTION ,V_STRCOU
count,V_STRGRPTYPE GRPTYPE,
TLPRO.TLID, TLPRO.TLNAME,TLPRO.TLFULLNAME,BR.BRNAME BRID  ,TLPRO.TLTITLE
FROM TLPROFILES TLPRO ,TLGRPUSERS TLGR , BRGRP BR
WHERE TLPRO.TLID =TLGR.TLID
AND BR.BRID = TLPRO.BRID
and TLGR.grpid  like V_STRGRPID
order by TLPRO.TLID ;


 EXCEPTION
   WHEN OTHERS
   THEN

      RETURN;
END;                                                              -- PROCEDURE
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
/
