SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE se0088 (
   PV_REFCURSOR   IN OUT   PKG_REPORT.REF_CURSOR,
   OPT            IN       VARCHAR2,
   BRID           IN       VARCHAR2,
   PV_KEY         IN       VARCHAR2
       )
IS

-- RP NAME : BAO CAO BANG KE CHUNG KHOAN GIAO DICH LO LE SUM GROUP THEO MA CHUNG KHOAN
-- PERSON :  QUYET.KIEU
-- DATE :    27/04/2011
-- COMMENTS : CREATE NEW
-- ---------   ------  -------------------------------------------
   V_STRKEY    NUMBER(10);

BEGIN
-- GET REPORT'S PARAMETERS

   V_STRKEY := TO_NUMBER(PV_KEY);

-- GET REPORT'S DATA
 OPEN PV_REFCURSOR
 FOR
SELECT  tl.sendoutid, CF.CUSTODYCD, CF.FULLNAME, CF.IDCODE, CF.IDDATE, CF.IDPLACE, CF.ADDRESS, CF.MOBILESMS,
    A.CDCONTENT TRADEPLACE, sb.SYMBOL, tl.TXDATE, dep.fullname depfullname, sen.recustodycd, nvl(sen.recustname,'') recustname,
    SUM(TL.TRADE) TRADE, SUM(TL.BLOCKED) BLOCKED, SUM(TL.TRADE_WFT) TRADE_WFT, SUM(TL.BLOCKED_WFT) BLOCKED_WFT
FROM SE2255_LOG TL, AFMAST AF, CFMAST CF ,
    (
        SELECT SB1.CODEID,
            (CASE WHEN SB1.REFCODEID IS NULL THEN SB1.SYMBOL ELSE SB2.SYMBOL END) SYMBOL,
            (CASE WHEN SB1.REFCODEID IS NULL THEN SB1.TRADEPLACE ELSE SB2.TRADEPLACE END) TRADEPLACE
        FROM SBSECURITIES SB1, SBSECURITIES SB2
        WHERE SB1.REFCODEID = SB2.CODEID(+)
    ) SB, ALLCODE A, sesendout sen, deposit_member dep
WHERE TL.AFACCTNO = AF.ACCTNO AND AF.CUSTID = CF.CUSTID
    AND TL.DELTD <> 'Y' AND A.CDTYPE = 'SE' AND TL.codeid = SB.CODEID
    AND AF.ACTYPE NOT IN ('0000')
    AND A.CDNAME = 'TRADEPLACE' AND SB.TRADEPLACE = A.CDVAL
    and tl.sendoutid = sen.autoid and sen.outward = dep.DEPOSITID
    AND  tl.sendoutid = V_STRKEY
GROUP BY tl.TXDATE, CF.CUSTODYCD, sb.SYMBOL, CF.FULLNAME, CF.IDCODE, CF.IDDATE, CF.IDPLACE,
    CF.ADDRESS, CF.MOBILESMS, A.CDCONTENT, tl.sendoutid, dep.fullname, sen.recustodycd, nvl(sen.recustname,'');
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN;
END;
/
