SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE SE00300 (
   PV_REFCURSOR   IN OUT   PKG_REPORT.REF_CURSOR,
   OPT            IN       VARCHAR2,
   BRID           IN       VARCHAR2,
   F_DATE         IN       VARCHAR2,
   T_DATE         IN       VARCHAR2,
   PV_CUSTODYCD   IN       VARCHAR2,
   PV_AFACCTNO    IN       VARCHAR2,
   PLSENT         IN       VARCHAR2
)
IS

-- RP NAME : YEU CAU CHUYEN KHOAN CHUNG KHOAN LO LE
-- PERSON --------------DATE---------------------COMMENTS
-- NAM.LY               18/11/2019               CREATE
-- SE00300: REPORT MAIN
-- ---------   ------  -------------------------------------------
   V_STRAFACCTNO  VARCHAR2 (15);
   V_CUSTODYCD VARCHAR2 (15);
   V_CURRDATE DATE;
   V_STRFULLNAME  VARCHAR2(200);
   V_STR_TVLK_CODE  VARCHAR2(10);
   V_STR_TVLK_NAME  VARCHAR2(200);
   V_STR_CUSTODYCD_NHAN  VARCHAR2(10);
   CUR            PKG_REPORT.REF_CURSOR;

   V_INBRID        VARCHAR2(4);
   V_STRBRID      VARCHAR2 (50);
   V_STROPTION    VARCHAR2(5);
   V_TOTALCAQTTY NUMBER;

   V_FRDATE DATE;
   V_TODATE DATE;

BEGIN
-- GET REPORT'S PARAMETERS
  V_STROPTION := UPPER(OPT);
  V_INBRID := BRID;
    IF(V_STROPTION = 'A') THEN
        V_STRBRID := '%%';
    ELSE
        IF(V_STROPTION = 'B') THEN
            SELECT BR.MAPID INTO V_STRBRID FROM BRGRP BR WHERE  BR.BRID = V_INBRID;
        ELSE
            V_STRBRID := V_INBRID;
        END IF;
    END IF;

    V_CUSTODYCD := UPPER(REPLACE( PV_CUSTODYCD,'.',''));

    V_STR_TVLK_NAME :=' ';
    V_STR_TVLK_CODE :=' ';
    V_STRFULLNAME :=' ';


    SELECT TO_DATE(VARVALUE,'DD/MM/RRRR') INTO V_CURRDATE
    FROM SYSVAR WHERE VARNAME = 'CURRDATE' AND GRNAME = 'SYSTEM';

   IF  (PV_AFACCTNO <> 'ALL')
   THEN
         V_STRAFACCTNO := PV_AFACCTNO;
   ELSE
         V_STRAFACCTNO := '%';
   END IF;

  --SELECT FULLNAME INTO V_STRFULLNAME FROM CFMAST WHERE CUSTODYCD = V_CUSTODYCD;

  SELECT  SUM(CAS.TRADE)  REPORT_QTTY INTO V_TOTALCAQTTY
  FROM CASCHD  CAS, CAMAST CA, CFMAST CF,
    AFMAST AF, SBSECURITIES SB
  WHERE CF.CUSTODYCD = V_CUSTODYCD AND CF.CUSTID = AF.CUSTID
    AND CAS.AFACCTNO = AF.ACCTNO AND CA.CAMASTID = CAS.CAMASTID
    AND AF.ACCTNO LIKE V_STRAFACCTNO
    AND CAS.CODEID = SB.CODEID
    AND CAS.STATUS ='O' ;

    V_FRDATE := TO_DATE (F_DATE  ,'DD/MM/RRRR');
    V_TODATE := TO_DATE (T_DATE  ,'DD/MM/RRRR');

-- GET REPORT'S DATA
 OPEN PV_REFCURSOR
 FOR

        SELECT
        NVL(DT.PARVALUE,10000) PARVALUE, NVL(DT.SYMBOL,'--') SYMBOL, NVL(DT.TK_NO,'') TK_NO, NVL(DT.TK_CO,'') TK_CO, AC.CUSTODYCD,
        NVL(DT.SAN_GD,'') SAN_GD, NVL(DT.NAMT,0) NAMT, NVL(DT.SE_TYPE,'') SE_TYPE, AC.FULLNAME, NVL(DT.TEN_TVLK_NHAN,'') TEN_TVLK_NHAN, NVL(DT.MA_TVLK_NHAN,'') MA_TVLK_NHAN,
        NVL(DT.SO_TKLK_NHAN,'') SO_TKLK_NHAN, NVL(DT.TEN_NGUOI_NHAN,AC.FULLNAME) TEN_NGUOI_NHAN,AUTOID2247,
        V_CURRDATE CURDATE,PLSENT  PL_SENT , NVL(V_TOTALCAQTTY,0) TOTALCAQTTY,
        TO_NUMBER(DT.ORD_NUM) ORD_NUM
    FROM (
        SELECT TL.AUTOID, NVL(REAT_2247.AUTOID,-1) AUTOID2247,TL.TXDATE, FLD.TXNUM, TL.BUSDATE, MAX(DECODE(FLD.FLDCD,'80',CVALUE,'')) CLOSETYPE ,
            MAX(DECODE(FLD.FLDCD,'88',CVALUE,'')) CUSTODYCD, MAX(DECODE(FLD.FLDCD,'31',CVALUE,'')) FULLNAME
        FROM VW_TLLOG_ALL TL, VW_TLLOGFLD_ALL FLD,
            (
                SELECT MAX(AUTOID) AUTOID
                FROM VW_TLLOG_ALL TL
                WHERE TL.TLTXCD='0088' AND TL.DELTD='N' AND TL.CFCUSTODYCD = V_CUSTODYCD
                    AND TL.BUSDATE >= V_FRDATE
                    AND TL.BUSDATE <= V_TODATE
            ) LOG,
            (
                SELECT MAX(AUTOID) AUTOID
                FROM VW_TLLOG_ALL TL
                WHERE TL.TLTXCD='2291' AND TL.DELTD='N' AND TL.CFCUSTODYCD = V_CUSTODYCD
                    AND TL.BUSDATE >= V_FRDATE
                    AND TL.BUSDATE <= V_TODATE
            ) REAT_0088,
            (
              SELECT MAX(AUTOID) AUTOID
              FROM VW_TLLOG_ALL TL
              WHERE TL.TLTXCD='2290' AND TL.DELTD='N' AND TL.CFCUSTODYCD = V_CUSTODYCD
                  AND TL.BUSDATE >= V_FRDATE
                  AND TL.BUSDATE <= V_TODATE
            ) REAT_2247
        WHERE TL.TLTXCD = '0088'  AND TL.DELTD = 'N' AND TL.AUTOID=LOG.AUTOID AND LOG.AUTOID > NVL(REAT_0088.AUTOID,0)
            AND FLD.TXNUM=TL.TXNUM AND FLD.TXDATE=TL.TXDATE
            AND FLD.FLDCD IN ('80','88','31')
            AND TL.TXDATE >= V_FRDATE
            AND TL.TXDATE <= V_TODATE
        GROUP BY TL.AUTOID, NVL(REAT_2247.AUTOID,-1),TL.TXDATE, FLD.TXNUM, TL.BUSDATE
    )AC, (
        SELECT DT.AUTOID, SB.PARVALUE , SB.SYMBOL,
            ('012' || (CASE WHEN DT.SE_TYPE IN ('8','7') THEN '72' ELSE
                (CASE WHEN DT.SE_TYPE = '1' THEN '12' ELSE '22' END) END) || '.' || DT.MA_TVLK_NHAN
            ) TK_NO,
            ('012' || (CASE WHEN DT.SE_TYPE IN ('8','7') THEN '72' ELSE
                (CASE WHEN DT.SE_TYPE = '1' THEN '12' ELSE '22' END) END) || '.022'
            ) TK_CO,
            DT.CUSTODYCD,
            (CASE WHEN  NVL(SB.TRADEPLACE,'') = '010' AND SB.SECTYPE IN ('003','006','222','333','444') THEN 'BOND'
                  ELSE
                      (CASE WHEN SB.TRADEPLACE='002' THEN 'HNX'
                            WHEN SB.TRADEPLACE='001' THEN 'HOSE'
                            WHEN SB.TRADEPLACE='005' THEN 'UPCOM'
                            WHEN SB.TRADEPLACE='003' THEN 'OTC'
                            WHEN SB.TRADEPLACE='009' THEN 'DCCNY'
                            ELSE 'UPCOM' END) END
            ) SAN_GD,
            RANK() OVER (ORDER BY ( (CASE WHEN  NVL(SB.TRADEPLACE,'') = '010' AND SB.SECTYPE IN ('003','006','222','333','444') THEN 4
                ELSE
                    (CASE WHEN SB.TRADEPLACE ='002' THEN 1
                          WHEN SB.TRADEPLACE='001' THEN 2
                          WHEN SB.TRADEPLACE='005' THEN 3
                          WHEN SB.TRADEPLACE='003' THEN 5
                          WHEN SB.TRADEPLACE='009' THEN 6
                          ELSE 3 END) END )))  ORD_NUM,
            DT.NAMT, DT.SE_TYPE,-- V_STRFULLNAME FULLNAME,
            NVL(DEP.FULLNAME,' ') TEN_TVLK_NHAN, MA_TVLK_NHAN, SO_TKLK_NHAN, NVL(CF.FULLNAME,'') TEN_NGUOI_NHAN
            --,PLSENT  PL_SENT , NVL(V_TOTALCAQTTY,0) TOTALCAQTTY
          FROM SBSECURITIES SB,
          (
            SELECT TL.AUTOID,TL.TXDATE,TL.TXNUM, MAX(SE.CUSTODYCD) CUSTODYCD,
                MAX(SE.AFACCTNO) AFACCTNO, MAX(SE.TXCD) TXCD,
                MAX(SE.SECTYPE) SECTYPE, MAX(SB.TRADEPLACE) TRADEPLACE,
                MAX(SE.NAMT) NAMT, MAX(SE.BUSDATE) BUSDATE,
                MAX(NVL(SB.REFCODEID,SB.CODEID))CODEID,
                MAX (CASE WHEN SB.REFCODEID IS NULL THEN '1' ELSE '7' END) SE_TYPE,
                MAX(DECODE(FLD.FLDCD,'11',FLD.NVALUE,NULL)) MENH_GIA,
                MAX(DECODE(FLD.FLDCD,'27',CVALUE,NULL)) MA_TVLK_NHAN,
                MAX(DECODE(FLD.FLDCD,'28',CVALUE,NULL)) SO_TKLK_NHAN,
                MAX(DECODE(FLD.FLDCD,'29',CVALUE,NULL)) TEN_NGUOI_NHAN
            FROM   VW_TLLOG_ALL TL,SBSECURITIES SB, VW_SETRAN_GEN SE,
                VW_TLLOGFLD_ALL FLD
            WHERE   TL.TLTXCD = '8815'  AND TL.DELTD = 'N'
                AND SE.TXNUM=TL.TXNUM AND SE.TXDATE=TL.TXDATE
                AND FLD.TXNUM=TL.TXNUM AND FLD.TXDATE=TL.TXDATE
                AND SE.TXCD='0040'
                AND SE.NAMT<>0
                AND SUBSTR(MSGACCT, 11, 6)=SB.CODEID
                AND TL.TXDATE >= TO_DATE (F_DATE  ,'DD/MM/RRRR')
                AND TL.TXDATE <= TO_DATE (T_DATE  ,'DD/MM/RRRR')
                AND SE.AFACCTNO LIKE V_STRAFACCTNO
                AND SE.CUSTODYCD LIKE V_CUSTODYCD
            GROUP BY TL.AUTOID,TL.TXNUM,TL.TXDATE
            UNION ALL
            SELECT  TL.AUTOID,TL.TXDATE,TL.TXNUM, MAX(SE.CUSTODYCD) CUSTODYCD,
                MAX(SE.AFACCTNO) AFACCTNO, MAX(SE.TXCD) TXCD,
                MAX(SE.SECTYPE) SECTYPE, MAX(SB.TRADEPLACE) TRADEPLACE,
                MAX(SE.NAMT) NAMT, MAX(SE.BUSDATE) BUSDATE,
                MAX(NVL(SB.REFCODEID,SB.CODEID))CODEID,
                MAX (CASE WHEN SB.REFCODEID IS NULL THEN '2' ELSE '8' END) SE_TYPE,
                MAX(DECODE(FLD.FLDCD,'11',FLD.NVALUE,NULL)) MENH_GIA,
                MAX(DECODE(FLD.FLDCD,'27',CVALUE,NULL)) MA_TVLK_NHAN,
                MAX(DECODE(FLD.FLDCD,'28',CVALUE,NULL)) SO_TKLK_NHAN,
                MAX(DECODE(FLD.FLDCD,'29',CVALUE,NULL)) TEN_NGUOI_NHAN
            FROM   VW_TLLOG_ALL TL,SBSECURITIES SB, VW_SETRAN_GEN SE,
                VW_TLLOGFLD_ALL FLD
            WHERE   TL.TLTXCD = '8815'  AND TL.DELTD = 'N'
                AND SE.TXNUM=TL.TXNUM AND SE.TXDATE=TL.TXDATE
                AND FLD.TXNUM=TL.TXNUM AND FLD.TXDATE=TL.TXDATE
                AND SE.TXCD='0044'
                AND SE.NAMT<>0
                AND SUBSTR(MSGACCT, 11, 6)=SB.CODEID
                AND TL.TXDATE >= TO_DATE (F_DATE  ,'DD/MM/RRRR')
                AND TL.TXDATE <= TO_DATE (T_DATE  ,'DD/MM/RRRR')
                AND SE.AFACCTNO LIKE V_STRAFACCTNO
                AND SE.CUSTODYCD LIKE V_CUSTODYCD
            GROUP BY TL.AUTOID,TL.TXNUM,TL.TXDATE
        ) DT, DEPOSIT_MEMBER DEP, CFMAST CF
        WHERE SB.CODEID= DT.CODEID --AND DT.CUSTODYCD LIKE V_CUSTODYCD
          AND DT.NAMT >0
          AND CF.CUSTODYCD(+)=DT.SO_TKLK_NHAN
          AND DT.MA_TVLK_NHAN = DEP.DEPOSITID(+)
    ) DT
    WHERE AC.CLOSETYPE='001'
        AND AC.CUSTODYCD=DT.CUSTODYCD(+)
        AND AC.AUTOID2247 < NVL(DT.AUTOID, AC.AUTOID2247+2)
        AND AC.CUSTODYCD LIKE V_CUSTODYCD
    ;



EXCEPTION
  WHEN OTHERS
   THEN
   DBMS_OUTPUT.PUT_LINE('SE0030 ERROR');
   
      RETURN;
END;
/
