SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE se0007 (
   PV_REFCURSOR   IN OUT   PKG_REPORT.REF_CURSOR,
   OPT            IN       VARCHAR2,
   BRID           IN       VARCHAR2,
   I_DATE         IN       VARCHAR2,
   SYMBOL         IN       VARCHAR2
)
IS
--
-- PURPOSE: BRIEFLY EXPLAIN THE FUNCTIONALITY OF THE PROCEDURE
-- DANH SACH NGUOI SO HUU CHUNG KHOAN  LUU KY
-- MODIFICATION HISTORY
-- PERSON      DATE    COMMENTS
-- NAMNT   20-DEC-06  CREATED
-- ---------   ------  -------------------------------------------
   V_STROPTION     VARCHAR2 (5);            -- A: ALL; B: BRANCH; S: SUB-BRANCH
   V_STRBRID       VARCHAR2 (4);                   -- USED WHEN V_NUMOPTION > 0
   V_STRAFACCTNO   VARCHAR2 (20);
   V_STRSYMBOL     VARCHAR2 (20);
     CUR             PKG_REPORT.REF_CURSOR;
   V_DATE            DATE;
   V_FDATE           DATE;
   v_day3            number;
   v_day5            number;
   v_typedate        varchar2(10);
   V_CODEID VARCHAR2(6);
BEGIN

   V_STROPTION := OPT;

  IF V_STROPTION = 'A' then
      V_STRBRID := '%';
  ELSIF V_STROPTION = 'B' then
      V_STRBRID := substr(BRID,1,2) || '__' ;
  else
      V_STRBRID:=BRID;
  END IF;

 -- GET REPORT'S PARAMETERS


    V_STRSYMBOL := replace(SYMBOL,' ','_');

    SELECT CODEID INTO V_CODEID  FROM SBSECURITIES WHERE SYMBOL = V_STRSYMBOL;

 -- END OF GETTING REPORT'S PARAMETERS

  -- GET REPORT'S DATA

OPEN PV_REFCURSOR
     FOR
SELECT I_DATE I_DATE,sb.TRADEPLACE, SB.symbol,SB.parvalue , CF.FULLNAME  FULLNAME,CASE WHEN SUBSTR(CF.CUSTODYCD,4,1) ='F' THEN CF.tradingcode ELSE  CF.IDCODE END IDCODE ,AL.CDCONTENT COUNTRY,cf.address address
,ISS.fullname SYMBOLNAME , substr(NUM.ACCTNO,1,10) ACCTNO,NUM.AMT, cf.email, cf.mobilesms fax1, cf.custodycd, af.acctno
FROM AFMAST AF,CFMAST CF,  SBSECURITIES  SB,ALLCODE AL, ISSUERS ISS,
(
SELECT SE.AFACCTNO || NVL(SB.REFCODEID,SB.CODEID ) ACCTNO  ,
SUM(SE.TRADE + SE.BLOCKED + se.EMKQTTY + se.secured + SE.BLOCKWITHDRAW + SE.WITHDRAW + SE.MORTAGE +NVL(SE.netting,0) + NVL(SE.dtoclose,0)+ NVL(SE.blockdtoclose,0)   - NVL(NUM.AMT,0) + SE.WTRADE
    ) AMT
 FROM  SEMAST SE,SBSECURITIES SB,
(
SELECT NVL(SUM(AMT ),0) AMT, ACCTNO
  FROM
 ( SELECT   SUM ((CASE WHEN APP.TXTYPE = 'D'THEN -TR.NAMT WHEN
          APP.TXTYPE = 'C' THEN TR.NAMT ELSE 0  END )) AMT, TR.ACCTNO ACCTNO
          FROM APPTX APP, SETRAN TR, TLLOG TL
          WHERE TR.TXCD = APP.TXCD
               AND TL.TXNUM =TR.TXNUM
               AND APP.APPTYPE = 'SE'
               AND APP.TXTYPE IN ('C', 'D')
               AND TL.DELTD <>'Y'
               AND  TR.NAMT<>0
               AND TL.BUSDATE > to_date(I_DATE,'DD/MM/YYYY')
               AND APP.FIELD IN   ('TRADE','BLOCKED','EMKQTTY','BLOCKWITHDRAW','WITHDRAW','MORTAGE','SECURED','NETTING','BLOCKDTOCLOSE','DTOCLOSE','WTRADE')
               GROUP BY  TR.ACCTNO
  UNION ALL
         SELECT   SUM ((CASE WHEN APP.TXTYPE = 'D'THEN -TR.NAMT WHEN
         APP.TXTYPE = 'C' THEN TR.NAMT ELSE 0 END )) AMT, TR.ACCTNO ACCTNO
         FROM APPTX APP, SETRANA TR ,TLLOGALL TL
         WHERE TR.TXCD = APP.TXCD
               AND TL.TXNUM =TR.TXNUM
               AND TL.TXDATE =TR.TXDATE
               AND APP.APPTYPE = 'SE'
               AND APP.TXTYPE IN ('C', 'D')
               AND TL.DELTD <>'Y'
               AND  TR.NAMT<>0
               AND TL.BUSDATE > to_date(I_DATE,'DD/MM/YYYY')
               AND APP.FIELD IN    ('TRADE','BLOCKED','EMKQTTY','BLOCKWITHDRAW','WITHDRAW','MORTAGE','SECURED','NETTING','BLOCKDTOCLOSE','DTOCLOSE','WTRADE')
               GROUP BY  TR.ACCTNO
                )
                GROUP BY ACCTNO


)NUM
WHERE SE.ACCTNO= NUM.ACCTNO (+)
AND SE.CODEID =SB.CODEID
AND NVL(SB.REFCODEID,SB.CODEID )=V_CODEID
AND (SE.TRADE + SE.BLOCKED + se.secured + SE.WITHDRAW + SE.MORTAGE +NVL(SE.netting,0) + NVL(SE.dtoclose,0) - NVL(NUM.AMT,0) + NVL(SE.WTRADE,0))<>0
GROUP BY SE.AFACCTNO || NVL(SB.REFCODEID,SB.CODEID )

 ) NUM
WHERE SUBSTR(NUM.ACCTNO,1,10) = AF.ACCTNO
AND AF.CUSTID =CF.CUSTID
AND AF.ACTYPE NOT IN ('0000')
AND SUBSTR(NUM.ACCTNO,11,6)= SB.CODEID
AND AL.CDNAME= 'COUNTRY'
AND AL.CDTYPE= 'CF'
AND AL.CDVAL = CF.COUNTRY
AND  ISS.ISSUERID = SB.ISSUERID
--PhucPP add
AND    substr( CF.CUSTID, 1,4) LIKE V_STRBRID
ORDER BY cf.custodycd, AF.ACCTNO ;

EXCEPTION
   WHEN OTHERS
   THEN
      RETURN;
END;                                                              -- PROCEDURE
/
