SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE se2023(
   PV_REFCURSOR     IN OUT   PKG_REPORT.REF_CURSOR,
   OPT              IN       VARCHAR2,
   BRID             IN       VARCHAR2,
   F_DATE           IN       VARCHAR2,
   T_DATE           IN       VARCHAR2,
  -- AFACCTNO         IN       VARCHAR2,
   SYMBOL           IN       VARCHAR2
  -- TLTXCD           IN       VARCHAR2,
   --TRADEPLACE       IN       VARCHAR2

        )
   IS
--
-- TO MODIFY THIS TEMPLATE, EDIT FILE PROC.TXT IN TEMPLATE
-- DIRECTORY OF SQL NAVIGATOR
--
-- PURPOSE: BRIEFLY EXPLAIN THE FUNCTIONALITY OF THE PROCEDURE
-- DANH SACH KHACH HANG CO GIAO DICH CHUNG KHOAN
-- MODIFICATION HISTORY
-- PERSON: THANH.TRAN
-- DATE  : 24/10/2007
-- COMMENTS
-- ---------   ------  -------------------------------------------

    V_STROPTION         VARCHAR2 (5);            -- A: ALL; B: BRANCH; S: SUB-BRANCH
    V_STRBRID           VARCHAR2 (4);            -- USED WHEN V_NUMOPTION > 0
    V_STRTLTXCD         VARCHAR (100);
    V_STRSYMBOL         VARCHAR (20);
   -- V_STRTRADEPLACE     VARCHAR2 (3);
   -- V_STRAFACCTNO       VARCHAR (20);

   -- DECLARE PROGRAM VARIABLES AS SHOWN ABOVE
BEGIN
    -- GET REPORT'S PARAMETERS
   V_STROPTION := OPT;

   IF (V_STROPTION <> 'A') AND (BRID <> 'ALL')
   THEN
      V_STRBRID := BRID;
   ELSE
      V_STRBRID := '%%';
   END IF;

  -- IF (TRADEPLACE <> 'ALL')
  -- THEN
   --   V_STRTRADEPLACE := TRADEPLACE;
  -- ELSE
      --V_STRTRADEPLACE := '%%';
   --END IF;

  -- IF  (AFACCTNO  <> 'ALL')
  -- THEN
     -- V_STRAFACCTNO := AFACCTNO;
  -- ELSE
      --V_STRAFACCTNO := '%%';
  -- END IF;

   IF  (SYMBOL <> 'ALL')
   THEN
      V_STRSYMBOL := replace(SYMBOL,' ','_');
   ELSE
      V_STRSYMBOL := '%%';
   END IF;

   --V_STRTLTXCD := TLTXCD;
   --IF (TLTXCD <> 'ALL')
  -- THEN
     --   V_STRTLTXCD := TLTXCD;
   --ELSE
       -- V_STRTLTXCD := '2200 2201 2202 2203 2240 2241 2242 2243 2244 2245 2246 2250 2252 8878';
  -- END IF;

   --END OF GET REPORT'S PARAMETERS

   --IF V_STRTLTXCD <> 'ALL' THEN

 OPEN PV_REFCURSOR
    FOR
SELECT    SYM.SYMBOL, iss.fullname issname,TLG.TLTXCD,SYM.PARVALUE,cf.fullname,
CF.CUSTODYCD,sewd.status,SUM(sewd.withdraw) withdraw
FROM 
SBSECURITIES SYM,AFMAST AF,CFMAST CF,ALLCODE A1
, SECURITIES_INFO SEINFO,  SEWITHDRAWDTL SEWD,issuers iss, (select *  from TLLOGALL union all select * from tllog) TLG
    WHERE SYM.CODEID=SEINFO.CODEID
    AND A1.CDTYPE = 'SA' AND A1.CDNAME = 'TRADEPLACE' AND A1.CDVAL = SYM.TRADEPLACE
    AND CF.CUSTID =AF.CUSTID
    AND iss.issuerid = sym.issuerid
    AND TLG.TXNUM = SEWD.TXNUM
    AND SEWD.AFACCTNO = AF.ACCTNO
    AND SUBSTR(TLG.MSGACCT,11,6)  = SYM.CODEID
    AND TLG.TXDATE = SEWD.TXDATE
    AND SEWD.AFACCTNO = AF.ACCTNO
    AND sewd.status ='C'
    AND SUBSTR(TLG.MSGACCT,1,10) =AF.ACCTNO
    AND SUBSTR(TLG.MSGACCT,1,10) =SEWD.AFACCTNO
    AND INSTR('2200', TLG.TLTXCD)>0
    AND TLG.deltd <> 'Y'
    AND TLG.BUSDATE >= TO_DATE (F_DATE  ,'DD/MM/YYYY')
    AND TLG.BUSDATE <= TO_DATE (T_DATE  ,'DD/MM/YYYY')
    and tlg.brid  like V_STRBRID
   AND SYM.SYMBOL LIKE V_STRSYMBOL
GROUP BY  SYM.SYMBOL, iss.fullname,TLG.TLTXCD,SYM.PARVALUE,cf.fullname,CF.CUSTODYCD,sewd.status;




EXCEPTION
    WHEN OTHERS
   THEN
      RETURN;
END; -- PROCEDURE 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
/
