SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE secmast_cv
    (   PV_BUSDATE      IN VARCHAR2, ---NGAY GIAO DICH CO HIEU LUC
        PV_AFACCTNO     IN VARCHAR2, ---SO TIEU KHOAN
        PV_SYMBOL       IN VARCHAR2, ---CHUNG KHOANG
        PV_QTTY         IN NUMBER,   ---SO LUONG
        PV_COSTPRICE    IN NUMBER   ---GIA VON (GIA CUA LAN NHAP/XUAT)
    )
IS
-- Purpose:
--
-- MODIFICATION HISTORY
-- Person      Date        Comments
-- DUNGNH      06/08/2013
-- ---------   ------  -------------------------------------------

    V_TXDATE        DATE;  ---NGAY TAO GIAO DICH
    V_BUSDATE       DATE; ---NGAY GIAO DICH CO HIEU LUC

    V_STRTXNUM      VARCHAR2(20); ---MA CHUNG TU CUA LENH
    V_STRAFACCTNO   VARCHAR2(20); ---SO TIEU KHOAN
    V_STRSYMBOL     VARCHAR2(50); ---CHUNG KHOANG
    V_STRSECTYPE    VARCHAR2(1); ---LOAI GIAO DICH (T:MUA/BAN ; D:LUU KY ; S:CHUYEN KHOAN ; C:QUYEN)
    V_STRPTYPE      VARCHAR2(1); ---GIAO DICH NHAP XUAT (I:NHAP ; O:XUAT)
    V_STRCAMASTID   VARCHAR2(20); ---MA SU KIEN(VOI SECTYPE = C. SECTYPE <> 'C' DE NULL)
    V_STRORDERID    VARCHAR2(20); ---MA LENH(VOI SECTYPE = T. SECTYPE <> 'T' DE NULL)
    V_NQTTY         NUMBER;   ---SO LUONG
    V_NCOSTPRICE    NUMBER;   ---GIA VON (GIA CUA LAN NHAP/XUAT)
    V_MAPAVL        VARCHAR2(1);  ---CO DUOC MAP LUON HAY KHONG.

BEGIN
    V_TXDATE    := TO_DATE(PV_BUSDATE,'DD/MM/RRRR');
    V_BUSDATE   := TO_DATE(PV_BUSDATE,'DD/MM/RRRR');

    V_STRTXNUM      := '9999000099';
    V_STRAFACCTNO   := PV_AFACCTNO;
    V_STRSYMBOL     := PV_SYMBOL;
    V_STRSECTYPE    := 'B';
    V_STRPTYPE      := 'I';
    V_STRCAMASTID   := NULL;
    V_STRORDERID    := NULL;
    V_NQTTY         := PV_QTTY;
    V_NCOSTPRICE    := PV_COSTPRICE;
    V_MAPAVL        := 'Y';

    INSERT INTO secmast (AUTOID,TXNUM,TXDATE,ACCTNO,CODEID,TRTYPE,PTYPE,CAMASTID,ORDERID,QTTY,COSTPRICE,MAPQTTY,STATUS,MAPAVL,BUSDATE,DELTD)
    VALUES (secmast_seq.NEXTVAL,V_STRTXNUM,V_TXDATE,V_STRAFACCTNO,V_STRSYMBOL,V_STRSECTYPE,V_STRPTYPE,V_STRCAMASTID,V_STRORDERID,V_NQTTY,V_NCOSTPRICE,0,'P',V_MAPAVL,V_BUSDATE,'N');
    --pr_error('secmast_CV', '[PV_AFACCTNO:' || PV_AFACCTNO || '],[PV_SYMBOL:' || PV_SYMBOL || ']');
EXCEPTION
   WHEN OTHERS THEN
            pr_error('secmast_CV', '[PV_AFACCTNO:' || PV_AFACCTNO || '],[PV_SYMBOL:' || PV_SYMBOL || ']');
            pr_error('secmast_CV', '[PV_COSTPRICE:' || to_char(PV_COSTPRICE) || '],[PV_QTTY:' || to_char(PV_QTTY) || ']');
            pr_error('secmast_CV', 'error:' || to_char(dbms_utility.format_error_backtrace));
            ---raise;
END;

 
 
 
 
 
 
 
 
 
 
/
