SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE sp_ba_grouptrans
   ( PV_TXDATE IN VARCHAR2)
   IS
    v_count NUMBER;
    v_desc VARCHAR2(500);
BEGIN
    v_count:=0;
    v_desc:='';
    FOR rec IN
    (
        SELECT *
        FROM GWTRANSFERLOG
        WHERE PROCESSED = 'N' AND TRANSTYPE IN ('BA','BF','SA','SF','SR') AND TRUNC(TXDATE)=TO_DATE(PV_TXDATE,'DD/MM/RRRR')
        AND GRPREPID IS NULL
    )
    LOOP
        SELECT COUNT(*) INTO v_count FROM GWTRANSFERLOG
        WHERE SECACCOUNT=rec.SECACCOUNT AND BANKACCOUNT=rec.BANKACCOUNT
        AND DESACCOUNT = rec.DESACCOUNT AND TRANSTYPE=rec.TRANSTYPE
        AND PROCESSED='N' AND TRUNC(TXDATE)=TRUNC(rec.TXDATE) AND GRPREPID=0;

        IF rec.TRANSTYPE IN ('SA','SF') THEN
            SELECT GW.TRANDESC || '(' || TO_CHAR(GETDATE(TO_DATE(PV_TXDATE,'DD/MM/RRRR')),'DD/MM/YYYY') || ') ' || ' TK ' || CF.CUSTODYCD INTO v_desc
         FROM GWTRAN GW,AFMAST AF,CFMAST CF
         WHERE AF.CUSTID=CF.CUSTID AND GW.BANKCODE=AF.BANKNAME
         AND GW.MAPCODE=rec.TRANSTYPE AND AF.ACCTNO=rec.SECACCOUNT;
        ELSE
            SELECT GW.TRANDESC || '(' || PV_TXDATE || ') ' || ' TK ' || CF.CUSTODYCD INTO v_desc
             FROM GWTRAN GW,AFMAST AF,CFMAST CF
             WHERE AF.CUSTID=CF.CUSTID AND GW.BANKCODE=AF.BANKNAME
             AND GW.MAPCODE=rec.TRANSTYPE AND AF.ACCTNO=rec.SECACCOUNT;
        END IF;



        IF v_count>0 THEN
            UPDATE GWTRANSFERLOG SET AMOUNT=AMOUNT+rec.AMOUNT,DESCRIPTIONS=v_desc
            WHERE SECACCOUNT=rec.SECACCOUNT AND BANKACCOUNT=rec.BANKACCOUNT
            AND DESACCOUNT = rec.DESACCOUNT AND TRANSTYPE=rec.TRANSTYPE
            AND PROCESSED='N' AND TXDATE=rec.TXDATE AND GRPREPID=0;
        ELSE
            BEGIN
                INSERT INTO GWTRANSFERLOG
                (AUTOID,TXDATE,SECACCOUNT,BANKACCOUNT,DESACCOUNT,TRANSTYPE,AMOUNT,PROCESSED,BATCHID,TRANSCODE,TRANSTATE,ERRORDESC,DESCRIPTIONS,GRPREPID,BANKACCOUNTNAME,DESACCOUNTNAME)
                VALUES(SEQ_GWTRANSFERLOG.NEXTVAL,TO_DATE(PV_TXDATE,'DD/MM/RRRR'),rec.SECACCOUNT,rec.BANKACCOUNT,rec.DESACCOUNT,rec.TRANSTYPE,rec.AMOUNT,'N',NULL,NULL,NULL,NULL,v_desc,0,rec.BANKACCOUNTNAME,rec.DESACCOUNTNAME);
            END;
        END IF;
        UPDATE GWTRANSFERLOG SET PROCESSED='D' WHERE AUTOID=rec.AUTOID;
    END LOOP;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        RETURN ;
END; -- Procedure
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
/
