SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE sp_exec_create_crbtxreq_tltxcd (p_err_code OUT VARCHAR2, p_tltxcd IN VARCHAR2, p_txdate IN VARCHAR2)
IS
TYPE v_CurTyp  IS REF CURSOR;
v_OBJTYPE      VARCHAR2(50);
v_OBJNAME      VARCHAR2(50);
v_FLDTRFCODE    VARCHAR2(50);
v_FLDAFFECTDATE    VARCHAR2(100);
v_FLDBANK      VARCHAR2(50);
v_FLDACCTNO   VARCHAR2(50);
v_FLDBANKACCT    VARCHAR2(50);
v_FLDREFCODE    VARCHAR2(50);
v_FLDNOTES    VARCHAR2(50);
v_FLDAMTEXP    VARCHAR2(50);
v_AMTEXP      VARCHAR2(50);
v_TXNUM      VARCHAR2(20);
v_TXDATE      DATE;
v_CHARTXDATE   VARCHAR2(20);
v_TRFCODE      VARCHAR2(50);
v_REFCODE    VARCHAR2(50);
v_BANK      VARCHAR2(50);
v_AFFECTDATE    VARCHAR2(100);
v_BANKACCT    VARCHAR2(50);
v_AFACCTNO    VARCHAR2(10);
v_NOTES      VARCHAR2(250);
v_VALUE      VARCHAR2(100);
v_REFAUTOID    NUMBER;
v_COUNT      NUMBER;
v_CURRDATE     varchar2(250);
v_extFLDNAME  VARCHAR2(20);
v_extFLDTYPE  VARCHAR2(20);
v_extAMTEXP    VARCHAR2(200);
v_extCMDSQL   VARCHAR2(250);
c0        v_CurTyp;
c1        v_CurTyp;
c2        v_CurTyp;
c3        v_CurTyp;
BEGIN
  --Kiem tra co khai bao tao bang ke khong
  SELECT COUNT(TRFCODE) INTO v_COUNT FROM CRBTXMAP MST WHERE MST.OBJTYPE ='T' AND MST.OBJNAME = p_tltxcd;
  IF v_COUNT=0 THEN
    RETURN;
  END IF;
  p_err_code:='0';
  SELECT VARVALUE INTO v_CURRDATE FROM SYSVAR WHERE VARNAME='CURRDATE';
  -- Dynamic SQL statement with placeholder:
  OPEN c1 FOR SELECT OBJTYPE, OBJNAME, TRFCODE, AFFECTDATE, FLDBANK, FLDACCTNO, FLDBANKACCT, FLDREFCODE, FLDNOTES, AMTEXP
  FROM CRBTXMAP MST WHERE MST.OBJTYPE ='T' AND MST.OBJNAME = p_tltxcd;
  --Luot qua danh sach bankcode cua bang ke
  LOOP
    FETCH c1 INTO v_OBJTYPE, v_OBJNAME, v_FLDTRFCODE, v_FLDAFFECTDATE, v_FLDBANK, v_FLDACCTNO, v_FLDBANKACCT,
    v_FLDREFCODE, v_FLDNOTES, v_FLDAMTEXP;
    EXIT WHEN c1%NOTFOUND;
    --DUYET CAC GIAO DICH TLLOG CHUA CO YEU CAU BANG KE
    IF p_txdate = v_CURRDATE OR p_txdate IS NULL THEN
      OPEN c2 FOR SELECT TXNUM, TXDATE
        FROM TLLOG LG WHERE LG.TLTXCD= p_tltxcd AND LG.DELTD='N'
        MINUS SELECT OBJKEY TXNUM, TXDATE
        FROM CRBTXREQ WHERE (TRFCODE=v_FLDTRFCODE OR SUBSTR(v_FLDTRFCODE,1,1)='$') AND OBJNAME=p_tltxcd AND OBJTYPE='T';
    ELSE
      OPEN c2 FOR SELECT TXNUM, TXDATE
        FROM TLLOGALL LG WHERE LG.TLTXCD= p_tltxcd AND LG.DELTD='N' AND TXDATE=TO_DATE(p_txdate,'DD/MM/YYYY')
        MINUS SELECT OBJKEY TXNUM, TXDATE
        FROM CRBTXREQ WHERE (TRFCODE=v_FLDTRFCODE OR SUBSTR(v_FLDTRFCODE,1,1)='$') AND OBJNAME=p_tltxcd AND OBJTYPE='T';
    END IF;
    LOOP
      FETCH c2 INTO v_TXNUM, v_TXDATE;
      EXIT WHEN c2%NOTFOUND;
      v_CHARTXDATE:=TO_CHAR(v_TXDATE,'DD/MM/YYYY');

      IF v_FLDREFCODE IS NULL THEN
        v_REFCODE:= v_CHARTXDATE || v_TXNUM;
      ELSE
        v_REFCODE:= FN_EVAL_AMTEXP(v_TXNUM, v_CHARTXDATE, v_FLDREFCODE);
      END IF;

      --TAO YEU CAU LAP BANG KE: GHI VAO BANG CRBTXREQ/CRBTXREQDTL
      v_TRFCODE:=v_FLDTRFCODE;
      IF SUBSTR(v_TRFCODE,1,1)='$' THEN
        --LAY  TRFCODE THEO GIAO DICH
        v_TRFCODE:= FN_EVAL_AMTEXP(v_TXNUM, v_CHARTXDATE, v_TRFCODE);
      END IF;

      IF v_FLDAFFECTDATE='<$TXDATE>' THEN
        v_AFFECTDATE:=v_CURRDATE;
      ELSE
        v_AFFECTDATE:= FN_EVAL_AMTEXP(v_TXNUM, v_CHARTXDATE, v_FLDAFFECTDATE);
      END IF;

      v_AFACCTNO := FN_EVAL_AMTEXP(v_TXNUM, v_CHARTXDATE, v_FLDACCTNO);
      v_NOTES := FN_EVAL_AMTEXP(v_TXNUM, v_CHARTXDATE, v_FLDNOTES);
      v_VALUE := FN_EVAL_AMTEXP(v_TXNUM, v_CHARTXDATE, v_FLDAMTEXP);
      v_BANKACCT := FN_EVAL_AMTEXP(v_TXNUM, v_CHARTXDATE, v_FLDBANKACCT);

      IF SUBSTR(v_FLDBANKACCT,1,1)='#' THEN
        --XAC DINH THONG TIN BO XUNG
        v_BANKACCT:= FN_CRB_GETCFACCTBYTRFCODE(v_TRFCODE, v_BANKACCT);
      END IF;

      v_BANK:= FN_EVAL_AMTEXP(v_TXNUM, v_CHARTXDATE, v_FLDBANK);
      IF SUBSTR(v_FLDBANK,1,1)='#' THEN
        --XAC DINH THONG TIN BO XUNG
        v_BANK:= FN_CRB_GETBANKCODEBYTRFCODE(v_TRFCODE, v_BANK);
      END IF;
      DBMS_OUTPUT.PUT_LINE(v_CHARTXDATE || '.' || v_TXNUM || '. TRFCODE:' || v_TRFCODE || '. BANK:' || v_FLDBANK || '.' || v_BANK);

      --Chi thuc hien neu chi ro ngan hang va tk tai ngan hang
      IF (NOT v_BANK IS NULL) AND (NOT v_BANKACCT IS NULL) THEN
        BEGIN
          v_REFAUTOID:=SEQ_CRBTXREQ.NEXTVAL;
          INSERT INTO CRBTXREQ (REQID, OBJTYPE, OBJNAME, OBJKEY, TRFCODE, REQCODE, TXDATE, AFFECTDATE, AFACCTNO, TXAMT, BANKCODE, BANKACCT, STATUS, REFVAL, NOTES)
          VALUES (v_REFAUTOID, 'T', p_tltxcd, v_TXNUM, v_TRFCODE, v_REFCODE, v_TXDATE, TO_DATE(v_AFFECTDATE,'DD/MM/RRRR'), v_AFACCTNO, v_VALUE, v_BANK, v_BANKACCT, 'P', NULL, v_NOTES);
          --GHI NHAN VAO BANG CRBTXREQDTL
          OPEN c3 FOR SELECT FLDNAME, FLDTYPE, AMTEXP, CMDSQL
                        FROM CRBTXMAPEXT MST WHERE MST.OBJTYPE ='T' AND MST.OBJNAME = p_tltxcd AND TRFCODE=v_FLDTRFCODE;
          LOOP
            FETCH c3 INTO v_extFLDNAME, v_extFLDTYPE, v_extAMTEXP, v_extCMDSQL;
            EXIT WHEN c3%NOTFOUND;
            IF NOT v_extAMTEXP IS NULL THEN
              v_VALUE := FN_EVAL_AMTEXP(v_TXNUM, v_CHARTXDATE, v_extAMTEXP);
            END IF;
            IF NOT v_extCMDSQL IS NULL THEN
              v_extCMDSQL:=REPLACE(v_extCMDSQL,'<$FILTERID>',v_VALUE);
              OPEN c0 FOR v_extCMDSQL;
              FETCH c0 INTO v_VALUE;
              CLOSE c0;
            END IF;
            INSERT INTO CRBTXREQDTL (AUTOID, REQID, FLDNAME, CVAL, NVAL)
            SELECT SEQ_CRBTXREQDTL.NEXTVAL, v_REFAUTOID, v_extFLDNAME,
              DECODE(v_extFLDTYPE, 'N', NULL, TO_CHAR(v_VALUE)),
              DECODE(v_extFLDTYPE, 'N', v_VALUE, 0) FROM DUAL;
          END LOOP;
          CLOSE c3;
        END;
      END IF;
    END LOOP;
    CLOSE c2;
    COMMIT;
  END LOOP;
  CLOSE c1;
EXCEPTION
   WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE(SUBSTR(SQLERRM(0), 1, 200));
          RETURN;
END;
/
