SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE "SP_GETMRKTPRICE_FROM_FINN" (pv_todate in date)
is
  v_srcmrkdata varchar2(50);
  pkgctx   plog.log_ctx;
begin
    plog.setbeginsection(pkgctx, 'sp_getmrktprice_from_finn');

    v_srcmrkdata := 'STX';

    for rec in (
        SELECT DISTINCT 'ST' STOCKTYP, ORGANCODE ORGANCD, 'HSX' EXCHCD, TICKER, TRADINGDATE, HIGHESTPRICE HPRICE, LOWESTPRICE LPRICE, OPENPRICE OPRICE, CLOSEPRICEADJUSTED CPRICE, TOTALMATCHVOLUME VOL
        FROM HOSESTOCK@LINKFIIN
        WHERE TO_DATE(trunc(UpdateDate)) = pv_todate
        UNION ALL
        SELECT DISTINCT 'ST' STOCKTYP, ORGANCODE ORGANCD, 'HNX' EXCHCD, TICKER, TRADINGDATE, HIGHESTPRICE HPRICE, LOWESTPRICE LPRICE, OPENPRICE OPRICE, CLOSEPRICEADJUSTED CPRICE, TOTALMATCHVOLUME VOL
        FROM HNXSTOCK@LINKFIIN
        WHERE TO_DATE(trunc(UpdateDate)) = pv_todate
        UNION ALL
        SELECT DISTINCT 'ST' STOCKTYP, ORGANCODE ORGANCD, 'UPCOM' EXCHCD, TICKER, TRADINGDATE, HIGHESTPRICE HPRICE, LOWESTPRICE LPRICE, OPENPRICE OPRICE, CLOSEPRICEADJUSTED CPRICE, TOTALMATCHVOLUME VOL
        FROM UPCOMSTOCK@LINKFIIN
        WHERE TO_DATE(trunc(UpdateDate)) = pv_todate
        UNION ALL
        SELECT DISTINCT 'IX' STOCKTYP, 'EXCH' ORGANCD, 'HSX' EXCHCD, COMGROUPCODE TICKER, TRADINGDATE, HIGHESTINDEX HPRICE, LOWESTINDEX LPRICE, OPENINDEX OPRICE, CLOSEINDEX CPRICE, TOTALMATCHVOLUME VOL
        FROM HOSEINDEX@LINKFIIN
        WHERE TO_DATE(trunc(UpdateDate)) = pv_todate
        UNION ALL
        SELECT DISTINCT 'IX' STOCKTYP, 'EXCH' ORGANCD, 'HNX' EXCHCD, COMGROUPCODE TICKER, TRADINGDATE, HIGHESTINDEX HPRICE, LOWESTINDEX LPRICE, OPENINDEX OPRICE, CLOSEINDEX CPRICE, TOTALMATCHVOLUME VOL
        FROM HNXINDEX@LINKFIIN
        WHERE TO_DATE(trunc(UpdateDate)) = pv_todate
        UNION ALL
        SELECT DISTINCT 'IX' STOCKTYP, 'EXCH' ORGANCD, 'UPCOM' EXCHCD, COMGROUPCODE TICKER, TRADINGDATE, HIGHESTINDEX HPRICE, LOWESTINDEX LPRICE, OPENINDEX OPRICE, CLOSEINDEX CPRICE, TOTALMATCHVOLUME VOL
        FROM UPCOMINDEX@LINKFIIN
        WHERE TO_DATE(trunc(UpdateDate)) = pv_todate
        UNION ALL
        SELECT DISTINCT 'CW' STOCKTYP, ORGANCODE ORGANCD, 'HSX' EXCHCD, TICKER, TRADINGDATE, HIGHESTPRICE HPRICE, LOWESTPRICE LPRICE, OPENPRICE OPRICE, CLOSEPRICE CPRICE, TOTALMATCHVOLUME VOL
        FROM GETCWSTOCKPRICE@LINKFIIN
        WHERE TO_DATE(trunc(UpdateDate)) = pv_todate
        UNION ALL
        SELECT DISTINCT 'DR' STOCKTYP, 'EXCH' ORGANCD, 'HNX' EXCHCD,TO_CHAR(DERIVATIVECODE) TICKER, TRADINGDATE, HIGHESTPRICE HPRICE, LOWESTPRICE LPRICE, OPENPRICE OPRICE, CLOSEPRICE CPRICE, TOTALMATCHVOLUME VOL
        FROM DERIVATIVEPRICE@LINKFIIN
        WHERE TO_DATE(trunc(UpdateDate)) = pv_todate
        UNION ALL
        SELECT DISTINCT 'DB' STOCKTYP, B.ORGANCODE ORGANCD, B.COMGROUPCODE EXCHCD, B.BONDCODE TICKER, B.TRADINGDATE, B.HIGHESTPRICE HPRICE, B.LOWESTPRICE LPRICE, B.OPENPRICE OPRICE, B.CLOSEPRICE CPRICE, B.TOTALMATCHVOLUME VOL
        FROM VW_BONDFIIN@LINKFIIN B
        WHERE TO_DATE(trunc(TRADINGDATE)) = pv_todate
    )loop
        DELETE FROM SBREFMRKDATA WHERE SRCMRKDATA = v_srcmrkdata AND TRADINGDT= TO_DATE(trunc(rec.TRADINGDATE)) AND FUNDCODEID = rec.STOCKTYP AND SYMBOL = rec.TICKER;
        DELETE FROM SBREFMRKDATA WHERE SRCMRKDATA = v_srcmrkdata AND TRADINGDT= TO_DATE(trunc(rec.TRADINGDATE)) AND FUNDCODEID IS NULL;

        INSERT INTO SBREFMRKDATA (AUTOID, SYMBOL, SRCMRKDATA, TRADINGDT, PHIGHEST, PLOWEST, PCLOSED, POPEN, VOLUME, tranvalue, FUNDCODEID)
        SELECT SEQ_SBREFMRKDATA.NEXTVAL, rec.TICKER, v_srcmrkdata, TO_DATE(trunc(rec.TRADINGDATE)), rec.HPRICE, rec.LPRICE, rec.CPRICE, rec.OPRICE, rec.VOL, (rec.CPRICE*rec.VOL), rec.STOCKTYP
        FROM DUAL;

    end loop;

    commit;
    plog.setendsection(pkgctx, 'sp_getmrktprice_from_finn');
exception
when others then
plog.error (pkgctx, SQLERRM || dbms_utility.format_error_backtrace);
return;
end;
/
