SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE SP_JOB_UPDATE_GETMRKTPRICE
IS
  PKGCTX   PLOG.LOG_CTX;
BEGIN
    PLOG.SETBEGINSECTION(PKGCTX, 'SP_JOB_UPDATE_GETMRKTPRICE');

    FOR REC IN (
        SELECT * FROM LOG_DATAJOB_GETMRKTPRICE WHERE STATUS = 'P' AND ROWNUM <= 5 ORDER BY CREATEDDATE
    )LOOP
        SP_GETMRKTPRICE_FROM_FINN2(REC.SYMBOL);
        UPDATE LOG_DATAJOB_GETMRKTPRICE SET STATUS = 'C' WHERE AUTOID = REC.AUTOID;
    END LOOP;

    COMMIT;
    PLOG.SETENDSECTION(PKGCTX, 'SP_JOB_UPDATE_GETMRKTPRICE');
EXCEPTION
WHEN OTHERS THEN
PLOG.ERROR (PKGCTX, SQLERRM || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
RETURN;
END;
/
