SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE update_cfsign(V_CUSTID varchar2, V_SIGNATURE varchar2, V_VALDATE varchar2, V_EXPDATE varchar2,V_AUTOID NUMBER,V_DESC varchar2) IS
    LONGLITERAL VARCHAR2(32767);

    BEGIN
       LONGLITERAL:=V_SIGNATURE;
       UPDATE CFSIGN
       SET SIGNATURE=LONGLITERAL, VALDATE = TO_DATE(V_VALDATE,'DD/MM/YYYY'),
           EXPDATE = TO_DATE(V_EXPDATE,'DD/MM/YYYY'),DESCRIPTION = V_DESC
       WHERE AUTOID=V_AUTOID;

    END ;

 
 
 
 
 
/
