SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE UPDATE_CFSIGNMEMO(V_CUSTID varchar2, V_SIGNATURE varchar2, V_VALDATE varchar2, V_EXPDATE varchar2,V_AUTOID NUMBER,V_DESC varchar2) IS
LONGLITERAL VARCHAR2(32767);

    BEGIN
    LONGLITERAL:=V_SIGNATURE;
        DELETE FROM CFSIGNMEMO WHERE AUTOID = V_AUTOID;
        INSERT INTO CFSIGNMEMO SELECT * FROM CFSIGN WHERE AUTOID = V_AUTOID;
        update CFSIGNMEMO set SIGNATURE = LONGLITERAL, EXPDATE = TO_DATE(V_EXPDATE,'DD/MM/RRRR'), DESCRIPTION = V_DESC WHERE AUTOID = V_AUTOID;

    END ;
 
 
 
 
 
/
