SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW SYN_CASCHD_LIST
(AUTOID, CAMASTID, BALANCE, QTTY, AMT, 
 AQTTY, AAMT, STATUS, AFACCTNO, CODEID, 
 EXCODEID, DELTD, PSTATUS, REFCAMASTID, RETAILSHARE, 
 DEPOSIT, REQTTY, REAQTTY, RETAILBAL, PBALANCE, 
 PQTTY, PAAMT, COREBANK, ISCISE, DFQTTY, 
 ISCI, ISSE, ISRO, TQTTY, TRADE, 
 INBALANCE, OUTBALANCE, PITRATEMETHOD, ISEXEC, NMQTTY, 
 DFAMT, INTAMT, RQTTY, RORETAILBAL, SENDPBALANCE, 
 SENDQTTY, SENDAQTTY, SENDAMT, ISRECEIVE, INQTTY, 
 CUTPBALANCE, CUTQTTY, CUTAQTTY, CUTAMT, PAFACCTNO, 
 ORGPBALANCE, TRFFEE, VSDSTATUS, QTTYCANCEL, SWIFTCLIENT, 
 TXDATE, LASTCHANGE, ACTIONTYPE)
AS 
select "AUTOID","CAMASTID","BALANCE","QTTY","AMT","AQTTY","AAMT","STATUS","AFACCTNO","CODEID","EXCODEID","DELTD","PSTATUS","REFCAMASTID","RETAILSHARE","DEPOSIT","REQTTY","REAQTTY","RETAILBAL","PBALANCE","PQTTY","PAAMT","COREBANK","ISCISE","DFQTTY","ISCI","ISSE","ISRO","TQTTY","TRADE","INBALANCE","OUTBALANCE","PITRATEMETHOD","ISEXEC","NMQTTY","DFAMT","INTAMT","RQTTY","RORETAILBAL","SENDPBALANCE","SENDQTTY","SENDAQTTY","SENDAMT","ISRECEIVE","INQTTY","CUTPBALANCE","CUTQTTY","CUTAQTTY","CUTAMT","PAFACCTNO","ORGPBALANCE","TRFFEE","VSDSTATUS","QTTYCANCEL","SWIFTCLIENT","TXDATE","LASTCHANGE","ACTIONTYPE"
    from CASCHD_LIST
/
