SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW V_AFMAST_ALL
(SHORTNAME, ACTYPE, ACNAME, CUSTID, FULLNAME, 
 CUSTNAME, CUSTODYCD, ISCOREBANK, COREBANKTEXT, ACCTNO, 
 AFTYPE, TYPENAME, TRADEFLOOR, TRADETELEPHONE, TRADEONLINE, 
 PIN, IDCODE, LICENSE, IDDATE, IDPLACE, 
 OLDTLID, CAREBY, BANKACCTNO, SWIFTCODE, EMAIL, 
 ADDRESS, FAX, ISOTC, VIA, LASTDATE, 
 STATUS, ADVANCELINE, BRATIO, TERMOFUSE, DESCRIPTION, 
 CAREBYNAME, CAREBYID, REFNAME, COREBANK, BANKNAME, 
 MRIRATE, MRMRATE, MRLRATE, MRCRLIMIT, MRCRLIMITMAX, 
 COUNTRY, EDITALLOW, APRALLOW, MRIRATIO, MRMRATIO, 
 MRLRATIO, PHONE1)
AS 
SELECT CF.SHORTNAME, AF.ACTYPE, AFT.TYPENAME ACNAME, AF.CUSTID CUSTID, CF.FULLNAME FULLNAME, CF.FULLNAME CUSTNAME,
CF.CUSTODYCD CUSTODYCD,
'' ISCOREBANK,
'' COREBANKTEXT,
AF.ACCTNO ACCTNO, AF.AFTYPE,'' TYPENAME, A1.CDCONTENT TRADEFLOOR,
A2.CDCONTENT TRADETELEPHONE,A3.CDCONTENT TRADEONLINE,CF.PIN,CF.IDCODE, CF.IDCODE LICENSE,
CF.IDDATE, CF.IDPLACE,  AF.TLID OLDTLID,  AF.CAREBY ,
AF.BANKACCTNO,AF.SWIFTCODE,CF.EMAIL,CF.ADDRESS,CF.FAX, A11.CDCONTENT ISOTC, A12.CDCONTENT VIA,
AF.LASTDATE, A8.CDCONTENT STATUS,
AF.ADVANCELINE,AF.BRATIO,A9.CDCONTENT TERMOFUSE,AF.DESCRIPTION, GRP.GRPNAME CAREBYNAME,
GRP.grpid CAREBYID, CF.REFNAME, AF.corebank,AF.bankname,
AF.MRIRATE,AF.MRMRATE,AF.MRLRATE,AF.MRCRLIMIT,AF.MRCRLIMITMAX,
 A13.CDCONTENT COUNTRY, (CASE WHEN AF.STATUS IN ('B','C','N') THEN 'N' ELSE 'Y' END) EDITALLOW,
(CASE WHEN AF.STATUS IN ('P') THEN 'Y' ELSE 'N' END) APRALLOW,
AF.mriratio, AF.mrmratio, AF.mrlratio, CF.mobilesms PHONE1
FROM AFMAST AF,CFMAST CF,AFTYPE AFT, TLGROUPS GRP, 
ALLCODE A1, ALLCODE A2,ALLCODE A3,
ALLCODE A8,ALLCODE A9 ,ALLCODE A11,ALLCODE A12, ALLCODE A13
WHERE AF.CUSTID = CF.CUSTID AND AF.ACTYPE = AFT.ACTYPE 
AND AF.CAREBY = GRP.GRPID AND GRP.GRPTYPE = '2'
AND AFT.ACTYPE = AF.ACTYPE
AND A1.CDTYPE = 'SY' AND A1.CDNAME = 'YESNO' AND A1.CDVAL= CF.TRADEFLOOR
AND A2.CDTYPE = 'SY' AND A2.CDNAME = 'YESNO' AND A2.CDVAL= CF.TRADETELEPHONE
AND A3.CDTYPE = 'SY' AND A3.CDNAME = 'YESNO' AND A3.CDVAL= CF.TRADEONLINE
AND A8.CDTYPE = 'CF' AND A8.CDNAME = 'STATUS' AND A8.CDVAL = AF.STATUS
AND A9.CDTYPE = 'CF' AND A9.CDNAME = 'TERMOFUSE' AND A9.CDVAL = AF.TERMOFUSE

AND A11.CDTYPE = 'SY' AND A11.CDNAME = 'YESNO' AND A11.CDVAL= AF.ISOTC
AND A12.CDTYPE = 'CF' AND A12.CDNAME = 'VIA' AND A12.CDVAL= AF.VIA
AND A13.CDTYPE = 'CF' AND A13.CDNAME = 'COUNTRY' AND A13.CDVAL= CF.COUNTRY
/
