SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW V_AFMASTCV
(CUSTODYCD, OPNDATE, ACTYPE, STATUS, COREBANK, 
 BANKNAME, BANKACCTNO, ADVANCELINE, ISONLINE, BRID)
AS 
SELECT cf.custodycd, to_char(af.opndate,'DD-MM-YYYY') opndate,af.actype , af.status,AF.COREBANK,DECODE(COREBANK,'Y',AF.BANKNAME,'BOSC') BANKNAME,DECODE(COREBANK,'Y', AF.BANKACCTNO,' ') BANKACCTNO,nvl(af.advanceline,0)advanceline,
nvl(CF.TRADEONLINE,' ') ISONLINE,cf.brid
FROM AFMAST af, CFMAST cf
WHERE cf.CUSTID = af.CUSTID
order by cf.custodycd
/
