SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW V_CA3354_DEL_N
(AUTOID, BALANCE, CAMASTID, AFACCTNO, CATYPE, 
 CODEID, EXCODEID, QTTY, AMT, AQTTY, 
 AAMT, SYMBOL, STATUS, SEACCTNO, EXSEACCTNO, 
 PARVALUE, EXPARVALUE, REPORTDATE, ACTIONDATE, POSTINGDATE, 
 DESCRIPTION, TASKCD, DUTYAMT, FULLNAME, IDCODE, 
 CUSTODYCD, ISCOREBANK, ISCOREBANKTEXT, INTAMT, ISDEBITSE, 
 TRADE, NOTINTAMT, ISINCODE, DELTD)
AS 
(
SELECT CA.AUTOID, CA.BALANCE, SUBSTR(CA.CAMASTID,1,4) || '.' || SUBSTR(CA.CAMASTID,5,6) || '.' || SUBSTR(CA.CAMASTID,11,6) CAMASTID, CA.AFACCTNO,
       A0.CDCONTENT CATYPE, CA.CODEID, CA.EXCODEID, CA.QTTY,
       /*
       ROUND(CASE WHEN CAMAST.CATYPE = '010'
    THEN (case when ca.status = 'K' then round(((100-camast.exerate)/100)*CA.AMT)
    else round((camast.exerate/100)*CA.AMT) end) ELSE CA.AMT END ) AMT
       */
       ROUND(CASE WHEN CAMAST.CATYPE = '010' THEN NVL(CAD.EXECRATE, CAMAST.EXERATE) /100*CA.AMT ELSE CA.AMT END) AMT,
       ROUND(CA.AQTTY) AQTTY, ROUND(CA.AAMT) AAMT, SYM.SYMBOL, A1.CDCONTENT STATUS, CA.AFACCTNO || CA.CODEID  SEACCTNO,
       CA.AFACCTNO || (CASE WHEN CAMAST.EXCODEID IS NULL THEN CAMAST.CODEID ELSE CAMAST.EXCODEID END) EXSEACCTNO,
       SYM.PARVALUE PARVALUE, EXSYM.PARVALUE EXPARVALUE, CAMAST.REPORTDATE REPORTDATE, CAMAST.ACTIONDATE ,CAMAST.ACTIONDATE  POSTINGDATE,
       CAMAST.DESCRIPTION || (CASE WHEN CAMAST.CATYPE = '010' AND NVL(CAD.EXECRATE,0) < 100
                                        THEN ' ( thanh toan ' || NVL(CAD.EXECRATE,0) || '/100% con lai ' || CAMAST.EXERATE || '%'   
                                    ELSE NULL END) DESCRIPTION,
       CAMAST.TASKCD,
       CASE WHEN CF.VAT='Y' THEN (CASE WHEN CAMAST.CATYPE IN ('016','023','027') THEN ROUND(CAMAST.PITRATE*CA.INTAMT/100)
                                      ELSE (CASE WHEN CAMAST.CATYPE = '010' THEN CAMAST.PITRATE * NVL(CAD.EXECRATE, CAMAST.EXERATE) /100
                                                 ELSE ROUND(CAMAST.PITRATE*CA.AMT/100) END) END) ELSE 0 END DUTYAMT,
       /*
       (CASE WHEN cf.VAT='Y' THEN (CASE WHEN CAMAST.CATYPE IN ('016','023') THEN ROUND(CAMAST.pitrate*CA.INTAMT/100)
        ELSE (case when camast.catype = '010' then
        (case when ca.status = 'K' then round(CAMAST.pitrate*(((100-camast.exerate)/100)*CA.AMT)/100) else round(CAMAST.pitrate*((camast.exerate/100)*CA.AMT)/100) end)
        else ROUND(CAMAST.pitrate*CA.AMT/100) end) END) ELSE 0 END
    ) DUTYAMT,
       */
       CF.FULLNAME, CF.IDCODE, CF.CUSTODYCD,CASE WHEN AF.COREBANK='Y' THEN 0 ELSE 1 END ISCOREBANK,CASE WHEN AF.COREBANK='Y' THEN 'YES' ELSE 'NO' END ISCOREBANKTEXT,
       CA.INTAMT,
       --(CASE WHEN CAMAST.CATYPE IN ('016','023','027') THEN 1 ELSE 0 END) ISDEBITSE,
       (CASE WHEN CAMAST.CATYPE IN ('027') THEN 1 ELSE 0 END) ISDEBITSE,
       (CASE WHEN CAMAST.CATYPE = '023' THEN 0 ELSE NVL(SE.TRADE,0) END) TRADE,
       (CASE WHEN CAMAST.CATYPE IN ('016','023','015','027') THEN 0 ELSE 1 END) NOTINTAMT, -- KHONG TACH RIENG PHAN LAI KHI LEN SAO KE
       CAMAST.ISINCODE, CAMAST.deltd
FROM CASCHD CA, SBSECURITIES SYM, SBSECURITIES EXSYM, ALLCODE A0, ALLCODE A1, CAMAST, AFMAST AF,
     CFMAST CF , AFTYPE TYP, SYSVAR SYS, SEMAST SE,
     (SELECT * FROM CAMASTDTL WHERE DELTD <> 'Y' AND STATUS ='P') CAD
WHERE A0.CDTYPE = 'CA' AND A0.CDNAME = 'CATYPE' AND A0.CDVAL = CAMAST.CATYPE
      AND A1.CDTYPE = 'CA' AND A1.CDNAME = 'CASTATUS' AND A1.CDVAL = CA.STATUS
      AND CA.CAMASTID = CAMAST.CAMASTID AND CAMAST.CODEID = SYM.CODEID
      AND CA.AFACCTNO = AF.ACCTNO AND AF.CUSTID = CF.CUSTID 
      AND CA.DELTD ='N' AND CA.STATUS IN ('K','S','G','H','J','W','I','K') AND CA.ISCI ='N' AND CAMAST.STATUS IN ('K','I','G','H','J')
      AND SE.ACCTNO(+)=CA.AFACCTNO||CA.CODEID
      AND CA.AMT > 0 AND CA.ISEXEC='Y'
      AND CAMAST.CAMASTID = CAD.CAMASTID (+)
      AND (CASE WHEN CA.PITRATEMETHOD='##' THEN CAMAST.PITRATEMETHOD ELSE CA.PITRATEMETHOD END) IN ('IS')
      AND AF.ACTYPE = TYP.ACTYPE AND SYS.GRNAME='SYSTEM' AND SYS.VARNAME='CADUTY'
      AND EXSYM.CODEID = (CASE WHEN CAMAST.EXCODEID IS NULL THEN CAMAST.CODEID ELSE CAMAST.EXCODEID END)
)
/
