SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW V_CA3380
(AUTOID, ACCTNO, REFCASAACCT, BALANCE, CAMASTID, 
 AFACCTNO, CATYPE, CODEID, EXCODEID, QTTY, 
 AMT, AQTTY, NMQTTY, AAMT, SYMBOL, 
 SYMBOLDIS, STATUS, STATUSCD, SEACCTNO, EXSEACCTNO, 
 PARVALUE, EXPARVALUE, REPORTDATE, ACTIONDATE, DESCRIPTION, 
 CUSTODYCD, FULLNAME, IDCODE, ISRIGHTOFF, QTTYDIS, 
 ISINCODE)
AS 
SELECT
      CA.AUTOID,DD.ACCTNO,DD.REFCASAACCT, CA.TRADE BALANCE, SUBSTR(CA.CAMASTID,1,4) || '.' || SUBSTR(CA.CAMASTID,5,6) || '.' || SUBSTR(CA.CAMASTID,11,6) CAMASTID,
      CA.AFACCTNO,A0.CDCONTENT CATYPE, CA.CODEID, CA.EXCODEID,
      CA.QTTY, CA.AMT, CA.AQTTY,CA.NMQTTY,
      CA.AAMT, (CASE WHEN nvl(CAMAST.TOCODEID,'A') = 'A' THEN sym.symbol ELSE symto.symbol END ) SYMBOL,SYM.SYMBOL SYMBOLDIS, A1.CDCONTENT STATUS, CA.STATUS STATUSCD,
      CA.AFACCTNO || (CASE WHEN CAMAST.ISWFT='Y' THEN (CASE WHEN nvl(CAMAST.TOCODEID,'A') = 'A' THEN (SELECT CODEID FROM SBSECURITIES WHERE REFCODEID =SYM.CODEID) ELSE (SELECT CODEID FROM SBSECURITIES WHERE REFCODEID =SYMTO.CODEID) END)
      ELSE (CASE WHEN nvl(CAMAST.TOCODEID,'A') = 'A' THEN CAMAST.CODEID ELSE CAMAST.TOCODEID END ) END)  SEACCTNO,CA.AFACCTNO
      || (CASE WHEN CAMAST.EXCODEID IS NULL THEN CAMAST.CODEID
      ELSE CAMAST.EXCODEID END) EXSEACCTNO,
      SYM.PARVALUE PARVALUE, EXSYM.PARVALUE EXPARVALUE,
      CAMAST.REPORTDATE REPORTDATE, CAMAST.ACTIONDATE  ,
      camast.description,cf.custodycd,cf.fullname,cf.idcode,
      (CASE WHEN CAMAST.CATYPE IN ('014', '040') THEN 0 ELSE 1 END) ISRIGHTOFF,
      (CASE WHEN camast.catype IN ('014', '023') THEN ca.qtty ELSE nvl(CA.TRADE,0) END) QTTYDIS, camast.isincode
FROM CASCHD CA, SBSECURITIES SYM, SBSECURITIES SYMTO, SBSECURITIES EXSYM,
     ALLCODE A0, ALLCODE A1, CAMAST ,AFMAST AF , CFMAST CF, (SELECT * FROM DDMAST WHERE ISDEFAULT='Y' AND STATUS<>'C') DD
WHERE
      A0.CDTYPE = 'CA' AND A0.CDNAME = 'CATYPE' AND A0.CDVAL = CAMAST.CATYPE
      AND A1.CDTYPE = 'CA' AND A1.CDNAME = 'CASTATUS' AND A1.CDVAL = CA.STATUS
      AND CA.AFACCTNO = AF.ACCTNO AND AF.CUSTID =CF.CUSTID
      and DD.CUSTID = CF.CUSTID
      AND CA.CAMASTID = CAMAST.CAMASTID AND camast.codeid=sym.codeid AND SYMTO.CODEID=(CASE WHEN nvl(CAMAST.TOCODEID,'A') <> 'A' THEN CAMAST.TOCODEID ELSE CAMAST.CODEID END)
      AND CA.DELTD ='N'
      AND(
        (ca.status IN('F','V','M') and CAMAST.catype IN ('014','023','040'))
        or
        (ca.status IN('A','M') and CAMAST.catype NOT IN ('014','023','040'))
      )
      and CAMAST.CATYPE not in ('018','019','002','026','019')
      and cf.custatcom = 'Y'
      AND EXSYM.CODEID = (CASE WHEN CAMAST.EXCODEID IS NULL THEN CAMAST.CODEID ELSE CAMAST.EXCODEID END)
      and (
        (CAMAST.catype = '014' and CA.TQTTY = CA.QTTY)
        or
        CAMAST.catype <> '014'
      )
/
