SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW V_CA3351
(AUTOID, BALANCE, CAMASTID, AFACCTNO, CATYPE, 
 CODEID, EXCODEID, QTTY, AMT, AQTTY, 
 DFQTTY, AAMT, SYMBOL, ISWFT, PITRATE, 
 TOCODEID, STATUS, SEACCTNO, EXSEACCTNO, PARVALUE, 
 EXPARVALUE, REPORTDATE, ACTIONDATE, POSTINGDATE, DESCRIPTION, 
 TASKCD, DUTYAMT, FULLNAME, IDCODE, CUSTODYCD, 
 PRICEACCOUNTING, CATYPEVALUE, COSTPRICE, ISCDCROUTAMT, ISSE, 
 ISINCODE)
AS 
(SELECT CA.AUTOID, CA.BALANCE, SUBSTR(CA.CAMASTID,1,4) || '.' || SUBSTR(CA.CAMASTID,5,6) || '.' || SUBSTR(CA.CAMASTID,11,6) CAMASTID, CA.AFACCTNO,A0.CDCONTENT CATYPE, tosym.CODEID, CA.EXCODEID, CA.QTTY, ROUND(CA.AMT) AMT,
       ROUND(CASE WHEN camast.catype IN ('017','020') THEN nvl(SE.trade,0)
                  WHEN camast.catype IN ('023') THEN (CASE WHEN CAMAST.FORMOFPAYMENT <> '001' THEN SE.TRADE ELSE CA.TRADE - CA.BALANCE END)
                  WHEN camast.catype IN ('027') THEN (CASE WHEN CA.PSTATUS LIKE '%X%' THEN nvl(CA.AQTTY,0) ELSE NVL(SE.TRADE,0) END)
                  ELSE 0 END) AQTTY,
       ROUND(CA.DFQTTY) DFQTTY,
       ROUND(CA.AAMT) AAMT, tosym.SYMBOL,ISWFT,PITRATESE PITRATE,CASE WHEN NVL(CAMAST.ISWFT,'N')='Y' THEN (SELECT CODEID FROM SBSECURITIES WHERE REFCODEID=nvl(CAMAST.TOCODEID,CAMAST.CODEID))  ELSE TOCODEID END TOCODEID , A1.CDCONTENT STATUS,
CA.AFACCTNO ||(CASE WHEN CAMAST.ISWFT='Y' THEN (CASE WHEN nvl(CAMAST.TOCODEID,'A') = 'A' THEN (SELECT CODEID FROM SBSECURITIES WHERE REFCODEID =SYM.CODEID) ELSE  (SELECT CODEID FROM SBSECURITIES WHERE REFCODEID =SYMTO.CODEID) END  )
 ELSE (CASE WHEN nvl(CAMAST.TOCODEID,'A') = 'A' THEN CAMAST.CODEID ELSE CAMAST.TOCODEID END ) END)  SEACCTNO,CA.AFACCTNO || (CASE WHEN CAMAST.EXCODEID IS NULL THEN CAMAST.CODEID ELSE CAMAST.EXCODEID END) EXSEACCTNO,
       SYM.PARVALUE PARVALUE, EXSYM.PARVALUE EXPARVALUE, CAMAST.REPORTDATE REPORTDATE, CAMAST.ACTIONDATE ,CAMAST.ACTIONDATE  POSTINGDATE,
   camast.description, camast.taskcd,
      (CASE WHEN cf.VAT='Y' THEN SYS.VARVALUE*CA.AMT/100 ELSE 0 END) DUTYAMT, CF.FULLNAME, CF.IDCODE, CF.CUSTODYCD
      ,decode(priceaccounting,0,exsym.parvalue,priceaccounting) priceaccounting, a0.cdval CATYPEVALUE,
      (CASE WHEN camast.catype='014' THEN camast.exprice
          WHEN camast.catype IN ('017','020','023','027') THEN (SELECT ROUND( costprice * round(CA.Aqtty)/ GREATEST(CA.Qtty,1),4)   FROM semast WHERE acctno= (CA.AFACCTNO || (CASE WHEN CAMAST.EXCODEID IS NULL THEN CAMAST.CODEID ELSE CAMAST.EXCODEID END)))
            ELSE 0 END)  costprice, (CASE WHEN  camast.catype IN ('017','020','023','027') THEN 1 ELSE 0 END ) ISCDCROUTAMT,
    ca.ISSE, camast.isincode
FROM CASCHD CA, SBSECURITIES SYM, SBSECURITIES SYMTO, SBSECURITIES EXSYM, ALLCODE A0, ALLCODE A1, CAMAST, AFMAST AF , CFMAST CF , AFTYPE TYP, SYSVAR SYS,
SEMAST SE, sbsecurities tosym
WHERE A0.CDTYPE = 'CA' AND A0.CDNAME = 'CATYPE' AND A0.CDVAL = CAMAST.CATYPE
AND A1.CDTYPE = 'CA' AND A1.CDNAME = 'CASTATUS' AND A1.CDVAL = CA.STATUS
AND CA.CAMASTID = CAMAST.CAMASTID AND camast.codeid=sym.codeid AND SYMTO.CODEID=(CASE WHEN nvl(CAMAST.TOCODEID,'A') <> 'A' THEN CAMAST.TOCODEID ELSE CAMAST.CODEID END)
AND CA.AFACCTNO = AF.ACCTNO AND AF.CUSTID = CF.CUSTID
AND CA.DELTD ='N'
--AND ISSE ='N'
AND CA.STATUS IN ('G','K','J','I','S','H') AND CAMAST.STATUS IN ('I','G','K','H')
AND (CA.qtty > 0 OR CA.Aqtty>0)
AND AF.ACTYPE = TYP.ACTYPE AND SYS.GRNAME='SYSTEM' AND SYS.VARNAME='CADUTY'
AND EXSYM.CODEID = (CASE WHEN CAMAST.EXCODEID IS NULL THEN CAMAST.CODEID ELSE CAMAST.EXCODEID END)
AND ca.afacctno||ca.codeid=se.acctno(+)
AND NVL(camast.tocodeid,camast.codeid)=tosym.codeid)
/
