SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW V_CTCIVIEW
(CUSTID, FULLNAME, TRADEPLACE, BORS, SEC_CODE, 
 QUANTITY, PRICE, AMOUNT, CUSTODYCD, MATCHTIME, 
 ORDERID)
AS 
(
SELECT CF.CUSTID,CF.FULLNAME,(CASE WHEN FLOOR_CODE='02'  THEN 'HOSTC'  WHEN FLOOR_CODE='10'  THEN 'HASTC' ELSE 'OTC' END) TRADEPLACE ,
'B' BORS,SEC_CODE,QUANTITY,PRICE,QUANTITY*PRICE AMOUNT,B_ACCOUNT_NO CUSTODYCD ,SUBSTR(REPLACE(MATCH_TIME,':','') || '000000',1,6) MATCHTIME,B_ORDER_NO ORDERID
FROM curr_trading_result RS ,CFMAST CF
WHERE  RS.B_ACCOUNT_NO=CF.CUSTODYCD
UNION ALL
SELECT CF.CUSTID,CF.FULLNAME,(CASE WHEN FLOOR_CODE='02'  THEN 'HOSTC'  WHEN FLOOR_CODE='10'  THEN 'HASTC' ELSE 'OTC' END) TRADEPLACE ,
'S' BORS,SEC_CODE,QUANTITY,PRICE,QUANTITY*PRICE AMOUNT,S_ACCOUNT_NO CUSTODYCD ,SUBSTR(REPLACE(MATCH_TIME,':','') || '000000',1,6) MATCHTIME ,S_ORDER_NO ORDERID
 FROM curr_trading_result RS ,CFMAST CF
WHERE  RS.S_ACCOUNT_NO=CF.CUSTODYCD)
/
