SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW V_GETBUYORDERINFO_BY_SYMBOL
(SEACCTNO, SERECEIVING)
AS 
SELECT SEACCTNO, SUM(RECEIVING) SERECEIVING
 FROM (
    SELECT OD.SEACCTNO, EXECQTTY  RECEIVING
       FROM ODMAST OD, SYSVAR SY
       WHERE OD.EXECTYPE IN ('NB', 'BC') and od.deltd <>'Y'
           and sy.grname='SYSTEM' and sy.varname='HOSTATUS'
           and od.orstatus <> '7'
    )
GROUP BY SEACCTNO
/
