SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW V_RM_GETTRFQUEUEDTL
(AUTOID, VERSION, TXDATE, AFFECTDATE, OBJNAME, 
 OBJKEY, BANKCODE, TRFCODE, CUSTODYCD, AFACCTNO, 
 BANKACCTNO, BANKACCTNAME, DESACCTNO, DESACCTNAME, AMT, 
 DESCRIPTIONS, REFHOLDID)
AS 
SELECT CRD.AUTOID,CRD.VERSION,CRD.TXDATE,REQ.AFFECTDATE,REQ.OBJNAME,REQ.OBJKEY, REQ.BANKCODE,CRD.TRFCODE,
CF.CUSTODYCD,CRD.AFACCTNO,AF.BANKACCTNO,CF.FULLNAME BANKACCTNAME,NVL(fn_getdesbankacc(req.reqid,req.bankcode, req.trfcode)  ,'N/A') DESACCTNO,
NVL(fn_getdesbankname(req.reqid,req.bankcode, req.trfcode),'N/A') DESACCTNAME,CRD.AMT,CRD.REFNOTES DESCRIPTIONS,CRD.REFHOLDID
FROM CRBTRFLOGDTL CRD,CRBTXREQ REQ,AFMAST AF,CFMAST CF
WHERE CRD.AFACCTNO=AF.ACCTNO AND AF.CUSTID=CF.CUSTID
AND CRD.REFREQID = REQ.REQID AND CRD.STATUS='P'
ORDER BY CRD.AUTOID
/
