SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW V_RM_CRBTRFLOGDTL
(AUTOID, VERSION, OBJNAME, TXDATE, AFFECTDATE, 
 OBJKEY, REQCODE, SYMBOL, AFACCTNO, CUSTODYCD, 
 FULLNAME, BANKACCTNO, DESACCTNO, DESACCTNAME, TXAMT, 
 NOTES, DESC_STATUS, ERRDESC, DTLAUTOID, FILEID, 
 STATUS, UNHOLD)
AS 
SELECT LG.AUTOID,LG.VERSION, REQ.OBJNAME, REQ.TXDATE,REQ.AFFECTDATE, REQ.OBJKEY, REQ.REQCODE,
       CASE WHEN NVL(SEC.SYMBOL,'N/A')='N/A' THEN
       CASE WHEN CSPKS_RMPROC.IS_NUMBER(SUBSTR(REQ.REQCODE,0,1))=1 THEN '' ELSE REQ.REQCODE END
            ELSE SEC.SYMBOL END SYMBOL,
       REQ.AFACCTNO,CF.CUSTODYCD,CF.FULLNAME,REQ.BANKACCT BANKACCTNO,FN_GETDESBANKACC(REQ.REQID,REQ.BANKCODE, REQ.TRFCODE) DESACCTNO,
       FN_GETDESBANKNAME(REQ.REQID,REQ.BANKCODE, REQ.TRFCODE) DESACCTNAME, LGD.AMT TXAMT,
       LGD.REFNOTES NOTES, A0.CDCONTENT DESC_STATUS, LGD.ERRMSG ERRDESC, LGD.AUTOID DTLAUTOID, LGD.FILEID FILEID, LGD.STATUS, NVL(LGD.UNHOLD, REQ.unhold) UNHOLD
FROM CRBTRFLOG LG, CRBTRFLOGDTL LGD, CRBTXREQ REQ,ALLCODE A0,SECURITIES_INFO SEC,AFMAST AF,CFMAST CF
WHERE LG.VERSION=LGD.VERSION AND LG.TRFCODE=LGD.TRFCODE AND LGD.REFREQID=REQ.REQID AND LG.UNHOLD=LGD.UNHOLD
      AND LG.AFFECTDATE=REQ.AFFECTDATE AND LG.TXDATE=LGD.TXDATE
      AND A0.CDTYPE='RM' AND A0.CDNAME='TRFLOGDTLSTS' AND A0.CDVAL=LGD.STATUS
      AND REQ.AFACCTNO=AF.ACCTNO AND AF.CUSTID=CF.CUSTID AND REQ.REQCODE = SEC.CODEID(+)
/
