SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW V_SBREFMRKDATA_FIIN
(STOCKTYP, ORGANCD, EXCHCD, TICKER, TRADINGDT, 
 HPRICE, LPRICE, OPRICE, CPRICE, VOL)
AS 
SELECT STOCKTYP,ORGANCD,EXCHCD,TICKER,TO_DATE(TO_CHAR(TRADINGDATE,'DD/MM/RRRR'),'DD/MM/RRRR') TRADINGDT,HPRICE,LPRICE,OPRICE,CPRICE,VOL

FROM
(
    SELECT DISTINCT 'ST' STOCKTYP, ORGANCODE ORGANCD, 'HSX' EXCHCD,TICKER,TRADINGDATE,HIGHESTPRICE HPRICE, LOWESTPRICE LPRICE,OPENPRICE OPRICE,CLOSEPRICEADJUSTED CPRICE,TOTALMATCHVOLUME VOL
        FROM HOSESTOCK@LINKFIIN
    UNION ALL
    SELECT DISTINCT 'ST' STOCKTYP, ORGANCODE ORGANCD, 'HNX' EXCHCD,TICKER,TRADINGDATE,HIGHESTPRICE HPRICE, LOWESTPRICE LPRICE,OPENPRICE OPRICE,CLOSEPRICEADJUSTED CPRICE,TOTALMATCHVOLUME VOL
        FROM HNXSTOCK@LINKFIIN
    UNION ALL
    SELECT DISTINCT 'ST' STOCKTYP, ORGANCODE ORGANCD, 'UPCOM' EXCHCD,TICKER,TRADINGDATE,HIGHESTPRICE HPRICE, LOWESTPRICE LPRICE,OPENPRICE OPRICE,AVERAGEPRICE CPRICE,TOTALMATCHVOLUME VOL
        FROM UPCOMSTOCK@LINKFIIN
    UNION ALL
    SELECT DISTINCT 'IX' STOCKTYP, 'EXCH' ORGANCD, 'HSX' EXCHCD,COMGROUPCODE TICKER,TRADINGDATE,HIGHESTINDEX HPRICE, LOWESTINDEX LPRICE,OPENINDEX OPRICE,CLOSEINDEX CPRICE,TOTALMATCHVOLUME VOL
        FROM HOSEINDEX@LINKFIIN
    UNION ALL
    SELECT DISTINCT 'IX' STOCKTYP, 'EXCH' ORGANCD, 'HNX' EXCHCD,COMGROUPCODE TICKER,TRADINGDATE,HIGHESTINDEX HPRICE, LOWESTINDEX LPRICE,OPENINDEX OPRICE,CLOSEINDEX CPRICE,TOTALMATCHVOLUME VOL
        FROM HNXINDEX@LINKFIIN
        UNION ALL
    SELECT DISTINCT 'IX' STOCKTYP, 'EXCH' ORGANCD, 'UPCOM' EXCHCD,COMGROUPCODE TICKER,TRADINGDATE,HIGHESTINDEX HPRICE, LOWESTINDEX LPRICE,OPENINDEX OPRICE,CLOSEINDEX CPRICE,TOTALMATCHVOLUME VOL
        FROM UPCOMINDEX@LINKFIIN
    UNION ALL
    SELECT DISTINCT 'CW' STOCKTYP, ORGANCODE ORGANCD, 'HSX' EXCHCD,TICKER,TRADINGDATE,HIGHESTPRICE HPRICE, LOWESTPRICE LPRICE,OPENPRICE OPRICE,CLOSEPRICE CPRICE,TOTALMATCHVOLUME VOL
        FROM GETCWSTOCKPRICE@LINKFIIN
    UNION ALL
    SELECT DISTINCT 'DR' STOCKTYP, 'EXCH' ORGANCD, 'HNX' EXCHCD,TO_CHAR(DERIVATIVECODE) TICKER,TRADINGDATE,HIGHESTPRICE HPRICE, LOWESTPRICE LPRICE,OPENPRICE OPRICE,CLOSEPRICE CPRICE,TOTALMATCHVOLUME VOL
        FROM DERIVATIVEPRICE@LINKFIIN
    UNION ALL
    SELECT DISTINCT 'DB' STOCKTYP, B.ORGANCODE ORGANCD, B.COMGROUPCODE EXCHCD,B.BONDCODE TICKER,B.TRADINGDATE,B.HIGHESTPRICE HPRICE, B.LOWESTPRICE LPRICE,B.OPENPRICE OPRICE,B.CLOSEPRICE CPRICE,
    B.TOTALMATCHVOLUME VOL
        FROM VW_BONDFIIN@LINKFIIN B
)
/
