SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW V_SE2205
(SYMBOL, CUSTODYCD, FULLNAME, IDCODE, ADDRESS, 
 TOTAL_QTTY, TRADE_QTTY, WTRADE, DEALFINANCING_QTTY, ORDERQTTY_NORMAL, 
 ORDERQTTY_BLOCKED, ORDERQTTY_BUY, MORTGAGE_QTTY, NETTING_QTTY, BLOCKED_QTTY, 
 SECURITIES_RECEIVING_T1, SECURITIES_RECEIVING_T2, SECURITIES_RECEIVING_TN, SECURITIES_SENDING_T1, SECURITIES_SENDING_T2, 
 SECURITIES_SENDING_TN, CA_RECEIVING, WITHDRAW_QTTY, DEPOSIT_QTTY, HOLD_QTTY, 
 CKCC_RECEIVING, CKCC_NETTING, EMKQTTY, TEMP, TRADE1404)
AS 
SELECT   max(SYMBOL) SYMBOL,max(CUSTODYCD) CUSTODYCD,max(FULLNAME) FULLNAME,
max(IDCODE) IDCODE ,max(ADDRESS)ADDRESS,
sum(TOTAL_QTTY) TOTAL_QTTY,sum(TRADE_QTTY) TRADE_QTTY ,   sum(WTRADE)WTRADE ,sum(DEALFINANCING_QTTY) DEALFINANCING_QTTY,
sum(ORDERQTTY_NORMAL) ORDERQTTY_NORMAL,   sum(ORDERQTTY_BLOCKED) ORDERQTTY_BLOCKED,sum(ORDERQTTY_BUY) ORDERQTTY_BUY,
sum(MORTGAGE_QTTY) MORTGAGE_QTTY,sum(NETTING_QTTY)NETTING_QTTY,  sum(BLOCKED_QTTY)BLOCKED_QTTY,
sum(SECURITIES_RECEIVING_T1)SECURITIES_RECEIVING_T1,
sum(SECURITIES_RECEIVING_T2) SECURITIES_RECEIVING_T2,
sum(SECURITIES_RECEIVING_TN) SECURITIES_RECEIVING_TN,
sum(SECURITIES_SENDING_T1) SECURITIES_SENDING_T1,
sum(SECURITIES_SENDING_T2) SECURITIES_SENDING_T2,
sum(SECURITIES_SENDING_TN) SECURITIES_SENDING_TN,sum(CA_RECEIVING)CA_RECEIVING,
SUM(WITHDRAW_QTTY) WITHDRAW_QTTY,
SUM(DEPOSIT_QTTY) DEPOSIT_QTTY,
SUM(HOLD_QTTY) HOLD_QTTY,
SUM(CKCC_RECEIVING) CKCC_RECEIVING,
SUM(CKCC_NETTING) CKCC_NETTING,
max(EMKQTTY) EMKQTTY,MAX(TEMP) TEMP,MAX(TRADE1404) TRADE1404
FROM  v_Se2206
GROUP BY custodycd, symbol
/
