SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW V_SEARCHCD
(SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, AUTHCODE, 
 OBJNAME, FRMNAME, ORDERBYCMDSQL, POSITION, FIELDCODE, 
 FIELDNAME, EN_FIELDNAME, FIELDTYPE, FIELDSIZE, MASK, 
 OPERATOR, FORMAT, DISPLAY, SRCH, KEY, 
 REFVALUE, TLTXCD, WIDTH, LOOKUPCMDSQL, MULTILANG, 
 ACDTYPE, ACDNAME, ROWPERPAGE, FIELDCMP, FIELDCMPKEY, 
 ISSMS, ISEMAIL, ROWLIMIT, CMDTYPE, CONDDEFFLD, 
 BANKINQ, BANKACCT, INTERVAL, QUICKSRCH, SUMMARYCD)
AS 
SELECT S.SEARCHCODE SEARCHCODE, S.SEARCHTITLE SEARCHTITLE, S.EN_SEARCHTITLE EN_SEARCHTITLE, S.SEARCHCMDSQL SEARCHCMDSQL,
        S.AUTHCODE, S.OBJNAME OBJNAME, S.FRMNAME FRMNAME,S.ORDERBYCMDSQL ORDERBYCMDSQL, SF.POSITION POSITION, SF.FIELDCODE FIELDCODE,
        SF.FIELDNAME FIELDNAME, SF.EN_FIELDNAME EN_FIELDNAME, SF.FIELDTYPE FIELDTYPE, SF.FIELDSIZE FIELDSIZE, SF.MASK MASK,
        SF.OPERATOR OPERATOR, SF.FORMAT FORMAT, SF.DISPLAY DISPLAY, SF.SRCH SRCH, SF.KEY KEY, REFVALUE, S.TLTXCD,
        SF.WIDTH WIDTH, SF.LOOKUPCMDSQL LOOKUPCMDSQL, SF.MULTILANG, SF.ACDTYPE, SF.ACDNAME, S.ROWPERPAGE,SF.FIELDCMP,SF.FIELDCMPKEY,
        (CASE WHEN REFDTL.TAGSMS>0 THEN 'Y' ELSE 'N' END) ISSMS,
        (CASE WHEN REFDTL.TAGEMAIL>0 THEN 'Y' ELSE 'N' END) ISEMAIL, s.rowlimit, s.cmdtype, s.conddeffld, s.bankinq, s.bankacct,s.INTERVAL,sf.QUICKSRCH,sf.SUMMARYCD
    FROM SEARCH S, SEARCHFLD SF,
      (SELECT VIEWLNK2TMP.SEARCHCODE, SUM(CASE WHEN CONTENTTMP.SENDVIA='S' THEN 1 ELSE 0 END) TAGSMS,
      SUM(CASE WHEN CONTENTTMP.SENDVIA='E' THEN 1 ELSE 0 END) TAGEMAIL
      FROM CONTENTTMP, VIEWLNK2TMP WHERE CONTENTTMP.TMPCODE=VIEWLNK2TMP.TMPCODE GROUP BY VIEWLNK2TMP.SEARCHCODE) REFDTL
    WHERE S.SEARCHCODE = SF.SEARCHCODE AND S.SEARCHCODE = REFDTL.SEARCHCODE (+)
/
