SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW V_SE2206
(SUBACCTNO, SYMBOL, TOTAL_QTTY, TRADE_QTTY, WTRADE, 
 DEALFINANCING_QTTY, ORDERQTTY_NORMAL, ORDERQTTY_BLOCKED, ORDERQTTY_BUY, MORTGAGE_QTTY, 
 NETTING_QTTY, BLOCKED_QTTY, SECURITIES_RECEIVING_T1, SECURITIES_RECEIVING_T2, SECURITIES_RECEIVING_TN, 
 SECURITIES_SENDING_T1, SECURITIES_SENDING_T2, SECURITIES_SENDING_TN, CA_RECEIVING, WITHDRAW_QTTY, 
 DEPOSIT_QTTY, HOLD_QTTY, CKCC_RECEIVING, CKCC_NETTING, ISINCODE, 
 FULLNAME, IDCODE, ADDRESS, CUSTODYCD, EMKQTTY, 
 TEMP, TRADE1404)
AS 
SELECT VW."SUBACCTNO",VW."SYMBOL",VW."TOTAL_QTTY",VW."TRADE_QTTY",VW."WTRADE",VW."DEALFINANCING_QTTY",
VW."ORDERQTTY_NORMAL",VW."ORDERQTTY_BLOCKED",VW."ORDERQTTY_BUY",VW."MORTGAGE_QTTY",VW."NETTING_QTTY",
VW."BLOCKED_QTTY",VW."SECURITIES_RECEIVING_T1",VW."SECURITIES_RECEIVING_T2",
VW."SECURITIES_RECEIVING_TN",VW."SECURITIES_SENDING_T1",
VW."SECURITIES_SENDING_T2",VW."SECURITIES_SENDING_TN",VW."CA_RECEIVING",
VW."WITHDRAW_QTTY",VW."DEPOSIT_QTTY",VW."HOLD_QTTY",VW."CKCC_RECEIVING",VW."CKCC_NETTING",VW.ISINCODE,
CF.FULLNAME,CF.IDCODE,CF.ADDRESS,CF.CUSTODYCD,VW.EMKQTTY,VW.TEMP,VW.TRADE1404 --trung.luu: 14-10-2020 SHBVNEX-1310
FROM
(
    SELECT MST.AFACCTNO SUBACCTNO,SB.SYMBOL,SB.ISINCODE,max(MST.EMKQTTY) EMKQTTY,
    MAX(MST.TRADE+MST.HOLD+MST.MORTAGE+MST.NETTING+MST.BLOCKED+MST.WITHDRAW+MST.BLOCKWITHDRAW+MST.EMKQTTY) TOTAL_QTTY,
    MAX(MST.TRADE) TRADE_QTTY,
    MAX(MST.WTRADE) WTRADE, 0 DEALFINANCING_QTTY,
    MAX(NVL(REFORDER.SECUREAMT,0)) ORDERQTTY_NORMAL,
    MAX(NVL(REFORDER.SECUREMTG,0)) ORDERQTTY_BLOCKED,
    MAX(NVL(REFORDER_BUY.SERECEIVING,0)) ORDERQTTY_BUY,
    MAX(MST.MORTAGE) MORTGAGE_QTTY,
    MAX(MST.NETTING) - MAX(NVL(ETF.CKCC_NETTING,0)) NETTING_QTTY,
    MAX(MST.BLOCKED) BLOCKED_QTTY,
    MAX(MST.WITHDRAW + MST.BLOCKWITHDRAW) WITHDRAW_QTTY,
    MAX(MST.DEPOSIT + MST.SENDDEPOSIT) DEPOSIT_QTTY,
    MAX(MST.HOLD) HOLD_QTTY,
    MAX(NVL(ETF.CKCC_RECEIVING,0)) CKCC_RECEIVING,
    MAX(NVL(ETF.CKCC_NETTING,0)) CKCC_NETTING,
    SUM(CASE WHEN ST.DUETYPE='RS' AND ST.NDAY=1 THEN ST.ST_QTTY-ST.ST_AQTTY ELSE 0 END) SECURITIES_RECEIVING_T1,
    SUM(CASE WHEN ST.DUETYPE='RS' AND ST.NDAY=2 THEN ST.ST_QTTY-ST.ST_AQTTY ELSE 0 END) SECURITIES_RECEIVING_T2,
    SUM(CASE WHEN ST.DUETYPE='RS' AND ST.NDAY=0 THEN ST.ST_QTTY-ST.ST_AQTTY ELSE 0 END) SECURITIES_RECEIVING_TN,
    --view VW_BD_PENDING_SETTLEMENT dang tinh theo ngay CLEARDATE nen bi nguoc
    SUM(CASE WHEN ST.DUETYPE='SS' AND ST.NDAY=1 THEN ST.ST_QTTY-ST.ST_AQTTY ELSE 0 END) SECURITIES_SENDING_T1,
    SUM(CASE WHEN ST.DUETYPE='SS' AND ST.NDAY=2 THEN ST.ST_QTTY-ST.ST_AQTTY ELSE 0 END) SECURITIES_SENDING_TN,
    SUM(CASE WHEN ST.DUETYPE='SS' AND ST.NDAY=0 THEN ST.ST_QTTY-ST.ST_AQTTY ELSE 0 END) SECURITIES_SENDING_T2,
    --
    MAX(MST.RECEIVING - NVL(ETF.CKCC_RECEIVING,0)) CA_RECEIVING,
    MAX(MST.TEMP) TEMP, --trung.luu: 14-10-2020 SHBVNEX-1310
    MAX(MST.TRADE1404) TRADE1404 --thoai.tran 29/06/2022 SHBVNEX-2577
    FROM SEMAST MST, AFMAST AF, CFMAST CF,
    V_GETSELLORDERINFO REFORDER,V_GETBUYORDERINFO_BY_SYMBOL REFORDER_BUY,
    (
        SELECT * FROM SBSECURITIES --WHERE SECTYPE<>'004'
    ) SB, 
    (
        SELECT * FROM VW_BD_PENDING_SETTLEMENT WHERE DUETYPE='RS' OR DUETYPE='SS'
    ) ST,
    (
        SELECT ACCTNO,
                SUM(CASE WHEN FIELD = 'RECEIVING' THEN (CASE WHEN TXTYPE = 'D' THEN -NAMT ELSE NAMT END) ELSE 0 END) RECEIVING_NAMT,
                SUM(CASE WHEN FIELD = 'RECEIVING' AND TXCD IN('3351','3350') THEN
                (CASE WHEN TXTYPE = 'D' THEN -NAMT ELSE NAMT END) ELSE 0 END) CA_RECEIVING_NAMT
        FROM VW_SETRAN_GEN
        WHERE DELTD <> 'Y' AND FIELD IN ('RECEIVING')
        GROUP BY ACCTNO
        HAVING
            SUM(CASE WHEN FIELD = 'RECEIVING' THEN (CASE WHEN TXTYPE = 'D' THEN -NAMT ELSE NAMT END) ELSE 0 END) <> 0 OR
                SUM(CASE WHEN FIELD = 'RECEIVING' AND TXCD IN('3351','3350') THEN
                (CASE WHEN TXTYPE = 'D' THEN -NAMT ELSE NAMT END) ELSE 0 END) <> 0
    ) TR,
    (
        SELECT SE.ACCTNO SEACCTNO, OD.EXECTYPE,
               --DECODE(OD.EXECTYPE,'NB',SUM(ETF.QTTY),0) CKCC_RECEIVING,
               --DECODE(OD.EXECTYPE,'NS',SUM(ETF.QTTY),0) CKCC_NETTING
               (case WHEN ETF.status = 'A' then 0 else DECODE(OD.EXECTYPE,'NB',SUM(ETF.QTTY),0) end) CKCC_RECEIVING,
               (case WHEN ETF.status = 'A' then 0 else DECODE(OD.EXECTYPE,'NS',SUM(ETF.QTTY),0) end) CKCC_NETTING
        FROM ETFWSAP ETF, ODMAST OD, SEMAST SE
        WHERE ETF.ORDERID = OD.ORDERID AND
              OD.ODTYPE = 'SWE' AND
              OD.DELTD <> 'Y' AND
              ETF.AFACCTNO = SE.AFACCTNO AND ETF.CODEID = SE.CODEID
        GROUP BY SE.ACCTNO, OD.EXECTYPE,ETF.status
    ) ETF
    WHERE MST.AFACCTNO=AF.ACCTNO AND AF.CUSTID=CF.CUSTID AND MST.CODEID=SB.CODEID
    AND MST.ACCTNO=REFORDER.SEACCTNO (+) AND MST.ACCTNO=REFORDER_BUY.SEACCTNO (+)
    AND MST.ACCTNO=ETF.SEACCTNO (+)
    AND MST.AFACCTNO=ST.AFACCTNO (+) AND MST.CODEID=ST.CODEID (+)
    AND MST.ACCTNO = TR.ACCTNO(+)
    GROUP BY MST.AFACCTNO, SB.SYMBOL, SB.ISINCODE
) VW, CFMAST CF ,AFMAST
WHERE VW.SUBACCTNO=AFMAST.ACCTNO AND AFMAST.CUSTID=CF.CUSTID
/
