SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW V_USERLIMIT
(TLIDUSER, IDCODE, USERNAME, FULLNAME, BRID, 
 USERTYPE, ALLOCATELIMMIT, ACCTLIMIT, USEDLIMMIT, REMAINISSUE, 
 T0, T0MAX, T0USED, T0REMAIN, TCUSED, 
 TCREMAIN, DPLIMIT, DPLIMITMAX)
AS 
SELECT TLID TLIDUSER, TL.IDCODE IDCODE, TL.TLNAME USERNAME, TO_CHAR(TL.TLFULLNAME) FULLNAME,BRGRP.BRNAME BRID,
       'FLEX' USERTYPE,
       NVL(ALLOCATELIMMIT,0) ALLOCATELIMMIT, -- HM MR
       NVL(ACCTLIMIT,0) ACCTLIMIT,  -- MR/KH
       NVL(MR.TCUSED,0) USEDLIMMIT, -- MR da su dung
       (NVL(ALLOCATELIMMIT,0)-NVL(MR.TCUSED,0)) REMAINISSUE, -- MR Con lai
       
       NVL(T0,0) T0,  -- HM T0
       NVL(T0MAX,0) T0MAX,  -- T0/KH
       NVL(T0.T0USED,0) T0USED,  -- T0 da su dung
       NVL(T0,0) - NVL(T0.T0USED,0) T0REMAIN, -- T0 con lai
       
       NVL(TC.TCUSED,0) TCUSED, -- TC da su dung
       NVL(DPLIMIT,0) - NVL(TC.TCUSED,0) TCREMAIN, -- TC con lai
       NVL(DPLIMIT,0) DPLIMIT, -- HM TC
       NVL(DPLIMITMAX,0) DPLIMITMAX -- TC /KH
    FROM BRGRP,USERLIMIT U ,TLPROFILES TL,
         (SELECT SUM(A.ACCLIMIT) T0USED ,A.TLIDUSER FROM USERAFLIMIT A WHERE A.TYPERECEIVE ='T0' GROUP BY A.TLIDUSER) T0,
         (SELECT SUM(B.ACCLIMIT) TCUSED ,B.TLIDUSER FROM USERAFLIMIT B WHERE B.TYPERECEIVE ='DP' GROUP BY B.TLIDUSER) TC,
         (SELECT SUM(B.ACCLIMIT) TCUSED ,B.TLIDUSER FROM USERAFLIMIT B WHERE B.TYPERECEIVE ='MR' GROUP BY B.TLIDUSER) MR
    WHERE U.TLIDUSER(+) = TLID AND T0.TLIDUSER(+) =TLID AND TC.TLIDUSER(+) =TLID AND MR.TLIDUSER(+) =TLID AND BRGRP.BRID=TL.BRID
/
