SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_AFMAST_DDACCOUNT_ISDEFAULT
(FILTERCD, VALUE, VALUECD, DISPLAY, EN_DISPLAY, 
 DESCRIPTION)
AS 
SELECT AF.ACCTNO FILTERCD, DD.ACCTNO VALUE, DD.ACCTNO VALUECD, DD.REFCASAACCT || '-' || DD.CCYCD || '-' || dd.ACCOUNTTYPE  DISPLAY,
DD.REFCASAACCT || '-' || DD.CCYCD || '-' || dd.ACCOUNTTYPE  EN_DISPLAY, DD.REFCASAACCT DESCRIPTION
FROM AFMAST AF, DDMAST DD
WHERE AF.ACCTNO=DD.AFACCTNO 
AND DD.status ='A'
AND DD.isdefault = 'Y'
order by isdefault DESC, autoid
/
