SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_AFMAST_CUSTODYCD
(CUSTODYCD, FULLNAME, ACTYPE, CUSTID, ACCTNO, 
 AFTYPE, BANKACCTNO, BANKNAME, SWIFTCODE, LASTDATE, 
 STATUS, PSTATUS, ADVANCELINE, DEPOSITLINE, BRATIO, 
 TERMOFUSE, DESCRIPTION, ISOTC, PISOTC, OPNDATE, 
 COREBANK, VIA, MRIRATE, MRMRATE, MRLRATE, 
 MRCRLIMIT, MRCRLIMITMAX, GROUPLEADER, T0AMT, BRID, 
 LAST_CHANGE, CLSDATE, CAREBY, AUTOADV, TLID, 
 MRIRATIO, MRMRATIO, MRLRATIO, DEPOLASTDT, BRKFEETYPE, 
 TRIGGERDATE, ALTERNATEACCT)
AS 
select cf.custodycd, cf.fullname,af."ACTYPE",af."CUSTID",af."ACCTNO",af."AFTYPE",af."BANKACCTNO",af."BANKNAME",af."SWIFTCODE",af."LASTDATE",af."STATUS",af."PSTATUS",af."ADVANCELINE",af."DEPOSITLINE",af."BRATIO",af."TERMOFUSE",af."DESCRIPTION",af."ISOTC",af."PISOTC",af."OPNDATE",af."COREBANK",af."VIA",af."MRIRATE",af."MRMRATE",af."MRLRATE",af."MRCRLIMIT",af."MRCRLIMITMAX",af."GROUPLEADER",af."T0AMT",af."BRID",af."LAST_CHANGE",af."CLSDATE",af."CAREBY",af."AUTOADV",af."TLID",af."MRIRATIO",af."MRMRATIO",af."MRLRATIO",af."DEPOLASTDT",af."BRKFEETYPE",af."TRIGGERDATE",af."ALTERNATEACCT" from cfmast cf, afmast af 
where cf.custid = af.custid
/
