SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_BA0001
(ISSUESID, CODEID, SYMBOL, SECTYPE, SECTYPE_NAME, 
 CUSTODYCD, ISSUECODE, BONDSYMBOL, ISSUERNAME, QTTY, 
 AMT, PRICE, VALUE)
AS 
SELECT ISS.AUTOID ISSUESID, SB.CODEID, SB.SYMBOL, SB.SECTYPE, A1.CDCONTENT SECTYPE_NAME,
       CF.CUSTODYCD,ISS.ISSUECODE, ISS.BONDSYMBOL, ISR.FULLNAME ISSUERNAME, SUM(MT.QTTY) QTTY, SUM(MT.AMT) AMT,
       (
        CASE WHEN SB.SECTYPE ='014' THEN 1
             WHEN SB.SECTYPE IN ('009','013') AND BI.PRICETYPE ='001'  THEN SB.PARVALUE * (BI.TPERCENT/100) --TIEN GUI CO KY HAN VA CHUNG CHI TIEN GOI
             ELSE NVL(BI.BONDPRICE,0)
       END) PRICE,
       (
        CASE WHEN SB.SECTYPE ='014' THEN SUM(MT.AMT)
             WHEN SB.SECTYPE IN ('009','013') AND BI.PRICETYPE ='001'  THEN (SB.PARVALUE * (BI.TPERCENT/100))*SUM(MT.QTTY)
             ELSE NVL(BI.BONDPRICE,0)*SUM(MT.QTTY)
        END) VALUE
FROM (
        SELECT REPLACE(SE.ACCTNO,SE.AFACCTNO,'') CODEID, SE.ISSUESID,SE.AFACCTNO,
            SUM(CASE WHEN SE.TLTXCD IN ('2232') THEN SE.QTTY
                     WHEN SE.TLTXCD IN ('2233') THEN -SE.QTTY ELSE 0 END) QTTY, 0 AMT
        FROM SEMORTAGE SE
        WHERE SE.DELTD <> 'Y'
        AND SE.STATUS IN ('C')
        AND SE.ISSUESID IS NOT NULL
        GROUP BY SE.ACCTNO, SE.AFACCTNO,SE.ISSUESID
        UNION ALL
        SELECT REPLACE(SE.ACCTNO,SE.AFACCTNO,'') CODEID, SE.ISSUESID,SE.AFACCTNO,
            SUM(CASE WHEN SE.TLTXCD IN ('1900') THEN SE.QTTY
                     WHEN SE.TLTXCD IN ('1901') THEN -SE.QTTY ELSE 0 END) QTTY, 0 AMT
        FROM SEMORTAGE SE
        WHERE SE.DELTD <> 'Y'
        AND SE.STATUS IN ('C')
        AND SE.ISSUESID IS NOT NULL
        GROUP BY SE.ACCTNO, SE.AFACCTNO,SE.ISSUESID
        UNION ALL
        SELECT BL.CODEID, BL.ISSUESID,BL.AFACCTNO, 0 QTTY,
            SUM(CASE WHEN BL.TLTXCD IN ('1909') THEN BL.AMT
                     WHEN BL.TLTXCD IN ('1910') THEN -BL.AMT ELSE 0 END) AMT
        FROM BLOCKAGE BL
        WHERE BL.DELTD <> 'Y'
        AND BL.ISSUESID IS NOT NULL
        GROUP BY BL.CODEID,BL.ISSUESID,BL.AFACCTNO
     ) MT
JOIN SBSECURITIES SB ON MT.CODEID = SB.CODEID
JOIN (SELECT AF.ACCTNO AFACCTNO, AF.CUSTID,CF.CUSTODYCD 
        FROM AFMAST AF,CFMAST CF 
        WHERE AF.CUSTID=CF.CUSTID
) CF ON MT.AFACCTNO = CF.AFACCTNO
JOIN (
        SELECT T.AUTOID, T.ISSUERID,T.ISSUECODE,LISTAGG(T.BONDSYMBOL, ', ') WITHIN GROUP (ORDER BY T.AUTOID, T.ISSUERID,T.ISSUECODE) BONDSYMBOL
        FROM (
                SELECT DISTINCT ISS.AUTOID, ISS.ISSUERID,ISS.ISSUECODE,BI.BONDSYMBOL
                FROM ISSUES ISS LEFT JOIN BONDISSUE BI ON ISS.AUTOID = BI.ISSUESID
                GROUP BY ISS.AUTOID, ISS.ISSUERID,ISS.ISSUECODE,BI.BONDSYMBOL
             ) T
        GROUP BY T.AUTOID, T.ISSUERID,T.ISSUECODE
    ) ISS ON MT.ISSUESID = ISS.AUTOID
LEFT JOIN (
            SELECT DISTINCT ISSUESID, BONDPRICE, CODEID,TPERCENT,PRICETYPE
            FROM BONDINFO
            WHERE (ISSUESID, TXDATE) IN (SELECT ISSUESID, MAX(TXDATE) FROM BONDINFO GROUP BY ISSUESID)
           ) BI ON BI.ISSUESID = ISS.AUTOID AND BI.CODEID = MT.CODEID
JOIN ALLCODE A1 ON A1.CDVAL = SB.SECTYPE AND CDNAME ='SECTYPE' AND CDTYPE ='SA'
JOIN ISSUERS ISR ON ISR.ISSUERID = ISS.ISSUERID
WHERE NOT (MT.QTTY = 0 AND MT.AMT = 0)
AND INSTR((SELECT ',' || LISTAGG(REPLACE(TICKERLIST,' ',''), ',') WITHIN GROUP (ORDER BY TICKERLIST) ||',' FROM BONDTYPE), ',' || SB.SYMBOL || ',') > 0
GROUP BY ISS.AUTOID, SB.CODEID, SB.SYMBOL, SB.SECTYPE,SB.PARVALUE, A1.CDCONTENT,CF.CUSTODYCD, ISS.ISSUECODE, ISS.BONDSYMBOL, ISR.FULLNAME, SB.SECTYPE, BI.BONDPRICE,BI.TPERCENT,BI.PRICETYPE
/
