SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_BD_PENDING_SETTLEMENT
(AFACCTNO, DUETYPE, CURRDATE, TXDATE, CLEARCD, 
 CLEARDAY, SYMBOL, TDAY, NDAY, ST_QTTY, 
 ST_AQTTY, ST_AMT, ST_AAMT, ST_FAMT, EN_DUETYPE_DESC, 
 DUETYPE_DESC, CODEID, FEEACR, TRFDAY, EXECAMTINDAY, 
 ST_PAIDAMT, ST_PAIDFEEAMT, TAXSELLAMT)
AS 
SELECT ST.AFACCTNO, ST.DUETYPE, TO_DATE(MAX(SYSVAR.VARVALUE),'DD/MM/RRRR') CURRDATE, ST.TXDATE, ST.CLEARCD, ST.CLEARDAY, SB.SYMBOL,
    --PhuNh: TDAY la ngay mua , khong phai ngay ve
    SP_BD_GETCLEARDAY(ST.CLEARCD, MAX(SB.TRADEPLACE), ST.TXDATE, TO_DATE(MAX(SYSVAR.VARVALUE),'DD/MM/RRRR')) TDAY,
    --ST.CLEARDAY-SP_BD_GETCLEARDAY(ST.CLEARCD, MAX(SB.TRADEPLACE), ST.TXDATE, TO_DATE(MAX(SYSVAR.VARVALUE),'DD/MM/RRRR')) TDAY,
    --ST.CLEARDATE-TO_DATE(MAX(SYSVAR.VARVALUE),'DD/MM/RRRR') NDAY,
    FN_GET_DATE_DIFF(TO_DATE(MAX(SYSVAR.VARVALUE),'DD/MM/RRRR'),ST.CLEARDATE,ST.CLEARCD)-1 NDAY,
    SUM(ST.QTTY) ST_QTTY, SUM(0) ST_AQTTY, SUM(ST.AMT) ST_AMT, SUM(0) ST_AAMT, SUM(ST.FeeAMT) ST_FAMT,
    MAX(CD1.CDCONTENT) EN_DUETYPE_DESC, MAX(CD1.CDCONTENT) DUETYPE_DESC, MAX(ST.CODEID) CODEID,
    SUM(OD.FEEACR)  FEEACR,
    SP_BD_GETCLEARDAY(ST.CLEARCD, MAX(SB.TRADEPLACE), TO_DATE(MAX(SYSVAR.VARVALUE),'DD/MM/RRRR'),max(ST.cleardate)) TRFDAY,
    SUM(CASE WHEN ST.TXDATE = TO_DATE(SYSVAR.VARVALUE,'DD/MM/RRRR') THEN ST.AMT ELSE 0 END) EXECAMTINDAY,
    0 ST_PAIDAMT, SUM(ST.paidfeeamt) ST_PAIDFEEAMT,
    SUM(CASE WHEN OD.TAXSELLAMT >0 THEN OD.TAXSELLAMT
            WHEN INSTR(OD.EXECTYPE,'S') >0 AND OD.EXECAMT >0 THEN OD.EXECAMT*TO_NUMBER(SYS1.VARVALUE)/100 ELSE 0 END) TAXSELLAMT
FROM STSCHD ST, SYSVAR, SBSECURITIES SB, ALLCODE CD1, CFMAST CF, AFMAST AF, ODMAST OD, SYSVAR SYS1
WHERE SYSVAR.VARNAME='CURRDATE' AND ST.CODEID=SB.CODEID
    AND CF.CUSTID=AF.CUSTID AND AF.ACCTNO=ST.AFACCTNO
    AND OD.ORDERID = ST.ORDERID
    AND ST.status = 'P' AND st.deltd = 'N'
    AND CD1.CDTYPE='OD' AND CD1.CDNAME='DUETYPE' AND ST.DUETYPE=CD1.CDVAL
    and sys1.varname = 'ADVSELLDUTY' and sys1.grname = 'SYSTEM'
    --AND OD.errod = 'N'
GROUP BY ST.AFACCTNO, ST.DUETYPE, ST.TXDATE, ST.CLEARCD, ST.CLEARDAY, SB.SYMBOL,ST.CLEARDATE
/
