SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_CFMAST_DDMAST_ACTIVE
(FILTERCD, VALUECD, VALUE, DISPLAY, EN_DISPLAY, 
 CUSTODYCD, AFACCTNO, CCYCD, ACCOUNTTYPE, ISDEFAULT, 
 REFCASAACCT, CIFID, BALANCE)
AS 
SELECT C.CUSTODYCD FILTERCD, D.ACCTNO VALUECD,D.ACCTNO VALUE,
    D.REFCASAACCT||'-'|| NVL(D.CCYCD,'')||'-'||NVL(D.ACCOUNTTYPE,'') DISPLAY,
    D.REFCASAACCT||'-'|| NVL(D.CCYCD,'')||'-'||NVL(D.ACCOUNTTYPE,'') EN_DISPLAY,
    C.CUSTODYCD, D.AFACCTNO, D.CCYCD, D.ACCOUNTTYPE,
    D.ISDEFAULT, d.REFCASAACCT, C.CIFID,D.BALANCE
FROM DDMAST D, CFMAST C
WHERE D.CUSTID = C.CUSTID
    AND D.STATUS NOT IN ('P','C')
ORDER BY ISDEFAULT DESC, C.CUSTODYCD, D.ACCTNO
/
