SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_CUSTOMER_AUTH
(FILTERCD, VALUE, VALUECD, DISPLAY, EN_DISPLAY, 
 DESCRIPTION, CAREBY)
AS 
SELECT DISTINCT AF.ACCTNO FILTERCD, CF.CUSTID VALUE, CF.CUSTID VALUECD,
     (CF.CUSTID || ': ' || CF.FULLNAME )  DISPLAY ,
     (CF.CUSTID || ': ' || CF.FULLNAME) EN_DISPLAY,
     CF.FULLNAME DESCRIPTION, AF.CAREBY
FROM CFMAST CF, AFMAST AF
WHERE CF.CUSTID=AF.CUSTID

UNION ALL

SELECT DISTINCT AF.ACCTNO FILTERCD, NVL(FU.CUSTID,FU.LICENSENO) VALUE, FU.CUSTID VALUECD,
     ('UQ ' || NVL(FU.CUSTID,FU.LICENSENO) || ': ' || FU.FULLNAME)  DISPLAY,
     ('UQ ' || NVL(FU.CUSTID,FU.LICENSENO) || ':  ' || FU.FULLNAME) EN_DISPLAY,
     FU.FULLNAME DESCRIPTION, AF.CAREBY
FROM CFMAST CF, CFAUTH FU, AFMAST AF
WHERE CF.CUSTID = AF.CUSTID
      AND CF.CUSTID = FU.CFCUSTID
      AND FU.DELTD <> 'Y'
      AND FU.EXPDATE >= (SELECT SYSVAR.VARVALUE FROM SYSVAR WHERE SYSVAR.VARNAME = 'CURRDATE')
      AND FU.VALDATE <= (SELECT SYSVAR.VARVALUE FROM SYSVAR WHERE SYSVAR.VARNAME = 'CURRDATE')
      AND SUBSTR(FU.LINKAUTH,3,1) = 'Y'
/
