SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_CUSTODYCD_SUBACCOUNT_ACTIVE
(FILTERCD, VALUE, VALUECD, DISPLAY, EN_DISPLAY, 
 DESCRIPTION, GROUPLEADER, CAREBY, ISODDLOT)
AS 
SELECT CF.CUSTODYCD FILTERCD, AF.ACCTNO VALUE, AF.ACCTNO VALUECD, AF.ACCTNO  DISPLAY,
AF.ACCTNO  EN_DISPLAY, CF.FULLNAME DESCRIPTION,AF.GROUPLEADER, AF.CAREBY, af.ISODDLOT
FROM CFMAST CF, AFMAST AF
WHERE CF.CUSTID=AF.CUSTID 
AND af.status <> 'C'
/
