SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_CRBTRFLOGDTL_ALL
(AUTOID, ITEMTRANCODE, VERSION, REFREQID, AFACCTNO, 
 AMT, REFNOTES, STATUS, ERRNUM, ERRMSG, 
 DONESTS, REFTXNUM, REFTXDATE, TRFCODE, REFHOLDID, 
 TXDATE, BANKCODE)
AS 
select "AUTOID","ITEMTRANCODE","VERSION","REFREQID","AFACCTNO","AMT","REFNOTES","STATUS","ERRNUM","ERRMSG","DONESTS","REFTXNUM","REFTXDATE","TRFCODE","REFHOLDID","TXDATE","BANKCODE" from crbtrflogdtl
union
select "AUTOID","ITEMTRANCODE","VERSION","REFREQID","AFACCTNO","AMT","REFNOTES","STATUS","ERRNUM","ERRMSG","DONESTS","REFTXNUM","REFTXDATE","TRFCODE","REFHOLDID","TXDATE","BANKCODE" from crbtrflogdtlhist
/
