SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_CBFA_FASFNOTICETX
(AUTOID, REFKEY, REFFUNDSFID, TXDATE, TXNUM, 
 TXBORS, FUNDCODEID, CUSTODYCD, REFSYMBOL, TXDESC, 
 TXAMT, TXQTTY, FEEAMT, DELTD, STATUS, 
 REFTXDATE, REFTXNUM, BUSDATE, CREATEDBY, INTLASTDT, 
 TRANSDATE, ISMATURITY, IDOBJECT, COST, PROFITORLOSS, 
 COSTPRICE, CLOSEDPRICE, REFNOTIFYID, TRADEDATE, TRANSACTIONTYPE, 
 LOGTIME, APACCT, ETFDATE)
AS 
SELECT "AUTOID","REFKEY","REFFUNDSFID","TXDATE","TXNUM","TXBORS","FUNDCODEID","CUSTODYCD","REFSYMBOL","TXDESC","TXAMT","TXQTTY","FEEAMT","DELTD","STATUS","REFTXDATE","REFTXNUM","BUSDATE","CREATEDBY","INTLASTDT","TRANSDATE","ISMATURITY","IDOBJECT","COST","PROFITORLOSS","COSTPRICE","CLOSEDPRICE","REFNOTIFYID","TRADEDATE","TRANSACTIONTYPE","LOGTIME","APACCT","ETFDATE"FROM CBFA_FASFNOTICETX@cbfaLINK WHERE STATUS = 'C'
UNION ALL
SELECT "AUTOID","REFKEY","REFFUNDSFID","TXDATE","TXNUM","TXBORS","FUNDCODEID","CUSTODYCD","REFSYMBOL","TXDESC","TXAMT","TXQTTY","FEEAMT","DELTD","STATUS","REFTXDATE","REFTXNUM","BUSDATE","CREATEDBY","INTLASTDT","TRANSDATE","ISMATURITY","IDOBJECT","COST","PROFITORLOSS","COSTPRICE","CLOSEDPRICE","REFNOTIFYID","TRADEDATE","TRANSACTIONTYPE","LOGTIME","APACCT","ETFDATE"FROM CBFA_FASFNOTICETX_HIST@cbfaLINK WHERE STATUS = 'C'
/
