SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_CAMASTDTL_ALL
(AUTOID, TXNUM, TXDATE, CAMASTID, TYPERATE, 
 DEVIDENTRATE, DEVIDENTVALUE, EXECRATE, FEEAMT, DELTD, 
 LASTDATE, STATUS)
AS 
Select "AUTOID","TXNUM","TXDATE","CAMASTID","TYPERATE","DEVIDENTRATE","DEVIDENTVALUE","EXECRATE","FEEAMT","DELTD","LASTDATE","STATUS" from camastdtl where deltd <> 'Y'
    UNION all 
Select "AUTOID","TXNUM","TXDATE","CAMASTID","TYPERATE","DEVIDENTRATE","DEVIDENTVALUE","EXECRATE","FEEAMT","DELTD","LASTDATE","STATUS" from camastdtlhist where deltd <> 'Y'
/
