SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_CUSTODYCD_MEMBER_CF
(FILTERCD, VALUE, VALUECD, DISPLAY, EN_DISPLAY, 
 DESCRIPTION, EN_DESCRIPTION)
AS 
SELECT BR.CUSTODYCD FILTERCD,BR.BRKID VALUE, BR.BRKID VALUECD,M.SHORTNAME DISPLAY,M.SHORTNAME EN_DISPLAY, M.FULLNAME DESCRIPTION, M.ENGLISHNAME EN_DESCRIPTION
FROM FABROKERAGE BR,FAMEMBERS M
WHERE BR.BRKID = M.AUTOID
AND M.ACTIVESTATUS = 'Y'
/
