SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_CUSTOMERID_SUBACCOUNT
(FILTERCD, VALUE, VALUECD, DISPLAY, EN_DISPLAY, 
 DESCRIPTION, GROUPLEADER, CAREBY)
AS 
SELECT CF.CUSTID FILTERCD, AF.ACCTNO VALUE, AF.ACCTNO VALUECD, AF.ACCTNO || ': ' || AFT.TYPENAME DISPLAY,
AF.ACCTNO || ': ' || AFT.TYPENAME EN_DISPLAY, CF.FULLNAME DESCRIPTION,AF.GROUPLEADER, AF.CAREBY
FROM CFMAST CF, AFMAST AF, AFTYPE AFT
WHERE CF.CUSTID=AF.CUSTID AND AF.ACTYPE=AFT.ACTYPE
/
