SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_CFMAST_M
(CUSTID, MCUSTID, SHORTNAME, FULLNAME, MNEMONIC, 
 DATEOFBIRTH, IDTYPE, IDCODE, IDDATE, IDPLACE, 
 IDEXPIRED, ADDRESS, PHONE, MOBILE, MOBILESMS, 
 FAX, EMAIL, COUNTRY, PROVINCE, POSTCODE, 
 RESIDENT, CLASS, GRINVESTOR, INVESTRANGE, TIMETOJOIN, 
 CUSTODYCD_ORG, CUSTODYCD, STAFF, COMPANYID, POSITION, 
 SEX, SECTOR, BUSINESSTYPE, INVESTTYPE, EXPERIENCETYPE, 
 INCOMERANGE, ASSETRANGE, FOCUSTYPE, BRID, CAREBY, 
 APPROVEID, LASTDATE, AUDITORID, AUDITDATE, LANGUAGE, 
 BANKACCTNO, BANKCODE, VALUDADDED, ISSUERID, DESCRIPTION, 
 MARRIED, TAXCODE, INTERNATION, OCCUPATION, EDUCATION, 
 CUSTTYPE, STATUS, PSTATUS, INVESTMENTEXPERIENCE, PCUSTODYCD, 
 EXPERIENCECD, ORGINF, TLID, ISBANKING, PIN, 
 USERNAME, RISKLEVEL, TRADINGCODE, TRADINGCODEDT, LAST_CHANGE, 
 OPNDATE, CFCLSDATE, CUSTATCOM, DMSTS, ACTIVEDATE, 
 AFSTATUS, OPENVIA, OLAUTOID, VAT, REFNAME, 
 TRADEFLOOR, TRADETELEPHONE, TRADEONLINE, CONSULTANT, ACTIVESTS, 
 LAST_MKID, LAST_OFID, COMMRATE, MARGINALLOW, MRLOANLIMIT, 
 T0LOANLIMIT, ISCHKONLIMIT, ONLINELIMIT, MANAGETYPE, CONTRACTNO, 
 ISFORCUSTMASTACC, MARGINCONTRACTNO, EMAILBR, PLACEOFBIRTH, NSDSTATUS, 
 SUBTAXCODE, TAXCODEISSUEORGAN, FAXNO, HEADOFFICE, HEADOFFICECORP, 
 OPERATINGMODE, ESTABLISHDATE, CEO, BANKATADDRESS, SWIFTCODE, 
 TAXCODEEXPIRYDATE, TAXCODEDATE, AMCID, LCBID, GCBID, 
 TRUSTEEID, CIFID, SUPEBANK, FEEDAILY, SENDSWIFT, 
 FUNDCODE, BONDAGENT, MCUSTODYCD)
AS 
SELECT b.custid, a.custid mcustid, a.shortname, a.fullname, a.mnemonic, a.dateofbirth,
       a.idtype, a.idcode, a.iddate, a.idplace, a.idexpired, a.address,
       a.phone, a.mobile, a.mobilesms, a.fax, a.email, a.country,
       a.province, a.postcode, a.resident, a.class, a.grinvestor,
       a.investrange, a.timetojoin, b.custodycd custodycd_org,nvl(b.mcustodycd,b.custodycd) custodycd, a.staff, a.companyid,
       a.position, a.sex, a.sector, a.businesstype, a.investtype,
       a.experiencetype, a.incomerange, a.assetrange, a.focustype,
       a.brid, a.careby, a.approveid, a.lastdate, a.auditorid,
       a.auditdate, a.language, a.bankacctno, a.bankcode, a.valudadded,
       a.issuerid, a.description, a.married, a.taxcode, a.internation,
       a.occupation, a.education, a.custtype, a.status, a.pstatus,
       a.investmentexperience, a.pcustodycd, a.experiencecd, a.orginf,
       a.tlid, a.isbanking, a.pin, a.username, a.risklevel,
       a.tradingcode, a.tradingcodedt, a.last_change, a.opndate,
       a.cfclsdate, a.custatcom, a.dmsts, a.activedate, a.afstatus,
       a.openvia, a.olautoid, a.vat, a.refname, a.tradefloor,
       a.tradetelephone, a.tradeonline, a.consultant, a.activests,
       a.last_mkid, a.last_ofid, a.commrate, a.marginallow,
       a.mrloanlimit, a.t0loanlimit, a.ischkonlimit, a.onlinelimit,
       a.managetype, a.contractno, a.isforcustmastacc,
       a.margincontractno, a.emailbr, a.placeofbirth, a.nsdstatus,
       a.subtaxcode, a.taxcodeissueorgan, a.faxno, a.headoffice,
       a.headofficecorp, a.operatingmode, a.establishdate, a.ceo,
       a.bankataddress, a.swiftcode, a.taxcodeexpirydate, a.taxcodedate,
       a.amcid, a.lcbid, a.gcbid, a.trusteeid, a.cifid, a.supebank,
       a.feedaily, a.sendswift, a.fundcode, a.bondagent, a.mcustodycd
  FROM cfmast b, cfmast a
  where nvl(b.mcustodycd,b.custodycd) =a.custodycd
/
