SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_CUSTODYCD_CFMAST
(FILTERCD, VALUE, VALUECD, DISPLAY, EN_DISPLAY, 
 DESCRIPTION)
AS 
SELECT CF.CUSTODYCD FILTERCD, CF.CUSTID VALUE, CF.CUSTID VALUECD, CF.CUSTID || ': ' || CF.FULLNAME DISPLAY,
CF.CUSTID || ': ' || CF.FULLNAME EN_DISPLAY, CF.FULLNAME DESCRIPTION
FROM CFMAST CF
/
