SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_CIMAST_CRBINFO
(ACTYPE, ACCTNO, CCYCD, AFACCTNO, CUSTID, 
 OPNDATE, CLSDATE, STATUS, PSTATUS, BALANCE, 
 HOLDBALANCE, PENDINGHOLD, PENDINGUNHOLD, RECEIVING, NETTING, 
 LAST_CHANGE, AVLBALANCE)
AS 
SELECT CI."ACTYPE",CI."ACCTNO",CI."CCYCD",CI."AFACCTNO",CI."CUSTID",CI."OPNDATE",CI."CLSDATE",CI."STATUS",
CI."PSTATUS",CI."BALANCE",

CI."HOLDBALANCE",CI."PENDINGHOLD",CI."PENDINGUNHOLD",
CI."RECEIVING",CI."NETTING",CI."LAST_CHANGE",
NVL(MST.AMT,0) AVLBALANCE
FROM AFMAST AF, DDMAST CI,
    -- Check co bang ke tang tien KH nhung chua chuyen qua NH thi thuc hien + vao suc mua de cho KH dat lenh
       (
          SELECT AFACCTNO ACCTNO, SUM(AMT) AMT
            FROM CRBTRFLOGDTL
            WHERE TXDATE = GETCURRDATE()
                AND TRFCODE = 'TRFSUBTRER'
                AND STATUS = 'S' -- CHI LAY NHUNG BANG KE CO TRANG THAI LA DA GUI SANG BANK
            GROUP BY AFACCTNO
        )MST
WHERE AF.ACCTNO = CI.AFACCTNO AND (AF.COREBANK ='Y' or AF.ALTERNATEACCT ='Y') AND CI.ACCTNO = MST.ACCTNO (+)
/
