SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_CASCHDDTL_ALL
(AUTOID, AUTOID_CASCHD, AUTOID_CAMASTDTL, AFACCTNO, CAMASTID, 
 AMT, AAMT, FEEAMT, DELTD, LASTDATE, 
 STATUS)
AS 
select "AUTOID","AUTOID_CASCHD","AUTOID_CAMASTDTL","AFACCTNO","CAMASTID","AMT","AAMT","FEEAMT","DELTD","LASTDATE","STATUS" from caschddtl where deltd <> 'Y'
    UNION ALL
select "AUTOID","AUTOID_CASCHD","AUTOID_CAMASTDTL","AFACCTNO","CAMASTID","AMT","AAMT","FEEAMT","DELTD","LASTDATE","STATUS" from caschddtl where deltd <> 'Y'
/
