SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_DDMAST_ACTIVE
(FILTERCD, VALUE, VALUECD, DISPLAY, EN_DISPLAY, 
 DESCRIPTION)
AS 
SELECT CF.CUSTODYCD FILTERCD, DD.ACCTNO VALUE, DD.ACCTNO VALUECD, DD.REFCASAACCT || '-' || DD.CCYCD || '-' || dd.ACCOUNTTYPE  DISPLAY,
DD.REFCASAACCT || '-' || DD.CCYCD || '-' || dd.ACCOUNTTYPE  EN_DISPLAY, DD.REFCASAACCT DESCRIPTION
FROM CFMAST CF, DDMAST DD
WHERE CF.CUSTODYCD=DD.CUSTODYCD
AND DD.STATUS <> 'C'
AND ISDEFAULT ='Y'
ORDER BY ISDEFAULT DESC, AUTOID
/
