SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_EXCHANGERATE_ALL
(AUTOID, TRADEDATE, LASTCHANGE, CURRENCY, VND, 
 NOTE, RTYPE, ITYPE)
AS 
SELECT "AUTOID","TRADEDATE","LASTCHANGE","CURRENCY","VND","NOTE","RTYPE","ITYPE" FROM exchangerate UNION ALL SELECT "AUTOID","TRADEDATE","LASTCHANGE","CURRENCY","VND","NOTE","RTYPE","ITYPE" FROM exchangerate_hist
/
