SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_EMAILLOG_ALL
(AUTOID, EMAIL, TEMPLATEID, DATASOURCE, STATUS, 
 CREATETIME, SENTTIME, AFACCTNO, NOTE, TYPESMS, 
 CREATETYPE, TXDATE, PAIDSTS)
AS 
select "AUTOID","EMAIL","TEMPLATEID","DATASOURCE","STATUS","CREATETIME","SENTTIME","AFACCTNO","NOTE","TYPESMS","CREATETYPE","TXDATE","PAIDSTS" from emaillog
UNION all 
select "AUTOID","EMAIL","TEMPLATEID","DATASOURCE","STATUS","CREATETIME","SENTTIME","AFACCTNO","NOTE","TYPESMS","CREATETYPE","TXDATE","PAIDSTS" from emailloghist
/
