SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_FEETRAN_DD0001
(TXDATE, TXNUM, DELTD, FEECD, GLACCTNO, 
 TXAMT, FEEAMT, FEERATE, VATRATE, VATAMT, 
 AUTOID, TRDESC, CCYCD, ORDERID, TYPE, 
 DEDUCTEDPLACE, STATUS, PAIDDATE, PSTATUS, SUBTYPE, 
 FEETYPES, CUSTODYCD, FEECODE, PAUTOID, FEEBIL)
AS 
select "TXDATE","TXNUM","DELTD","FEECD","GLACCTNO","TXAMT","FEEAMT","FEERATE","VATRATE","VATAMT","AUTOID","TRDESC","CCYCD","ORDERID","TYPE","DEDUCTEDPLACE","STATUS","PAIDDATE","PSTATUS","SUBTYPE","FEETYPES","CUSTODYCD","FEECODE","PAUTOID", fn_get_billingmonth(TO_CHAR(TXDATE, 'DD/MM/RRRR')) FEEBIL from feetran
union all
select "TXDATE","TXNUM","DELTD","FEECD","GLACCTNO","TXAMT","FEEAMT","FEERATE","VATRATE","VATAMT","AUTOID","TRDESC","CCYCD","ORDERID","TYPE","DEDUCTEDPLACE","STATUS","PAIDDATE","PSTATUS","SUBTYPE","FEETYPES","CUSTODYCD","FEECODE","PAUTOID", fn_get_billingmonth(TO_CHAR(TXDATE, 'DD/MM/RRRR')) FEEBIL from feetrana
/
