SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_FEETRANREPAIR_ALL
(TXDATE, TXNUM, ORDERID, EXECTYPE, SYMBOL, 
 CLEARDATE, QTTY, AMOUNT, FEEAMT, REPAIRAMT, 
 CUSTID, AFACCTNO, STATUS, DELTD, MAKERID, 
 CHECKERID)
AS 
SELECT "TXDATE","TXNUM","ORDERID","EXECTYPE","SYMBOL","CLEARDATE","QTTY","AMOUNT","FEEAMT","REPAIRAMT","CUSTID","AFACCTNO","STATUS","DELTD","MAKERID","CHECKERID" FROM FEETRANREPAIR
UNION ALL
SELECT "TXDATE","TXNUM","ORDERID","EXECTYPE","SYMBOL","CLEARDATE","QTTY","AMOUNT","FEEAMT","REPAIRAMT","CUSTID","AFACCTNO","STATUS","DELTD","MAKERID","CHECKERID" FROM FEETRANREPAIRHIST
/
