SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_FEEDETAILS_ALL
(FILTERCD, VALUE, VALUECD, DISPLAY, EN_DISPLAY, 
 ID)
AS 
SELECT  A2.CDVAL FILTERCD,A2.CDVAL VALUE, A2.CDVAL VALUECD, A2.CDCONTENT DISPLAY, A2.EN_CDCONTENT EN_DISPLAY, 'SEDEPO' ID FROM  ALLCODE A2
    WHERE A2.CDNAME = 'SEDEPO' AND A2.CDTYPE = 'SA'
    UNION ALL
    SELECT  A2.CDVAL FILTERCD,A2.CDVAL VALUE, A2.CDVAL VALUECD, A2.CDCONTENT DISPLAY, A2.EN_CDCONTENT EN_DISPLAY, 'OTHER' ID FROM  ALLCODE A2
    WHERE A2.CDNAME = 'OTHER' AND A2.CDTYPE = 'SA'
    UNION ALL
    SELECT  A2.CDVAL FILTERCD,A2.CDVAL VALUE, A2.CDVAL VALUECD, A2.CDCONTENT DISPLAY, A2.EN_CDCONTENT EN_DISPLAY, 'TRANREPAIR' ID FROM  ALLCODE A2
    WHERE A2.CDNAME = 'TRANREPAIR' AND A2.CDTYPE = 'SA'
    UNION ALL
    SELECT  A2.CDVAL FILTERCD,A2.CDVAL VALUE, A2.CDVAL VALUECD, A2.CDCONTENT DISPLAY, A2.EN_CDCONTENT EN_DISPLAY, 'PROXY' ID FROM  ALLCODE A2
    WHERE A2.CDNAME = 'PROXY' AND A2.CDTYPE = 'SA'
    UNION ALL
    SELECT  A2.CDVAL FILTERCD,A2.CDVAL VALUE, A2.CDVAL VALUECD, A2.CDCONTENT DISPLAY, A2.EN_CDCONTENT EN_DISPLAY, 'STC' ID FROM  ALLCODE A2
    WHERE A2.CDNAME = 'STC' AND A2.CDTYPE = 'SA'
    UNION ALL
    SELECT  A2.CDVAL FILTERCD,A2.CDVAL VALUE, A2.CDVAL VALUECD, A2.CDCONTENT DISPLAY, A2.EN_CDCONTENT EN_DISPLAY, 'BONDOTHER' ID FROM  ALLCODE A2
    WHERE A2.CDNAME = 'BONDOTHER' AND A2.CDTYPE = 'SA'
    UNION ALL
    SELECT  A2.CDVAL FILTERCD,A2.CDVAL VALUE, A2.CDVAL VALUECD, A2.CDCONTENT DISPLAY, A2.EN_CDCONTENT EN_DISPLAY, 'SETRAN' ID FROM  ALLCODE A2
    WHERE A2.CDNAME = 'SETRAN' AND A2.CDTYPE = 'SA'
    UNION ALL
    SELECT  A2.CDVAL FILTERCD,A2.CDVAL VALUE, A2.CDVAL VALUECD, A2.CDCONTENT DISPLAY, A2.EN_CDCONTENT EN_DISPLAY, 'ASSETMNG' ID FROM  ALLCODE A2
    WHERE A2.CDNAME = 'ASSETMNG' AND A2.CDTYPE = 'SA'
    UNION ALL
    SELECT  A2.CDVAL FILTERCD,A2.CDVAL VALUE, A2.CDVAL VALUECD, A2.CDCONTENT DISPLAY, A2.EN_CDCONTENT EN_DISPLAY, 'BONDMNG' ID FROM  ALLCODE A2
    WHERE A2.CDNAME = 'BONDMNG' AND A2.CDTYPE = 'SA'
    UNION ALL
    SELECT  A2.CDVAL FILTERCD,A2.CDVAL VALUE, A2.CDVAL VALUECD, A2.CDCONTENT DISPLAY, A2.EN_CDCONTENT EN_DISPLAY, 'PAYAGENCY' ID FROM  ALLCODE A2
    WHERE A2.CDNAME = 'PAYAGENCY' AND A2.CDTYPE = 'SA'
/
