SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_GL_EXP_TRAN
(REF, REFAUTOID, TLTXCD, TXNUM, TXDATE, 
 BUSDATE, CUSTID, CUSTODYCD, CIFID, SYMBOL, 
 QTTY, AMOUNT, CCYCD, DORC, DEBITACCT, 
 CREDITACCT, DELTD, LAST_CHANGE)
AS 
select "REF","REFAUTOID","TLTXCD","TXNUM","TXDATE","BUSDATE","CUSTID","CUSTODYCD","CIFID","SYMBOL","QTTY","AMOUNT","CCYCD","DORC","DEBITACCT","CREDITACCT","DELTD","LAST_CHANGE" from gl_exp_tran
/
