SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_IMPORT_ETF
(CUSTODYCD, TRANSDATE, FUNDCODEID, TRADINGID, TYPE, 
 AP, NAV, QUANTITY, VALUE, DIFFERENCE, 
 TRADINGFEE, TAX, SERCURITIES, SECQTTY, SECPRICE, 
 SECVALUE, FILEID, CLEARDATE, TLIDOVR, IMPTLID, 
 STATUS, OVRSTATUS, VIA, ERRMSG, MBID, 
 AP_SERCURITIES, HOLDFORSELL, LISTAUTOID, DETAIL, PLACE, 
 FULLNAME, ACCTNO)
AS 
SELECT H."CUSTODYCD",H."TRANSDATE",H."FUNDCODEID",H."TRADINGID",H."TYPE",H."AP",H."NAV",H."QUANTITY",H."VALUE",H."DIFFERENCE",H."TRADINGFEE",H."TAX",H."SERCURITIES",H."SECQTTY",H."SECPRICE",H."SECVALUE",H."FILEID",H."CLEARDATE",H."TLIDOVR",H."IMPTLID",H."STATUS",H."OVRSTATUS",H."VIA",H."ERRMSG",H."MBID",H."AP_SERCURITIES",H."HOLDFORSELL",H."LISTAUTOID",H."DETAIL",H."PLACE", CF.FULLNAME, AF.ACCTNO FROM
  (SELECT MAX(C.CUSTODYCD) CUSTODYCD,CASE WHEN INSTR(MAX(C.TRANSDATE),':')>0 THEN SUBSTR(MAX(C.TRANSDATE),0,10) ELSE MAX(C.TRANSDATE) END TRANSDATE, MAX(C.FUNDCODEID) FUNDCODEID, MAX(C.TRADINGID) TRADINGID,
         MAX(C.TYPE) TYPE, MAX(C.AP) AP, MAX(C.NAV) NAV, MAX(C.QUANTITY) QUANTITY, MAX(C.VALUE) VALUE, MAX(NVL(C.DIFFERENCE,0)) DIFFERENCE,
         MAX(C.TRADINGFEE) TRADINGFEE, MAX(C.TAX) TAX, MAX(C.SERCURITIES) SERCURITIES, MAX(NVL(C.SECQTTY,0)) SECQTTY,
         MAX(C.SECPRICE) SECPRICE, SUM(NVL(C.SECVALUE,0)) SECVALUE, MAX(C.FILEID) FILEID,CASE WHEN INSTR(MAX(C.CLEARDATE),':')>0 THEN SUBSTR(MAX(C.CLEARDATE),0,10) ELSE MAX(C.CLEARDATE) END CLEARDATE, MAX(C.TLIDOVR) TLIDOVR, 
         MAX(C.IMPTLID) IMPTLID, MAX(C.STATUS) STATUS, MAX(C.OVRSTATUS) OVRSTATUS, MAX(C.VIA) VIA,MAX(NVL(C.ERRMSG,'')) ERRMSG, MAX(C.MBID) MBID,
         MAX(NVL(C.AP_SERCURITIES,0)) AP_SERCURITIES, 
         MAX(NVL(C.HOLDFORSELL,0)) HOLDFORSELL,
         LISTAGG(LISTAUTOID,'#') WITHIN GROUP(ORDER BY C.FILEID,C.CUSTODYCD,C.FUNDCODEID,C.TRADINGID,C.TYPE,C.AP,C.TRANSDATE,C.CLEARDATE) AS LISTAUTOID,
         LISTAGG(DETAIL,'#') WITHIN GROUP(ORDER BY C.FILEID,C.CUSTODYCD,C.FUNDCODEID,C.TRADINGID,C.TYPE,C.AP,C.TRANSDATE,C.CLEARDATE) AS DETAIL,
         MAX(C.PLACE) PLACE
  FROM
  (
    SELECT MAX(T.CUSTODYCD) CUSTODYCD,MAX(T.TRANSDATE) TRANSDATE, MAX(T.FUNDCODEID) FUNDCODEID, MAX(T.TRADINGID) TRADINGID,
           MAX(T.TYPE) TYPE, MAX(T.AP) AP, MAX(T.NAV) NAV, MAX(T.QUANTITY) QUANTITY, SUM(T.VALUE) VALUE, MAX(NVL(T.DIFFERENCE,0)) DIFFERENCE,
           MAX(T.TRADINGFEE) TRADINGFEE, MAX(T.TAX) TAX, MAX(T.SERCURITIES) SERCURITIES, SUM(NVL(T.SECQTTY,0)) SECQTTY,
           MAX(T.SECPRICE) SECPRICE, SUM(NVL(T.SECVALUE,0)) SECVALUE, MAX(T.FILEID) FILEID,MAX(T.CLEARDATE) CLEARDATE, MAX(T.TLIDOVR) TLIDOVR, 
           MAX(T.IMPTLID) IMPTLID, MAX(T.STATUS) STATUS, MAX(T.OVRSTATUS) OVRSTATUS, MAX(T.VIA) VIA,MAX(NVL(T.ERRMSG,'')) ERRMSG, MAX(T.MBID) MBID,
           SUM(NVL(T.AP_SERCURITIES,0)) AP_SERCURITIES, 
           SUM(NVL(T.HOLDFORSELL,0)) HOLDFORSELL,
           MAX(T.TRADINGACCOUNT) TRADINGACCOUNTCD,
           CASE WHEN T.TRADINGACCOUNT  IS NULL OR LENGTH( T.TRADINGACCOUNT ) = 0 THEN '$$' ELSE T.TRADINGACCOUNT END TRADINGACCOUNT,
           LISTAGG(AUTOID,'#') WITHIN GROUP(ORDER BY T.FILEID,T.CUSTODYCD,T.FUNDCODEID,T.TRADINGID,T.TYPE,T.AP,T.TRANSDATE,T.CLEARDATE) AS LISTAUTOID,
           S.CODEID || '|' || SUM(NVL(T.SECQTTY,0))|| '|' || SUM(NVL(T.AP_SERCURITIES,0))|| '|' || SUM(NVL(T.HOLDFORSELL,0)) || '|' || MAX(T.SECPRICE)|| '|' ||SUM(NVL(T.SECVALUE,0))|| '|' ||T.TRADINGACCOUNT  DETAIL,
           'BACK' PLACE
    FROM ETFRESULT_TEMP T,SBSECURITIES S WHERE S.SYMBOL = T.SERCURITIES
    GROUP BY T.FILEID,T.FUNDCODEID,T.TRADINGID,T.AP,T.TYPE,T.SERCURITIES,S.CODEID,T.TRADINGACCOUNT
  ) C
  GROUP BY C.FILEID,C.CUSTODYCD,C.FUNDCODEID,C.TRADINGID,C.AP,C.TYPE,C.TRANSDATE,C.CLEARDATE
  UNION ALL
  SELECT MAX(C.CUSTODYCD) CUSTODYCD,MAX(C.TRANSDATE) TRANSDATE, MAX(C.FUNDCODEID) FUNDCODEID, MAX(C.TRADINGID) TRADINGID,
         MAX(C.TYPE) TYPE, MAX(C.AP) AP, MAX(C.NAV) NAV, MAX(C.QUANTITY) QUANTITY, MAX(C.VALUE) VALUE, MAX(NVL(C.DIFFERENCE,0)) DIFFERENCE,
         MAX(C.TRADINGFEE) TRADINGFEE, MAX(C.TAX) TAX, MAX(C.SERCURITIES) SERCURITIES, MAX(NVL(C.SECQTTY,0)) SECQTTY,
         MAX(C.SECPRICE) SECPRICE, SUM(NVL(C.SECVALUE,0)) SECVALUE, MAX(C.FILEID) FILEID,MAX(C.CLEARDATE) CLEARDATE, MAX(C.TLIDOVR) TLIDOVR, 
         MAX(C.IMPTLID) IMPTLID, MAX(C.STATUS) STATUS, MAX(C.OVRSTATUS) OVRSTATUS, MAX(C.VIA) VIA,MAX(NVL(C.ERRMSG,'')) ERRMSG, MAX(C.MBID) MBID,
         MAX(NVL(C.AP_SERCURITIES,0)) AP_SERCURITIES, 
         MAX(NVL(C.HOLDFORSELL,0)) HOLDFORSELL,
         LISTAGG(LISTAUTOID,'#') WITHIN GROUP(ORDER BY C.FILEID,C.CUSTODYCD,C.FUNDCODEID,C.TRADINGID,C.TYPE,C.AP,C.TRANSDATE,C.CLEARDATE) AS LISTAUTOID,
         LISTAGG(DETAIL,'#') WITHIN GROUP(ORDER BY C.FILEID,C.CUSTODYCD,C.FUNDCODEID,C.TRADINGID,C.TYPE,C.AP,C.TRANSDATE,C.CLEARDATE) AS DETAIL,
         MAX(C.PLACE) PLACE
  FROM
  (
    SELECT MAX(T.CUSTODYCD) CUSTODYCD,MAX(T.TRANSDATE) TRANSDATE, MAX(T.FUNDCODEID) FUNDCODEID, MAX(T.TRADINGID) TRADINGID,
           MAX(T.TYPE) TYPE, MAX(T.AP) AP, MAX(T.NAV) NAV, MAX(T.QUANTITY) QUANTITY, SUM(T.VALUE) VALUE, MAX(NVL(T.DIFFERENCE,0)) DIFFERENCE,
           MAX(T.TRADINGFEE) TRADINGFEE, MAX(T.TAX) TAX, MAX(T.SERCURITIES) SERCURITIES, SUM(NVL(T.SECQTTY,0)) SECQTTY,
           MAX(T.SECPRICE) SECPRICE, SUM(NVL(T.SECVALUE,0)) SECVALUE, MAX(T.FILEID) FILEID,MAX(T.CLEARDATE) CLEARDATE, MAX(T.TLIDOVR) TLIDOVR, 
           MAX(T.IMPTLID) IMPTLID, MAX(T.STATUS) STATUS, MAX(T.OVRSTATUS) OVRSTATUS, MAX(T.VIA) VIA,MAX(NVL(T.ERRMSG,'')) ERRMSG, MAX(T.MBID) MBID,
           SUM(NVL(T.AP_SERCURITIES,0)) AP_SERCURITIES, 
           SUM(NVL(T.HOLDFORSELL,0)) HOLDFORSELL,
           MAX(T.TRADINGACCOUNT) TRADINGACCOUNTCD,
           CASE WHEN T.TRADINGACCOUNT  IS NULL OR LENGTH( T.TRADINGACCOUNT ) = 0 THEN '$$' ELSE T.TRADINGACCOUNT END TRADINGACCOUNT,
           LISTAGG(AUTOID,'#') WITHIN GROUP(ORDER BY T.FILEID,T.CUSTODYCD,T.FUNDCODEID,T.TRADINGID,T.TYPE,T.AP,T.TRANSDATE,T.CLEARDATE) AS LISTAUTOID,
           S.CODEID || '|' || SUM(NVL(T.SECQTTY,0))|| '|' || SUM(NVL(T.AP_SERCURITIES,0))|| '|' || SUM(NVL(T.HOLDFORSELL,0)) || '|' || MAX(T.SECPRICE)|| '|' ||SUM(NVL(T.SECVALUE,0))|| '|' ||T.TRADINGACCOUNT  DETAIL,
           'ONLINE' PLACE
    FROM ETFRESULT_TEMP4WEB T,SBSECURITIES S WHERE S.SYMBOL = T.SERCURITIES
    GROUP BY T.FILEID,T.FUNDCODEID,T.TRADINGID,T.AP,T.TYPE,T.SERCURITIES,S.CODEID,T.TRADINGACCOUNT
  ) C
  GROUP BY C.FILEID,C.CUSTODYCD,C.FUNDCODEID,C.TRADINGID,C.AP,C.TYPE,C.TRANSDATE,C.CLEARDATE ) H,
  CFMAST CF, AFMAST AF
WHERE  H.CUSTODYCD = CF.CUSTODYCD AND CF.CUSTID = AF.CUSTID AND H.LISTAUTOID IS NOT NULL
/
