SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_MEMBER_PHONE
(FILTERCD, VALUE, VALUECD, DISPLAY, EN_DISPLAY, 
 DESCRIPTION)
AS 
SELECT M.AUTOID FILTERCD, N.AUTOID VALUE, N.AUTOID VALUECD, N.EXTRAVAL  DISPLAY,
N.EXTRAVAL  EN_DISPLAY, N.EXTRAVAL DESCRIPTION
from FAMEMBERS M, (select * from FAMEMBERSEXTRA where  Extracd = 'I')N
where  M.AUTOID = N.MEMBERID
/
