SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_ODMAST_ALL
(ORDERID, CODEID, SYMBOL, CUSTID, AFACCTNO, 
 DDACCTNO, SEACCTNO, CUSTODYCD, TXNUM, TXDATE, 
 TIMETYPE, EXECTYPE, NORK, MATCHTYPE, VIA, 
 CLEARDAY, CLEARDATE, ORSTATUS, PRICETYPE, ORDERPRICE, 
 ORDERQTTY, EXECQTTY, EXECAMT, FEEAMT, FEEACR, 
 DELTD, TLID, LASTCHANGE, ACTYPE, GRPORDER, 
 REMAINQTTY, TAXSELLAMT, APRVTIME, APRVTLID, CANCELSTATUS, 
 REFORDERID, FOACCTNO, TXTIME, CONTRAFIRM, CLIENTID, 
 EXCFEEAMT, EXCFEEREFID, TAXRATE, NAV, MEMBER, 
 AUTHORIZED, IDENTITY, TAXAMT, NETAMOUNT, ISHOLD, 
 TRANSACTIONTYPE, AP, CITAD, ODTYPE, TRADE_DATE)
AS 
select "ORDERID","CODEID","SYMBOL","CUSTID","AFACCTNO","DDACCTNO","SEACCTNO","CUSTODYCD","TXNUM","TXDATE","TIMETYPE","EXECTYPE","NORK","MATCHTYPE","VIA","CLEARDAY","CLEARDATE","ORSTATUS","PRICETYPE","ORDERPRICE","ORDERQTTY","EXECQTTY","EXECAMT","FEEAMT","FEEACR","DELTD","TLID","LASTCHANGE","ACTYPE","GRPORDER","REMAINQTTY","TAXSELLAMT","APRVTIME","APRVTLID","CANCELSTATUS","REFORDERID","FOACCTNO","TXTIME","CONTRAFIRM","CLIENTID","EXCFEEAMT","EXCFEEREFID","TAXRATE","NAV","MEMBER","AUTHORIZED","IDENTITY","TAXAMT","NETAMOUNT","ISHOLD","TRANSACTIONTYPE","AP","CITAD","ODTYPE","TRADE_DATE" from odmast
union all
select "ORDERID","CODEID","SYMBOL","CUSTID","AFACCTNO","DDACCTNO","SEACCTNO","CUSTODYCD","TXNUM","TXDATE","TIMETYPE","EXECTYPE","NORK","MATCHTYPE","VIA","CLEARDAY","CLEARDATE","ORSTATUS","PRICETYPE","ORDERPRICE","ORDERQTTY","EXECQTTY","EXECAMT","FEEAMT","FEEACR","DELTD","TLID","LASTCHANGE","ACTYPE","GRPORDER","REMAINQTTY","TAXSELLAMT","APRVTIME","APRVTLID","CANCELSTATUS","REFORDERID","FOACCTNO","TXTIME","CONTRAFIRM","CLIENTID","EXCFEEAMT","EXCFEEREFID","TAXRATE","NAV","MEMBER","AUTHORIZED","IDENTITY","TAXAMT","NETAMOUNT","ISHOLD","TRANSACTIONTYPE","AP","CITAD","ODTYPE","TRADE_DATE" from odmasthist
/
