SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_OD6002
(ORD, TYPE_NAME, TYPE, CDVAL)
AS 
(
SELECT 'A' AS ORD, 'Tín phiếu' AS TYPE_NAME, 'SECTYPE' AS TYPE, NVL((SELECT CDVAL FROM ALLCODE WHERE CDCONTENT='Tín phiếu' AND CDNAME='SECTYPE' AND CDTYPE='SA'),999) AS CDVAL FROM DUAL
UNION ALL
SELECT 'B' AS ORD, 'Trái phiếu' AS TYPE_NAME, 'SECTYPE' AS TYPE, NVL((SELECT CDVAL FROM ALLCODE WHERE CDCONTENT='Trái phiếu' AND CDNAME='SECTYPE' AND CDTYPE='SA'),999) AS CDVAL FROM DUAL
UNION ALL
SELECT 'C' AS ORD, 'Cổ phiếu' AS TYPE_NAME, 'SECTYPE' AS TYPE, NVL((SELECT CDVAL FROM ALLCODE WHERE CDCONTENT='Cổ phiếu thường' AND CDNAME='SECTYPE' AND CDTYPE='SA'),999) AS CDVAL FROM DUAL
UNION ALL
SELECT 'D' AS ORD, 'Chứng chỉ quỹ' AS TYPE_NAME, 'SECTYPE' AS TYPE, NVL((SELECT CDVAL FROM ALLCODE WHERE CDCONTENT='Chứng chỉ quỹ' AND CDNAME='SECTYPE' AND CDTYPE='SA'),999) AS CDVAL FROM DUAL
UNION ALL
SELECT 'E' AS ORD, 'Các loại chứng khoán khác' AS TYPE_NAME, 'SECTYPE' AS TYPE, NVL((SELECT CDVAL FROM ALLCODE WHERE CDCONTENT='Các loại chứng khoán khác' AND CDNAME='SECTYPE' AND CDTYPE='SA'),999) AS CDVAL FROM DUAL
UNION ALL
SELECT 'F' AS ORD, 'Chứng chỉ tiền gửi, tiền mặt' AS TYPE_NAME, 'SECTYPE' AS TYPE, NVL((SELECT CDVAL FROM ALLCODE WHERE CDCONTENT='Chứng chỉ tiền gửi, tiền mặt' AND CDNAME='SECTYPE' AND CDTYPE='SA'),999) AS CDVAL FROM DUAL
UNION ALL
SELECT 'B1' AS ORD, 'Trái phiếu Chính phủ' AS TYPE_NAME, 'BONDTYPE' AS TYPE, NVL((SELECT CDVAL FROM ALLCODE WHERE CDCONTENT='Trái phiếu chính phủ' AND CDNAME='BONDTYPE' AND CDTYPE='SA'),999) AS CDVAL FROM DUAL
UNION ALL
SELECT 'B2' AS ORD, 'Trái phiếu chính quyền địa phương' AS TYPE_NAME, 'BONDTYPE' AS TYPE, NVL((SELECT CDVAL FROM ALLCODE WHERE CDCONTENT='Trái phiếu chính quyền' AND CDNAME='BONDTYPE' AND CDTYPE='SA'),999) AS CDVAL FROM DUAL
UNION ALL
SELECT 'B3' AS ORD, 'Trái phiếu doanh nghiệp' AS TYPE_NAME, 'BONDTYPE' AS TYPE, NVL((SELECT CDVAL FROM ALLCODE WHERE CDCONTENT='Trái phiếu doanh nghiệp' AND CDNAME='BONDTYPE' AND CDTYPE='SA'),999) AS CDVAL FROM DUAL
UNION ALL
SELECT 'C1' AS ORD, 'Cổ phiếu niêm yết' AS TYPE_NAME, 'BONDTYPE' AS TYPE, NVL((SELECT CDVAL FROM ALLCODE WHERE CDCONTENT='Cổ phiếu niêm yết' AND CDNAME='BONDTYPE' AND CDTYPE='SA'),999) AS CDVAL FROM DUAL
UNION ALL
SELECT 'C2' AS ORD, 'Cổ phiếu công ty đại chúng đăng ký giao dịch (UPCOM)' AS TYPE_NAME, 'BONDTYPE' AS TYPE, NVL((SELECT CDVAL FROM ALLCODE WHERE CDCONTENT='Cổ phiếu công ty đại chúng đăng ký giao dịch (UPCOM)' AND CDNAME='BONDTYPE' AND CDTYPE='SA'),999) AS CDVAL FROM DUAL
UNION ALL
SELECT 'C3' AS ORD, 'Giá trị vốn góp mua cổ phần, đơn vị quỹ thành viên' AS TYPE_NAME, 'BONDTYPE' AS TYPE, NVL((SELECT CDVAL FROM ALLCODE WHERE CDCONTENT='Giá trị vốn góp mua cổ phần, đơn vị quỹ thành viên' AND CDNAME='BONDTYPE' AND CDTYPE='SA'),999) AS CDVAL FROM DUAL
)
/
