SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_RE0387
(REROLE, REACCTNO, REREVIEWTERMID, TERMNAME, FRDATE, 
 TODATE, NCFEE, NOTE, TLNAME, AMT, 
 FEEAMT, AVGFEEAMT, AVGNEWFEE, CURSALARY, BASICSALARY, 
 ADDNEW, ADDNEW2, NEWSALARY, FULLNAME, CUSTODYCD)
AS 
select REROLE, REACCTNO, REREVIEWTERMID, TERMNAME, FRDATE, TODATE, NCFEE, NOTE,
TLNAME, AMT, FEEAMT, AVGFEEAMT, AVGNEWFEE, CURSALARY, BASICSALARY, ADDNEW,
ADDNEW2, NEWSALARY, FULLNAME, CUSTODYCD
from review0387
where 0=0
/
