SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_STRADE_CA_RIGHTOFF_3384_DEL_N
(ABC, AUTOID, CUSTODYCD, FULLNAME, PHONE, 
 AFACCTNO, ACCTNO, CAMASTID, SYMBOL, CODEID, 
 TRADE, MAXBALANCE, BALANCE, PBALANCE, QTTY, 
 MAXQTTY, AVLQTTY, SUQTTY, SUAAMT, AAMT, 
 INBALANCE, OUTBALANCE, OPTCODEID, OPTSYMBOL, ISCOREBANK, 
 COREBANK, STATUS, SEACCTNO, OPTSEACCTNO, PARVALUE, 
 REPORTDATE, ACTIONDATE, EXPRICE, EN_DESCRIPTION, DESCRIPTION, 
 CATYPE, CUSTNAME, IDCODE, IDPLACE, IDDATE, 
 ADDRESS, ISSNAME, DUEDATE, BALDEFOVD, BANKACCTNO, 
 BANKNAME, SYMBOL_ORG, ISINCODE, CAREBY, RIGHTOFFRATE, 
 MCUSTODYCD, DELTD)
AS 
(
SELECT
    0 ABC,-- Khong dung de mac dinh la 0
    SC.autoid  ,CF.CUSTODYCD, CF.FULLNAME,CF.MOBILESMS PHONE, SC.AFACCTNO,DD.ACCTNO,
    SUBSTR(CA.CAMASTID,1,4) || '.' || SUBSTR(CA.CAMASTID,5,6) || '.' || SUBSTR(CA.CAMASTID,11,6) CAMASTID,
    SYM.SYMBOL, CA.TOCODEID CODEID, SC.TRADE,SC.balance + SC.pbalance + SC.OUTBALANCE MAXBALANCE, SC.balance + SC.OUTBALANCE balance, SC.PBALANCE - SC.QTTYCANCEL PBALANCE, SC.PQTTY QTTY, SC.PQTTY + SC.QTTY MAXQTTY, SC.PQTTY AVLQTTY, SC.QTTY SUQTTY,
    CA.EXPRICE*SC.QTTY SUAAMT, SC.AAMT AAMT, SC.INBALANCE,SC.OUTBALANCE, CA.OPTCODEID, OPTSYM.SYMBOL OPTSYMBOL,
    (CASE WHEN DD.COREBANK ='Y' THEN 1 ELSE 0 END) ISCOREBANK, ( CASE WHEN DD.COREBANK ='Y' THEN 'Yes' ELSE 'No' END) COREBANK,
    --A1.CDCONTENT
    SC.STATUS,
    SC.AFACCTNO ||(CASE WHEN CA.ISWFT='Y' THEN (SELECT CODEID FROM SBSECURITIES WHERE REFCODEID =SYM.CODEID ) ELSE CA.TOCODEID END) SEACCTNO, SC.AFACCTNO || CA.OPTCODEID OPTSEACCTNO,
    SYM.PARVALUE PARVALUE, CA.REPORTDATE REPORTDATE,-- PhuongHT sua loi lay nham ngay reportdate thanh duedate
    CA.ACTIONDATE, CA.EXPRICE,CA.description EN_DESCRIPTION,CA.DESCRIPTION,
    --A2.CDCONTENT
    CA.CATYPE, CF.FULLNAME CUSTNAME, (case when cf.country = '234' then cf.idcode else cf.tradingcode end) IDCODE, CF.IDPLACE,
    (case when cf.country = '234' then cf.iddate else cf.tradingcodedt end) IDDATE,
    CF.ADDRESS,iss.fullname issname,CA.DUEDATE,
    --fn_getBalRightoff(DD.AFACCTNO) BALDEFOVD, Khong dung --> de mac dinh la 0
    0 BALDEFOVD,
    AF.BANKACCTNO, AF.BANKNAME, sym_org.symbol SYMBOL_ORG, CA.isincode, cf.careby,
    CA.RIGHTOFFRATE,
    CF.MCUSTODYCD,
    ca.deltd
FROM CFMAST CF, AFMAST AF, DDMAST DD, CAMAST CA, CASCHD SC, SBSECURITIES SYM, SBSECURITIES OPTSYM,
SBSECURITIES SYM_ORG, ISSUERS ISS --,  ALLCODE A1,  ALLCODE A2
WHERE CF.CUSTID=AF.CUSTID AND AF.ACCTNO=DD.AFACCTNO
AND DD.AFACCTNO=SC.AFACCTNO AND SC.CAMASTID=CA.CAMASTID
AND NVL(CA.TOCODEID,CA.CODEID) = SYM.CODEID AND CA.OPTCODEID = OPTSYM.CODEID
AND SYM_ORG.CODEID=CA.CODEID AND ISS.ISSUERID = SYM.ISSUERID
--AND A1.CDTYPE = 'CA' AND A1.CDNAME = 'CASTATUS'
--AND A2.CDTYPE = 'CA' AND A2.CDNAME = 'CATYPE'
--AND A1.CDVAL = SC.STATUS
--AND CA.CATYPE = A2.CDVAL
AND DD.ISDEFAULT ='Y' AND DD.STATUS <> 'C'
AND TO_DATE(CA.BEGINDATE,'DD/MM/YYYY') <= TO_DATE(GETCURRDATE,'DD/MM/YYYY')
AND CA.STATUS  IN( 'V','M')
AND SC.status IN( 'V','M')
AND SC.PBALANCE - SC.QTTYCANCEL > 0
AND SC.PQTTY > 0
AND CA.CATYPE='014')
/
