SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_SEMAST_CUSTODYCD
(CUSTODYCD, SYMBOL, TRADEPLACE, ACTYPE, ACCTNO, 
 CODEID, AFACCTNO, OPNDATE, CLSDATE, LASTDATE, 
 STATUS, PSTATUS, IRTIED, IRCD, COSTPRICE, 
 TRADE, MORTAGE, MARGIN, NETTING, STANDING, 
 WITHDRAW, DEPOSIT, LOAN, BLOCKED, RECEIVING, 
 TRANSFER, PREVQTTY, DCRQTTY, DCRAMT, DEPOFEEACR, 
 REPO, PENDING, TBALDEPO, CUSTID, COSTDT, 
 SECURED, ICCFCD, ICCFTIED, TBALDT, SENDDEPOSIT, 
 SENDPENDING, DDROUTQTTY, DDROUTAMT, DTOCLOSE, SDTOCLOSE, 
 QTTY_TRANSFER, LAST_CHANGE, DEALINTPAID, WTRADE, GRPORDAMT, 
 EMKQTTY, BLOCKWITHDRAW, BLOCKDTOCLOSE, HOLD)
AS 
select cf.custodycd, sb.symbol, sb.tradeplace, se."ACTYPE",se."ACCTNO",se."CODEID",se."AFACCTNO",se."OPNDATE",se."CLSDATE",se."LASTDATE",se."STATUS",se."PSTATUS",se."IRTIED",se."IRCD",se."COSTPRICE",se."TRADE",se."MORTAGE",se."MARGIN",se."NETTING",se."STANDING",se."WITHDRAW",se."DEPOSIT",se."LOAN",se."BLOCKED",se."RECEIVING",se."TRANSFER",se."PREVQTTY",se."DCRQTTY",se."DCRAMT",se."DEPOFEEACR",se."REPO",se."PENDING",se."TBALDEPO",se."CUSTID",se."COSTDT",se."SECURED",se."ICCFCD",se."ICCFTIED",se."TBALDT",se."SENDDEPOSIT",se."SENDPENDING",se."DDROUTQTTY",se."DDROUTAMT",se."DTOCLOSE",se."SDTOCLOSE",se."QTTY_TRANSFER",se."LAST_CHANGE",se."DEALINTPAID",se."WTRADE",se."GRPORDAMT",se."EMKQTTY",se."BLOCKWITHDRAW",se."BLOCKDTOCLOSE",se."HOLD"
from cfmast cf, afmast af, semast se, sbsecurities sb 
where cf.custid = af.custid and af.acctno = se.afacctno and se.codeid = sb.codeid
/
