SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_STSCHD_ALL
(AUTOID, DUETYPE, ORDERID, CODEID, SYMBOL, 
 CUSTID, AFACCTNO, DDACCTNO, SEACCTNO, CUSTODYCD, 
 TXDATE, CLEARDAY, CLEARCD, AMT, QTTY, 
 FEEAMT, VAT, STATUS, DELTD, CLEARDATE, 
 LASTCHANGE, ORGORDERID, PAIDFEEAMT, PAIDVAT, FVSTATUS)
AS 
select "AUTOID","DUETYPE","ORDERID","CODEID","SYMBOL","CUSTID","AFACCTNO","DDACCTNO","SEACCTNO","CUSTODYCD","TXDATE","CLEARDAY","CLEARCD","AMT","QTTY","FEEAMT","VAT","STATUS","DELTD","CLEARDATE","LASTCHANGE","ORGORDERID","PAIDFEEAMT","PAIDVAT","FVSTATUS" from stschd
where deltd <> 'Y'
union all
select "AUTOID","DUETYPE","ORDERID","CODEID","SYMBOL","CUSTID","AFACCTNO","DDACCTNO","SEACCTNO","CUSTODYCD","TXDATE","CLEARDAY","CLEARCD","AMT","QTTY","FEEAMT","VAT","STATUS","DELTD","CLEARDATE","LASTCHANGE","ORGORDERID","PAIDFEEAMT","PAIDVAT","FVSTATUS" from stschdhist
where deltd <> 'Y'
/
