SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_STRADE_SUBACCOUNT_INFO
(AFACCTNO, CUSTID, CUSTODYCD, SHORTNAME, FULLNAME, 
 EN_IDTYPE_DESC, IDTYPE_DESC, IDCODE, IDDATE, IDPLACE, 
 IDEXPIRED, ADDRESS, PHONE, MOBILE, FAX, 
 EMAIL)
AS 
SELECT DTL.ACCTNO AFACCTNO, MST.CUSTID, MST.CUSTODYCD, MST.SHORTNAME, MST.FULLNAME,
CD1.EN_CDCONTENT EN_IDTYPE_DESC, CD1.CDCONTENT IDTYPE_DESC, MST.IDCODE, MST.IDDATE, MST.IDPLACE, MST.IDEXPIRED,
MST.ADDRESS, MST.PHONE, MST.MOBILE, MST.FAX, MST.EMAIL
FROM AFMAST DTL, CFMAST MST, ALLCODE CD1
WHERE DTL.CUSTID=MST.CUSTID
AND CD1.CDTYPE='CF' AND CD1.CDNAME='IDTYPE' AND MST.IDTYPE=CD1.CDVAL
/
