SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_STRADE_FEE_ADV_PAYMENT
(INTRATE, MINVAL)
AS 
SELECT SUM(CASE WHEN VARNAME='AINTRATE' THEN TO_NUMBER(VARVALUE) ELSE 0 END) INTRATE,
SUM(CASE WHEN VARNAME='AMINBAL' THEN TO_NUMBER(VARVALUE) ELSE 0 END) MINVAL
FROM SYSVAR WHERE VARNAME='AINTRATE' OR VARNAME='AMINBAL'
/
