SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_STRADE_LISTOF_RIGHTOFF
(REQUESTID, RQSSTS, TXDATE, TXNUM, ERRNUM, 
 ERRMSG, CUSTODYCD, AFACCTNO, QTTY)
AS 
SELECT RQS.REQUESTID, RQS.STATUS RQSSTS, RQS.TXDATE, RQS.TXNUM, RQS.ERRNUM, RQS.ERRMSG,
RQS_CUST.CVALUE CUSTODYCD, RQS_AFACCTNO.CVALUE AFACCTNO, NVL(RQS_QTTY.NVALUE, 0) QTTY
FROM BORQSLOG RQS, BORQSLOGDTL RQS_CUST, BORQSLOGDTL RQS_QTTY, BORQSLOGDTL RQS_AFACCTNO
WHERE RQS.RQSTYP='CAR'
AND RQS.AUTOID=RQS_CUST.AUTOID AND RQS_CUST.VARNAME='CUSTODYCD'
AND RQS.AUTOID=RQS_AFACCTNO.AUTOID AND RQS_AFACCTNO.VARNAME='AFACCTNO'
AND RQS.AUTOID=RQS_QTTY.AUTOID AND RQS_QTTY.VARNAME='QTTY'
/
