SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_SEMAST_VSDDEP_FEETERM
(SECTYPE, TRADEPLACE, AFACCTNO, ACCTNO, TBALDT, 
 AUTOID, FORP, FEEAMT, LOTDAY, LOTVAL, 
 ROUNDTYP, SEBAL, ODRNUM)
AS 
SELECT SB.SECTYPE, SB.TRADEPLACE,SE.AFACCTNO, SE.ACCTNO, SE.TBALDT,  1 AUTOID, 'F' FORP,
(CASE WHEN sb.issedepofee = 'Y' THEN
      (CASE WHEN SB.SECTYPE = '111' OR DECODE(SB.SECTYPE,'001','111','002','111','007','111','008','111','003','222','006','222') = '111' THEN
            (CASE WHEN SB.TRADEPLACE = '005' THEN (SELECT TO_NUMBER(VARVALUE) FROM SYSVAR WHERE GRNAME = 'DEFINED' AND VARNAME = 'FEEVSDUC_CP')
                  WHEN SB.TRADEPLACE IN ('001', '002', '003') THEN (SELECT TO_NUMBER(VARVALUE) FROM SYSVAR WHERE GRNAME = 'DEFINED' AND VARNAME = 'FEEVSD_CP')
                  WHEN SB.TRADEPLACE = '006' THEN
                       (CASE WHEN REF.TRADEPLACE = '005' THEN (SELECT TO_NUMBER(VARVALUE) FROM SYSVAR WHERE GRNAME = 'DEFINED' AND VARNAME = 'FEEVSDUC_CP')
                             WHEN REF.TRADEPLACE IN ('001', '002') THEN (SELECT TO_NUMBER(VARVALUE) FROM SYSVAR WHERE GRNAME = 'DEFINED' AND VARNAME = 'FEEVSD_CP')
                             WHEN REF.TRADEPLACE = '099' THEN (SELECT TO_NUMBER(VARVALUE) FROM SYSVAR WHERE GRNAME = 'DEFINED' AND VARNAME = 'FEEVSD_TPRL')
                        ELSE 0 END)
                  WHEN SB.TRADEPLACE = '099' THEN (SELECT TO_NUMBER(VARVALUE) FROM SYSVAR WHERE GRNAME = 'DEFINED' AND VARNAME = 'FEEVSD_TPRL')
             ELSE 0 END)
            WHEN SB.SECTYPE = '222' OR DECODE(SB.SECTYPE,'001','111','002','111','007','111','008','111','003','222','006','222') = '222' THEN
                (CASE WHEN SB.TRADEPLACE = '099' THEN (SELECT TO_NUMBER(VARVALUE) FROM SYSVAR WHERE GRNAME = 'DEFINED' AND VARNAME = 'FEEVSD_TPRL')
                    ELSE (SELECT TO_NUMBER(VARVALUE) FROM SYSVAR WHERE GRNAME = 'DEFINED' AND VARNAME = 'FEEVSD_TP')
                    END)
            WHEN SB.SECTYPE = '011' THEN (SELECT TO_NUMBER(VARVALUE) FROM SYSVAR WHERE GRNAME = 'DEFINED' AND VARNAME = 'FEEVSD_CW')
            WHEN SB.SECTYPE = '012' THEN (SELECT TO_NUMBER(VARVALUE) FROM SYSVAR WHERE GRNAME = 'DEFINED' AND VARNAME = 'FEEVSD_TNP')
       ELSE 0 END)
ELSE 0 END) FEEAMT, 30 LOTDAY, 1 LOTVAL, 'U' ROUNDTYP,
(se.trade + se.margin + se.mortage + se.blocked + se.secured + se.repo + se.netting + se.dtoclose + se.withdraw+ se.emkqtty+ se.blockdtoclose + se.blockwithdraw + se.hold) SEBAL, 0 ODRNUM
FROM SBSECURITIES SB, SEMAST SE, AFMAST AF,CFMAST CF, SBSECURITIES REF
WHERE
(se.trade + se.margin + se.mortage + se.blocked + se.secured + se.repo + se.netting + se.dtoclose + se.withdraw + se.emkqtty+ se.blockdtoclose + se.blockwithdraw + se.hold)>0
AND SB.CODEID=SE.CODEID
AND SE.AFACCTNO=AF.ACCTNO
--AND AF.STATUS IN ('A','P','B')
AND CF.CUSTID=AF.CUSTID AND CF.CUSTATCOM='Y'
AND SB.REFCODEID = REF.CODEID(+)
/
