SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_SMSFEESCHD_ALL
(AUTOID, TXDATE, AFACCTNO, FRDATE, TODATE, 
 FEEAMT, VATAMT, PAIDFEEAMT, PAIDVATAMT, PAIDTXDATE, 
 PAIDTXNUM, DELTD, TXNUM, SMSTYPE)
AS 
SELECT "AUTOID","TXDATE","AFACCTNO","FRDATE","TODATE","FEEAMT","VATAMT","PAIDFEEAMT","PAIDVATAMT","PAIDTXDATE","PAIDTXNUM","DELTD","TXNUM","SMSTYPE" FROM SMSFEESCHD UNION ALL SELECT "AUTOID","TXDATE","AFACCTNO","FRDATE","TODATE","FEEAMT","VATAMT","PAIDFEEAMT","PAIDVATAMT","PAIDTXDATE","PAIDTXNUM","DELTD","TXNUM","SMSTYPE" FROM SMSFEESCHDHIST
/
