SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_TLLOG_ALL
(AUTOID, TXNUM, TXDATE, TXTIME, BRID, 
 TLID, OFFID, OVRRQS, CHID, CHKID, 
 TLTXCD, IBT, BRID2, TLID2, CCYUSAGE, 
 OFF_LINE, DELTD, BRDATE, BUSDATE, TXDESC, 
 IPADDRESS, WSNAME, TXSTATUS, MSGSTS, OVRSTS, 
 BATCHNAME, MSGAMT, MSGACCT, CHKTIME, OFFTIME, 
 CAREBYGRP, REFTXNUM, NAMENV, CFCUSTODYCD, CREATEDT, 
 CFFULLNAME, PTXSTATUS)
AS 
select "AUTOID","TXNUM","TXDATE","TXTIME","BRID","TLID","OFFID","OVRRQS","CHID","CHKID","TLTXCD","IBT","BRID2","TLID2","CCYUSAGE","OFF_LINE","DELTD","BRDATE","BUSDATE","TXDESC","IPADDRESS","WSNAME","TXSTATUS","MSGSTS","OVRSTS","BATCHNAME","MSGAMT","MSGACCT","CHKTIME","OFFTIME","CAREBYGRP","REFTXNUM","NAMENV","CFCUSTODYCD","CREATEDT","CFFULLNAME","PTXSTATUS" from tllog where deltd <> 'Y' union all select "AUTOID","TXNUM","TXDATE","TXTIME","BRID","TLID","OFFID","OVRRQS","CHID","CHKID","TLTXCD","IBT","BRID2","TLID2","CCYUSAGE","OFF_LINE","DELTD","BRDATE","BUSDATE","TXDESC","IPADDRESS","WSNAME","TXSTATUS","MSGSTS","OVRSTS","BATCHNAME","MSGAMT","MSGACCT","CHKTIME","OFFTIME","CAREBYGRP","REFTXNUM","NAMENV","CFCUSTODYCD","CREATEDT","CFFULLNAME","PTXSTATUS" from tllogall where deltd <> 'Y'
/
