SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('ISSUES_TX','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('ISSUES_TX', 'Quản lý đợt phát hành trái phiếu', 'Bond issue management ', 'SELECT ISS.AUTOID, ISS.ISSUERID, ISR.SHORTNAME, ISR.FULLNAME, ISS.ISSUECODE, ISS.VALUEOFISSUE,
ISS.ISSUEDATE, A1.<@CDCONTENT> TYPERATE, LTVRATE, MAXLTVRATE, WARNINGLTVRATE,(CASE WHEN ISS.STATUS IN (''P'') THEN ''Y'' ELSE ''N'' END) APRALLOW,
LB.LISTBONDSYMBOL
FROM ISSUES ISS JOIN ISSUERS ISR ON ISS.ISSUERID = ISR.ISSUERID
                JOIN ALLCODE A1 ON A1.CDTYPE = ''CB'' AND A1.CDNAME = ''TYPERATE'' AND A1.CDUSER = ''Y'' AND A1.CDVAL = ISS.TYPERATE
                LEFT JOIN (
                        SELECT ISS.AUTOID, ISS.ISSUECODE, LISTAGG(BONDSYMBOL,'', NULL) WITHIN GROUP(ORDER BY ISSUESID ) LISTBONDSYMBOL
                        FROM BONDISSUE BI, ISSUES ISS
                        WHERE BI.ISSUESID = ISS.AUTOID
                        GROUP BY ISS.AUTOID, ISS.ISSUECODE
                     ) LB ON ISS.AUTOID = LB.AUTOID', 'ISSUES', NULL, 'ISS.AUTOID DESC', NULL, NULL, 5000, 'Y', 30, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;