SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('TD0002','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('TD0002', 'Trang thai so du gui ho tro lai suat', 'Interest supported account status', 'SELECT mst.actype, A3.CDCONTENT DESC_SCHDTYPE, MST.ACCTNO, MST.AFACCTNO, CF.FULLNAME,
    MST.ORGAMT, MST.FRDATE,(SELECT min(sbdate) FROM SBCLDR WHERE CLDRTYPE = ''000''
                                AND SBDATE >= MST.TODATE AND HOLIDAY = ''N'') TODATE,
    MST.BALANCE, MST.INTPAID,
    FN_TDMASTINTRATIO(MST.ACCTNO,TO_DATE(SYSVAR.VARVALUE,''DD/MM/YYYY''),MST.BALANCE) INTAVLAMT,
    MST.INTPAID+
    FN_TDMASTINTRATIO(MST.ACCTNO,TO_DATE(SYSVAR.VARVALUE,''DD/MM/YYYY''),MST.BALANCE) total_INT,
    MST.MORTGAGE
FROM TDMAST MST, AFMAST AF, CFMAST CF, ALLCODE A3, SYSVAR
WHERE MST.AFACCTNO=AF.ACCTNO AND AF.CUSTID=CF.CUSTID AND MST.STATUS in (''N'',''A'')
AND A3.CDTYPE=''TD'' AND A3.CDNAME=''SCHDTYPE'' AND MST.SCHDTYPE=A3.CDVAL
AND SYSVAR.VARNAME= ''CURRDATE''
AND MST.BALANCE > 0
AND CF.CAREBY IN (SELECT TLGRP.GRPID FROM TLGRPUSERS TLGRP WHERE TLID = ''<$TELLERID>'')
', 'TDMAST', 'frmTDMAST', '', '', 0, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;