SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('UNHOLDORDERT','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('UNHOLDORDERT', 'Unhold số tiền phong tỏa lệnh mua thường', 'Unhold  buy order', 'SELECT A1.<@CDCONTENT> ASSETTYPE, DD.CUSTODYCD, CRB.OBJKEY REFTXNUM, OD.TRADE_DATE TRADEDATE, OD.CLEARDATE SETTLE_DATE, CF.CUSTID SECACCOUNT, DD.ACCTNO DDACCTNO, CF.FULLNAME CUSTNAME, OD.ORDERID, --STS.AUTOID,
    DD.REFCASAACCT REFCASAACCT, DD.BALANCE, DD.HOLDBALANCE, vmb.value MEMBERID, '''' BRNAME,'''' BRPHONE, CRB.CURRENCY CCYCD, CRB.TXAMT AMOUNT, '''' NOTE
FROM DDMAST DD, CFMAST CF, VW_CUSTODYCD_MEMBER vmb,
(SELECT * FROM CRBTXREQ WHERE REQCODE = ''HOLDOD'' AND STATUS = ''C'' AND UNHOLD = ''N'' AND OBJNAME = ''6690'') CRB,
(SELECT * FROM ODMAST) OD,
--(SELECT * FROM STSCHD_NETOFF WHERE ISHOLD = ''Y'' AND DELTD = ''N'' AND STATUS = ''P'') STS,
(SELECT * FROM SBSECURITIES WHERE BONDTYPE <> ''001'' AND TRADEPLACE NOT IN (''099'')) SB,
(SELECT * FROM SYSVAR WHERE VARNAME = ''DEALINGCUSTODYCD'') SYS,
(SELECT * FROM ALLCODE WHERE CDTYPE = ''OD'' AND CDNAME = ''ASSETTYPE'') A1
WHERE DD.ACCTNO = CRB.AFACCTNO
AND DD.CUSTODYCD = CF.CUSTODYCD
--AND TO_CHAR(STS.AUTOID) = CRB.REQTXNUM
and vmb.filtercd = dd.custodycd and vmb.value = od.member
AND OD.CODEID = SB.CODEID
AND OD.ORDERID = CRB.REQTXNUM
AND OD.CODEID = SB.CODEID
AND SUBSTR(CF.CUSTODYCD,0,4) NOT LIKE SYS.VARVALUE
AND (CASE WHEN SB.TRADEPLACE = ''099'' THEN ''TPRL'' ELSE ''CKNY'' END) = A1.CDVAL(+)
AND NOT EXISTS (
    SELECT F.CVALUE
    FROM TLLOG TL, TLLOGFLD F
    WHERE TL.TXNUM = F.TXNUM
    AND TL.TXDATE = F.TXDATE
    AND TL.TLTXCD = ''6623''
    AND F.FLDCD = ''95''
    AND TL.TXSTATUS IN (''1'', ''4'')
    --AND F.CVALUE = TO_CHAR(STS.AUTOID)
    AND F.CVALUE = OD.ORDERID
)', 'UNHOLDORDERT', '', '', '6623', NULL, 5000, 'N', 30, 'NNNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;