SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('FEEMASTER','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('FEEMASTER', 'Biểu phí', 'Fee scheme', 'SELECT MST.FEECD, MST.FEENAME, A0.<@CDCONTENT> FORP, A1.<@CDCONTENT> STATUS,
   MST.FEEAMT, MST.FEERATE, MST.MINVAL, MST.MAXVAL, MST.VATRATE, MST.FEEAMT*MST.VATRATE/100 RATE,
   A2.<@CDCONTENT> CCYCD, A3.<@CDCONTENT> FEETYPE, A4.<@CDCONTENT> SUBTYPE, MST.FEECODE,
   FN_GET_FEENAME(MST.REFCODE,MST.SUBTYPE) FEECSTD,
   MST.FEEAMTVAT
FROM FEEMASTER MST, ALLCODE A0, ALLCODE A1,ALLCODE A2, ALLCODE A3, ALLCODE A4
WHERE A0.CDTYPE=''SA'' AND A0.CDNAME=''FORP'' AND A0.CDVAL=MST.FORP
AND A1.CDTYPE=''SY'' AND A1.CDNAME=''YESNO'' AND A1.CDVAL=MST.STATUS
AND A2.CDTYPE=''FA'' AND A2.CDNAME = ''CCYCD'' AND A2.CDVAL=MST.CCYCD
AND A3.CDTYPE = ''CF'' AND A3.CDNAME = ''REFCODE'' AND A3.CDVAL=MST.REFCODE
AND A4.CDTYPE = ''SA'' AND A4.CDNAME = MST.REFCODE AND A4.CDVAL=MST.SUBTYPE', 'FEEMASTER', 'frmFEEMASTER', '', '', 0, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;