SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('NAV_INFO','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('NAV_INFO', 'Quản lý kết quả NAV đồng bộ từ FA', 'Management of  NAV sync from FA', 'SELECT MI.*, A1.<@CDCONTENT> CREQSTATUS, A2.<@CDCONTENT> CFTYPE, ''N'' APRALLOW,
    TO_CHAR(LASTCHANGE, ''DD/MM/RRRR HH24:MI:SS'') CLASTCHANGE
FROM NAV_INFO MI,
(SELECT * FROM ALLCODE WHERE CDNAME = ''SYNC_AITHER_STATUS'' AND CDTYPE = ''SA'') A1,
(SELECT * FROM ALLCODE WHERE CDNAME = ''SUPRVFUNDTYPE'' AND CDTYPE = ''SB'') A2
WHERE MI.REQSTATUS = A1.CDVAL(+)
AND MI.FTYPE = A2.CDVAL(+)', 'NAV_INFO', 'frmNAV_INFO', 'AUTOID DESC', '', 0, 5000, 'N', 1, 'YYYYYYYNNNN', 'Y', 'T', '', 'N', '');COMMIT;