SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SBACTIMST','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('SBACTIMST', 'Theo dõi công việc', 'Work status', 'SELECT SB.AUTOID,
       A1.CDCONTENT ACTIMSTTYP,
       A2.CDCONTENT PRIORITY,
       SB.RESOLUTION,
       A3.CDCONTENT COMPONENT,
       SB.LABELS,
       SB.TITLE,
       SB.TITLE_EN,
       SB.NOTES,
       SB.TXNUM,
       SB.TXDATE,
       SB.CREATEDT,
       SB.UPDATEDT,
       SB.RESOLVEDT,
       SB.DUEDT,
       SB.RESOLVETMPDT,
       A.CDCONTENT STATUS
  FROM SBACTIMST SB,
       ALLCODE   A,
       ALLCODE   A1,
       ALLCODE   A2,
       ALLCODE   A3
       WHERE SB.SBSTATUS = A.CDVAL AND A.CDTYPE = ''SB''
       AND A.CDNAME = ''SBSTATUS''
       AND SB.ACTIMSTTYP = A1.CDVAL AND A1.CDTYPE = ''SB''   AND A1.CDNAME = ''ACTIMSTTYP''   AND SB.PRIORITY = A2.CDVAL AND A2.CDTYPE = ''SB''   AND A2.CDNAME = ''SBACTIMST_PRIORITY''   AND SB.COMPONENT = A3.CDVAL AND A3.CDTYPE = ''SB''   AND A3.CDNAME = ''SBACTIMST_COMPONENT''   AND NVL(SB.DELTD, ''N''  ) <> ''Y''', 'SBACTIMST', 'frmSBACTIMST', 'AUTOID DESC', '', 0, 50, 'N', 1, 'YYYYYYYYYYN', 'Y', 'T', '', 'N', '');COMMIT;