SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3351','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CA3351', 'Tra cứu đợt thực hiện quyền chờ thực hiện', 'View corporate actions to execute', 'SELECT V.DESCRIPTION, TASKCD, PARVALUE, EXPARVALUE, REPORTDATE, ACTIONDATE, POSTINGDATE,
    AUTOID, CAMASTID, AFACCTNO, SYMBOL, CATYPE, V.STATUS, BALANCE, QTTY,
    (case when catypevalue in (''023'',''020'') then 0 else AQTTY end)  AQTTY, DUTYAMT,
    SEACCTNO, EXSEACCTNO, V.IDCODE, V.CUSTODYCD, ISCDCROUTAMT, V.FULLNAME, PRICEACCOUNTING,
    CATYPEVALUE, COSTPRICE, CODEID, ISINCODE, CF.CIFID
--FROM V_CA3351 V 
FROM v_ca3351_del_n V
left join CFMAST CF on CF.CUSTODYCD = V.CUSTODYCD 
WHERE (case when catypevalue in (''023'',''020'') then ISSE else ''N'' end) <> ''Y''', 'CAMAST', NULL, NULL, NULL, NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;