SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CF0053','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CF0053', 'DANH KH DANG KY CHUYEN KHOAN TIEN RA NGOAI', 'List of registering outward transfer ', '
SELECT   B.CUSTODYCD,
         BANKACC,
         BANKACNAME,
         BANKNAME,
         ACNIDCODE,
         ACNIDPLACE,
         CITYEF,
         CITYBANK,
         fEECD,
         A.BANKCODE, substr(B.custid,1,4) brid
  FROM   CFOTHERACC A, CFMAST B
 WHERE   TYPE = ''1'' AND A.CFCUSTID = B.CUSTID', 'AFMAST', NULL, NULL, NULL, NULL, 1000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;