SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CF0088AF','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CF0088AF', 'Tra cứu thông tin tiểu khoản', 'View sub-account for closing', 'select * from
(
SELECT CUSTODYCD, AFACCTNO, BALANCE, OUTSTANDING,
BLOCKED, WITHDRAW, DEPOSIT, CRINTACR, ODINTACR, CIWITHDRAWAL, TRADE_QTTY,
TRADE_LIMIT_QTTY, LOAN_QTTY, RS_QTTY, SS_QTTY, RM_AMT, SM_AMT, MRCRLIMITMAX,
MRCRLIMIT, T0AMT, CA_QTTY, CIDEPOFEEACR, DEPOFEEAMT, NB_CHK_QTTY, NS_CHK_QTTY,
EXTENDDAYS, DEPOAMT, WAIT_QTTY, SERETAIL_QTTY, STANDING, DF_QTTY, EMKAMT,
GROUPLEADER, TDAMT, DFBLOCKAMT, RPPTSTATUS, DPODAMT, MRODAMT, SMSFEEAMT, LNFEEEXT
FROM VW_AFMAST_FOR_CLOSE_ACCOUNT
union all
SELECT CUSTODYCD, CUSTODYCD || ''|ALL'' AFACCTNO, sum(BALANCE) BALANCE, sum(OUTSTANDING) OUTSTANDING,
SUM(BLOCKED) BLOCKED, sum(WITHDRAW) WITHDRAW, sum(DEPOSIT) DEPOSIT, sum(round(CRINTACR)) CRINTACR, sum(ODINTACR) ODINTACR, Sum(CIWITHDRAWAL) CIWITHDRAWAL, sum(TRADE_QTTY) TRADE_QTTY,
sum(TRADE_LIMIT_QTTY) TRADE_LIMIT_QTTY, sum(LOAN_QTTY) LOAN_QTTY, sum(RS_QTTY) RS_QTTY, sum(SS_QTTY) SS_QTTY, sum(RM_AMT) RM_AMT, sum(SM_AMT) SM_AMT, sum(MRCRLIMITMAX) MRCRLIMITMAX,
sum(MRCRLIMIT) MRCRLIMIT, sum(T0AMT) T0AMT, sum(CA_QTTY) CA_QTTY, sum(round(CIDEPOFEEACR)) CIDEPOFEEACR, sum(DEPOFEEAMT) DEPOFEEAMT, sum(NB_CHK_QTTY) NB_CHK_QTTY, sum(NS_CHK_QTTY) NS_CHK_QTTY,
max(EXTENDDAYS) EXTENDDAYS, sum(DEPOAMT) DEPOAMT, sum(WAIT_QTTY) WAIT_QTTY, sum(SERETAIL_QTTY) SERETAIL_QTTY, sum(STANDING) STANDING, sum(DF_QTTY) DF_QTTY, sum(EMKAMT) EMKAMT,
max(GROUPLEADER) GROUPLEADER, sum(TDAMT) TDAMT, sum(DFBLOCKAMT) DFBLOCKAMT, max(RPPTSTATUS) RPPTSTATUS,
SUM(DPODAMT) DPODAMT, SUM(MRODAMT) MRODAMT , SUM(SMSFEEAMT) SMSFEEAMT, sum(LNFEEEXT) LNFEEEXT
FROM VW_AFMAST_FOR_CLOSE_ACCOUNT
group by custodycd
) where 0=0', 'CFLINK', NULL, NULL, NULL, NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;