SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('ESCROW_TX','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('ESCROW_TX', 'Hợp đồng Escrow', 'Escrow contract', 'SELECT M.*, ASE.<@CDCONTENT> SESTATUS_DESC, ACI.<@CDCONTENT> DDSTATUS_DESC
FROM (
    SELECT E.*,  nvl(A1.CDCONTENT,E.STATUS) STATUS_DESC, NVL(CB.BANKNAME,'''') SBANKNAME, E.DDSTATUS||NVL(RQ.STATUS,''C'') CISTATUS
    FROM (SELECT MST.*, DECODE(MST.DDSTATUS,''B'',MST.HOLDREQID, ''A'',MST.UNHOLDREQID,MST.TRFREQID) BANKREQID
            FROM ESCROW MST
            WHERE MST.DELTD <> ''Y'' and status <> ''P''
        ) E
        LEFT JOIN
        (SELECT RQ.REQID,RQ.REQCODE, RQ.REQTXNUM,  (CASE WHEN RQ.STATUS IN (''P'',''C'',''R'') THEN RQ.STATUS ELSE ''A'' END) STATUS
            FROM VW_CRBTXREQ_ALL RQ
            WHERE REQCODE IN (''HOLD1102'',''UNHOLD1104'',''PAYMENT1106'') AND STATUS <> ''C''
        ) RQ ON E.BANKREQID =  RQ.REQTXNUM
        LEFT JOIN CRBBANKLIST CB ON E.SBANKID = CB.CITAD
        LEFT JOIN (SELECT * FROM ALLCODE WHERE CDNAME = ''ESCROW_STATUS'' AND CDTYPE = ''EA'') A1 on E.STATUS = A1.CDVAL
    ORDER BY E.CREATEDDT DESC
) M , (SELECT * FROM ALLCODE WHERE CDNAME=''SUBSTATUS'' AND CDTYPE =''EA'') ASE, (SELECT * FROM ALLCODE WHERE CDNAME=''SUBSTATUS'' AND CDTYPE =''EA'') ACI
WHERE M.SESTATUS = ASE.CDVAL
    AND M.CISTATUS = ACI.CDVAL', 'ESCROW_TX', 'frmESCROW', NULL, NULL, NULL, 5000, 'Y', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;