SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('RM6610','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('RM6610', 'Tra cứu các giao dịch phong toả bị lệch (6610)', 'View unmatched hold balance (6610)', 'SELECT CH.REFNO,CH.BANKCODE,CRB.BANKNAME,CF.CUSTODYCD,CF.FULLNAME,AF.ACCTNO AFACCTNO,
CH.BANKACCTNO,CH.HOLDAMOUNT,CH.BANKAMOUNT,CI.HOLDBALANCE,CG.TOTALCHOLD,CG.TOTALBHOLD
FROM CRBHOLDLIST CH,CRBDEFBANK CRB,AFMAST AF,CFMAST CF,CIMAST CI,
(
    SELECT BANKCODE,BANKACCTNO,SUM(HOLDAMOUNT) TOTALCHOLD,SUM(BANKAMOUNT) TOTALBHOLD
    FROM CRBHOLDLIST WHERE STATUS IN (''A'',''V'') GROUP BY BANKCODE,BANKACCTNO
) CG
WHERE CH.BANKCODE=AF.BANKNAME AND CH.BANKACCTNO=AF.BANKACCTNO
AND CH.BANKCODE=CRB.BANKCODE AND AF.CUSTID=CF.CUSTID
AND CI.AFACCTNO=AF.ACCTNO AND CH.BANKCODE=CG.BANKCODE
AND CH.BANKACCTNO=CG.BANKACCTNO AND CH.STATUS IN (''A'',''V'')
AND (CH.HOLDAMOUNT<>CH.BANKAMOUNT OR CG.TOTALCHOLD<>CG.TOTALBHOLD)', 'BANKINFO', '', '', '6610', 0, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;