SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('ICCFTYPESCHD','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('ICCFTYPESCHD', 'Quản lý lịch biểu phí lãi tiền gửi', 'ICCF schedule management', 'SELECT AUTOID,IC.ACTYPE, IC.ACNAME, CD6.CDCONTENT ICCFSTATUS, CD3.CDCONTENT RULETYPE, APP.EVENTNAME APPEVENTNAME,
CD0.CDCONTENT MONTHDAY, CD1.CDCONTENT YEARDAY, CD2.CDCONTENT PERIOD, PERIODDAY,
CD4.CDCONTENT ICTYPE, ICFLAT, CD5.CDCONTENT ICRATECD, ICRATEID, ICRATE, MINVAL, MAXVAL
FROM ICCFTYPESCHD IC,APPEVENTS APP, ALLCODE CD0, ALLCODE CD1, ALLCODE CD2, ALLCODE CD3, ALLCODE CD4, ALLCODE CD5, ALLCODE CD6
WHERE CD0.CDTYPE=''SA'' AND CD0.CDNAME=''MONTHDAY'' AND TRIM(CD0.CDVAL)=TRIM(IC.MONTHDAY)
    AND IC.EVENTCODE=APP.EVENTCODE
    AND CD1.CDTYPE=''SA'' AND CD1.CDNAME=''YEARDAY'' AND TRIM(CD1.CDVAL)=TRIM(IC.YEARDAY)
    AND CD2.CDTYPE=''SA'' AND CD2.CDNAME=''PERIOD'' AND TRIM(CD2.CDVAL)=TRIM(IC.PERIOD)
    AND CD3.CDTYPE=''SA'' AND CD3.CDNAME=''RULETYPE'' AND TRIM(CD3.CDVAL)=TRIM(IC.RULETYPE)
    AND CD4.CDTYPE=''SA'' AND CD4.CDNAME=''ICTYPE'' AND TRIM(CD4.CDVAL)=TRIM(IC.ICTYPE)
    AND CD5.CDTYPE=''SA'' AND CD5.CDNAME=''ICRATECD'' AND TRIM(CD5.CDVAL)=TRIM(IC.ICRATECD)
    AND CD6.CDTYPE=''SA'' AND CD6.CDNAME=''ICCFSTATUS'' AND TRIM(CD6.CDVAL)=TRIM(IC.ICCFSTATUS) AND IC.DELTD=''N''', 'ICCFTYPESCHD', 'frmICCFTYPESCHD', NULL, NULL, NULL, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;