SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CAMAST_RIGHTOFF','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CAMAST_RIGHTOFF', 'Quản lý thực hiện quyền', 'Coporate action management', '
SELECT SYM.SYMBOL,CAMAST.CAMASTID VALUE,CAMAST.AUTOID,SUBSTR(CAMAST.CAMASTID,1,4)||''.''||SUBSTR(CAMAST.CAMASTID,5,6)||''.''||SUBSTR(CAMAST.CAMASTID,11,6) CAMASTID,
CAMAST.CODEID, CAMAST.EXCODEID, A1.CDVAL TYPEID, A1.CDCONTENT CATYPE,REPORTDATE ,DUEDATE,ACTIONDATE ,BEGINDATE, EXPRICE, EXRATE, RIGHTOFFRATE, DEVIDENTRATE,OPTCODEID,
 DEVIDENTSHARES, SPLITRATE, INTERESTRATE,CAMAST.DESCRIPTION DESCRIPTION,CAMAST.DESCRIPTION CONTENTS, INTERESTPERIOD, A2.CDCONTENT STATUS, FRDATERETAIL, TODATERETAIL, TRFLIMIT,
 (case when CAMAST.CATYPE=''014'' then CAMAST.EXPRICE end) ROPRICE,
 (case when CAMAST.CATYPE=''011'' then CAMAST.EXPRICE end) TVPRICE,
(CASE WHEN EXRATE IS NOT NULL THEN EXRATE ELSE (CASE WHEN RIGHTOFFRATE IS NOT NULL
       THEN RIGHTOFFRATE ELSE (CASE WHEN DEVIDENTRATE IS NOT NULL THEN DEVIDENTRATE  ELSE
       (CASE WHEN SPLITRATE IS NOT NULL THEN SPLITRATE ELSE (CASE WHEN INTERESTRATE IS NOT NULL
       THEN INTERESTRATE ELSE
       (CASE WHEN DEVIDENTSHARES IS NOT NULL THEN DEVIDENTSHARES ELSE ''0'' END)END)END)END) END)END) RATE, PITRATE, A3.CDVAL PITRATEMETHOD_CD, A3.CDCONTENT PITRATEMETHOD,
       CAMAST.CATYPE CATYPEVAL,FRDATETRANSFER,TODATETRANSFER,DEVIDENTVALUE,(CASE WHEN CAMAST.STATUS IN (''P'') THEN ''Y'' ELSE ''N'' END) APRALLOW,
      PITRATESE,nvl(camast.tocodeid,camast.codeid) tocodeid,
 tosym.symbol TOSYMBOL, camast.isincode
 FROM (select * from camast order by autoid desc)CAMAST, SBSECURITIES SYM, ALLCODE A1, ALLCODE A2, ALLCODE A3,
 SBSECURITIES TOSYM
 WHERE CAMAST.CODEID=SYM.CODEID AND A1.CDTYPE = ''CA''
 AND A1.CDNAME = ''CATYPE'' AND A1.CDVAL=CATYPE
 and A3.CDTYPE=''CA'' AND A3.CDNAME=''PITRATEMETHOD'' AND A3.CDVAL=CAMAST.PITRATEMETHOD
 AND A2.CDTYPE = ''CA'' AND A2.CDNAME = ''CASTATUS''
 AND A2.CDVAL=CAMAST.STATUS AND CAMAST.DELTD =''N''
 and camast.catype=''014'' and camast.status in (''V'',''M'')
 and nvl(camast.tocodeid,camast.codeid)=tosym.codeid', 'CAMAST_RIGHTOFF', 'frmCAMAST', NULL, NULL, NULL, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;