SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3349','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CA3349', 'Danh sách khách hàng voting', 'Views voting results of customers', 'select CA.CAMASTID, CA.ISINCODE,CA.CATYPE,A1.<@CDCONTENT> CATYPEVALUE, CA.REPORTDATE, CA.CODEID, SB.SYMBOL,
VO.CUSTODYCD,CF.CIFID,CF.FULLNAME, VO.VOTECODE, CAT.VOTING, A2.<@CDCONTENT> OPINIONVALUE, VO.OPINION
from VOTINGDETAIL VO, CAMAST CA, ALLCODE A1, CFMAST CF, CAVOTING CAT, SBSECURITIES SB, ALLCODE A2
where VO.CAMASTID=CA.CAMASTID
and VO.CUSTODYCD=CF.CUSTODYCD
and VO.VOTECODE=CAT.VOTECODE
and VO.CAMASTID=CAT.CAMASTID
and CA.CODEID=SB.CODEID
and A1.CDNAME=''CATYPE'' and A1.CDTYPE=''CA''
and A1.CDVAL=CA.CATYPE
AND A2.CDNAME=''OPINIONVOTING'' AND A2.CDTYPE=''CA''
AND A2.CDVAL=VO.OPINION', 'CAMAST', NULL, NULL, NULL, 0, 5000, 'N', 1, 'NNNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;