SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CFSY01','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CFSY01', 'Danh sách chi tiết AF gán  LN & OD', 'Details aftype assign LN and OD', 'SELECT MST.*, A1.CDCONTENT  DESC_LOANTYPE FROM
(
  SELECT MST1.* FROM
  (
    SELECT * FROM
    (
        SELECT AF.ACTYPE AFTYPE, AF.TYPENAME AF_TYPENAME, LNT.ACTYPE, LNT.TYPENAME, LNT.LOANTYPE, ''LNTYPE'' OBJNAME
        FROM AFIDTYPE AFI, AFTYPE AF, LNTYPE LNT
        WHERE AFI.OBJNAME=''LN.LNTYPE''
              AND AFI.AFTYPE = AF.ACTYPE
              AND AFI.ACTYPE = LNT.ACTYPE
        UNION
        SELECT AF.ACTYPE AFTYPE, AF.TYPENAME AF_TYPENAME, LNT.ACTYPE, LNT.TYPENAME, LNT.LOANTYPE, ''LNTYPE'' OBJNAME
        FROM AFTYPE AF, LNTYPE LNT
        WHERE AF.LNTYPE = LNT.ACTYPE
        UNION
        SELECT AF.ACTYPE AFTYPE, AF.TYPENAME AF_TYPENAME, LNT.ACTYPE, LNT.TYPENAME, LNT.LOANTYPE, ''LNTYPE'' OBJNAME
        FROM AFTYPE AF, LNTYPE LNT
        WHERE AF.DPLNTYPE = LNT.ACTYPE
        UNION
        SELECT AF.ACTYPE AFTYPE, AF.TYPENAME AF_TYPENAME, LNT.ACTYPE, LNT.TYPENAME, LNT.LOANTYPE, ''LNTYPE'' OBJNAME
        FROM AFTYPE AF, LNTYPE LNT
        WHERE AF.T0LNTYPE = LNT.ACTYPE

    )
    UNION ALL
    SELECT * FROM
    (
        SELECT AF.ACTYPE AFTYPE, AF.TYPENAME AF_TYPENAME, ODT.ACTYPE, ODT.TYPENAME, '''' LOANTYPE, ''ODTYPE'' OBJNAME
        FROM AFIDTYPE AFI, AFTYPE AF, ODTYPE ODT
        WHERE AFI.OBJNAME=''OD.ODTYPE''
              AND AFI.AFTYPE = AF.ACTYPE
              AND AFI.ACTYPE = ODT.ACTYPE
    )
    UNION ALL
    SELECT * FROM 
    (
        SELECT AF.ACTYPE AFTYPE, AF.TYPENAME AF_TYPENAME, MRT.ACTYPE, MRT.TYPENAME, '''' LOANTYPE, ''MRTYPE'' OBJNAME
        FROM AFTYPE AF, MRTYPE MRT
        WHERE AF.MRTYPE = MRT.ACTYPE
    )
    UNION ALL
    SELECT * FROM 
    (
        SELECT AF.ACTYPE AFTYPE, AF.TYPENAME AF_TYPENAME, ADT.ACTYPE, ADT.TYPENAME, '''' LOANTYPE, ''ADTYPE'' OBJNAME
        FROM AFTYPE AF, ADTYPE ADT
        WHERE AF.ADTYPE = ADT.ACTYPE
    )
  ) MST1
) MST, (SELECT * FROM ALLCODE WHERE CDNAME =''LOANTYPE'' AND CDTYPE =''LN'') A1
WHERE MST.LOANTYPE = A1.CDVAL (+) AND 0=0', 'CFSY01', '', '', '', NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;