SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SE2247','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('SE2247', 'Tra cứu các tiểu khoản đang chờ gửi không đóng tài khoản (2247)', 'View wait send deposit (full transfer) (2247)', 'SELECT FN_GET_LOCATION(SUBSTR(A.AFACCTNO,1,4)) LOCATION, A.*,
       CASE WHEN A.RIGHTQTTY+A.RIGHTOFFQTTY+A.CAQTTYRECEIV+A.CAQTTYDB+A.CAAMTRECEIV >0 and A.TRADE > 0 THEN ''T''
            WHEN A.RIGHTQTTY+A.RIGHTOFFQTTY+A.CAQTTYRECEIV+A.CAQTTYDB+A.CAAMTRECEIV >0 and A.TRADE = 0 and A.BLOCKED > 0  THEN ''H'' ELSE ''N'' END ISTRFCA,
       CF.PCOD BUYRPCOD,
       NVL(D.BICCODE, ''XXAAXXAA'') || CASE WHEN CF.COUNTRY <> ''234'' THEN ''-CUSF''
                                          WHEN CF.COUNTRY = ''234'' THEN ''-CUSD''
                                          WHEN SUBSTR(A.REFCUSTODYCD,4,1) =''F'' THEN ''-CUSF''
                                          ELSE ''-CUSD'' END BUYRDAAS
FROM V_SE2247 A, CFMAST CF, DEPOSIT_MEMBER D
WHERE A.DESTTYPECD = ''001''
AND A.REFCUSTODYCD = CF.CUSTODYCD (+)
AND A.REFINWARD = D.DEPOSITID (+)
AND 0=0', 'SEMAST', '', '', '2247', NULL, 5000, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;