SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('AP0002','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('AP0002', 'Rút Kho Chứng Từ cặp 1405', 'Decrease Vault pair 1405', 'SELECT DOC.AUTOID, DOC.OPNDATE, DOC.CRPHYSAGREEID, CF.CUSTODYCD, CF.FULLNAME, CR.QTTY CRQTTY,
       DOC.REFNO, CR.NO CRPHYSAGREENO, DOC.CODEID, DOC.SYMBOL, DOC.QTTY
FROM DOCSTRANSFER DOC,CRPHYSAGREE CR, CFMAST CF
WHERE DOC.CRPHYSAGREEID = CR.CRPHYSAGREEID (+)
      AND DOC.CUSTID = CF.CUSTID
      AND DOC.STATUS = ''OPN''
      AND DOC.DELTD <> ''Y''
      AND NOT EXISTS (SELECT * FROM TLLOG TL WHERE TLTXCD =''1406'' AND MSGACCT = DOC.AUTOID  AND TXSTATUS = ''4'')', 'CRPHYSAGREE', NULL, 'OPNDATE', '1406', 0, 5000, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;