SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('DD0001','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('DD0001', 'Theo dõi nợ phí của KH', 'Manage customer charges', 'SELECT FE.FEEBIL, CF.CIFID PROFOLIOCD, CF.FULLNAME, FE.VATAMT VATAMOUNT,
    FE.FEEAMT FEEAMOUNT, FE.STATUS STATUSVAL, FE.TXDATE BOOKINGDATE,FE.FEECODE FEECODECSTD,
    DECODE(FE.CCYCD,''VND'',ROUND((NVL(FE.FEEAMT,0) + NVL(FE.VATAMT,0)),0),ROUND((NVL(FE.FEEAMT,0) + NVL(FE.VATAMT,0)),2)) FEEAMTVAT,
    FE.TRDESC DESCRIPTION,
    CASE WHEN FM.ROLES = ''AMC'' THEN FM.FULLNAME ELSE '''' END AMC,
    CASE WHEN FM1.ROLES = ''GCB'' THEN FM1.FULLNAME ELSE '''' END GCB,
    FE.CUSTODYCD, FE.CCYCD, FE.SUBTYPE SUBTYPEVAL, FE.FEETYPES FEETYPESVAL, CF.MCIFID, CF.MCUSTODYCD,
    LP.<@CDCONTENT> FEETYPES, CY.<@CDCONTENT> CURRENCY, ST.<@CDCONTENT> STATUS, CS.<@CDCONTENT> FEENAMECSTD, SB.<@CDCONTENT> SUBTYPE,
    A1.<@CDCONTENT> CCITADFEERT
FROM FAMEMBERS FM, FAMEMBERS FM1, 
(
    SELECT FE.FEETYPES, FE.SUBTYPE, FE.CUSTODYCD, FE.FEEAMT FEEAMT, FE.CCYCD,FE.FEEBIL, FE.TRDESC, FE.STATUS, FE.TXDATE, FE.FEECODE, NVL(FE.VATAMT,0) VATAMT
    FROM VW_FEETRAN_DD0001 FE
    WHERE FE.TYPE = ''F''
    AND FE.DELTD <> ''Y''
    ORDER BY FE.FEEBIL DESC
) FE,
(
    SELECT * FROM CFMAST 
    WHERE SUPEBANK = ''N'' 
    --AND STATUS NOT IN (''C'') 
) CF,
(SELECT * FROM ALLCODE WHERE CDTYPE = ''CF'' AND CDNAME = ''REFCODE'') LP,
(SELECT * FROM ALLCODE) SB,
(SELECT * FROM ALLCODE WHERE CDTYPE = ''FA'' AND CDNAME = ''CCYCD'') CY,
(SELECT * FROM ALLCODE WHERE CDTYPE = ''SA'' AND CDNAME = ''FEESTATUS'') ST,
(SELECT * FROM ALLCODE WHERE CDTYPE = ''SA'' AND CDNAME = ''FEECODES'') CS,
(SELECT * FROM ALLCODE WHERE CDTYPE = ''SY'' AND CDNAME = ''YESNO'') A1
WHERE FE.FEETYPES = LP.CDVAL(+)
AND FE.FEETYPES = SB.CDNAME 
AND FE.SUBTYPE = SB.CDVAL
AND FE.CUSTODYCD = CF.CUSTODYCD 
AND FE.CCYCD = CY.CDVAL(+)
AND FE.STATUS = ST.CDVAL(+)
AND FE.FEECODE = CS.CDVAL(+)
AND CF.AMCID = FM.AUTOID(+)
AND CF.GCBID = FM1.AUTOID(+)
AND CF.CITADFEERT = A1.CDVAL(+)', 'feetran', 'frmFEE', 'FEEBIL DESC', '1294', 0, 1000, 'N', 1, 'NNNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;