SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('RM6614','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('RM6614', 'Tra cứu điện lỗi', 'Look up error request', 'SELECT REQID, BANKACCT, C.AFACCTNO, TXAMT, NOTES, A.CDCONTENT STATUSTEXT,C.STATUS, RBANKACCOUNT, RBANKNAME, RBANKCITAD, RBANKACCNAME,
       ERRORDESC, C.PSTATUS, CURRENCY, DORC, FEEAMT, TAXAMT, FEECODE, FEETYPE ,D.CUSTODYCD ,C.AFACCTNO REFCASAACCT
FROM CRBTXREQ C, DDMAST D,
(SELECT * FROM ALLCODE WHERE CDNAME = ''RMSTATUS'' AND CDTYPE = ''CI'') A
WHERE C.STATUS = A.CDVAL(+)
AND C.STATUS NOT IN (''C'',''P'')
AND C.AFACCTNO = D.ACCTNO(+)', 'RM6614', NULL, NULL, '6614', NULL, 5000, 'N', 1, 'NNNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;