SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CF0029','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CF0029', 'Tra cứu số tài khoản cá nhân', 'Bank account management', 'SELECT CF.FULLNAME, CF.CUSTODYCD, AF.ACCTNO AFACCTNO,AF.BANKNAME, AF.BANKACCTNO, AF.AUTOTRF
FROM AFMAST AF, CFMAST CF
WHERE AF.CUSTID = CF.CUSTID
AND ALTERNATEACCT =''Y''
AND (SUBSTR(CF.CUSTID,1,4) = DECODE(''<$BRID>'', ''<$HO_BRID>'', SUBSTR(CF.CUSTID,1,4), ''<$BRID>'')
OR AF.CAREBY IN (SELECT TLGRP.GRPID FROM TLGRPUSERS TLGRP WHERE TLID = ''<$TELLERID>''))', 'ALTERNATEACCT', 'frmALTERNATEACCT', '', '', NULL, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;