SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('V_CRBTRFACCTSRC','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('V_CRBTRFACCTSRC', 'Quản lý tài khoản nguồn ngân hàng', 'Manage bank source account', 'SELECT SRC.AUTOID, SRC.BANKACCTNO, SRC.BANKACCTNAME BANKNAME, SRC.BANKCODE, SRC.BANKACCTNO ||'':''||SRC.BANKACCTNAME FILTERCD,SRC.BANKACCTNO VALUE,
SRC.BANKACCTNO VALUECD,SRC.BANKACCTNO ||'':''||SRC.BANKACCTNAME DISPLAY,
SRC.BANKACCTNO ||'':''||SRC.BANKACCTNAME EN_DISPLAY,SRC.BANKACCTNO ||'':''||SRC.BANKACCTNAME DESCRIPTION, SRC.BANKACCTNAME BANKACCTNAME
FROM
(SELECT MAX(AUTOID) AUTOID, REFBANK BANKCODE, REFACCTNO BANKACCTNO, REFACCTNAME BANKACCTNAME
    FROM CRBDEFACCT
    GROUP BY REFBANK, REFACCTNO, REFACCTNAME) SRC, AFMAST AF
WHERE SRC.BANKCODE=AF.BANKNAME
--AND AF.ACCTNO=''<$TAGFIELD>''
', 'CRBTRFACCTSRC', 'CRBTRFACCTSRC', '', '', 0, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;