SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('DD0002','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('DD0002', 'Theo dõi các loại thuế của KH', 'Manage customer taxes', 'SELECT DISTINCT Row_number() over(order by fee.autoid) NO, FEE.TXDATE POSTDATE, '' '' TYPETAX,
                FEE.DEDUCTEDPLACE PLACETAXVAL, A1.<@CDCONTENT> PLACETAX,CF.CUSTODYCD,CF.FULLNAME,
                FEE.VATAMT AMOUNT, A0.<@CDCONTENT> STATUS, FEE.STATUS STATUSVAL,FEE.PAIDDATE PAIDDATE, FEE.AUTOID AUTOID,
                case when fee.SUBTYPE is null then A2.<@CDCONTENT> else A3.<@CDCONTENT> END TAXTYPE,
                FEE.TXAMT
FROM VW_FEETRAN_ALL FEE, CFMAST CF, ALLCODE A0, ALLCODE A1, ALLCODE A2, ALLCODE A3
WHERE FEE.TYPE = ''T''
AND FEE.DELTD <> ''Y''
AND FEE.CUSTODYCD = CF.CUSTODYCD
AND A0.CDTYPE=''DD'' AND A0.CDNAME=''STATUS'' AND A0.CDVAL=FEE.STATUS
AND A1.CDTYPE=''SA'' AND A1.CDNAME=''DEDUCTEDPLACE'' AND A1.CDVAL = FEE.DEDUCTEDPLACE
AND A2.CDTYPE=''SA'' AND A2.CDNAME=''TAXTYPEDD'' AND A2.Cdval = ''PIT''
AND A3.CDTYPE=''SA'' AND A3.CDNAME=''TAXTYPEDD'' AND A3.Cdval = ''VAT''
AND FEE.VATAMT >0', 'taxtran', 'frmTAX', 'STATUSVAL', '1292', NULL, 5000, 'N', 1, 'NNNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;