SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SE0088','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('SE0088', 'Danh sách KH gửi hồ sơ chuyển khoản chứng khoán ra ngoài', 'List of customers transfer stock outward', 'SELECT sendoutid, CUSTODYCD, FULLNAME, IDCODE, IDDATE, IDPLACE, ADDRESS, MOBILESMS,
    TRADEPLACE, SYMBOL, TXDATE, TRADE, BLOCKED, TRADE_WFT, BLOCKED_WFT
FROM (SELECT tl.sendoutid, CF.CUSTODYCD, CF.FULLNAME, CF.IDCODE, CF.IDDATE, CF.IDPLACE, CF.ADDRESS, CF.MOBILESMS,
    A.CDCONTENT TRADEPLACE, sb.SYMBOL, tl.TXDATE,
    SUM(TL.TRADE) TRADE, SUM(TL.BLOCKED) BLOCKED, SUM(TL.TRADE_WFT) TRADE_WFT, SUM(TL.BLOCKED_WFT) BLOCKED_WFT
FROM SE2255_LOG TL, AFMAST AF, CFMAST CF ,
    (
        SELECT SB1.CODEID,
            (CASE WHEN SB1.REFCODEID IS NULL THEN SB1.SYMBOL ELSE SB2.SYMBOL END) SYMBOL,
            (CASE WHEN SB1.REFCODEID IS NULL THEN SB1.TRADEPLACE ELSE SB2.TRADEPLACE END) TRADEPLACE
        FROM SBSECURITIES SB1, SBSECURITIES SB2
        WHERE SB1.REFCODEID = SB2.CODEID(+)
    ) SB, ALLCODE A
WHERE TL.AFACCTNO = AF.ACCTNO AND AF.CUSTID = CF.CUSTID
    AND TL.DELTD <> ''Y'' AND A.CDTYPE = ''SE'' AND TL.codeid = SB.CODEID
    AND A.CDNAME = ''TRADEPLACE'' AND SB.TRADEPLACE = A.CDVAL
GROUP BY tl.TXDATE, CF.CUSTODYCD, sb.SYMBOL, CF.FULLNAME, CF.IDCODE, CF.IDDATE, CF.IDPLACE, CF.ADDRESS, CF.MOBILESMS,
A.CDCONTENT, tl.sendoutid ) WHERE 0=0', 'CFMAST', 'frmCFMAST', '', '', NULL, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;