SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CRPHYSAGREE_EX','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CRPHYSAGREE_EX', 'Quản lý thông tin hợp đồng đặt mua physical', 'Manage physical subscription agreement ', 'SELECT CRP.AUTOID,CRP.NO,CRP.EFFDATE,CRP.NAME,CRP.CUSTODYCD,CRP.CODEID,CRP.SYMBOL,CRP.ACCTNO,CRE.CQTTY,CRE.CVALUE,CRE.REQTTY,CRE.REVALUE,CRE.REMQTTY,CRE.REMVALUE,CRE.STATUS
FROM 
     (SELECT CR.AUTOID,CR.NO,CR.NAME,CR.CUSTODYCD,CR.CODEID,CR.ACCTNO,CR.QTTY,CR.EFFDATE,CR.EXPDATE, SB.SYMBOL
       FROM CRPHYSAGREE CR,SBSECURITIES SB 
       WHERE CR.CODEID=SB.CODEID) CRP, CRPHYSAGREE_EX CRE
WHERE CRP.AUTOID =CRE.CRPHYSAGREEID(+)', 'CRPHYSAGREE', NULL, NULL, NULL, 0, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;