SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('BACONTRACT_2232','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('BACONTRACT_2232', 'Quản lý hợp đồng', 'Contracts management', 'SELECT DISTINCT
MST.AUTOID, MST.ISSUESID, ISS.ISSUECODE, A1.<@CDCONTENT> CONTRACTTYPE, MST.CONTRACTNO, MST.CONTRACTDATE, MST.DESCRIPTION
FROM ISSUER_CONTRACTNO MST, ISSUES ISS, ALLCODE A1
WHERE   A1.CDTYPE = ''CB''
        AND A1.CDVAL = MST.CONTRACTTYPE
        AND A1.CDNAME = ''CONTRACTTYPE''
        AND ISS.AUTOID = MST.ISSUESID', 'ISSUER_CONTRACTNO', NULL, 'MST.CONTRACTDATE, MST.CONTRACTNO', NULL, NULL, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;