SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('OD0006','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('OD0006', 'Tra cứu nghĩa vụ thanh toán bù trừ', 'Settl. date', 'SELECT OD.SETLDATE SETLDATE,
    (SUMSELLODT-SUMBUYODT) NETAMT, SUMBUYODT SUMBUY, SUMSELLODT SUMSELL,
    (SUMSELLTPRL-SUMBUYTPRL) NETAMTTPRL, SUMBUYTPRL SUMBUYTPRL, SUMSELLTPRL SUMSELLTPRL,
    SUMBUYODG SUMBUYGBOND, SUMSELLODG SUMSELLGBOND,
    (SUMFEEBR + SUMTAXBR) SUMFEETAX
FROM (
    SELECT OD.SETLDATE,
            SUM(CASE WHEN OD.ODTYPE = ''ODT'' AND OD.EXECTYPEVAL =''NB'' AND SB.TRADEPLACE NOT IN (''099'') THEN OD.AMT ELSE 0 END) SUMBUYODT,
            SUM(CASE WHEN OD.ODTYPE = ''ODT'' AND OD.EXECTYPEVAL =''NS'' AND SB.TRADEPLACE NOT IN (''099'') THEN OD.AMT ELSE 0 END) SUMSELLODT,
            SUM(CASE WHEN OD.ODTYPE = ''ODT'' AND OD.EXECTYPEVAL =''NB'' AND SB.TRADEPLACE IN (''099'') THEN OD.AMT ELSE 0 END) SUMBUYTPRL,
            SUM(CASE WHEN OD.ODTYPE = ''ODT'' AND OD.EXECTYPEVAL =''NS'' AND SB.TRADEPLACE IN (''099'') THEN OD.AMT ELSE 0 END) SUMSELLTPRL,
            SUM(CASE WHEN OD.ODTYPE = ''ODG'' AND OD.EXECTYPEVAL =''NB'' AND SB.TRADEPLACE NOT IN (''099'') THEN OD.AMT ELSE 0 END) SUMBUYODG,
            SUM(CASE WHEN OD.ODTYPE = ''ODG'' AND OD.EXECTYPEVAL =''NS'' AND SB.TRADEPLACE NOT IN (''099'') THEN OD.AMT ELSE 0 END) SUMSELLODG,
            SUM(OD.FEE) SUMFEEBR,
            SUM(OD.TAX) SUMTAXBR
    FROM VW_ODMAST_IMPORT OD, SBSECURITIES SB
    WHERE OD.SYMBOL = SB.SYMBOL
    AND OD.STATUS = ''4''
    AND OD.ODTYPE <> ''SWE''
    GROUP BY OD.SETLDATE
)OD WHERE 0 = 0', 'OD0006', 'frmODMAST', 'SETLDATE DESC', '', NULL, 5000, 'N', 1, 'NNNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;