SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('RM0014','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('RM0014', 'Chờ duyệt 6639 tương lai', 'Pending 6639 order with future valuedate', 'SELECT L.*, DD.CACCTNO, A1.<@CDCONTENT> CTRANSFER, A2.<@CDCONTENT> CFEETYPE, A3.CDCONTENT CINSTRUCTION
FROM LOG_FUTURE6639 L, 
(
    SELECT DD.*,  DD.REFCASAACCT ||'' - ''|| DD.CCYCD || '' - '' || A.<@CDCONTENT> CACCTNO
    FROM DDMAST DD, 
    (SELECT * FROM ALLCODE WHERE CDNAME=''ACCOUNTTYPE'' AND CDTYPE = ''DD'') A
    WHERE DD.ACCOUNTTYPE = A.CDVAL
) DD,
(SELECT * FROM ALLCODE WHERE CDNAME=''TRANSTYPE'' AND CDTYPE = ''FA'') A1,
(SELECT * FROM ALLCODE WHERE CDNAME=''IOROFEE'' AND CDTYPE = ''SA'') A2,
(SELECT * FROM ALLCODE WHERE CDNAME=''CBTXTYPE'') A3
WHERE L.TRANSFER = A1.CDVAL(+)
AND L.FEETYPE = A2.CDVAL(+)
AND L.INSTRUCTION = A3.CDVAL(+)
AND L.ACCTNO = DD.ACCTNO
AND L.STATUS IN (''P'',''E'')', 'RM0014', 'frmRM0014', 'L.AUTOID DESC', '6638', NULL, 5000, 'N', 1, 'NNNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;