SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CRBTXREQHISTCITAD','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CRBTXREQHISTCITAD', 'Quản lý lịch sử thông tin điện gửi qua ngân hàng', 'Bank request management hist', 'SELECT * FROM (
    SELECT distinct R.REQID,R.OBJKEY TXNUM,R.TRFCODE,N.DESCRIPTION REQCODE,NVL(R.REQTXNUM,R.OBJKEY) REQTXNUM,
            CASE WHEN R.TRFCODE LIKE ''PAYMENTINTEREST%'' THEN NULL ELSE NVL(D.CUSTODYCD,CF.CUSTODYCD) END CUSTODYCD,R.TXDATE,
            R.BANKACCT,RBANKACCOUNT,RBANKNAME,
            R.CURRENCY CURRENCY,
            R.TXAMT AMOUNT, R.STATUS,A.<@CDCONTENT> STATUSTEXT,R.ERRORDESC, R.REFVAL,
            to_char(R.CREATEDATE,''dd/MM/yyyy hh24:mi:ss'')CREATEDATE,
            R.RBANKCITAD,R.FEEAMT,R.TAXAMT, a2.<@CDCONTENT> FEETYPE,R.FEECODE
    FROM CRBTXREQHIST R, CRBTRFCODE N, CFMAST CF, 
    (SELECT * FROM DDMAST WHERE STATUS <> ''C'') D,
    (SELECT * FROM ALLCODE WHERE CDNAME = ''RMSTATUS'' AND CDTYPE = ''CI'') A,  
    (SELECT * FROM ALLCODE WHERE CDNAME = ''IOROFEE'' AND CDTYPE = ''SA'') A2
    WHERE R.STATUS = A.CDVAL
    AND R.REQCODE = N.TRFCODE(+)
    AND R.BANKACCT= D.REFCASAACCT(+)
    AND R.AFACCTNO = CF.CIFID(+)
    AND R.FEETYPE=A2.CDVAL(+)
    and R.trfcode = ''OTRANSFER''
)
WHERE 0=0', 'CRBTXREQHISTCITAD', NULL, 'REQID DESC', NULL, NULL, 500, 'Y', 1, 'NNNNYYNNNNNY', 'Y', 'T', NULL, 'N', NULL);COMMIT;