SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CRPHYSAGREE_SELL','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CRPHYSAGREE_SELL', 'Quản lý thông tin hợp đồng ', 'Manage physical subscription agreement ', 'SELECT CR.*, (CR.QTTY-CR.REQTTY) TREMQTTY, 0 CHECKVAL
     , A0.EN_CDCONTENT STATUSCNT
     , A1.EN_CDCONTENT PAYSTATUSCNT
     , A2.EN_CDCONTENT BALANCESTATUSCNT
     , A3.EN_CDCONTENT REPOSSTATUSCNT
     , SB.PARVALUE, SB.INTERESTDATE
     , ISS.FULLNAME ISSUERNAME
     , CF.FULLNAME
FROM (select CR1.crphysagreeid, CR1.no, CR1.name, CR1.codeid, CR1.qtty, CR1.status, CR1.creatdate, CR1.effdate, CR1.acctno, CR1.clvalue, CR1.bankacctno, CR1.bankcode, CR1.description, CR1.pstatus,
            CR1.reqtty, CR1.symbol, CR1.paystatus, CR1.balancestatus, CR1.reposstatus, CR1.citad, CR1.issuerid, CR1.txdate, CR1.txnum,CR1.origional_no, CR1.rollid, CR1.bname, 
        CF.CUSTODYCD
    From CRPHYSAGREE CR1, CFMAST CF
    where CR1.deltd <>''Y''
    AND CR1.ACCTNO = CF.CUSTID) CR,
ISSUERS ISS, SBSECURITIES SB, ALLCODE A0, ALLCODE A1,ALLCODE A2,ALLCODE A3, CFMAST CF
WHERE CR.ISSUERID = ISS.ISSUERID
AND CR.CODEID = SB.CODEID
AND CF.CUSTODYCD = CR.CUSTODYCD
AND A0.CDVAL =CR.STATUS AND A0.CDTYPE=''AP'' AND A0.CDNAME=''STATUS''
AND A1.CDVAL =CR.PAYSTATUS AND A1.CDTYPE=''AP'' AND A1.CDNAME=''PAYSTATUS''
AND A2.CDVAL =CR.BALANCESTATUS AND A2.CDTYPE=''AP'' AND A2.CDNAME=''BALANCESTATUS''
AND A3.CDVAL =CR.REPOSSTATUS AND A3.CDTYPE=''AP'' AND A3.CDNAME=''REPOSSTATUS''
AND CR.STATUS = ''A''
AND CR.QTTY > CR.REQTTY', 'CRPHYSAGREE_SELL', '', 'CRPHYSAGREEID DESC', '', 0, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;