SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SE2236','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('SE2236', 'Gửi hồ sơ cầm cố/tạm giữ lên VSD (2236)', 'Send mortage/temporary request to VSD(wait for 2236)', 'SELECT SE.AUTOID, SE.BUSDATE, SE.TXDATE, SE.AFACCTNO, SE.ACCTNO, CF.FULLNAME CUSTNAME, CF.CUSTODYCD, SB.SYMBOL, SB.PARVALUE,
    (SE.QTTY - (GREATEST(SE.SENDQTTY, 0) + SE.RELEASED)) QTTY, SB.CODEID, CF.ADDRESS, CF.IDCODE LICENSE, CF.MCUSTODYCD,
    SE.TLTXCD
FROM SEMORTAGE SE, AFMAST AF ,CFMAST CF, SBSECURITIES SB
WHERE SE.AFACCTNO = AF.ACCTNO
AND AF.CUSTID = CF.CUSTID
AND SE.TLTXCD IN (''2232'',''2238'')
AND SE.STATUS IN (''N'')
AND SE.DELTD = ''N''
AND SE.CODEID = SB.CODEID
AND SE.QTTY - (GREATEST(SE.SENDQTTY, 0) + SE.RELEASED) > 0', 'SEMAST', '', 'AUTOID DESC', '2236', 0, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;