SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3391','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CA3391', 'Đăng ký mua CP Phát hành thêm(không phong tỏa tiền)', 'Register right issue (not block balance)', 'SELECT autoid,V.CUSTODYCD, V.FULLNAME, AFACCTNO, CAMASTID, SYMBOL,
CODEID,CF.CIFID,
TRADE,BALANCE, PBALANCE,INBALANCE,OUTBALANCE, QTTY, MAXQTTY, CUSTNAME, V.IDCODE,
V.IDPLACE, V.ADDRESS,
V.IDDATE, AAMT, OPTCODEID, OPTSYMBOL, ISCOREBANK,
COREBANK, V.STATUS, SEACCTNO, OPTSEACCTNO,issname,
PARVALUE, REPORTDATE, ACTIONDATE, EXPRICE,
EN_DESCRIPTION, V.DESCRIPTION, CATYPE, BALDEFOVD CIBALANCE FROM
vw_strade_ca_rightoff V LEFT JOIN CFMAST CF ON CF.CUSTODYCD = V.CUSTODYCD  WHERE 0=0', 'CAMAST', NULL, NULL, '3391', NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;