SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('HOLDORDER','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('HOLDORDER', 'Hold số tiền mua khớp', 'Hold the matched purchase amount', 'SELECT STS.AUTOID REQTXNUM, ''HOLDOD'' REQCODE, CF.CUSTID ACCTNO, CF.CIFID, CF.CUSTODYCD, CF.FULLNAME CUSTNAME, 
    DD.ACCTNO DDACCTNO, DD.REFCASAACCT, DD.BALANCE, DD.HOLDBALANCE, DD.HOLDBALANCE BANKHOLDEDBYBROKER,
    SB.CODEID, SB.SYMBOL, 
    STS.TXDATE, STS.CLEARDATE SETTLE_DATE, STS.RECEVING QUANTITY, STS.CASHNETTING AMOUNT, NVL(STS.FEEAMT,0) FEE, NVL(STS.VAT,0) TAX
FROM CFMAST CF, SBSECURITIES SB,
(SELECT * FROM SYSVAR WHERE VARNAME = ''DEALINGCUSTODYCD'') SYS,
(SELECT * FROM STSCHD_NETOFF WHERE ISHOLD = ''N'' AND DELTD = ''N'') STS,
(SELECT * FROM DDMAST WHERE STATUS NOT IN (''C'') AND CCYCD = ''VND'' AND ISDEFAULT = ''Y'') DD
WHERE CF.CUSTID = STS.CUSTID
AND CF.CUSTID = DD.CUSTID
AND STS.CODEID = SB.CODEID
AND STS.ISHOLD = ''N''
AND STS.CASHNETTING > 0
AND SUBSTR(CF.CUSTODYCD,0,4) NOT LIKE SYS.VARVALUE
AND NOT EXISTS (
    SELECT F.CVALUE 
    FROM TLLOG TL, TLLOGFLD F 
    WHERE TL.TXNUM = F.TXNUM 
    AND TL.TXDATE = F.TXDATE 
    AND TL.TLTXCD = ''6690'' 
    AND F.FLDCD = ''95'' 
    AND TL.TXSTATUS IN(''1'', ''4'') 
    AND F.CVALUE =  TO_CHAR(STS.AUTOID)
)', 'HOLDORDER', NULL, NULL, '6690', NULL, 5000, 'N', 1, 'NNNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;