SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('TD0001','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('TD0001', 'Bang ke so du TD va lai du chi', 'TD balance and payable interest', 'SELECT mst.actype tdtype, nvl(tlgroups.grpname,'' '') CAREBY, MST.ACCTNO, MST.AFACCTNO,
    CF.FULLNAME, MST.BALANCE, MST.OPNDATE, MST.FRDATE,
        (SELECT min(sbdate) FROM SBCLDR WHERE CLDRTYPE = ''000''
                                AND SBDATE >= MST.TODATE AND HOLIDAY = ''N'') TODATE,
    FN_TDMASTINTRATIO(MST.ACCTNO,(SELECT min(sbdate) FROM SBCLDR WHERE CLDRTYPE = ''000''
                                AND SBDATE >= MST.TODATE AND HOLIDAY = ''N''),
        MST.BALANCE) INTAVLAMT
FROM TDMAST MST, AFMAST AF, CFMAST CF, TDTYPE TYP, SYSVAR, tlgroups
WHERE MST.ACTYPE=TYP.ACTYPE AND MST.AFACCTNO=AF.ACCTNO
    AND AF.CUSTID=CF.CUSTID AND SYSVAR.VARNAME=''CURRDATE''
    AND MST.DELTD<>''Y'' AND MST.status in (''N'',''A'')
    and cf.careby = tlgroups.grpid(+)
', 'TDMAST', 'frmTDMAST', '', '', 0, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;