SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('POSTMAPEXT','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('POSTMAPEXT', 'Map kế toán ngoại bảng', 'Map off-balance sheet accounts', 'SELECT MST.AUTOID, MST.ACNAME, MST.ACTYPE, MST.DORC,MST.CFTYPE,MST.CCYCD,MST.TRADEPLACE,MST.DEBITACCOUNT,MST.CREBITACCOUNT,
        A1.<@CDCONTENT> ACTYPE_DESC, A2.<@CDCONTENT> DORC_DESC,  A3.<@CDCONTENT> CFTYPE_DESC, A4.<@CDCONTENT> TRADEPLACE_DESC,
        STATUS, A5.<@CDCONTENT> DESC_STATUS,  SB.SHORTCD, TO_CHAR(MST.CREATEDDT, ''DD/MM/RRRR HH24:MI:SS'') CREATEDDT,
        (CASE WHEN MST.STATUS IN (''P'') THEN ''Y'' ELSE ''N'' END) APRALLOW
FROM POSTMAPEXT MST, ALLCODE A1, ALLCODE A2, ALLCODE A3, ALLCODE A4, ALLCODE A5, SBCURRENCY SB
WHERE MST.ACTYPE = A1.CDVAL AND A1.CDNAME =''TRADETYPE'' AND A1.CDTYPE =''GL'' AND A1.CDUSER=''Y''
    AND MST.DORC = A2.CDVAL AND A2.CDNAME =''DORC'' AND A2.CDTYPE =''GL'' AND A2.CDUSER=''Y''
    AND MST.CFTYPE = A3.CDVAL AND A3.CDNAME =''CUSTYPE'' AND A3.CDTYPE =''GL'' AND A3.CDUSER=''Y''
    AND MST.TRADEPLACE = A4.CDVAL AND A4.CDNAME =''TRADEPLACE'' AND A4.CDTYPE =''GL'' AND A4.CDUSER=''Y''
    AND MST.STATUS = A5.CDVAL AND A5.CDNAME =''APPRV_STS'' AND A5.CDTYPE =''SY'' AND A5.CDUSER=''Y''
    AND MST.CCYCD = SB.CCYCD', 'POSTMAPEXT', '', '', '', NULL, 5000, 'Y', 1, '', 'Y', 'T', '', 'N', '');COMMIT;