SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('OD0020','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('OD0020', 'Lệnh G-Bond đã khớp', 'G-Bond order matched', 'SELECT OD.TXDATE TRADEDATE,OD.ORDERID,OD.CUSTODYCD,CF.FULLNAME,OD.CITAD,OD.IDENTITY,OD.SYMBOL TPCP
    FROM ODMAST OD ,CFMAST CF, SBSECURITIES SB
    WHERE   OD.CUSTODYCD = CF.CUSTODYCD
        AND OD.CODEID = SB.CODEID
        AND SB.BONDTYPE = ''001''
        --AND (OD.CITAD IS NULL or OD.IDENTITY IS NULL)
        AND OD.ORSTATUS IN (''4'',''7'')
        --AND OD.ISPAYMENT =''N'' 
        AND OD.TXDATE <=GETCURRDATE', 'OD.ODMAST', 'frmODMAST', NULL, '8814', 0, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;