SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('RMFACBSTATEMENT','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('RMFACBSTATEMENT', 'Tra cứu trạng thái bảng kê từ FA', 'Bank transfer statement status (from FA)', 'SELECT F.GLOBALID,F.CUSTODYCD,F.FUNDACCOUNT, F.SETTLEMENTDATE,A1.EN_CDCONTENT TXTYPE,F.SYMBOL,F.BENEFICIARYACCOUNT BANKACCT,
       F.BENEFICIARYBANK BANKNAME, F.BENEFICIARYNAME CUSTNAME,F.TXAMT,
       A2.EN_CDCONTENT BANKSTATUS, NVL(F.VAT,0) VAT, NVL(F.TAXAMT,0) TAXAMT,A3.EN_CDCONTENT FEETYPE, F.RESPONSE, D.EN_ERRDESC ERRMSG,
       F.FEECODE,F.FEENAME
FROM FACB_STATEMENTGROUP F,ALLCODE A1, ALLCODE A2, ALLCODE A3, DEFERROR D
WHERE A1.CDNAME = ''CBTXTYPE'' AND A1.CDVAL = F.TXTYPE
      AND A2.CDTYPE = ''SA''AND A2.CDNAME = ''SYNCBANKSTATUS'' AND A2.CDVAL = F.BANKSTATUS
      AND A3.CDNAME = ''IOROFEE'' AND A3.CDVAL = F.FEETYPE AND A3.CDTYPE = ''SA''
      AND D.ERRNUM(+) = F.ERR_CODE', 'RMFACBSTATEMENT', 'frmRMCBFABANKPAYMENT', 'GLOBALID DESC', '', 0, 100, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;