SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3312','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CA3312', 'Danh sách chốt tạm (3312)', 'Finalize the entitlement (3312)', 'SELECT V.*, A0.<@CDCONTENT> CCATYPE
FROM V_CA3312 V,
(SELECT * FROM ALLCODE WHERE CDNAME = ''CATYPE'' AND CDTYPE = ''CA'') A0
WHERE V.CATYPE = A0.CDVAL(+)
AND  0=0', 'CAMAST', NULL, 'CAAUTOID DESC', NULL, NULL, 500, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;