SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('UNHOLDORDER','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('UNHOLDORDER', 'Unhold số tiền phong tỏa trong ngày', 'Unhold blockade amount of the day', 'SELECT DD.CUSTODYCD, F.TXNUM REFTXNUM, CRB.TXDATE REFTXDATE, DD.AFACCTNO SECACCOUNT, DD.ACCTNO DDACCTNO, CF.FULLNAME CUSTNAME,
    DD.REFCASAACCT REFCASAACCT, DD.BALANCE, DD.HOLDBALANCE, F.MEMBERID, F.BRNAME, F.BRPHONE, F.CCYCD, CRB.TXAMT AMOUNT, F.NOTE,
    CRB.CREATEDATE, CRB.REQID 
FROM CRBTXREQ CRB,DDMAST DD,CFMAST CF,
(
    SELECT TXNUM,
    MAX (CASE WHEN F.FLDCD = ''05'' THEN F.CVALUE ELSE '''' END)  MEMBERID,
    MAX (CASE WHEN F.FLDCD = ''06'' THEN F.CVALUE ELSE '''' END)  BRNAME,
    MAX (CASE WHEN F.FLDCD = ''07'' THEN F.CVALUE ELSE '''' END)  BRPHONE,
    MAX (CASE WHEN F.FLDCD = ''93'' THEN F.CVALUE ELSE '''' END)  BANKACCTNO,
    MAX (CASE WHEN F.FLDCD = ''20'' THEN F.CVALUE ELSE '''' END)  CCYCD,
    MAX (CASE WHEN F.FLDCD = ''30'' THEN F.CVALUE ELSE '''' END)  NOTE
    FROM TLLOGFLD F
    WHERE FLDCD IN (''04'',''05'', ''06'', ''07'', ''20'', ''93'',''30'')
    GROUP BY TXNUM
)F
WHERE CRB.OBJNAME = ''6690''
AND CRB.REQCODE = ''BANKHOLDEDBYBROKER''
AND CRB.TXDATE = GETCURRDATE
AND DD.ACCTNO = CRB.AFACCTNO
AND DD.CUSTODYCD = CF.CUSTODYCD
AND CRB.OBJKEY = F.TXNUM
AND CRB.UNHOLD = ''N''
AND CRB.STATUS = ''C''
AND NOT EXISTS (
    SELECT F1.CVALUE 
    FROM TLLOG TL, TLLOGFLD F1 
    WHERE TL.TXNUM = F1.TXNUM 
    AND TL.TXDATE = F1.TXDATE 
    AND TL.TLTXCD = ''6691'' 
    AND TL.TXSTATUS IN(''1'', ''4'') 
    AND F1.FLDCD = ''91'' 
    AND F1.CVALUE = F.TXNUM
)', 'UNHOLDORDER', NULL, 'CREATEDATE DESC, REQID DESC', '6691', NULL, 5000, 'N', 1, 'NNNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;