SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3383','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CA3383', 'Chuyển khoản quyền mua ra ngoài và nội bộ', 'Transfer right issue outward and internal company', 'SELECT MST.*, (CASE WHEN VW.ISSUERMEMBER=''Y'' THEN ''TVQT TCPH'' ELSE ''NO'' END ) ISSUERMEMBER,
    M.VARVALUE FROMCUSADD, (CASE WHEN VW.ISSUERMEMBER=''Y''THEN ''Y'' ELSE ''N'' END ) ISSUERMEMBERCD,
    MST.PQTTY PTRADE, NVL(CALOG.BLOCKED,0) - NVL(CALOG.INBLOCKED,0) PBLOCKED
FROM (
SELECT CAF.QTTY, CAF.PQTTY ,
    SUBSTR(CAMAST.CAMASTID,1,4) || ''.''||
    SUBSTR(CAMAST.CAMASTID,5,6) ||''.'' ||
    SUBSTR(CAMAST.CAMASTID,11,6) CAMASTID, CA.AFACCTNO, NVL(GETBALDEFAVL(CA.AFACCTNO),0) BALDEFAVL, CAMAST.OPTCODEID  CODEID,
    SYM.SYMBOL,SYM.TRADEPLACE, A1.<@CDCONTENT> STATUS,CA.AFACCTNO || CAMAST.CODEID SEACCTNO,SYM.PARVALUE PARVALUE,CAMAST.REPORTDATE REPORTDATE,
    CAMAST.ACTIONDATE,CAMAST.EXPRICE, AFM.*, A2.<@CDCONTENT>
    CATYPE, CAMAST.TRFLIMIT,ISS.FULLNAME ISSNAME,
    CAMAST.CODEID CODEID0,CA.AUTOID, SB2.SYMBOL TOSYMBOL, ISS2.FULLNAME TOISSNAME,
    SB2.CODEID TOCODEID, CAMAST.ISINCODE
FROM  SBSECURITIES SYM,ISSUERS ISS , ALLCODE A1, CAMAST, CASCHD CA,
      (
  SELECT AF.ACCTNO, CF.CUSTODYCD, CF.MCUSTODYCD, CF.FULLNAME CUSTNAME,CF.CIFID,
         A1.CDCONTENT COUNTRY, CF.ADDRESS, CF.COUNTRY COUNTRYID,
        (CASE WHEN CF.COUNTRY = ''234'' THEN CF.IDCODE ELSE CF.TRADINGCODE END) LICENSE,
        (CASE WHEN CF.COUNTRY = ''234'' THEN CF.IDDATE ELSE CF.TRADINGCODEDT END) IDDATE,
        CF.IDPLACE, DD.REFCASAACCT || ''-'' || DD.CCYCD || ''-'' || DD.ACCOUNTTYPE REFCASAACCT
      FROM CFMAST CF, AFMAST AF, ALLCODE A1, (SELECT * FROM DDMAST WHERE ISDEFAULT=''Y'' AND STATUS=''A'') DD
      WHERE AF.CUSTID = CF.CUSTID
            AND CF.CUSTID=DD.CUSTID
              AND AF.STATUS  IN (''A'',''N'')
              AND CF.COUNTRY = A1.CDVAL
              AND A1.CDTYPE =''CF''
              AND A1.CDNAME = ''COUNTRY''
       ) AFM, ALLCODE A2, SBSECURITIES SB2, ISSUERS ISS2,
       (
        SELECT CF.CUSTODYCD, CA.CAMASTID,
            SUM(CA.PBALANCE-CA.INBALANCE) QTTY, SUM(CA.PBALANCE- CA.INBALANCE) PQTTY
        FROM CAMAST, CASCHD CA, CFMAST CF, AFMAST AF
        WHERE CF.CUSTID = AF.CUSTID AND AF.ACCTNO = CA.AFACCTNO
            AND CAMAST.STATUS IN (''V'',''S'',''M'')
            AND CAMAST.CATYPE = ''014'' AND CA.CAMASTID = CAMAST.CAMASTID
            AND CA.STATUS IN(''V'',''S'',''M'') AND CA.DELTD <>''Y'' AND CA.PBALANCE - CA.INBALANCE > 0
            AND CAMAST.TRFLIMIT = ''Y''
            AND TO_DATE(CAMAST.FRDATETRANSFER,''DD/MM/RRRR'') <= TO_DATE(GETCURRDATE,''DD/MM/RRRR'')
            AND TO_DATE(CAMAST.TODATETRANSFER,''DD/MM/RRRR'') >= TO_DATE(GETCURRDATE,''DD/MM/RRRR'')
        GROUP BY CF.CUSTODYCD, CA.CAMASTID
        ) CAF
WHERE CA.AFACCTNO=AFM.ACCTNO AND A1.CDTYPE = ''CA''
    AND A1.CDNAME = ''CASTATUS'' AND A1.CDVAL = CA.STATUS
    AND CAMAST.CODEID = SYM.CODEID AND CAMAST.STATUS IN (''V'',''S'',''M'')
    AND AFM.CUSTODYCD = CAF.CUSTODYCD AND CA.CAMASTID = CAF.CAMASTID
    AND CAMAST.CATYPE=''014'' AND CA.CAMASTID = CAMAST.CAMASTID
    AND CA.STATUS IN(''V'',''S'',''M'') AND CA.DELTD <>''Y'' AND CA.PBALANCE - CA.INBALANCE > 0
    AND CAMAST.CATYPE = A2.CDVAL AND A2.CDTYPE = ''CA''
    AND A2.CDNAME = ''CATYPE'' AND CAMAST.TRFLIMIT = ''Y'' AND ISS.ISSUERID = SYM.ISSUERID
    AND NVL(CAMAST.TOCODEID, CAMAST.CODEID) = SB2.CODEID AND SB2.ISSUERID = ISS2.ISSUERID
    AND TO_DATE(CAMAST.FRDATETRANSFER,''DD/MM/RRRR'') <= TO_DATE(GETCURRDATE,''DD/MM/RRRR'')
    AND TO_DATE(CAMAST.TODATETRANSFER,''DD/MM/RRRR'') >= TO_DATE(GETCURRDATE,''DD/MM/RRRR'')
) MST,
(SELECT * FROM CASCHD_LOG WHERE DELTD = ''N'') CALOG,
(SELECT VWW.*, ''Y'' ISSUERMEMBER FROM VW_ISSUER_MEMBER VWW) VW,
(SELECT VARVALUE FROM SYSVAR WHERE VARNAME LIKE ''%ISSUERMEMBER%'') M
WHERE  MST.CUSTODYCD = VW.CUSTODYCD  (+) AND MST.SYMBOL = VW.SYMBOL (+)
AND REPLACE(MST.CAMASTID,''.'')=CALOG.CAMASTID(+) AND MST.CODEID0=CALOG.CODEID(+) AND MST.AFACCTNO=CALOG.AFACCTNO(+)', 'CAMAST', NULL, NULL, '3383', 0, 50, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;