SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CASCHD','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CASCHD', 'Thông tin CK được thực hiện quyền', 'CA stock information', 'SELECT CA.AUTOID, CA.BALANCE, CA.CAMASTID, CA.AFACCTNO,A0.CDCONTENT CATYPE, CA.CODEID, CA.EXCODEID, CA.QTTY, CA.AMT, CA.AQTTY,
       CA.AAMT, SYM.SYMBOL, A1.CDCONTENT STATUS,
       CA.AFACCTNO ||(case when camast.iswft=''Y'' then (select codeid from sbsecurities where refcodeid=symto.codeid) else symto.codeid end) SEACCTNO,
       CA.AFACCTNO || (CASE WHEN CAMAST.EXCODEID IS NULL THEN CAMAST.CODEID ELSE CAMAST.EXCODEID END) EXSEACCTNO,
       SYM.PARVALUE PARVALUE, EXSYM.PARVALUE EXPARVALUE, CAMAST.REPORTDATE REPORTDATE, CAMAST.ACTIONDATE,
       CFMAST.FULLNAME, CFMAST.IDCODE, CFMAST.CUSTODYCD,CFMAST.CIFID,CASE WHEN CI.COREBANK=''Y'' THEN 1 ELSE 0 END COREBANK,
       CASE WHEN CI.COREBANK=''Y'' THEN ''Yes'' ELSE ''No'' END ISCOREBANK
       ,decode(priceaccounting,0,exsym.parvalue,priceaccounting) priceaccounting, a0.cdval CATYPEVALUE,
       CA.ISCI,ISSE,CA.PBALANCE, CA.RQTTY, CA.TRADE,CAMAST.DESCRIPTION,afmast.BANKNAME,afmast.BANKACCTNO, camast.isincode,CA.TRFFEE TRFEEAMT
FROM CASCHD CA, SBSECURITIES SYM, SBSECURITIES EXSYM, ALLCODE A0, ALLCODE A1, CAMAST, AFMAST, CFMAST,DDMAST CI,
SBSECURITIES SYMTO
WHERE A0.CDTYPE = ''CA'' AND A0.CDNAME = ''CATYPE'' AND A0.CDVAL = CAMAST.CATYPE
AND A1.CDTYPE = ''CA'' AND A1.CDNAME = ''CASTATUS'' AND A1.CDVAL = CA.STATUS
AND CA.CAMASTID = CAMAST.CAMASTID AND CAMAST.CODEID = SYM.CODEID
AND CA.DELTD =''N''
AND EXSYM.CODEID = (CASE WHEN CAMAST.EXCODEID IS NULL THEN CAMAST.CODEID ELSE CAMAST.EXCODEID END)
AND CA.AFACCTNO = AFMAST.ACCTNO AND CI.AFACCTNO=AFMAST.ACCTNO
AND AFMAST.CUSTID = CFMAST.CUSTID
and nvl(camast.tocodeid,camast.codeid)=symto.codeid AND CI.isdefault = ''Y'' and CI.status <> ''C''', 'CASCHD', 'frmCASCHD', '', '', NULL, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;