SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3401','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CA3401', 'Tra cứu xác nhận danh sách người sở hữu chứng khoán lưu ký thực hiện quyền (TPRL)', 'Lookup confirmed list of holders of securities depository execution rights (PPBs)', 'SELECT CA.CAMASTID, CA.CODEID, SB.SYMBOL, CA.REPORTDATE, CA.DESCRIPTION, CA.VSDID,
    A1.<@CDCONTENT> CATYPE, A2.<@CDCONTENT> CASTATUS, A3.<@CDCONTENT> VSDSTATUS
FROM CAMAST CA, SBSECURITIES SB,
(SELECT * FROM ALLCODE WHERE CDNAME = ''CATYPE'')A1,
(SELECT * FROM ALLCODE WHERE CDNAME = ''CASTATUS'')A2,
(SELECT * FROM ALLCODE WHERE CDNAME = ''CAVSDSTS'')A3
WHERE CA.CODEID = SB.CODEID
AND CA.CATYPE = A1.CDVAL(+)
AND CA.STATUS = A2.CDVAL(+)
AND CA.VSDSTATUS = A3.CDVAL(+)
AND CA.STATUS IN (''N'',''A'',''V'')
AND CA.DELTD = ''N''
AND SB.TRADEPLACE IN (''099'')
AND CA.VSDID IS NOT NULL', 'CA3401', '', 'CAMASTID DESC', '3401', NULL, 5000, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;