SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('DD1001','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('DD1001', 'Tất toán phí', 'Fee settlement', 'SELECT * FROM (
    SELECT FEE.AUTOID, CF.FULLNAME, CF.CUSTODYCD, FEE.CIFID PROFOLIOCD, FEE.CURRENCY CCYCD, FEE.FEEAMOUNT, FEE.FXRATE, FEE.FXAMOUNT, NVL(FEE.TAXAMOUNT,0) TAXAMOUNT,
            DECODE(FEE.CURRENCY,''VND'',ROUND((NVL(FEE.FEEAMOUNT,0) + NVL(FEE.TAXAMOUNT,0)),0),ROUND((NVL(FEE.FEEAMOUNT,0) + NVL(FEE.TAXAMOUNT,0)),2)) FEEAMTVAT,
            AL.CDVAL STATUSCDVAL, FEE.FEECODE, FEE.SETTLEDATE PAIDDATE, FEE.REMARK, TO_CHAR(FEE.TRANSDATE, ''DD/MM/RRRR'') TRANSDATE, TO_CHAR(FEE.SETTLEDATE, ''DD/MM/RRRR'') SETTLEDATE,
            FEE.TXDATE, FEE.FEETXDATE, FEE.FEETXNUM, FEE.BANKREFID, FEE.SPRACNO,
            TO_DATE(TO_CHAR(FEE.LASTCHANGE,''DD/MM/RRRR''),''DD/MM/RRRR'')LASTCHANGE,
            TO_CHAR(FEE.LASTCHANGE,''HH24:MI:SS'') CREATEDATE,A2.CDVAL DELTDCDVAL,FEE.FEENAME FEENAMECSTD,FEE.MCIFID,CF.MCUSTODYCD,
            AMC.SHORTNAME AMCSHORTNAME, GCB.SHORTNAME GCBSHORTNAME, ''Settle '' || FEE.REMARK SETTREMARK,
            (CASE WHEN NVL(CF.SETTLETYPE, ''60'') = ''60'' THEN NOSTRO.BANKACCTNO ELSE DD.REFCASAACCT END) BANKACCTNO,
            NVL(CF.SETTLETYPE, ''60'') SETTLETYPE,
            AL.<@CDCONTENT> STATUS, A2.<@CDCONTENT> DELTD, A3.<@CDCONTENT> AUTOFEE
    FROM
    (
        SELECT * FROM FEE_BOOKING_RESULT
        UNION ALL
        SELECT * FROM FEE_BOOKING_RESULTHIST
    ) FEE,
    (
        SELECT CF.* FROM CFMAST CF WHERE CF.SUPEBANK = ''N'' AND CF.STATUS NOT IN (''C'')
    ) CF,
    (
        SELECT * FROM DDMAST WHERE PAYMENTFEE = ''Y'' AND STATUS <> ''C''
    ) DD,
    (
        SELECT BANKACCTNO, ''VND'' CCYCD FROM BANKNOSTRO WHERE BANKTRANS = ''OUTTRFMONFEESETTVND'' AND ROWNUM = 1
        UNION ALL
        SELECT BANKACCTNO, ''USD'' CCYCD FROM BANKNOSTRO WHERE BANKTRANS = ''OUTTRFMONFEESETTUSD'' AND ROWNUM = 1
    ) NOSTRO,
    (SELECT * FROM ALLCODE WHERE CDTYPE = ''DD'' AND CDNAME = ''FSTATUS'') AL,
    (SELECT * FROM ALLCODE WHERE CDTYPE = ''DD'' AND CDNAME = ''DELTDTEXT'') A2,
    (SELECT * FROM ALLCODE WHERE CDTYPE = ''SY'' AND CDNAME = ''YESNO'') A3,
    (SELECT * FROM FAMEMBERS WHERE ROLES = ''AMC'') AMC,
    (SELECT * FROM FAMEMBERS WHERE ROLES = ''GCB'') GCB
    WHERE FEE.CIFID = CF.CIFID
    AND FEE.STATUS = AL.CDVAL(+)
    AND FEE.DELTD = A2.CDVAL(+)
    AND CF.AMCID = AMC.AUTOID(+)
    AND CF.GCBID = GCB.AUTOID(+)
    AND NVL(FEE.DELTD,''N'') NOT IN (''Y'')
    AND FEE.STATUS = ''C''
    AND FEE.AUTOID NOT IN (SELECT FEEBOOKINGAUOID FROM SETTLE_FEE_LOG WHERE STATUS IN (''P'',''C''))
    AND CF.CUSTID = DD.CUSTID(+)
    AND FEE.CURRENCY = NOSTRO.CCYCD(+)
    AND NVL(CF.AUTOSETTLEFEE, ''Y'') = A3.CDVAL(+)
)
WHERE 0=0', 'DD1001', 'frmFEEBOOKING', 'LASTCHANGE desc,CREATEDATE desc', '1207', 0, 5000, 'N', 1, 'NNNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;