SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('BANKNOSTRO6622','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('BANKNOSTRO6622', 'Danh sach tài khoản đi tiền/nhận tiền', 'Listings accounts Travel/Receive money', 'SELECT BK.AUTOID,BK.FULLNAME,DECODE(BK.BANKTYPE,''002'',''C'',''001'',''D'') DORC,OWNERNAME,BANKACCTNO,GLACCOUNT,BANKAFFILIATE,A1.<@CDCONTENT> BANKTYPE, A2.<@CDCONTENT> BANKTRANS,DESCRIPTSION
FROM BANKNOSTRO BK, 
(SELECT * FROM ALLCODE A1 WHERE A1.CDTYPE=''SA'' AND A1.CDNAME=''BANKTYPE'') A1,
(SELECT * FROM ALLCODE A2 WHERE A2.CDTYPE=''SY'' AND A2.CDNAME=''TRFCODE'') A2
WHERE BK.BANKTYPE=A1.CDVAL(+)
AND BK.BANKTRANS=A2.CDVAL(+)
AND BK.BANKTYPE = ''002''', 'BANKNOSTRO', 'BANKNOSTRO', '', '', 0, 5000, 'N', 1, 'YYYYYYNNNNN', 'Y', 'T', '', 'N', '');COMMIT;