SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('RM6690','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('RM6690', 'Danh sách tài khoản cần HOLD từ BIDV', 'List of account hold from BIDV', 'SELECT AF.ACTYPE, CF.CUSTODYCD, AF.ACCTNO, AF.BANKNAME BANKCODE, AF.BANKNAME, AF.BANKACCTNO, CI.BALANCE, CI.HOLDBALANCE,
       CI.BANKAVLBAL, CI.BANKBALANCE, /*getrmbaldefavl(AF.ACCTNO)*/ 0 UNHOLDBALANCE,  CI.BANKAVLBAL HOLDAMOUNT,
       CF.FULLNAME, CF.ADDRESS, CF.IDTYPE, CF.IDCODE, CF.IDDATE, CF.IDPLACE, CF.CAREBY
FROM CFMAST CF, AFMAST AF, CIMAST CI
WHERE CF.CUSTID = AF.CUSTID
      AND AF.ACCTNO = CI.AFACCTNO
      AND AF.BANKNAME LIKE ''BIDV%''
      AND AF.ALTERNATEACCT = ''Y''
      AND CI.BANKAVLBAL > 0 and CI.HOLDBALANCE = 0
      AND AF.STATUS IN (''A'')', 'RM6690', NULL, NULL, '6690', NULL, 1000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;