SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CFMAST_CFAUTH','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CFMAST_CFAUTH', 'TTKH', 'Customer information', 'select *  FROM (
        SELECT CF.CUSTID FILTERCD, CF.CUSTODYCD,
               NVL(AU.CUSTID, AU.LICENSENO) CUSTID, AU.FULLNAME , AU.ADDRESS, AU.licenseno IDCODE, AU.lnplace IDPLACE, AU.lniddate IDDATE
        FROM CFAUTH AU, CFMAST CF, AFMAST AF, SYSVAR SYS
        WHERE CF.CUSTID = AU.CFCUSTID
              AND AF.CUSTID = CF.CUSTID
              AND SYS.VARNAME = ''CURRDATE''
              AND TO_DATE(VARVALUE,''DD/MM/RRRR'') BETWEEN AU.valdate AND AU.expdate
        UNION ALL
        SELECT CUSTID FILTERCD, CUSTODYCD, CUSTID ,  FULLNAME  , ADDRESS, IDCODE, IDPLACE, IDDATE
        FROM CFMAST  )
WHERE 0=0', 'CFMAST', 'frmCFMAST', 'FULLNAME', '', NULL, 1000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;