SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('ED_COMPARECSV','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('ED_COMPARECSV', 'Danh sách file CSV', 'Danh sách file CSV', 'SELECT B.AUTOID, B.REFREQID, M.RPTID REPORTID, B.FILENAME, B.TXDATE, M.DESCRIPTION RPTNAME, M.RPTID, M.DESCRIPTION, TO_CHAR(B.TIMECREATED,''HH24:MI:SS.'') CREATEDATE
FROM CSVCOMPAREREPORT A, VSDCONTENTLOG B, RPTMASTER M
WHERE B.RPTID = M.RPTID
AND M.RPTID = A.DESCRIPTION
AND UPPER(B.FILENAME) LIKE ''%.CSV''
AND A.CMPID = ''ED''
AND B.STATUS = ''C''', 'ED_COMPARECSV', 'frmCAMAST', 'AUTOID DESC', NULL, 0, 50, 'N', 30, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;