SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3337','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CA3337', 'Hoàn tất chuyển nhượng quyền mua', 'Complete assignment of purchase rights', 'SELECT MST.AUTOID, MST.CAMASTID, MST.NOTRANSCT, SB1.SYMBOL, SB2.SYMBOL TOSYMBOL,
    MST.TOACCTNO TOCUSTODYCD,CFT.CIFID TOCIFID,MST.CUSTNAME2,MST.IDDATE2, MST.CUSTODYCD,CFT.CIFID,CF.FULLNAME, CF.IDDATE,
    MST.REMOACCOUNT,MST.CITAD,MST.TOMEMCUS,MST.AMT QTTY,MST.TRANSFERPRICE EXPRICE,MST.AMT*MST.TRANSFERPRICE AMOUNT,MST.VSDSTOCKTYPE,
    CF.MCUSTODYCD
FROM CATRANSFER MST, SBSECURITIES SB1, SBSECURITIES SB2, CFMAST CF, CFMAST CFT, camast ca
WHERE MST.CODEID=SB1.CODEID AND MST.OPTCODEID=SB2.CODEID AND CFT.CUSTODYCD(+) = MST.TOACCTNO AND MST.CUSTODYCD=CF.CUSTODYCD(+)
and mst.camastid = ca.camastid
AND MST.MSGSTATUS IN (''S'',''C'') AND MST.OPTSEACCTNODR IS NOT NULL
AND (MST.STATUS =''P''
--Check tai khoan mua khong thuoc SHV cho Hoan tat khong can qua di tien
OR (MST.STATUS =''H'' AND MST.TOACCTNO NOT IN (SELECT CUSTODYCD FROM CFMAST WHERE STATUS <> ''A'' AND CUSTATCOM=''Y'' AND CUSTODYCD IS NOT NULL)))', 'CAMAST', '', 'CAMASTID DESC', '3337', 0, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;