SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('REMAST','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('REMAST', 'Tài khoản đại lý/môi giới', 'Remiser account', 'SELECT MST.ACCTNO, TYP.TYPENAME, CF.FULLNAME,
CF.FULLNAME || '' ['' || A0.CDCONTENT || ''] '' REFVALUE,
MST.DIRECTACR, MST.INDIRECTACR,
MST.BALANCE, A0.CDCONTENT DESC_RETYPE, A2.CDCONTENT
DESC_REROLE, A1.CDCONTENT DESC_STATUS
FROM RECFLNK RF, REMAST MST, CFMAST CF, RETYPE TYP,
ALLCODE A0, ALLCODE A1, ALLCODE A2
WHERE MST.ACTYPE=TYP.ACTYPE AND MST.CUSTID=CF.CUSTID
AND A0.CDTYPE=''RE'' AND A0.CDNAME=''RETYPE'' AND
TYP.RETYPE=A0.CDVAL
AND A2.CDTYPE=''RE'' AND A2.CDNAME=''REROLE'' AND
TYP.REROLE=A2.CDVAL
AND A1.CDTYPE=''RE'' AND A1.CDNAME=''STATUS'' AND
MST.STATUS=A1.CDVAL
AND MST.STATUS=''A''
AND RF.CUSTID=MST.CUSTID AND RF.AUTOID=<$KEYVAL>', 'RE.REMAST', 'frmTDMAST', '', '', 0, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;