SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3384','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CA3384', 'Đăng ký mua CP phát hành thêm', 'Register right issue', 'SELECT V.ABC, V.AUTOID,V.CUSTODYCD,CF.CIFID, V.FULLNAME, V.AFACCTNO, V.AFACCTNO TRFACCTNO, V.CAMASTID, V.SYMBOL,
V.CODEID, V.TRADE, V.MAXBALANCE, V.BALANCE, V.PBALANCE, V.INBALANCE, V.OUTBALANCE, V.QTTY, V.MAXQTTY, V.AVLQTTY, V.SUQTTY BUYQTTY, V.CUSTNAME, V.IDCODE,
V.IDPLACE, V.ADDRESS,V.IDDATE, V.AAMT, V.OPTCODEID, V.OPTSYMBOL, V.ISCOREBANK,
V.COREBANK, A1.<@CDCONTENT> STATUS, V.SEACCTNO, V.OPTSEACCTNO, V.ISSNAME,
V.PARVALUE, V.REPORTDATE, V.ACTIONDATE, V.EXPRICE,
V.EN_DESCRIPTION, V.DESCRIPTION, A2.<@CDCONTENT> CATYPE, V.BALDEFOVD CIBALANCE,V.PHONE, V.BANKACCTNO, V.BANKNAME,V.SYMBOL_ORG , V.ISINCODE,GRP.GRPID, GRP.GRPNAME CAREBY,
V.MCUSTODYCD
FROM VW_STRADE_CA_RIGHTOFF_3384 V, TLGROUPS GRP, ALLCODE A1,  ALLCODE A2, CFMAST CF
WHERE V.CAREBY = GRP.GRPID
AND A1.CDTYPE = ''CA'' AND A1.CDNAME = ''CASTATUS''
AND A2.CDTYPE = ''CA'' AND A2.CDNAME = ''CATYPE''
AND A1.CDVAL = V.STATUS
AND V.CATYPE = A2.CDVAL
AND CF.CUSTODYCD = V.CUSTODYCD', 'CAMAST', '', '', '3384', NULL, 5000, 'N', 1, 'NYNNYYYNNY', 'Y', 'T', '', 'N', '');COMMIT;