SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CFMAST_ALL','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CFMAST_ALL', 'Thông tin khách hàng', 'Customer information', 'SELECT format_custid(CF.CUSTID) CUSTID,
CF.CUSTODYCD,
(CF.CUSTODYCD) CUSTODYCD_SRCH,
CF.SHORTNAME,CF.FULLNAME,CF.MNEMONIC,CF.DATEOFBIRTH,A1.CDCONTENT IDTYPE,CF.IDCODE,CF.IDDATE,CF.IDPLACE,CF.IDEXPIRED,CF.ADDRESS,CF.mobilesms MOBILE,
CF.PHONE,CF.FAX,CF.EMAIL,A2.CDCONTENT COUNTRY,A3.CDCONTENT PROVINCE,CF.POSTCODE,'''' CLASS,'''' GRINVESTOR,
'''' INVESTRANGE,'''' TIMETOJOIN,'''' STAFF,CF.COMPANYID,CF.ISSUERID,'''' POSITION,A11.CDCONTENT SEX,
'''' SECTOR,'''' FOCUSTYPE,'''' BUSINESSTYPE,'''' INVESTTYPE,'''' EXPERIENCETYPE,
'''' INCOMERANGE,'''' ASSETRANGE,CF.BRID,GRP.GRPNAME CAREBY,CF.APPROVEID,CF.LASTDATE,CF.AUDITORID,CF.AUDITDATE,
A19.CDCONTENT LANGUAGE,CF.BANKACCTNO,CF.bankcode BANKCODE1,
A20.CDCONTENT BANKCODE,A21.CDCONTENT MARRIED,CF.DESCRIPTION,A22.CDCONTENT STATUS,A23.CDCONTENT ISBANKING,CF.CLASS CLASS1,CF.STAFF STAFF1,
CF.FOCUSTYPE FOCUSTYPE1,CF.REFNAME REFNAME1, MRLOANLIMIT, CF.TRADINGCODE, CF.TRADINGCODEDT, CF.VAT,
(CASE WHEN CF.STATUS IN (''B'',''C'',''N'') THEN ''N'' ELSE ''Y'' END) EDITALLOW,
(CASE WHEN CF.STATUS IN (''P'') THEN ''Y'' ELSE ''N'' END) APRALLOW, ''Y'' DELALLOW, CF.RISKLEVEL, CF.ACTIVESTS, CF.CUSTTYPE, CF.ISFORCUSTMASTACC, CF.COUNTRY COUNTRYCODE
FROM
CFMAST CF,TLGROUPS GRP, ALLCODE A1, ALLCODE A2,ALLCODE A3, ALLCODE A11,ALLCODE A19,ALLCODE A20,ALLCODE A21,ALLCODE A22, ALLCODE A23
WHERE
CF.CAREBY = GRP.GRPID
AND A1.CDTYPE = ''CF'' AND A1.CDNAME = ''IDTYPE'' AND A1.CDVAL= CF.IDTYPE
AND A2.CDTYPE = ''CF'' AND A2.CDNAME = ''COUNTRY'' AND A2.CDVAL= CF.COUNTRY
AND A3.CDTYPE = ''CF'' AND A3.CDNAME = ''PROVINCE'' AND A3.CDVAL= CF.PROVINCE
AND A11.CDTYPE = ''CF'' AND A11.CDNAME = ''SEX'' AND A11.CDVAL= CF.SEX
AND A19.CDTYPE = ''CF'' AND A19.CDNAME = ''LANGUAGE'' AND A19.CDVAL= CF.LANGUAGE
AND A20.CDTYPE = ''CF'' AND A20.CDNAME = ''BANKCODE'' AND A20.CDVAL= CF.BANKCODE
AND A21.CDTYPE = ''CF'' AND A21.CDNAME = ''MARRIED'' AND A21.CDVAL= CF.MARRIED
AND A22.CDTYPE = ''CF'' AND A22.CDNAME = ''CFSTATUS'' AND A22.CDVAL= CF.STATUS
AND A23.CDTYPE = ''SY'' AND A23.CDNAME = ''YESNO'' AND A23.CDVAL= CF.ISBANKING
AND (SUBSTR(CF.CUSTID,1,4) = DECODE(''<$BRID>'', ''<$HO_BRID>'', SUBSTR(CF.CUSTID,1,4), ''<$BRID>'')
    OR CF.CAREBY IN (SELECT TLGRP.GRPID FROM TLGRPUSERS TLGRP WHERE TLID = ''<$TELLERID>'')
    )', 'CFMAST_ALL', 'frmCFMAST', NULL, NULL, NULL, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;