SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('MR9003','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('MR9003', 'Tra cứu dự tính vay cuối ngày', 'View estimate release loan EOD', 'SELECT MST.CUSTODYCD, MST.AFACCTNO, MST.FULLNAME, MST.BALANCE, MST.AVLADVANCE, MST.SECUREAMT,          
        GREATEST(MST.SWAPRELEASE,0) SWAPRELEASE,                
        GREATEST(MST.MRRELEASE,0) MRRELEASE, 
        GREATEST(MST.DPRELEASE,0) DPRELEASE,
        GREATEST(MST.ADVRELEASE,0) ADVRELEASE,
        GREATEST(MST.T0RELEASE,0) T0RELEASE,        
        MST.MRSEASS, MST.DPSEASS, 
        MST.MRODAMT, 
        MST.DPODAMT,
        MST.DUEAMT,
        MST.T0ODAMT,
        MST.DPDUEAMT,
        MST.OVDAMT,
        GREATEST(MST.MRASSSWAP,0) MRASSSWAP,
        GREATEST(MST.MRASSRELEASE,0) MRASSRELEASE,
        GREATEST(MST.DPASSRELEASE,0) DPASSRELEASE,
        MST.SECUREAMT_REMAIN, 
        MST.SECUREAMT_REMAIN2,
        MST.MRCRLIMITMAX_REMAIN,
        MST.DPCRLIMITMAX_REMAIN       
FROM V_GETSECMARGINRELEASE MST
WHERE SECUREAMT + SWAPRELEASE + MRRELEASE + DPRELEASE  <> 0', 'MRTYPE', NULL, NULL, NULL, NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;