SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('IMP6639_R0061ONLINE','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('IMP6639_R0061ONLINE', 'Tra cứu thông tin import 6639_R0061', 'Tra cứu thông tin import 6639_R0061', 'SELECT T.SETTYPE,T.DEBANKACC,TO_CHAR(T.NGAYTT,''DD/MM/RRRR'') NGAYTT,T.TENTHUHUONG,
T.DIACHI,T.BANKCODE,T.BANKACC,T.NOIDUNG,T.TIENTE,
T.SOTIEN,T.TENNH,T.SOTHCHIEU,T.SESSIONNO,TO_CHAR(T.TRADINGDATE,''DD/MM/RRRR'') TRADINGDATE,
T.TYPES, ''TABLE'' TYPE
FROM (
    SELECT * FROM PAYMENTCASH_R0061_TEMP
    UNION ALL
    SELECT * FROM PAYMENTCASH_R0061_TEMP_HIST
) T
WHERE 1 = 1', 'IMP6639_R0061ONLINE', NULL, NULL, NULL, NULL, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;