SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('PR0002','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('PR0002', 'Tra cứu Room CK margin (theo UBCK)', 'Margin room Master', 'SELECT ROWNUM NO, CODEID, SYMBOL, LISTINGQTTY, ROOMLIMITMAX, ROOMLIMIT, ROOMUSED, ROOMREMAIN,
    MRPRICELOAN, MARKETVAL, MRMAXBALANCE, ''M'' roomtype
FROM (SELECT  SB.CODEID, SB.SYMBOL, SB.LISTINGQTTY, (SB.LISTINGQTTY*SYSR1.VARVALUE/100) ROOMLIMITMAX, RM.ROOMLIMIT ROOMLIMIT, RM.ROOMUSED, RM.ROOMREMAIN,
        sb.basicprice MRPRICELOAN, RM.ROOMUSED*sb.basicprice MARKETVAL, SYSR.VARVALUE MRMAXBALANCE
        FROM VW_MARGINROOMSYSTEM RM, SECURITIES_INFO SB, SECURITIES_RISK SRK, SYSVAR SYSR, ALLCODE A0,SYSVAR SYSR1,
               (SELECT CODEID, SUM(PRINUSED) PRINUSED FROM VW_AFPRALLOC_ALL WHERE RESTYPE = ''M'' GROUP BY CODEID) AFPR
        WHERE RM.CODEID = AFPR.CODEID(+) AND RM.CODEID = SB.CODEID AND SRK.CODEID=RM.CODEID AND SYSR.GRNAME=''MARGIN''
            AND SYSR.VARNAME =''MAXDEBTSE'' AND A0.CDNAME=''YESNO'' AND A0.CDTYPE=''SY'' AND A0.CDVAL=SRK.ISMARGINALLOW
            AND SYSR1.GRNAME=''MARGIN'' AND SYSR1.VARNAME =''MAXDEBTQTTYRATE'' AND SRK.ISMARGINALLOW=''Y''
        ORDER BY SB.SYMBOL)
        WHERE 0=0 ', 'SYSMRROOM', '', '', '0104', NULL, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;