SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CFDDMAST','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CFDDMAST', 'Thông tin tài khoản thanh toán khách hàng', 'Customer payment account information', 'select CF.CUSTODYCD, CF.FULLNAME, DD.AFACCTNO, 
DD.ACCTNO,DD.OPNDATE, DD.CCYCD, 
DD.REFCASAACCT,DD.BALANCE, 
DD.HOLDBALANCE, DD.receiving
,DD.NETTING, DD.PENDINGHOLD, 
DD.pendingunhold,ALLCODE.CDCONTENT STATUS, 
ALLCODE.EN_CDCONTENT STATUS_EN
from DDMAST DD,AFMAST AF, CFMAST CF, ALLCODE
where CF.custid = AF.CUSTID AND AF.ACCTNO = DD.AFACCTNO 
AND ALLCODE.CDTYPE = ''CI'' AND ALLCODE.CDNAME = ''STATUS'' 
AND ALLCODE.cdval = DD.STATUS', 'DDMAST', NULL, NULL, NULL, NULL, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;