SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('ISSUES_NO','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('ISSUES_NO', 'Danh sách mã đợt phát hành', 'Issuance code', 'SELECT * FROM (SELECT DISTINCT  SB.ISSUECODE, SB.ISSUEDATE, A0.CDCONTENT ISSUETYPE 
FROM ISSUES SB , ALLCODE A0 
WHERE A0.CDTYPE = ''CB'' AND
      A0.CDNAME = ''CONTRACTTYPE'' AND
      A0.CDVAL = SB.TYPERATE  ) WHERE 0=0 ', 'ISSUES_NO', '', '', '', NULL, 5000, 'N', 30, '', 'Y', 'T', '', 'N', '');COMMIT;