SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CF0090','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CF0090', 'Do giao dich 0090', 'Transaction 0090', 'SELECT CF.CUSTID,CF.USERNAME,CF.CUSTODYCD, ''AAA'' LOGINPWD ,''BBB'' TRADINGPWD,
30 DAY ,  ''Y'' ISMASTER,CF.EMAIL
FROM (SELECT * FROM CFMASTCV WHERE EMAIL IS NOT NULL) US , CFMAST CF
WHERE TRIM(US.CUSTODYCD)= CF.CUSTODYCD
 AND CF.CUSTID NOT IN (SELECT  MSGACCT FROM TLLOG WHERE TLTXCD =''0090'')', 'USERLIMIT', 'frmSATLID', '', '0090', NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;