SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SE2203S','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('SE2203S', 'Tra cứu chứng khoán bị tạm giữ (VSD)', 'View securities blocked (VSD)', 'SELECT FN_GET_LOCATION(AF.BRID) LOCATION, CF.CUSTODYCD, AF.ACCTNO AFACCTNO, SE.ACCTNO, DT.CODEID, DT.SYMBOL, SE.BLOCKED,  
    SE.EMKQTTY, DT.PARVALUE, DT.TRADEPLACE, SE.CONTRACT_NO, SE.QTTYTYPE,
    DT.PRICE, CF.ADDRESS, CF.FULLNAME, CF.IDCODE, NVL(DTL.CONFIRMQTTY, 0) CONFIRMQTTY, A1.CDCONTENT C_QTTYTYPE
FROM CFMAST CF, AFMAST AF, SEMAST, 
(
    SELECT ACCTNO, CONTRACT_NO, QTTYTYPE, SUM(QTTY) QTTY,
        SUM(CASE WHEN QTTYTYPE = ''002'' THEN QTTY ELSE 0 END) BLOCKED,
        SUM(CASE WHEN QTTYTYPE = ''007'' THEN QTTY ELSE 0 END) EMKQTTY
    FROM SEMASTDTL 
    WHERE DELTD = ''N''
    AND CONTRACT_NO IS NOT NULL
    GROUP BY ACCTNO, CONTRACT_NO, QTTYTYPE
) SE,
(SELECT ACCTNO, SUM (QTTY) QTTY FROM SEMORTAGE WHERE STATUS =''N'' AND DELTD <> ''Y'' GROUP BY ACCTNO) SEM,
(SELECT SSEACCTNO ACCTNO, SUM(BLOCKEDQTTY) QTTY FROM ESCROW ES WHERE ES.DELTD <> ''Y'' GROUP BY SSEACCTNO) ER,
(
    SELECT SB.SYMBOL, SB.CODEID, SB.PARVALUE, SEIN.PREVCLOSEPRICE PRICE, A4.CDCONTENT TRADEPLACE
    FROM SECURITIES_INFO SEIN, SBSECURITIES SB, ALLCODE A4
    WHERE SB.CODEID = SEIN.CODEID
    AND A4.CDTYPE = ''SE''
    AND A4.CDNAME = ''TRADEPLACE''
    AND A4.CDVAL = SB.TRADEPLACE
) DT,
(
    SELECT SB.CODEID, DTL.CUSTODYCD, DTL.CONTRACT_NO, SUM(DTL.RELEASEQTTY) RELEASEQTTY, SUM(DTL.CONFIRMQTTY - DTL.EXECQTTY) CONFIRMQTTY
    FROM SEBLOCKEDDTL DTL, SBSECURITIES SB
    WHERE DTL.RELEASEQTTY > 0 
    AND DTL.CONFIRMQTTY - DTL.EXECQTTY > 0 
    AND DTL.SYMBOL = SB.SYMBOL
    GROUP BY SB.CODEID, DTL.CUSTODYCD, DTL.CONTRACT_NO
)DTL,
(
    SELECT * FROM ALLCODE 
    WHERE CDTYPE = ''SE'' 
    AND CDNAME=''QTTYTYPE'' 
    AND CDVAL IN (''002'',''007'')
) A1
WHERE AF.CUSTID = CF.CUSTID
AND SUBSTR(SE.ACCTNO,1, 10) = AF.ACCTNO
AND SUBSTR(SE.ACCTNO, 11, 6) = DT.CODEID
AND SE.CONTRACT_NO = DTL.CONTRACT_NO(+)
AND DT.CODEID = DTL.CODEID(+)
AND CF.CUSTODYCD = DTL.CUSTODYCD(+)
AND SE.ACCTNO = SEMAST.ACCTNO(+)
AND SE.ACCTNO = SEM.ACCTNO(+)
AND SE.ACCTNO = ER.ACCTNO(+)
AND SE.QTTYTYPE = A1.CDVAL', 'SEMAST', '', '', '2203', NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;