SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('IRRATE','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('IRRATE', 'Quản lý lịch lãi cài đặt trước', 'Management calendar interest presets', 'SELECT RATEID, RATENAME,S.SHORTCD CCYCD, RATE,FLRRATE,CELRATE,EFFECTIVEDT,A.CDCONTENT STATUS, REFNAME, A2.CDCONTENT RATETERMCD, RATETERM,
B.CDCONTENT OPERAND, DELTA, BASEDRATE, MINVAL, MAXVAL,
(CASE WHEN STATUS IN (''P'') THEN ''Y'' ELSE ''N'' END) APRALLOW
FROM IRRATE, ALLCODE A, ALLCODE B, SBCURRENCY S, ALLCODE A2
WHERE A.CDTYPE = ''SA'' AND A.CDNAME = ''STATUS''
AND A.CDVAL=STATUS AND S.CCYCD=IRRATE.CCYCD
AND B.CDTYPE = ''SY'' AND B.CDNAME=''OPERAND'' AND B.CDVAL=OPERAND
AND RATETERMCD = A2.CDVAL AND A2.CDNAME =''RATETERMCD'' AND A2.CDTYPE =''SA''', 'IRRATE', 'frmIRRATE', '', '', NULL, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;