SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CF0065','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CF0065', 'Tra cứu trạng thái gửi SMS và Email', 'SMS/Email sent status', 'SELECT E.EMAIL,TO_CHAR(E.SENTTIME,''HH24:MI:SS'') SENTTIME, TO_CHAR(E.CREATETIME,''HH24:MI:SS'') CREATETIME, TO_DATE(TO_CHAR(E.CREATETIME,''DD/MM/RRRR''),''DD/MM/RRRR'') CREATEDATE,
    TEMPLATEID, E.SUBJECT, MST.CUSTODYCD,
    DECODE(T.TYPE,''E'',''EMAIL'',''S'',''SMS'') TYPE, E.AUTOID,
    DECODE(CREATETYPE,''C'', ''Y'', ''N'') CREATETYPE,
    E.DATASOURCE, NVL(A1.CDCONTENT, E.STATUS) STATUS, NVL(A1.CDVAL, E.STATUS) STATUS_VALUE, E.NOTE, R.REFRPTFILE FILENAME,
    E.REFID
FROM TEMPLATES T, VW_AFMAST_CUSTODYCD MST, RPTLOGS R,
(
    SELECT * FROM EMAILLOG
    UNION ALL
    SELECT * FROM EMAILLOGHIST WHERE TO_DATE( TO_CHAR(CREATETIME,''DD/MM/YYYY''),''DD/MM/YYYY'') >= TO_DATE( TO_CHAR(SYSDATE,''DD/MM/YYYY''),''DD/MM/YYYY'') - 90
) E,
(SELECT * FROM ALLCODE WHERE CDNAME = ''EMAILSTATUS'' AND CDTYPE = ''SY'') A1
WHERE E.AFACCTNO =MST.ACCTNO(+) AND E.TEMPLATEID = T.CODE
AND E.STATUS = A1.CDVAL(+)
AND E.STATUS <> ''L''
AND E.REFRPTLOGS = R.AUTOID(+)', 'CFLINK', '', 'CREATEDATE DESC, CREATETIME DESC', '0065', NULL, 1000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;