SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('ODCTCIVIEW','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('ODCTCIVIEW', 'Quan ly so lenh CTCI', 'CTCI Order view', 'SELECT * FROM V_CTCIVIEW where
CUSTID in(
SELECT CUSTID FROM AFMAST WHERE ACCTNO=''<$AFACCTNO>''
UNION ALL
SELECT  CUSTID FROM  AFMAST WHERE CUSTID=''<$CUSTID>''
UNION
SELECT  cfauth.CFCUSTID CUSTID FROM CFAUTH WHERE CFAUTH.CUSTID=''<$CUSTID>'' AND SUBSTR(LINKAUTH,4,2)IN (''YY'',''YN'',''NY''))', 'OD.ODMAST', 'frmCTCIVIEW', 'MATCHTIME DESC', '', NULL, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;