SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA1008','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CA1008', 'Danh sách phân bổ chứng khoán đặt mua (đối chiếu)', 'Danh sách phân bổ chứng khoán đặt mua (đối chiếu)', 'SELECT *
FROM
(
    SELECT MCF.CUSTODYCD, CAS.CAMASTID,
        MAX(MCF.CIFID) CIFID, MAX(MCF.IDPLACE) IDPLACE, MAX(MCF.ADDRESS) ADDRESS, MAX(MCF.FULLNAME) FULLNAME,
        DECODE(SUBSTR(MCF.CUSTODYCD,4,1), ''F'', MAX(CF.TRADINGCODE), MAX(MCF.IDCODE)) IDCODE,
        DECODE(SUBSTR(MCF.CUSTODYCD,4,1), ''F'', MAX(CF.TRADINGCODEDT), MAX(MCF.IDDATE)) IDDATE,
        MAX(CAS.AUTOID) AUTOID, MAX(CAS.AFACCTNO) AFACCTNO, MAX(CAS.CODEID) CODEID,
        SUM(CAS.BALANCE) BALANCE, SUM(CAS.QTTY) QTTY, SUM(CAS.AMT) AMT, SUM(CAS.AQTTY) AQTTY, SUM(CAS.AAMT) AAMT, SUM(CAS.TRADE) TRADE, SUM(CAS.PBALANCE) PBALANCE,
        MAX(CA.REPORTDATE) REPORTDATE, MAX(CA.ACTIONDATE) ACTIONDATE, MAX(CA.ISINCODE) ISINCODE,
        MAX(SYM.SYMBOL) SYMBOL,
        MAX(A0.CDVAL) CATYPEVALUE, MAX(A0.<@CDCONTENT>) CATYPE, MAX(A1.<@CDCONTENT>) STATUS
    FROM CASCHD CAS, SBSECURITIES SYM,CAMAST CA, AFMAST AF, CFMAST CF, CFMAST MCF,
        (SELECT * FROM ALLCODE WHERE CDNAME = ''CATYPE'' AND CDTYPE = ''CA'') A0,
        (SELECT * FROM ALLCODE WHERE CDNAME = ''CASTATUS'' AND CDTYPE = ''CA'') A1
    WHERE CAS.CAMASTID = CA.CAMASTID
    AND CA.CODEID = SYM.CODEID
    AND CAS.AFACCTNO = AF.ACCTNO
    AND AF.CUSTID = CF.CUSTID
    AND CA.CATYPE = A0.CDVAL(+)
    AND CAS.STATUS = A1.CDVAL(+)
    AND NVL(CF.MCUSTODYCD, CF.CUSTODYCD) = MCF.CUSTODYCD
    AND CA.CATYPE IN (''014'')
    AND CAS.DELTD =''N''
    GROUP BY MCF.CUSTODYCD, CAS.CAMASTID
) WHERE QTTY > 0', 'CASCHD', 'frmCASCHD', NULL, NULL, NULL, 5000, 'N', 1, 'NYNNYYYNNY', 'Y', 'T', NULL, 'N', NULL);COMMIT;