SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('P_ACCTNO','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('P_ACCTNO', 'Quản lý tiểu khoản', 'Sub account management', 'Select a.*, nvl(LIMITMAX,0)LIMITMAX ,nvl(USERHAVE,0)USERHAVE from
(SELECT CF.SHORTNAME, AF.ACTYPE,AFT.TYPENAME ACNAME, format_custid(AF.CUSTID) CUSTID,CF.FULLNAME FULLNAME,CF.FULLNAME CUSTNAME,
format_custodycd(CF.CUSTODYCD) CUSTODYCD,
CF.CUSTODYCD CUSTODYCD_SRCH,
format_subac(AF.ACCTNO) ACCTNO, AF.AFTYPE,A10.CDCONTENT TYPENAME, A1.CDCONTENT TRADEFLOOR,
A2.CDCONTENT TRADETELEPHONE,A3.CDCONTENT TRADEONLINE,cf.PIN,cf.MOBILESMS TRADEPHONE,CF.IDCODE,CF.IDDATE, CF.IDPLACE,
AF.BANKACCTNO,AF.SWIFTCODE,cf.EMAIL,cf.ADDRESS,cf.FAX, A11.CDCONTENT ISOTC, A12.CDCONTENT VIA,
format_subac(AF.ACCTNO) CIACCTNO,AF.LASTDATE,A8.CDCONTENT STATUS,
AF.ADVANCELINE,AF.DEPOSITLINE,AF.BRATIO,A9.CDCONTENT TERMOFUSE,AF.DESCRIPTION,
GRP.GRPNAME CAREBY, GRP.grpid CAREBYID, CF.REFNAME, AF.corebank,AF.bankname,
AF.MRIRATE,AF.MRMRATE,AF.MRLRATE,AF.MRCRLIMIT,AF.MRCRLIMITMAX,NVL(USF.ACCLIMIT,0) ACCLIMIT,
A0.cdcontent mrtype, A13.CDCONTENT COUNTRY
FROM AFMAST AF,CFMAST CF,AFTYPE AFT, TLGROUPS GRP,MRTYPE MRT, ALLCODE A0,
ALLCODE A1, ALLCODE A2,ALLCODE A3,
ALLCODE A8,ALLCODE A9 ,ALLCODE A10 ,ALLCODE A11,ALLCODE A12, ALLCODE A13,
(SELECT * FROM USERAFLIMIT WHERE  TLIDUSER=''<$TELLERID>'' AND  TYPERECEIVE=''MR'') USF
WHERE AF.CUSTID=CF.CUSTID AND AF.ACTYPE=AFT.ACTYPE AND AFT.MRTYPE=MRT.ACTYPE
AND AF.ACCTNO =USF.ACCTNO (+)
AND AF.CAREBY = GRP.GRPID AND GRP.GRPTYPE = ''2''
AND AFT.ACTYPE = AF.ACTYPE
AND A0.CDTYPE = ''SA''   AND A0.CDNAME = ''MARGINTYPE''   AND A0.CDVAL = MRT.MRTYPE
AND A1.CDTYPE = ''SY'' AND A1.CDNAME = ''YESNO'' AND A1.CDVAL= CF.TRADEFLOOR
AND A2.CDTYPE = ''SY'' AND A2.CDNAME = ''YESNO'' AND A2.CDVAL= CF.TRADETELEPHONE
AND A3.CDTYPE = ''SY'' AND A3.CDNAME = ''YESNO'' AND A3.CDVAL= cf.TRADEONLINE
AND A8.CDTYPE = ''CF'' AND A8.CDNAME = ''STATUS'' AND A8.CDVAL = AF.STATUS
AND A9.CDTYPE = ''CF'' AND A9.CDNAME = ''TERMOFUSE'' AND A9.CDVAL = AF.TERMOFUSE
AND A10.CDTYPE = ''CF'' AND A10.CDNAME = ''AFTYPE''AND A10.CDVAL = AF.AFTYPE
AND A11.CDTYPE = ''SY'' AND A11.CDNAME = ''YESNO'' AND A11.CDVAL= AF.ISOTC
AND A12.CDTYPE = ''CF'' AND A12.CDNAME = ''VIA'' AND A12.CDVAL= AF.VIA
AND A13.CDTYPE = ''CF'' AND A13.CDNAME = ''COUNTRY'' AND A13.CDVAL= CF.COUNTRY
AND (SUBSTR(CF.CUSTID,1,4) = DECODE(''<$BRID>'', ''<$HO_BRID>'', SUBSTR(CF.CUSTID,1,4), ''<$BRID>'')
    OR AF.CAREBY IN (SELECT TLGRP.GRPID FROM TLGRPUSERS TLGRP WHERE TLID = ''<$TELLERID>'')))a
LEFT JOIN
(Select NVL(US.ACCTLIMIT,0) LIMITMAX,NVL(US.ALLOCATELIMMIT-US.USEDLIMMIT,0) USERHAVE
  from userlimit US where US.tliduser=''<$TELLERID>'') us on 0=0', 'AFMAST', 'frmAFMAST', NULL, NULL, NULL, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;