SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('AP0003','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('AP0003', '1413 Giảm số dư VSE2210 cặp 1414', '1413 Decrease VSE2210 pair 1414', 'SELECT  CR.CRPHYSAGREEID,CR.NO CRPHYSAGREENO,CF.CUSTODYCD,CF.FULLNAME,CR.SYMBOL,CR.CODEID,CR.QTTY CRQTTY,SE.TRADE TRADESEMAST,
        (NVL(NH.QTTY_NHAP,0) + NVL(RUT.ICQTTY,0) - NVL(RUT.QTTY_RUT,0) - NVL(B.QTTY_BAN,0) + NVL(Q1444.QTTY_1444,0))MAXQTTY,
        (NVL(NH.QTTY_NHAP,0) + NVL(RUT.ICQTTY,0) - NVL(RUT.QTTY_RUT,0) - NVL(B.QTTY_BAN,0) + NVL(Q1444.QTTY_1444,0)) QTTY,(CR.ACCTNO||CR.CODEID) ACCTNO
    FROM    (SELECT CRPHYSAGREEID,SUM(QTTY)QTTY_NHAP FROM CRPHYSAGREE_LOG WHERE TYPE =''R''  GROUP BY CRPHYSAGREEID)NH ,
            (SELECT CRPHYSAGREEID,SUM(WDQTTY)QTTY_RUT, SUM(ICQTTY) ICQTTY FROM CRPHYSAGREE_WITHDRAW_LOG  GROUP BY CRPHYSAGREEID)RUT,
            (SELECT CRPHYSAGREEID,SUM(QTTY) QTTY_BAN FROM CRPHYSAGREE_SELL_LOG GROUP BY CRPHYSAGREEID)B,
            (SELECT CRPHYSAGREEID,SUM(QTTY) QTTY_1444 FROM CRPHYSAGREE_LOG_ALL WHERE TLTXCD = ''1444'' GROUP BY CRPHYSAGREEID) Q1444,
            CRPHYSAGREE CR,SEMAST SE,CFMAST CF
    WHERE   CR.CRPHYSAGREEID = B.CRPHYSAGREEID(+)
        AND CR.CRPHYSAGREEID = NH.CRPHYSAGREEID(+)
        AND CR.CRPHYSAGREEID = RUT.CRPHYSAGREEID(+)
        AND CR.CRPHYSAGREEID = Q1444.CRPHYSAGREEID(+)
        AND CR.ACCTNO||CR.CODEID = SE.ACCTNO
        AND CR.ACCTNO = CF.CUSTID', 'CRPHYSAGREE', '', '', '1413', 0, 5000, 'N', 1, 'NNNNYNYNNNN', 'Y', 'T', '', 'N', '');COMMIT;