SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CF0024','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CF0024', 'Danh sách tài khoản hoạt động nhưng các tài khoản tiền đóng hết', 'List of active custodycd code but closing bank current account', 'SELECT DD.CUSTODYCD,DD.AFACCTNO,CF.FULLNAME,A1.<@CDCONTENT> STATUS,DD.REFCASAACCT DDACCTNO,A3.<@CDCONTENT> ACCOUNTTYPE,A2.<@CDCONTENT> CCYCD,DD.LAST_CHANGE CLOSEDATE
FROM CFMAST CF, DDMAST DD, ALLCODE A1, ALLCODE A2,ALLCODE A3
WHERE      CF.STATUS  = ''A'' 
      AND  DD.STATUS = ''C'' 
      AND  A1.CDNAME = ''STATUS'' 
      AND  A1.CDVAL = ''C'' 
      AND  A1.CDTYPE = ''CF'' 
      AND  A1.CDVAL = DD.STATUS 
      AND  A2.CDTYPE=''FA'' 
      AND  A2.CDNAME=''CCYCD'' 
      AND  A2.CDVAL = DD.CCYCD
      AND  DD.CUSTODYCD  = CF.CUSTODYCD
      AND  A3.CDNAME = ''ACCOUNTTYPE''
      AND  A3.CDTYPE = ''DD''       
      AND  CF.accounttype = A3.cdval', 'CFMAST', NULL, NULL, NULL, NULL, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;