SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SE2249','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('SE2249', 'Tra cứu hoàn tất đóng tiểu khoản (2249)', 'View sub account ready for close  (2249)', 'SELECT CF.CUSTODYCD, AF.ACCTNO,
FN_GET_LOCATION(MAX(AF.BRID)) LOCATION,
MAX(CF.FULLNAME) FULLNAME,
MAX(CF.IDCODE) IDCODE,
MAX(TYP.TYPENAME) TYPENAME,
NVL(MAX(SE.LASTDATE), MAX(AF.LASTDATE)) LASTDATE
FROM AFMAST AF, DDMAST CI, CFMAST CF, AFTYPE TYP,
    (
        SELECT SE.* FROM SEMAST SE, SBSECURITIES SB WHERE SE.CODEID = SB.CODEID AND SB.SECTYPE <> ''004''
    ) SE,
    (
        SELECT MST.CATYPE, SCHD.* FROM CASCHD SCHD, CAMAST MST WHERE MST.CAMASTID = SCHD.CAMASTID AND SCHD.DELTD=''N''
    ) CA
WHERE TYP.ACTYPE = AF.ACTYPE
AND CF.CUSTID = AF.CUSTID
AND AF.ACCTNO = SE.AFACCTNO(+)
AND AF.ACCTNO = CA.AFACCTNO (+)
AND AF.ACCTNO = CI.AFACCTNO (+)
AND AF.STATUS = ''N''
AND (CA.AFACCTNO IS NULL OR CA.STATUS NOT IN (''A'',''S'') OR (CA.ISSE = ''Y'' AND CA.QTTY > 0) OR (CA.ISCI = ''Y'' AND CA.AMT > 0) OR (CA.STATUS = ''A'' AND CA.CATYPE = ''014'') OR (CA.STATUS = ''S'' AND CA.CATYPE = ''014'' AND CA.QTTY = 0 ))
GROUP BY CF.CUSTODYCD, AF.ACCTNO
HAVING SUM(NVL(SE.DTOCLOSE,0))+SUM(NVL(SE.TRADE,0)) + SUM(NVL(SE.BLOCKDTOCLOSE,0))=0', 'SEMAST', '', '', '2249', NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;