SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SE2239','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('SE2239', 'Yêu cầu giải tạm giữ cố lên VSD', 'Register release securities temporary hold to VSD', 'SELECT MT.AUTOID, SE.AFACCTNO AFACCTNO, SE.ACCTNO ACCTNO, CF.FULLNAME CUSTNAME, CF.CUSTODYCD, SB.SYMBOL,
    SB.PARVALUE,  MT.QTTY - NVL(RL.QTTY,0) QTTY, SB.CODEID, CF.ADDRESS, CF.IDCODE LICENSE,
    MT.CRPLACEID, MT.CRFULLNAME, MT.MDATE, MT.NUM_MG, I1.AUTOID ISSUESID, I1.ISSUECODE,CF.MCUSTODYCD,
    TO_CHAR(MT.REQID) REQID
FROM SEMORTAGE MT, SEMAST SE, SBSECURITIES SB, AFMAST AF, CFMAST CF, ISSUES I1,
(SELECT REFID, SUM(QTTY) QTTY FROM SEMORTAGE WHERE TLTXCD = ''2239'' AND DELTD = ''N'' AND REFID IS NOT NULL GROUP BY REFID) RL
WHERE MT.ACCTNO = SE.ACCTNO AND SE.CODEID = SB.CODEID
AND SE.AFACCTNO = AF.ACCTNO AND AF.CUSTID = CF.CUSTID
AND MT.AUTOID = RL.REFID (+)
AND MT.STATUS IN (''C'',''E'') AND MT.CRPLACEID IS NOT NULL
AND MT.QTTY - NVL(RL.QTTY,0) > 0 AND SE.EMKQTTY > 0
AND MT.ISSUESID = I1.AUTOID(+)', 'SEMAST', '', '', '2239', 0, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;