SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3358','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CA3358', 'Gửi hồ sơ chuyển nhượng quyền mua lên VSD(GD 3358)', 'Send outward Tranfer to VSD (Trans 3358)', 'SELECT MST.AUTOID, MST.CAMASTID, MST.NOTRANSCT, SB1.SYMBOL, SB2.SYMBOL TOSYMBOL,
    MST.TOACCTNO TOCUSTODYCD,CFT.CIFID TOCIFID,MST.CUSTNAME2,MST.IDDATE2, MST.CUSTODYCD,CF.FULLNAME, CF.IDDATE, CF.CIFID,
    MST.REMOACCOUNT,MST.CITAD,MST.TOMEMCUS,MST.AMT QTTY,MST.TRANSFERPRICE EXPRICE,MST.AMT*MST.TRANSFERPRICE AMOUNT,
    CF.MCUSTODYCD, CFT.PCOD BUYRPCOD
FROM CATRANSFER MST, SBSECURITIES SB1, SBSECURITIES SB2, CFMAST CF, CFMAST CFT, CAMAST CA
WHERE MST.CODEID = SB1.CODEID 
AND MST.OPTCODEID = SB2.CODEID 
AND MST.CUSTODYCD = CF.CUSTODYCD(+) 
AND MST.TOACCTNO = CFT.CUSTODYCD(+)
AND MST.CAMASTID = CA.CAMASTID
AND MST.STATUS = ''H'' 
AND MST.MSGSTATUS IN (''P'',''N'',''R'') 
AND MST.OPTSEACCTNODR IS NOT NULL', 'CAMAST', '', '', '3358', NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;