SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA1049','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CA1049', 'Danh sách các sự kiện quyền sắp đến ngày phân bổ', 'List of CA to upcoming allocation date', '
SELECT CA.VALUE, CA.AUTOID,CA.SYMBOL,
           CA.CAMASTID,
           CA.CODEID, CA.EXCODEID,CA.TYPEID,A1.EN_CDCONTENT CATYPE, CA.KHQDATE, CA.REPORTDATE, CA.DUEDATE,
           CA.ACTIONDATE, CA.BEGINDATE, CA.EXPRICE, CA.EXRATE, CA.RIGHTOFFRATE, CA.OPTCODEID, CA.DEVIDENTSHARES,
           CA.SPLITRATE, CA.INTERESTRATE, CA.DESCRIPTION,CA.CONTENTS, CA.INTERESTPERIOD,A2.EN_CDCONTENT STATUS, CA.FRDATERETAIL,
           CA.TODATERETAIL, CA.TRFLIMIT,
          CA.ROPRICE,
          CA.TVPRICE,
          CA.RATE,
          CA.PITRATE, CA.PITRATEMETHOD_CD,CA.PITRATEMETHOD,
          CA.CATYPEVAL, CA.FRDATETRANSFER, CA.TODATETRANSFER, CA.APRALLOW,
          CA.PITRATESE,  CA.INACTIONDATE, CA.AMT, CA.QTTY,
          CA.TAXAMT,CA.AMTAFTER,
          CA.STATUSVAL, CA.ISCHANGESTT,
          CA.MAKERID,CA.APPRVID,
          CA.ISRIGHTOFF,
          CA.TRADE, CA.TRADE3375,
          CA.TOSYMBOL,CA.TOCODEID,
          CA.CAQTTY,CA.CANCELDATE,
          CA.RECEIVEDATE,
          CA.ISINCODE, CA.ADVDESC, CA.TYPERATE, CA.DEVIDENTRATE,  CA.DEVIDENTVALUE,
          CA.REMAINDEVIDENTRATE,
          CA.REMAINDEVIDENTVALUE,
          CA.TRADEDATE,CA.RATE1, CA.STATUS1
--FROM V_CAMAST ca, sysvar a, sysvar b,ALLCODE A1, ALLCODE A2
FROM V_CAMAST_CA1049 ca, sysvar a, sysvar b,ALLCODE A1, ALLCODE A2
WHERE a.GRNAME = ''SYSTEM'' AND a.VARNAME =''CURRDATE''
    and b.GRNAME = ''CA'' AND b.VARNAME =''CAWARNINGDAYS''
    and ca.ACTIONDATE >= getprevdate(to_date(a.VARVALUE,''dd/MM/rrrr''),to_number(b.VARVALUE)+1)
    --and ca.ACTIONDATE - to_date(a.VARVALUE,''dd/MM/rrrr'') <= to_number(b.VARVALUE)
    and ca.statusval not in (''J'',''C'')
      AND A1.CDTYPE = ''CA''
      AND A1.CDNAME = ''CATYPE'' AND A1.CDVAL = CA.CATYPE
      AND A2.CDTYPE = ''CA'' AND A2.CDNAME = ''CASTATUS''
      AND CA.STATUS = A2.CDVAL', 'CAMAST', 'frmCAMAST', 'AUTOID DESC', NULL, NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;