SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('INDEX_INFO','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('INDEX_INFO', 'Quản lý thông tin chỉ số thị trường', 'Management of Index information', 'SELECT MI.*, A1.<@CDCONTENT> CREQSTATUS, A2.<@CDCONTENT> CINDEXCATEGORY, A3.<@CDCONTENT> CEXCHANGE, ''N'' APRALLOW
FROM INDEX_INFO MI,
(SELECT * FROM ALLCODE WHERE CDNAME = ''SYNC_AITHER_STATUS'' AND CDTYPE = ''SA'') A1,
(SELECT * FROM ALLCODE WHERE CDNAME = ''SYNC_AITHER_INDEXCATEGORY'' AND CDTYPE = ''SA'') A2,
(SELECT * FROM ALLCODE WHERE CDNAME = ''SYNC_AITHER_EXCHANGE'' AND CDTYPE = ''SA'') A3
WHERE MI.REQSTATUS = A1.CDVAL(+)
AND MI.INDEXCATEGORY = A2.CDVAL(+)
AND MI.EXCHANGE = A3.CDVAL(+)', 'INDEX_INFO', 'frmINDEX_INFO', 'AUTOID DESC', '', 0, 5000, 'N', 1, 'YYYYYYYNNNN', 'Y', 'T', '', 'N', '');COMMIT;