SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('USERLOGIN','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('USERLOGIN', 'Thông tin đăng ký dịch vụ trực tuyến', 'Online service registration information', 'SELECT DT.*
FROM
(
    SELECT UL.USERNAME, UL.ROLE, UL.EMAIL, A1.CDCONTENT AUTHTYPEDESC, UL.ROLECD, A2.CDCONTENT STATUS, LISTCUSTODYCD, REFFAMEMBERID, CUSTODYCD, UL.AUTHTYPE, UL.LASTCHANGED,
        CASE WHEN STATUS = ''P'' THEN ''Y'' ELSE ''N'' END APRALLOW,
        CASE WHEN STATUS = ''E'' THEN ''N'' ELSE ''Y'' END EDITALLOW
    FROM USERLOGIN UL
    INNER JOIN (SELECT * FROM ALLCODE WHERE CDTYPE = ''CF'' AND CDNAME = ''OTAUTHTYPE'' ) A1 ON UL.AUTHTYPE = A1.CDVAL
    LEFT JOIN (SELECT * FROM ALLCODE WHERE CDTYPE = ''DF'' AND CDNAME = ''STATUS'' ) A2 ON UL.STATUS = A2.CDVAL
    ORDER BY UL.LASTCHANGED DESC
) DT,
(
    SELECT LG.TO_VALUE USERNAME, TL.TLGROUP TLGROUP
    FROM MAINTAIN_LOG LG, TLPROFILES TL
    WHERE TABLE_NAME = ''USERLOGIN''
    AND COLUMN_NAME = ''USERNAME''
    AND ACTION_FLAG = ''ADD''
    AND LG.MAKER_ID = TL.TLID
    AND TL.TLGROUP IN (''013'')
    UNION ALL
    SELECT USERNAME, ''000'' TLGROUP FROM USERLOGIN
) A1,
(
    SELECT * FROM TLPROFILES TL WHERE TLID = ''<$TELLERID>''
) TL
WHERE (CASE WHEN TL.TLGROUP IN (''013'') THEN TL.TLGROUP ELSE ''000'' END) = A1.TLGROUP
AND DT.USERNAME = A1.USERNAME', 'USERLOGIN', 'frmUSERLOGIN', NULL, NULL, 0, 5000, 'N', 1, 'YYYYYYYYYNY', 'Y', 'T', NULL, 'N', NULL);COMMIT;