SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SYN_AITHER_REQ','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('SYN_AITHER_REQ', 'Tra cứu lịch sử đồng bộ dữ liệu vận hành qua DNA', 'History of operation data sync to DNA (without customer)', 'SELECT MI.*, BODYREQ DESCRIPTION, A1.<@CDCONTENT> CSTATUS, ''N'' APRALLOW,
    TO_CHAR(CREATED_AT, ''DD/MM/RRRR HH24:MI:SS'') CCREATED_AT, 
    TO_CHAR(TXDATE, ''DD/MM/RRRR'') CTXDATE
FROM SYN_AITHER_REQ MI,
(SELECT * FROM ALLCODE WHERE CDNAME = ''SYNC_AITHER_STATUS'' AND CDTYPE = ''SA'') A1
WHERE MI.STATUS = A1.CDVAL(+)', 'SYN_AITHER_REQ', 'frmSYN_AITHER_REQ', 'AUTOID DESC', '6632', 0, 5000, 'N', 1, 'NNNNYYYNNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;