SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('OD0016','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('OD0016', 'Danh sách lệnh đã thanh toán bù trừ', 'List of clearing orders', 'SELECT OD.ORDERID,OD.SYMBOL,OD.CUSTODYCD,DD.REFCASAACCT,OD.CLEARDATE SETTLEMENT,FA.SHORTNAME BROKER,A1.<@CDCONTENT> TYPEORDER,A1.CDVAL CDVALTYPEORDER,
    (CASE WHEN CF.FEEDAILY =''Y'' THEN OD.NETAMOUNT ELSE OD.EXECAMT END) AMT,
    A2.<@CDCONTENT> STATUSUNHOLD, A2.CDVAL CDVALSTATUSUNHOLD,
    A4.<@CDCONTENT> STATUSPAYMENT, A4.CDVAL CDVALSTATUSPAYMENT,
    (CASE WHEN OD.exectype =''NB'' THEN A5.<@CDCONTENT> ELSE A6.<@CDCONTENT> END) STATUSOD,
    (CASE WHEN OD.EXECTYPE = ''NB'' THEN A5.CDVAL ELSE A6.CDVAL END) CDVALSTATUSOD,
    A7.<@CDCONTENT> ASSETTYPE
FROM ODMAST OD, DDMAST DD, FAMEMBERS FA, CFMAST CF, SBSECURITIES SB,
(SELECT * FROM ALLCODE WHERE CDNAME = ''ORDERSIDE'' AND CDTYPE = ''OD'') A1,
(SELECT * FROM ALLCODE WHERE CDNAME = ''ISHOLD'' AND CDTYPE = ''OD'') A2,
(SELECT * FROM ALLCODE WHERE CDNAME = ''ISPAYMENT'' AND CDTYPE = ''OD'') A4,
(SELECT * FROM ALLCODE WHERE CDNAME = ''ISSEMAST'' AND CDTYPE = ''OD'') A5,
(SELECT * FROM ALLCODE WHERE CDNAME = ''ISSEMASTNS'' AND CDTYPE = ''OD'') A6,
(SELECT * FROM ALLCODE WHERE CDNAME = ''ASSETTYPE'' AND CDTYPE = ''OD'') A7
WHERE OD.DDACCTNO = DD.ACCTNO
AND OD.MEMBER = FA.AUTOID
AND OD.CUSTID = CF.CUSTID
AND OD.CODEID = SB.CODEID
AND DD.STATUS <> ''C''
AND FA.STATUS <> ''C''
AND OD.EXECTYPE = A1.CDVAL(+)
AND OD.ISHOLD = A2.CDVAL(+)
AND OD.ISPAYMENT = A4.CDVAL(+)
AND OD.ORSTATUS = A5.CDVAL(+)
AND OD.ORSTATUS = A6.CDVAL(+)
AND (CASE WHEN SB.TRADEPLACE = ''099'' THEN ''TPRL'' ELSE ''CKNY'' END) = A7.CDVAL(+)
/*AND  NOT EXISTS (
    SELECT F.CVALUE
    FROM TLLOG TL, TLLOGFLD F
    WHERE TL.TXNUM = F.TXNUM
    AND TL.TXDATE = F.TXDATE AND TL.TLTXCD = ''8805'' AND F.FLDCD = ''01''
    AND TL.TXSTATUS IN(''1'', ''4'') AND F.CVALUE = OD.ORDERID AND OD.ISPAYMENT = ''N'')*/', 'OD0016', 'frmODMAST', NULL, '8805', NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;