SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('RPMAST','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('RPMAST', 'Quản lý Tiểu khoản Repo', 'Repo sub account management', 'SELECT ACTYPE, SUBSTR(ACCTNO,1,4) || ''.'' || SUBSTR(ACCTNO,5,6) || ''.'' || SUBSTR(ACCTNO,11,6) ACCTNO, SUBSTR(CUSTID,1,4) || ''.'' || SUBSTR(CUSTID,5,6) CUSTID, SUBSTR(AFACCTNO,1,4) || ''.'' || SUBSTR(AFACCTNO,5,6) AFACCTNO, SUBSTR(CIACCTNO,1,4) || ''.'' || SUBSTR(CIACCTNO,5,6) CIACCTNO,OPNDATE,SPOTDATE,FORWARDDATE,LASTDATE,A1.CDCONTENT STATUS,

PSTATUS,SPOTCODEID,SPOTRATE,SPOTBUY,SPOTSELL,SPOTQTTY,FORWARDCODEID,FORWARDRATE,

FORWARDBUY,FORWARDSELL,FORWARDQTTY,DESCRIPTION 

from RPMAST,ALLCODE A1

WHERE 

A1.CDTYPE = ''RP'' AND A1.CDNAME = ''STATUS'' AND A1.CDVAL= STATUS', 'RPMAST', 'frmRPMAST', '', '', NULL, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;