SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('RECFDEF_01','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('RECFDEF_01', 'Loại hình đại lý/môi giới', 'Broker/Remiser product', 'SELECT (CF.CUSTID||''.''||RF.REACTYPE) REACCT, RF.AUTOID, CFMAST.FULLNAME, TYP.ACTYPE, TYP.TYPENAME, A2.CDCONTENT AFSTATUS, 
typ.rerole,A0.CDCONTENT DESC_REROLE, A1.CDCONTENT DESC_RETYPE, RF.EFFDATE, RF.EXPDATE,RF.ODRNUM, (CFMAST.FULLNAME || ''/''|| TYP.TYPENAME || ''/''||A2.CDCONTENT) DESC_TYPE, CF.CUSTID
FROM RECFDEF RF, RETYPE TYP, ALLCODE A0, ALLCODE A1, ALLCODE A2, RECFLNK CF, CFMAST
WHERE A0.CDTYPE=''RE'' AND A0.CDNAME=''REROLE'' AND A0.CDVAL=TYP.REROLE
AND A2.CDTYPE = ''RE'' AND A2.CDNAME = ''AFSTATUS'' AND A2.CDVAL = TYP.AFSTATUS
AND A1.CDTYPE=''RE'' AND A1.CDNAME=''RETYPE'' AND A1.CDVAL=TYP.RETYPE
AND RF.REACTYPE=TYP.ACTYPE 
AND RF.REFRECFLNKID = CF.AUTOID
AND CF.CUSTID = CFMAST.CUSTID', 'RE.RECFDEF_01', 'frmRECFDEF_01', 'ACTYPE,TYPENAME,FULLNAME', NULL, 0, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;