SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('AP1416','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('AP1416', 'Giảm Physical( Không tính phí)', 'Decrease Physical ( none fee)', 'SELECT  CR.CRPHYSAGREEID,CR.NO CRPHYSAGREENO,CF.CUSTODYCD,CF.FULLNAME,CR.SYMBOL,CR.CODEID,CR.QTTY CRQTTY,SE.TRADE TRADESEMAST,
        (NVL(NH.QTTY_NHAP,0) - NVL(RUT.QTTY_RUT,0)) QTTY,(CR.ACCTNO||CR.CODEID) ACCTNO
    FROM    (SELECT CRPHYSAGREEID,SUM(QTTY) QTTY_NHAP FROM CRPHYSAGREE_LOG WHERE TYPE =''TRADE1404''  GROUP BY CRPHYSAGREEID)NH ,--Nhap 1415
            (SELECT CRPHYSAGREEID,SUM(QTTY) QTTY_RUT FROM CRPHYSAGREE_LOG WHERE TYPE =''RUT1404''  GROUP BY CRPHYSAGREEID)RUT,--Rut 1416
            (SELECT CRPHYSAGREEID,SUM(QTTY) QTTY_BAN FROM CRPHYSAGREE_SELL_LOG GROUP BY CRPHYSAGREEID)B,
            (SELECT CRPHYSAGREEID,SUM(QTTY) QTTY_1444 FROM CRPHYSAGREE_LOG_ALL WHERE TLTXCD = ''1444'' GROUP BY CRPHYSAGREEID) Q1444,
            CRPHYSAGREE CR,SEMAST SE,CFMAST CF
    WHERE   CR.CRPHYSAGREEID = B.CRPHYSAGREEID(+)
        AND CR.CRPHYSAGREEID = NH.CRPHYSAGREEID(+)
        AND CR.CRPHYSAGREEID = RUT.CRPHYSAGREEID(+)
        AND CR.CRPHYSAGREEID = Q1444.CRPHYSAGREEID(+)
        AND CR.ACCTNO||CR.CODEID = SE.ACCTNO
        AND CR.ACCTNO = CF.CUSTID
        AND (NVL(NH.QTTY_NHAP,0) - NVL(RUT.QTTY_RUT,0)) > 0', 'CRPHYSAGREE', NULL, NULL, '1416', 0, 5000, 'N', 1, 'NNNNYNYNNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;