SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('BROKER_SEMAST','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('BROKER_SEMAST', 'Tra cứu thông tin tài khoản thấu chi', 'Overdraft account information', 'SELECT SYMBOL,TOTAL,TRADE,HOLD,EMKQTTY,MORTAGE,BLOCKED,RECEIVING_T1,RECEIVING_T2
                FROM ( select se.*,(CASE WHEN ST.DUETYPE=''RS'' AND ST.TDAY=0 THEN ST.ST_QTTY ELSE 0 END) RECEIVING_T0,
                           (CASE WHEN ST.DUETYPE=''RS'' AND ST.TDAY=1 THEN ST.ST_QTTY ELSE 0 END) RECEIVING_T1,
                           (CASE WHEN ST.DUETYPE=''RS'' AND ST.TDAY=2 THEN ST.ST_QTTY ELSE 0 END) RECEIVING_T2 ,
                           0 RECEIVING_CA, 0 TOTAL
from  vw_semast_custodycd se,
        (select ST.AFACCTNO, ST.DUETYPE, ST.TXDATE, ST.CLEARCD, ST.CLEARDAY,sb.codeid, SB.SYMBOL,SP_BD_GETCLEARDAY(ST.CLEARCD, MAX(SB.TRADEPLACE), ST.TXDATE, TO_DATE(MAX(SYSVAR.VARVALUE),''DD/MM/RRRR'')) TDAY, SUM(ST.QTTY) ST_QTTY
        FROM STSCHD ST, SYSVAR, SBSECURITIES SB
        WHERE SYSVAR.VARNAME=''CURRDATE'' AND ST.CODEID=SB.CODEID
           and  ST.status = ''N'' AND st.deltd = ''N''
        and    ST.DUETYPE=''RS''
        GROUP BY ST.AFACCTNO, ST.DUETYPE, ST.TXDATE, ST.CLEARCD, ST.CLEARDAY, SB.SYMBOL, sb.codeid) st
where se.afacctno = st.AFACCTno(+)
and se.codeid = st.codeid(+))  WHERE (TRADE+HOLD+EMKQTTY+MORTAGE+BLOCKED+RECEIVING_T1+RECEIVING_T2) >0', 'CIMAST', '', '', '', 0, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;