SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA1003','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CA1003', 'Chia cổ tức bằng tiền(đối chiếu)', 'Cash dividend (compare)', 'SELECT *
FROM
(
    SELECT MCF.CUSTODYCD, CAS.CAMASTID,
        MAX(MCF.CIFID) CIFID, MAX(MCF.IDPLACE) IDPLACE, MAX(MCF.ADDRESS) ADDRESS, MAX(MCF.FULLNAME) FULLNAME,
        DECODE(SUBSTR(MCF.CUSTODYCD,4,1), ''F'', MAX(MCF.TRADINGCODE), MAX(MCF.IDCODE)) IDCODE,
        DECODE(SUBSTR(MCF.CUSTODYCD,4,1), ''F'', MAX(MCF.TRADINGCODEDT), MAX(MCF.IDDATE)) IDDATE,
        MAX(CAS.AUTOID) AUTOID, MAX(CAS.AFACCTNO) AFACCTNO, MAX(CAS.CODEID) CODEID,
        SUM(CAS.BALANCE) BALANCE, SUM(CAS.QTTY) QTTY, SUM(CAS.AMT) AMT, SUM(CAS.AQTTY) AQTTY, SUM(CAS.AAMT) AAMT,
        SUM(CAS.TAXAMT) TAXAMT, SUM(CAS.AMT - CAS.TAXAMT) AMTAFTER,
        MAX(CAS.REPORTDATE) REPORTDATE, MAX(CAS.ACTIONDATE) ACTIONDATE, MAX(CAS.ISINCODE) ISINCODE,
        MAX(CAS.SYMBOL) SYMBOL,
        MAX(CAS.CATYPEVALUE) CATYPEVALUE, MAX(CAS.CATYPE) CATYPE, MAX(CAS.STATUS) STATUS
    FROM
    (
        SELECT SCHD.AUTOID, SCHD.CAMASTID, SCHD.AFACCTNO, NVL(CF.MCUSTODYCD, CF.CUSTODYCD) CUSTODYCD,
             MST.REPORTDATE, MST.ACTIONDATE, MST.ISINCODE, MST.CODEID,
             SYM.SYMBOL,
             SCHD.BALANCE, SCHD.AQTTY, SCHD.AAMT, SCHD.AMT, SCHD.QTTY,
             (ROUND(MST.PITRATE *(CASE WHEN (CASE WHEN SCHD.PITRATEMETHOD=''##'' THEN MST.PITRATEMETHOD ELSE SCHD.PITRATEMETHOD END) =''SC'' THEN 1 ELSE 0 END)
                                *(CASE WHEN CF.VAT=''Y'' THEN SCHD.AMT ELSE 0 END) /100
             )) TAXAMT,
             A0.CDVAL CATYPEVALUE, A0.<@CDCONTENT> CATYPE, A1.<@CDCONTENT> STATUS
        FROM CASCHD SCHD, CAMAST MST, AFMAST AF, AFTYPE AFT, CFMAST CF, SBSECURITIES SYM,
             (SELECT * FROM ALLCODE WHERE CDNAME = ''CATYPE'' AND CDTYPE = ''CA'') A0,
             (SELECT * FROM ALLCODE WHERE CDNAME = ''CASTATUS'' AND CDTYPE = ''CA'') A1
        WHERE AF.CUSTID = CF.CUSTID
        AND MST.CAMASTID = SCHD.CAMASTID
        AND SCHD.AFACCTNO = AF.ACCTNO
        AND AF.ACTYPE = AFT.ACTYPE
        AND MST.CODEID = SYM.CODEID
        AND MST.CATYPE = A0.CDVAL(+)
        AND SCHD.STATUS = A1.CDVAL(+)
        AND MST.CATYPE IN (''010'')
        AND MST.DELTD=''N''
        AND SCHD.DELTD=''N''
    ) CAS, CFMAST MCF
    WHERE CAS.CUSTODYCD = MCF.CUSTODYCD
    GROUP BY MCF.CUSTODYCD, CAS.CAMASTID
) WHERE 0=0', 'CASCHD', 'frmCASCHD', NULL, NULL, NULL, 5000, 'N', 1, 'NYNNYYYNNY', 'Y', 'T', NULL, 'N', NULL);COMMIT;