SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('MT1721','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('MT1721', 'Foreign Exchange Order (Online)', 'Foreign Exchange Order (Online)', 'SELECT L.*, CF.CIFID, A.<@CDCONTENT> CSTATUS, ''Y'' ISONLINE, DD1.BALANCE,
    DD1.REFCASAACCT DDTRANACCTNO, DD2.REFCASAACCT DDRECEACCTNO
FROM LOG_1721 L, CFMAST CF,
(SELECT * FROM DDMAST WHERE STATUS <> ''C'') DD1,
(SELECT * FROM DDMAST WHERE STATUS <> ''C'') DD2,
(SELECT * FROM ALLCODE WHERE CDNAME = ''MT380_STATUS'' AND CDTYPE = ''MT'') A
WHERE L.CUSTODYCD = CF.CUSTODYCD
AND L.STATUS = A.CDVAL(+)
AND L.TRANACCTNO = DD1.ACCTNO(+)
AND L.RECEACCTNO = DD2.ACCTNO(+)
AND L.DELTD = ''N''', '1721', NULL, 'L.AUTOID DESC', '1720', 0, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;