SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('I073_IMP8864ONLINE','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('I073_IMP8864ONLINE', 'Tra c?u thông tin import I073', 'Tra c?u thông tin import I073', '    select nvl( m.shortname ,t.broker_code)BROKER_CODE ,t.TRANS_TYPE,t.CUSTODYCD CUSTODYCD,t.SEC_ID,t.TRADE_DATE,t.SETTLE_DATE,t.QUANTITY,t.PRICE,
           t.GROSS_AMOUNT,t.COMMISSION_FEE,t.TAX,t.NET_AMOUNT,t.MAKER,t.TRANSACTIONTYPE,t.AP,
           t.APACCT,t.ETFDATE,t.TYPE,t.FILEID
   from(
    select BROKER_CODE ,TRANS_TYPE,CUSTODYCD CUSTODYCD,SEC_ID,TRADE_DATE,SETTLE_DATE,QUANTITY,PRICE,
           GROSS_AMOUNT,COMMISSION_FEE,TAX,NET_AMOUNT,TLIDIMP "MAKER",'''' TRANSACTIONTYPE,'''' AP,
           '''' APACCT,TO_CHAR(getcurrdate) ETFDATE,''TABLE'' TYPE,FILEID
    from ODMASTCMP
    union all
    select BROKER_CODE,TRANS_TYPE,ST_CODE CUSTODYCD,SEC_ID,TRADE_DATE,SETTLE_DATE,QUANTITY,PRICE,
           GROSS_AMOUNT,COMMISSION_FEE,TAX,NET_AMOUNT,TLIDIMP "MAKER",'''' TRANSACTIONTYPE,'''' AP,
           '''' APACCT,TO_CHAR(getcurrdate) ETFDATE,''TABLE'' TYPE,FILEID
    from ODMASTCMP_TEMP
    union all
    select BROKER_CODE,TRANS_TYPE,ST_CODE CUSTODYCD,SEC_ID,TRADE_DATE,SETTLE_DATE,QUANTITY,PRICE,
           GROSS_AMOUNT,COMMISSION_FEE,TAX,NET_AMOUNT,TLIDIMP "MAKER",'''' TRANSACTIONTYPE,'''' AP,
           '''' APACCT,TO_CHAR(getcurrdate) ETFDATE,''TABLE'' TYPE,FILEID
     from   odmastcmphist    ) t,(SELECT * FROM FAMEMBERS WHERE ROLES=''BRK'') M
     where t.broker_code= depositmember(+)', 'I073_IMP8864ONLINE', '', '', '', NULL, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;