SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('GLBANK','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('GLBANK', 'Chức năng lưu trữ kế toán đồ', 'Chart of account', 'SELECT GLBANK, GLNAME, 
A1.CDCONTENT MASTER, A2.CDCONTENT ACTYPE,A3.CDCONTENT BALTYPE,A4.CDCONTENT AUTOOPEN,SUBCD,A5.CDCONTENT LASTLEVEL,A6.CDCONTENT PRINDTL FROM GLBANK,
ALLCODE A1,ALLCODE A2,ALLCODE A3,ALLCODE A4,ALLCODE A5, ALLCODE A6 
WHERE A1.CDTYPE = ''SY'' AND A1.CDNAME = ''YESNO'' AND A1.CDVAL=MASTER AND 
A2.CDTYPE = ''GL'' AND A2.CDNAME = ''ACTYPE'' AND A2.CDVAL=ACTYPE AND
A3.CDTYPE = ''GL'' AND A3.CDNAME = ''BALTYPE'' AND A3.CDVAL=BALTYPE AND
A4.CDTYPE = ''SY'' AND A4.CDNAME = ''YESNO'' AND A4.CDVAL=AUTOOPEN AND
A5.CDTYPE = ''SY'' AND A5.CDNAME = ''YESNO'' AND A5.CDVAL=LASTLEVEL AND
A6.CDTYPE = ''SY'' AND A6.CDNAME = ''YESNO'' AND A6.CDVAL=PRINDTL', 'GLBANK', 'frmGLBANK', '', '', NULL, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;