SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CRPHYSAGREE_ORI','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CRPHYSAGREE_ORI', 'Quản lý thông tin hợp đồng đặt mua physical', 'Manage physical subscription agreement ', 'SELECT CR.*, (CR.QTTY-CR.REQTTY) TREMQTTY,(nvl(NH.QTTY_NHAP,0) - NVL(RUT.QTTY_RUT,0) - nvl(B.QTTY_BAN,0)) TOTALQTTY, 0 CHECKVAL
     , A0.EN_CDCONTENT STATUSCNT
     , A1.EN_CDCONTENT PAYSTATUSCNT
     , A2.EN_CDCONTENT BALANCESTATUSCNT
     , A3.EN_CDCONTENT REPOSSTATUSCNT
     , SB.PARVALUE, SB.INTERESTDATE
     , ISS.FULLNAME ISSUERNAME,
     ''Y'' EDITALLOW,
    (CASE WHEN CR.STATUS IN (''P'') THEN ''Y'' ELSE ''N'' END) APRALLOW,
     (CASE WHEN CR.STATUS IN (''P'') THEN ''Y'' ELSE ''N'' END) DELALLOW
FROM CRPHYSAGREE CR,ISSUERS ISS, SBSECURITIES SB, ALLCODE A0, ALLCODE A1,ALLCODE A2,ALLCODE A3,
        (SELECT CRPHYSAGREEID,SUM(QTTY)QTTY_NHAP FROM CRPHYSAGREE_LOG WHERE TYPE =''R''  GROUP BY CRPHYSAGREEID)NH ,
            (SELECT CRPHYSAGREEID,SUM(WDQTTY)QTTY_RUT FROM CRPHYSAGREE_WITHDRAW_LOG  GROUP BY CRPHYSAGREEID)RUT,
            (SELECT CRPHYSAGREEID,SUM(QTTY) QTTY_BAN FROM CRPHYSAGREE_SELL_LOG GROUP BY CRPHYSAGREEID)B
WHERE CR.ISSUERID = ISS.ISSUERID
AND CR.CODEID = SB.CODEID
AND A0.CDVAL =CR.STATUS AND A0.CDTYPE=''AP'' AND A0.CDNAME=''STATUS''
AND A1.CDVAL =CR.PAYSTATUS AND A1.CDTYPE=''AP'' AND A1.CDNAME=''PAYSTATUS''
AND A2.CDVAL =CR.BALANCESTATUS AND A2.CDTYPE=''AP'' AND A2.CDNAME=''BALANCESTATUS''
AND A3.CDVAL =CR.REPOSSTATUS AND A3.CDTYPE=''AP'' AND A3.CDNAME=''REPOSSTATUS''
AND CR.CRPHYSAGREEID = B.CRPHYSAGREEID(+)
AND CR.CRPHYSAGREEID = NH.CRPHYSAGREEID(+)
AND CR.CRPHYSAGREEID = RUT.CRPHYSAGREEID(+)', 'CRPHYSAGREE_ORI', '', 'CR.CRPHYSAGREEID DESC', '', 0, 5000, 'N', 30, '', 'Y', 'T', '', 'N', '');COMMIT;