SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CLTYPE','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CLTYPE', 'Loại hình tài sản đảm bảo', 'Collateral product type', 'SELECT ACTYPE, SBC.CCYNAME CCYCD, TYPENAME, GLGRP, A0.CDCONTENT STATUS, A1.CDCONTENT LINE, A2.CDCONTENT CLTYPE, GLBANK, SUBCD, NOTES, SECUREDRATIO, DELTA ,
A03.CDCONTENT APPRV_STS,
(CASE WHEN APPRV_STS IN (''D'') THEN ''N'' ELSE ''Y'' END) EDITALLOW, (CASE WHEN APPRV_STS IN (''P'') THEN ''Y'' ELSE ''N'' END) APRALLOW,
(CASE WHEN APPRV_STS IN (''D'') THEN ''N'' ELSE ''Y'' END) AS DELALLOW
FROM CLTYPE TYP, SBCURRENCY SBC, ALLCODE A0, ALLCODE A1, ALLCODE A2, ALLCODE A03
WHERE A0.CDTYPE = ''SY'' AND A0.CDNAME = ''STATUS'' AND A0.CDVAL=TYP.STATUS AND A1.CDTYPE = ''SY'' AND A1.CDNAME = ''YESNO''
AND A1.CDVAL=TYP.LINE AND A2.CDTYPE = ''CL'' AND A2.CDNAME = ''CLTYPE'' AND A2.CDVAL=TYP.CLTYPE AND SBC.CCYCD=TYP.CCYCD
AND A03.CDVAL = TYP.APPRV_STS AND A03.CDTYPE = ''SY'' AND A03.CDNAME = ''APPRV_STS''', 'CLTYPE', 'frmCLTYPE', '', '', NULL, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;