SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('DFCB_RDF53','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('DFCB_RDF53', 'Nguồn giải ngân', 'Drawdown source', '
        SELECT CDVAL CUSTID, CDCONTENT BANKNAME, CDCONTENT DESCRIPTION, LSTODR FROM
        (SELECT ''ALL'' CDVAL, ''Tất cả'' CDCONTENT, -1 LSTODR FROM DUAL
        UNION SELECT ''BSC'' CDVAL, ''Nguồn công ty'' CDCONTENT, 0 LSTODR FROM DUAL
        UNION SELECT a.custid CDVAL, a.fullname CDCONTENT, ROWNUM LSTODR
            FROM (SELECT cf.custid, cf.fullname FROM CFMAST CF WHERE CF.isbanking = ''Y'' ORDER BY custid) a
        ) where 0=0
', 'DFMAST', NULL, 'LSTODR', NULL, NULL, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;