SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('IMP6639_I080ONLINE','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('IMP6639_I080ONLINE', 'Tra c?u thông tin import 6639_I080', 'Tra c?u thông tin import 6639_I080', '    select t.FTYPE,t.SYMBOL,t.TRANSDATE,t.AMOUNT,t.DESCRIPTION,t.BANKTRANSFERS,
           t.beneficiaryaccount,t.BENEFICIARYBANK,t.TLIDIMP MAKER,''TABLE'' TYPE from(
        select * from PAYMENTINSTRUCTION_TAEX
        union all
        select * from PAYMENTINSTRUCTION_TAEX_HIST) t
    where  1=1', 'IMP6639_I080ONLINE', '', '', '', NULL, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;