SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('BA0013','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('BA0013', 'RELEASE CASH (Bond Agent)(1910)', 'RELEASE CASH (Bond Agent)(1910)', 'SELECT BL.AUTOID, BL.CODEID, SB.SYMBOL, BL.TXDATE, BL.TXNUM, SB.CONTRACTNO, SB.CONTRACTDATE, BL.CUSTODYCD, CF.FULLNAME, ISS.ISSUECODE, BL.DDACCTNO, BL.ACTIONDATE, BL.AMT
FROM BLOCKAGE BL, SBSECURITIES SB, ISSUES ISS, CFMAST CF
WHERE BL.DELTD <> ''Y'' AND BL.STATUS <> ''Y'' AND BL.TLTXCD =''1909'' AND BL.REFID IS NULL AND
      BL.CODEID = SB.CODEID AND
      BL.ISSUESID = ISS.AUTOID AND
      BL.CUSTODYCD = CF.CUSTODYCD AND
      NOT EXISTS(SELECT * FROM TLLOG TL WHERE TLTXCD =''1910'' AND MSGACCT = BL.AUTOID AND TXSTATUS = ''4'')', 'DDMAST', NULL, 'AUTOID ASC', '1910', NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;