SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CFSY02','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CFSY02', 'Danh sách rổ chứng khoán theo loại hình vay', 'List of basket by loan type', 'SELECT MST.*, A1.CDCONTENT  DESC_LOANTYPE, LN.BASKETID, LN.EFFDATE,
        MST.AFTYPE ||  MST.ACTYPE || LN.BASKETID KEYVAL
FROM
(
        -- LN PHU
        SELECT AF.ACTYPE AFTYPE, AF.TYPENAME AF_TYPENAME, LNT.ACTYPE, LNT.TYPENAME, LNT.LOANTYPE
        FROM AFIDTYPE AFI, AFTYPE AF, LNTYPE LNT
        WHERE AFI.OBJNAME=''LN.LNTYPE''
              AND AFI.AFTYPE = AF.ACTYPE
              AND AFI.ACTYPE = LNT.ACTYPE
        UNION
        -- LN CHINH
        SELECT AF.ACTYPE AFTYPE, AF.TYPENAME AF_TYPENAME, LNT.ACTYPE, LNT.TYPENAME, LNT.LOANTYPE
        FROM AFTYPE AF, LNTYPE LNT
        WHERE AF.LNTYPE = LNT.ACTYPE
        UNION
        -- LN TRA CHAM
        SELECT AF.ACTYPE AFTYPE, AF.TYPENAME AF_TYPENAME, LNT.ACTYPE, LNT.TYPENAME, LNT.LOANTYPE
        FROM AFTYPE AF, LNTYPE LNT
        WHERE AF.DPLNTYPE = LNT.ACTYPE
        UNION
        -- LN BAO LANH
        SELECT AF.ACTYPE AFTYPE, AF.TYPENAME AF_TYPENAME, LNT.ACTYPE, LNT.TYPENAME, LNT.LOANTYPE
        FROM AFTYPE AF, LNTYPE LNT
        WHERE AF.T0LNTYPE = LNT.ACTYPE

  ) MST, LNSEBASKET LN, (SELECT * FROM ALLCODE WHERE CDNAME =''LOANTYPE'' AND CDTYPE =''LN'') A1
WHERE MST.LOANTYPE = A1.CDVAL (+)
      AND MST.AFTYPE ||  MST.ACTYPE || LN.BASKETID LIKE (CASE WHEN ''<$KEYVAL>'' LIKE ''%KEYVAL%'' THEN ''%'' ELSE ''<$KEYVAL>'' END)
      AND MST.ACTYPE = LN.ACTYPE', 'CFSY02', NULL, NULL, NULL, NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;