SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('PR0001','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('PR0001', 'Tra cứu Room CK hệ thống', 'System room Master', '
  SELECT ROWNUM NO, CODEID, SYMBOL, LISTINGQTTY, ROOMLIMIT, 
      SYROOMLIMIT, SYROOMUSED, SYROOMREMAIN,
      DB_ROOMLIMIT, DB_ROOMUSED, DB_ROOMREMAIN, 
      MRPRICELOAN, MRMARKETVAL, TCMARKETVAL, MRBALANCE, TCBALANCE,
      ISMARGINALLOW, MRMAXBALANCE, ''S'' roomtype
  FROM (SELECT  SB.CODEID, SB.SYMBOL, SB.LISTINGQTTY,(SB.LISTINGQTTY*SYSR1.VARVALUE/100) ROOMLIMIT, 
          RM.SYROOMLIMIT, nvl(AFPR.PRINUSED,0) SYROOMUSED, RM.SYROOMLIMIT-nvl(AFPR.PRINUSED,0) SYROOMREMAIN,
          RM.DB_ROOMLIMIT, nvl(AFPR.DBPRINUSED,0) DB_ROOMUSED, RM.DB_ROOMLIMIT-nvl(AFPR.DBPRINUSED,0) DB_ROOMREMAIN, 
          sb.basicprice MRPRICELOAN, NVL(LN.MRSEAMT_MARKET,0) MRMARKETVAL, RM.DB_ROOMLIMIT-NVL(LN.DPSEAMT_MARKET,0) TCMARKETVAL,
          NVL(LN.MRODAMT,0) MRBALANCE,  NVL(LN.DPODAMT,0) TCBALANCE,A0.CDCONTENT ISMARGINALLOW , SYSR.VARVALUE MRMAXBALANCE
          FROM VW_MARGINROOMSYSTEM RM, SECURITIES_INFO SB, SECURITIES_RISK SRK, SYSVAR SYSR, ALLCODE A0,SYSVAR SYSR1,
                 (SELECT CODEID, 
                         SUM(DECODE(RESTYPE, ''S'',PRINUSED, 0)) PRINUSED ,
                         SUM(DECODE(RESTYPE, ''O'',PRINUSED, 0)) DBPRINUSED
                  FROM VW_AFPRALLOC_ALL 
                  WHERE RESTYPE in (''S'',''O'') GROUP BY CODEID) AFPR,
                 (
                    SELECT V.SYMBOL, SUM(V.MRODAMT) MRODAMT, SUM(V.DPODAMT) DPODAMT,
                        SUM(V.MRQTTY*SE.AVGPRICE) MRSEAMT_MARKET, SUM(V.DPQTTY*SE.AVGPRICE) DPSEAMT_MARKET
                    FROM LNPROBRKLOG V, SECURITIES_INFO SE
                    WHERE SE.SYMBOL=V.SYMBOL AND V.DELTD<>''Y''
                    GROUP BY V.SYMBOL
                 ) LN
          WHERE RM.CODEID = AFPR.CODEID(+) AND RM.CODEID = SB.CODEID AND SRK.CODEID=RM.CODEID AND SYSR.GRNAME=''MARGIN''
              AND SYSR.VARNAME =''MAXDEBTSE'' AND A0.CDNAME=''YESNO'' AND A0.CDTYPE=''SY'' AND A0.CDVAL=SRK.ISMARGINALLOW
              AND SYSR1.GRNAME=''MARGIN'' AND SYSR1.VARNAME =''MAXDEBTQTTYRATE''
              AND SB.symbol=LN.SYMBOL(+)
          ORDER BY SB.SYMBOL
       )
  WHERE 0=0  ', 'SYSROOM', '', '', '0104', NULL, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;