SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SE2275','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('SE2275', 'Tra cứu gửi hồ sơ nhận chuyển khoản chứng khoán ra ngoài(GD 2275)', 'Look up and send documents to transfer securities(Trans 2275)', 'SELECT RE.AUTOID, RE.TRFTXNUM, RE.VSDMSGID, RE.RECUSTODYCD, RE.CUSTODYCD, RE.SYMBOL,
       RE.TRADE, RE.BLOCKED, RE.VSDMSGDATE, RE.FRBICCODE, SB.CODEID,
       CF.FULLNAME CUSTNAME, CF.ADDRESS, DE.FULLNAME FRFULLNAME, NVL(RE.PARVALUE, SB.PARVALUE) PARVALUE, RE.DAAS SELLDAAS, RE.PCOD SELLPCOD, 
       RE.REASON, A1.<@CDCONTENT> CREASON
FROM SERECEIVED RE, SBSECURITIES SB, CFMAST CF, DEPOSIT_MEMBER DE,
(SELECT * FROM ALLCODE WHERE CDNAME = ''PURPOSESEND2255'' AND CDTYPE = ''SY'') A1
WHERE RE.SYMBOL = SB.SYMBOL
AND RE.RECUSTODYCD = CF.CUSTODYCD
AND RE.FRBICCODE = DE.BICCODE
AND RE.REASON = A1.CDVAL(+)
AND RE.STATUS IN (''P'',''R'')', 'SEMAST', '', '', '2275', 0, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;