SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3403','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CA3403', 'Gửi yêu cầu đăng ký bán lại TPRL lên VSD', 'Submit PPBs resale registration request to VSD', 'SELECT V.*, REG.QTTY REGQTTY, REG.AUTOID REGAUTOID
FROM V_CA040REG V, 
(
    SELECT * FROM CA040REGISTER  WHERE MSGSTATUS IN (''P'', ''R'') AND DELTD = ''N'' 
) REG
WHERE V.AUTOID = REG.CASCHDAUTOID', 'CA3403', '', 'REGAUTOID DESC', '3403', NULL, 5000, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;