SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CF0038','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CF0038', 'Thay đổi trạng thái tài khoản thanh toán(0038)', 'Change the status of payment account(0038)', 'SELECT *
FROM
(
    SELECT CF.CUSTODYCD, CF.FULLNAME, DD.ACCTNO, DD.REFCASAACCT, DD.ACCOUNTTYPE, DD.CCYCD, DD.BALANCE, DD.STATUS, CF.CIFID, CF.MCIFID,
    (CASE WHEN DD.CLSDATE IS NOT NULL THEN TO_CHAR(DD.CLSDATE,''DD/MM/RRRR'') ELSE '''' END) CLOSEDATE, 
    A1.<@CDCONTENT> STATUS_DESC, A2.<@CDCONTENT> ISDEFAULT_DESC, A3.<@CDCONTENT> PAYMENTFEE_DESC
    FROM CFMAST CF, DDMAST DD, 
    (SELECT * FROM ALLCODE WHERE CDNAME=''STATUS'' AND CDTYPE = ''CF'') A1,
    (SELECT * FROM ALLCODE WHERE CDNAME=''YESNO'' AND CDTYPE = ''SY'') A2,
    (SELECT * FROM ALLCODE WHERE CDNAME=''YESNO'' AND CDTYPE = ''SY'') A3
    WHERE CF.CUSTID = DD.CUSTID
    AND DD.STATUS IN (''A'',''C'')
    AND DD.STATUS = A1.CDVAL
    AND DD.ISDEFAULT = A2.CDVAL
    AND DD.PAYMENTFEE = A3.CDVAL
    ORDER BY CF.CUSTODYCD, DD.REFCASAACCT
) WHERE 0=0', 'feetran', 'frmFEE', NULL, '0038', NULL, 5000, 'N', 1, 'NNNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;