SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('OD8838','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('OD8838', 'Danh sách lệnh REPO', 'REPO order list', 'SELECT OD.ORDERID, CF.CUSTODYCD, AF.ACCTNO, CF.FULLNAME, OD.EXECQTTY, OD.EXPRICE, OD.EXECAMT
  FROM ODMAST OD, (SELECT ORDERID2  ORDERID FROM  TBL_ODREPO WHERE deltd=''N'' AND status =''A'' AND ORDERID2 IS NOT NULL
             union
             SELECT REF_ORDERID2 ORDERID FROM TBL_ODREPO WHERE DELTD=''N'' AND REF_ORDERID2 IS NOT NULL ) TBL2,
             AFMAST AF, CFMAST CF
  WHERE OD.ORDERID = TBL2.ORDERID AND AF.ACCTNO=OD.AFACCTNO AND AF.CUSTID=CF.CUSTID
        AND od.deltd <> ''Y'' AND OD.TXDATE=getcurrdate', 'OD.ODMAST', 'frmODMAST', 'ORDERID DESC', '8838', NULL, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;