SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('OD0014C1','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('OD0014C1', 'Nhận tiền bán (TPRL)', 'Receive money for sale (PPBs)', 'SELECT MST.AUTOID, MST.ORDERID,  MST.AFACCTNO,  MST.AFACCTNO || MST.CODEID SEACCTNO , MST.CODEID ,MST.QTTY, MST.AMT, MST.FEEAMT,MST.CLEARDATE SETTLEMENT,FA.SHORTNAME BROKER,
    DD.REFCASAACCT,A1.<@CDCONTENT> TYPEORDER,MST.VAT TAXAMT,
    MST.CUSTODYCD, MST.SYMBOL,MST.DDACCTNO,A1.CDVAL,''DD''TYPE,
    (''SETTLE-SELL - ''||MST.ORDERID ||'' - ''||MST.SYMBOL || '' - '' ||MST.QTTY) DESCT,
    A2.<@CDCONTENT> ASSETTYPE
FROM ODMAST OD, FAMEMBERS FA, DDMAST DD,
(SELECT * FROM SBSECURITIES WHERE TRADEPLACE = ''099'') SB,
(SELECT * FROM STSCHD WHERE STATUS = ''P'' AND DELTD <> ''Y'' AND DUETYPE IN (''RM'')) MST,
(SELECT VARVALUE FROM SYSVAR WHERE GRNAME = ''SYSTEM'' AND VARNAME = ''CURRDATE'') CRD,
(SELECT * FROM ALLCODE WHERE CDNAME = ''EXECTYPE'' AND CDTYPE = ''OD'') A1,
(SELECT * FROM ALLCODE WHERE CDNAME = ''ASSETTYPE'' AND CDTYPE = ''OD'') A2
WHERE MST.ORDERID = OD.ORDERID
AND MST.CODEID = SB.CODEID
AND MST.DDACCTNO = DD.ACCTNO
AND OD.MEMBER = FA.AUTOID
AND OD.EXECTYPE = A1.CDVAL(+)
AND OD.EXECTYPE IN (''NS'')
AND OD.ISPAYMENT = ''N''
AND TO_DATE(MST.CLEARDATE,''DD/MM/RRRR'') = TO_DATE(CRD.VARVALUE,''DD/MM/RRRR'')
AND (CASE WHEN SB.TRADEPLACE = ''099'' THEN ''TPRL'' ELSE ''CKNY'' END) = A2.CDVAL(+)
AND NOT EXISTS (
    SELECT F.CVALUE
    FROM TLLOG TL, TLLOGFLD F
    WHERE TL.TXNUM = F.TXNUM
    AND TL.TXDATE = F.TXDATE
    AND TL.TLTXCD = ''8820''
    AND TL.TXSTATUS IN (''1'', ''4'')
    AND F.FLDCD = ''01''
    AND F.NVALUE = MST.AUTOID
)', 'OD.ODMAST', 'frmODMAST', NULL, '8820', NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;