SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CF1044','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CF1044', 'Hủy thay đổi thông tin khách hàng cần xác nhận VSD', 'Hủy thay đổi thông tin khách hàng cần xác nhận VSD', '
SELECT CFL.CUSTID,OFULLNAME,NFULLNAME,OADDRESS,NADDRESS,OIDCODE,NIDCODE,OIDDATE,NIDDATE,OIDEXPIRED,NIDEXPIRED,OIDPLACE,
NIDPLACE,OTRADINGCODE,NTRADINGCODE,OTRADINGCODEDT,NTRADINGCODEDT,CFL.TXDATE,CFL.TXNUM,CONFIRMTXDATE,CONFIRMTXNUM,OCUSTTYPE,
NCUSTTYPE,OCOUNTRY,NCOUNTRY,CFL.DELTD, CF.CUSTODYCD
FROM CFVSDLOG CFL, CFMAST CF WHERE DELTD <>''Y'' and CONFIRMTXDATE is null and CONFIRMTXNUM is null
AND CF.CUSTID= CFL.CUSTID
', 'CFVSDLOG', NULL, 'TXDATE , TXNUM', '0004', 0, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;