SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('DD2000','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('DD2000', 'Quản lý thuế', 'Management tax', 'select * from (
        SELECT TAX.AUTOID,CF.FULLNAME,TAX.BANKACCOUNT BANKACCTNO,TAX.CIFID PROFOLIOCD,TAX.CURRENCY CCYCD ,TAX.VATAMOUNT,
            AL.<@CDCONTENT> STATUS,AL.CDVAL STATUSCDVAL,TAX.PAYMENTDATE PAIDDATE ,TAX.REMARK ,TAX.TRANSDATE,TAX.SETTLETYPE,TAX.BANKREFID,
            to_date(to_char(TAX.LASTCHANGE,''dd/MM/RRRR''),''dd/MM/RRRR'')LASTCHANGE,
            to_char(TAX.LASTCHANGE,''HH24:MI:SS'') CREATEDATE,A2.<@CDCONTENT> DELTD,A2.CDVAL DELTDCDVAL
        FROM TAX_BOOKING_RESULT TAX, CFMAST CF, (select *from ALLCODE where CDTYPE = ''DD'' AND CDNAME = ''FSTATUS'') AL,
            (select *from allcode where cdtype = ''DD'' and cdname = ''DELTDTEXT'') A2
        WHERE   CF.CIFID(+)= TAX.CIFID
            AND TAX.STATUS=AL.CDVAL(+)
            and TAX.DELTD =  A2.CDVAL(+) and TAX.VATAMOUNT > 0   
    )
where 0=0', 'DD2000', 'frmFEEBOOKING', 'LASTCHANGE desc,CREATEDATE desc', NULL, 0, 5000, 'N', 1, 'NNNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;