SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3345','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CA3345', 'Sự kiện chuyển đổi(Hủy TP cũ hoặc hủy CP cũ)', 'Bond converting (delete old bond/old stock)', '
SELECT * FROM (
    SELECT MAX(A.AUTOID) AUTOID,A.CAMASTID, A.DESCRIPTION, B.SYMBOL, A.ACTIONDATE ,A.CANCELDATE POSTINGDATE, MAX(CD.<@CDCONTENT>) CATYPE,
           MAX(NVL(A.CODEID,A.TOCODEID)) CODEID, MAX(B2.SYMBOL) SYMBOL_ORG, ''Y'' ISCANCEL, A.ISINCODE, SUM(CHD.AMT) CASHAMT,
           SUM(CASE WHEN A.CATYPE = ''023'' AND A.FORMOFPAYMENT = ''002'' THEN CHD.TRADE ELSE CHD.QTTY END) QTTY,
           SUM(
            CASE WHEN A.CATYPE = ''023'' THEN CHD.TRADE-CHD.BALANCE 
                 WHEN A.CATYPE = ''040'' THEN CHD.TRADE
                 ELSE CHD.BALANCE 
            END
            ) CONVERTED
    FROM SBSECURITIES B, SBSECURITIES B2,
    (SELECT * FROM CAMAST WHERE STATUS IN (''I'',''G'',''H'') AND CATYPE IN (''017'',''023'',''020'',''016'',''040'') AND CANCELSTATUS = ''N'' AND DELTD <> ''Y'') A,
    (SELECT * FROM CASCHD WHERE DELTD <> ''Y'') CHD,
    (SELECT * FROM ALLCODE WHERE CDNAME = ''CATYPE'' AND CDTYPE =''CA'') CD
    WHERE NVL(A.TOCODEID,A.CODEID) = B.CODEID
    AND A.CAMASTID = CHD.CAMASTID
    AND CD.CDVAL = A.CATYPE
    AND B2.CODEID = A.CODEID
    --AND (A.FORMOFPAYMENT=''002'' OR A.FORMOFPAYMENT IS NULL)
    AND NOT EXISTS (SELECT * FROM TLLOG WHERE MSGACCT = A.CAMASTID AND TXSTATUS =''4'' AND TLTXCD =''3345'')
    GROUP BY A.ISINCODE,A.CAMASTID, A.DESCRIPTION, B.SYMBOL, A.ACTIONDATE, A.CANCELDATE
    HAVING SUM(CASE WHEN A.CATYPE = ''023'' AND A.FORMOFPAYMENT = ''002'' THEN CHD.TRADE ELSE CHD.QTTY END) <>0
) WHERE 0=0', 'CAMAST', '', 'AUTOID DESC', '3345', NULL, 5000, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;