SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3344','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CA3344', 'Danh sách điều chỉnh phân bổ cổ phiếu thưởng', 'List of adjusting hold balance with bank', 'SELECT CA.AUTOID, CA.TRADE, CA.CAMASTID, CA.AFACCTNO,A0.CDCONTENT CATYPE, CA.CODEID, CA.EXCODEID,
CA.QTTY, (CA.AMT-CA.INTAMT)AMT, CA.AQTTY, CFMAST.ADDRESS ,
       CA.AAMT, SYM.SYMBOL, A1.CDCONTENT STATUS,
       CA.AFACCTNO || (CASE WHEN CAMAST.ISWFT=''Y'' THEN (CASE WHEN nvl(CAMAST.TOCODEID,''A'') = ''A''
                   THEN (SELECT CODEID FROM SBSECURITIES WHERE REFCODEID =SYM.CODEID) ELSE (SELECT CODEID FROM SBSECURITIES WHERE REFCODEID =SYMTO.CODEID) END)
                   ELSE (CASE WHEN nvl(CAMAST.TOCODEID,''A'') = ''A'' THEN CAMAST.CODEID ELSE CAMAST.TOCODEID END ) END)  SEACCTNO,
       CA.AFACCTNO || (CASE WHEN CAMAST.EXCODEID IS NULL THEN CAMAST.CODEID ELSE CAMAST.EXCODEID END) EXSEACCTNO,
       SYM.PARVALUE PARVALUE, EXSYM.PARVALUE EXPARVALUE, CAMAST.REPORTDATE REPORTDATE, CAMAST.ACTIONDATE,
       CFMAST.FULLNAME, CFMAST.IDCODE, CFMAST.CUSTODYCD,CFMAST.CIFID,CASE WHEN CI.COREBANK=''Y'' THEN 1 ELSE 0 END COREBANK,
       CASE WHEN CI.COREBANK=''Y'' THEN ''Yes'' ELSE ''No'' END ISCOREBANK
       ,decode(priceaccounting,0,exsym.parvalue,priceaccounting) priceaccounting, a0.cdval CATYPEVALUE,
       CA.INTAMT, (CASE when CA.STATUS in (''S'',''I'') then 1 else 0 end) EXECRCV, camast.isincode
FROM CASCHD CA, SBSECURITIES SYM,SBSECURITIES SYMTO, SBSECURITIES EXSYM, ALLCODE A0, ALLCODE A1, CAMAST, AFMAST, CFMAST,DDMAST CI
WHERE A0.CDTYPE = ''CA'' AND A0.CDNAME = ''CATYPE'' AND A0.CDVAL = CAMAST.CATYPE
AND A1.CDTYPE = ''CA'' AND A1.CDNAME = ''CASTATUS'' AND A1.CDVAL = CA.STATUS
AND CA.CAMASTID = CAMAST.CAMASTID AND CAMAST.CODEID = SYM.CODEID AND SYMTO.CODEID=(CASE WHEN nvl(CAMAST.TOCODEID,''A'') <> ''A'' THEN CAMAST.TOCODEID ELSE CAMAST.CODEID END)
AND CA.DELTD =''N'' AND CA.STATUS in (''A'',''S'',''I'') AND CA.ISCI =''N''
AND CAMAST.CATYPE=''021''
AND EXSYM.CODEID = (CASE WHEN CAMAST.EXCODEID IS NULL THEN CAMAST.CODEID ELSE CAMAST.EXCODEID END)
AND CA.AFACCTNO = AFMAST.ACCTNO AND CI.AFACCTNO=AFMAST.ACCTNO
AND AFMAST.CUSTID = CFMAST.CUSTID  AND CA.QTTY>0 and CI.isdefault = ''Y'' and CI.status <> ''C''', 'CAMAST', NULL, NULL, '3344', NULL, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;