SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('BA6021','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('BA6021', 'Danh sách trái phiếu theo dõi', 'List of bonds agent', 'SELECT SB.CODEID, SB.SYMBOL, SB.ISSUERID, ISS.FULLNAME, CF.CUSTID, CF.CUSTODYCD, SB.CONTRACTNO
FROM SBSECURITIES SB, ISSUERS ISS, CFMAST CF
WHERE SECTYPE IN (''003'', ''006'', ''222'')
      AND ROLEOFSHV IN (''002'', ''003'', ''004'')
      AND SB.CONTRACTNO IS NOT NULL
      AND ISS.ISSUERID = SB.ISSUERID
      --AND ISS.ROLECD = ''006''
      AND ISS.CUSTID = CF.CUSTID(+)', 'BA6021', NULL, NULL, NULL, 0, 1000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;