SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('BONDCAMAST','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('BONDCAMAST', 'Danh sách trả lãi trái phiếu ', 'Danh sách trả lãi trái phiếu ', 'SELECT CA.ISINCODE, CA.CAMASTID, A1.<@CDCONTENT> CATYPECNT, A2.<@CDCONTENT> STATUSCNT, CA.CODEID, SB.SYMBOL,
       CA.INTERESTRATE, CA.REPORTDATE, CA.ACTIONDATE, CA.CATYPE, CA.STATUS, CA.EXCODEID, CA.DESCRIPTION,
       CA.PITRATE, CA.PITRATESE
FROM CAMAST CA, ALLCODE A1, ALLCODE A2, SBSECURITIES SB
WHERE A1.CDTYPE = ''CA'' AND A1.CDNAME = ''CATYPE'' AND A1.CDVAL = CA.CATYPE AND CA.CATYPE IN (''015'',''016'',''033'')
AND A2.CDTYPE = ''CA'' AND A2.CDNAME = ''CASTATUS''  AND A2.CDVAL=CA.STATUS and CA.STATUS NOT IN (''D'',''R'')
AND CA.DELTD <> ''Y''
AND CA.CODEID = SB.CODEID', 'BONDCAMAST', '', '', '', 0, 5000, 'N', 30, '', 'Y', 'T', '', 'N', '');COMMIT;