SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('OD0015A','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('OD0015A', 'Thanh toán phí giao dịch cho Broker', 'Pay transaction fees to Broker', 'SELECT DT.*, A2.<@CDCONTENT> CASSETTYPE
FROM
(
    SELECT CLEARDATE, TXDATE, BROKER, ASSETTYPE, MAX(BROKERNAME) BROKERNAME, MAX(BANKACCBROKER) BANKACCBROKER, MAX(BANKNAMEBROKER) BANKNAMEBROKER, MAX(BRANKBANK) BRANKBANK, MAX(BENEFICIARY) BENEFICIARY, MAX(BANKCITADCODE) CITAD, 
        SUM(FEE) FEE,
        SUM(TAX) TAX,
        SUM(FEE) + SUM(TAX) TOTAL
    FROM (
        SELECT FA.SHORTNAME BROKER, FA.FULLNAME BROKERNAME, FA.BANKACCTNO BANKACCBROKER, FA.BANKNAME BANKNAMEBROKER, FA.BRANCHNAME BRANKBANK, FA.BENEFICIARY, FA.BANKCITADCODE,
            (NVL(FE.FEEAMT,0) - NVL(FE.PAIDFEEAMT,0))FEE,
            (NVL(FE.VAT,0) - NVL(FE.PAIDVAT,0)) TAX,
            FE.CLEARDATE, FE.TXDATE, DECODE(SB.TRADEPLACE, ''099'', ''TPRL'', ''CKNY'') ASSETTYPE
        FROM FAMEMBERS FA, CFMAST CF, SBSECURITIES SB,
        (
            SELECT * FROM VW_STSCHD_ALL WHERE DUETYPE IN (''SM'',''RM'') AND DELTD = ''N'' AND FVSTATUS = ''A''
        ) FE,
        (
            SELECT * FROM ODMAST WHERE ODTYPE IN (''ODT'',''ODG'')
        ) OD,
        (
            SELECT VARVALUE FROM SYSVAR WHERE VARNAME = ''DEALINGCUSTODYCD''
        )SYS
        WHERE OD.MEMBER = FA.AUTOID
        AND OD.ORDERID = FE.ORDERID
        AND OD.CODEID = SB.CODEID
        AND FE.CUSTODYCD = CF.CUSTODYCD
        AND SUBSTR(CF.CUSTODYCD,0,4) NOT LIKE SYS.VARVALUE
        AND CF.FEEDAILY <> ''N''
        AND GREATEST(NVL(FE.FEEAMT,0) - NVL(FE.PAIDFEEAMT,0),0) + GREATEST(NVL(FE.VAT,0) - NVL(FE.PAIDVAT,0),0) <> 0
    )
    GROUP BY BROKER, CLEARDATE, TXDATE, ASSETTYPE
) DT, (SELECT * FROM ALLCODE WHERE CDNAME = ''ASSETTYPE'' AND CDTYPE = ''OD'') A2
WHERE DT.ASSETTYPE = A2.CDVAL(+)', 'OD.ODMAST', 'frmODMAST', '', '8888', NULL, 5000, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;