SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('RM1003','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('RM1003', 'Danh sách KH cần phong toả thu phí lưu ký (6640)', 'View account must hold for custody fee (6640)', 'SELECT CF.CUSTODYCD,AF.ACCTNO,CF.FULLNAME,CF.ADDRESS,CF.IDCODE LICENSE,CF.CAREBY,
AF.BANKACCTNO,CRB.BANKCODE,CRB.BANKCODE || CRB.BANKNAME BANKNAME,CI.HOLDBALANCE,
GETAVLPP(AF.ACCTNO) AVLRELEASE,
CASE WHEN CI.HOLDBALANCE-CI.DEPOFEEAMT>0 THEN 0 ELSE CI.DEPOFEEAMT-CI.HOLDBALANCE END MUSTHOLDAMT
FROM CIMAST CI,AFMAST AF,CFMAST CF,CRBDEFBANK CRB
WHERE CI.AFACCTNO=AF.ACCTNO AND AF.CUSTID=CF.CUSTID
AND CI.COREBANK=''Y''
AND AF.BANKNAME=CRB.BANKCODE
AND CASE WHEN CI.HOLDBALANCE-CI.DEPOFEEAMT>0 THEN 0 ELSE CI.DEPOFEEAMT-CI.HOLDBALANCE END >0
and ci.status=''A''
and ci.corebank=''Y''
AND NOT EXISTS (
    SELECT * FROM CRBTXREQ REQ WHERE REQ.AFACCTNO=AF.ACCTNO AND REQ.TRFCODE IN (''HOLD'')
    AND REQ.TXDATE=(SELECT TO_DATE(SYS.VARVALUE,''DD/MM/RRRR'') FROM SYSVAR SYS WHERE VARNAME=''CURRDATE'')
    AND REQ.TXAMT=(CASE WHEN CI.HOLDBALANCE-CI.DEPOFEEAMT>0 THEN 0 ELSE CI.DEPOFEEAMT-CI.HOLDBALANCE END)
    AND REQ.STATUS IN (''C'',''P'',''E'')
)', 'CRBTRFLOG', NULL, NULL, '6640', 0, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;