SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SE2256','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('SE2256', 'Giao dịch trở lại của chứng khoán chờ giao dịch', 'WTF to trade (2256)', 'SELECT distinct  LOG.BUSDATE TXDATE,A4.CDCONTENT TRADEPLACE , ACTYPE, SUBSTR(SEMAST.ACCTNO,1,4) || ''.'' || SUBSTR(SEMAST.ACCTNO,5,6) || ''.'' || SUBSTR(SEMAST.ACCTNO,11,6) ACCTNO, SYM.SYMBOL, SYM.PARVALUE, SEMAST.CODEID, SUBSTR(AFACCTNO,1,4) || ''.'' || SUBSTR(AFACCTNO,5,6) AFACCTNO,SUBSTR(CUSTODYCD,1,4) || ''.'' || SUBSTR(CUSTODYCD,5,6) CUSTODYCD, SEMAST.OPNDATE, CLSDATE, SEMAST.LASTDATE,
A1.CDCONTENT STATUS, SEMAST.PSTATUS, A2.CDCONTENT IRTIED, A3.CDCONTENT ICCFTIED, IRCD, COSTPRICE,SEDEPOSIT.DEPOSITQTTY SENDDEPOSIT,SEDEPOSIT.DEPOSITPRICE DEPOSITPRICE,SEDEPOSIT.DESCRIPTION DESCRIPTION,SEDEPOSIT.AUTOID AUTOID, CFMAST.CUSTID, COSTDT, LOG.BUSDATE PDATE,SEDEPOSIT.RDATE,
CFMAST.FULLNAME, CFMAST.ADDRESS, CFMAST.IDCODE,DEPOTRADE,DEPOBLOCK,A5.CDCONTENT CD_QTTYTYPE, SEDEPOSIT.TYPEDEPOBLOCK QTTYTYPE, SEDEPOSIT.WTRADE WTRADE
FROM SEMAST,CFMAST,SBSECURITIES SYM,(SELECT * FROM SEDEPOSIT WHERE STATUS=''C'' AND DELTD <> ''Y'') SEDEPOSIT, ALLCODE A1, ALLCODE A2, ALLCODE A3,ALLCODE A4,ALLCODE A5, ( SELECT MSGACCT,MAX(BUSDATE) BUSDATE FROM  ( SELECT * FROM TLLOG  WHERE TXSTATUS = ''1'' AND DELTD = ''N'' AND TLTXCD = ''2246'' UNION ALL SELECT * FROM TLLOGALL WHERE TXSTATUS = ''1'' AND DELTD = ''N'' AND TLTXCD = ''2246'' ) GROUP BY MSGACCT ) LOG
WHERE SEMAST.WTRADE>0 AND A1.CDTYPE = ''SE'' AND A1.CDNAME = ''STATUS'' AND A1.CDVAL = SEMAST.STATUS
AND SEMAST.CUSTID=CFMAST.CUSTID
AND A2.CDTYPE = ''SY'' AND A2.CDNAME = ''YESNO''  AND A2.CDVAL = IRTIED
AND nvl(A5.CDTYPE,''SE'') = ''SE'' AND NVL(A5.CDNAME,''QTTYTYPE'') = ''QTTYTYPE'' AND SEDEPOSIT.TYPEDEPOBLOCK=A5.CDVAL (+)
AND SYM.CODEID = SEMAST.CODEID
AND A3.CDTYPE = ''SY'' AND A3.CDNAME = ''YESNO''  AND A3.CDVAL = SEMAST.ICCFTIED
AND A4.CDTYPE = ''SE'' AND A4.CDNAME = ''TRADEPLACE''  AND A4.CDVAL = SYM.TRADEPLACE
AND SEDEPOSIT.ACCTNO=SEMAST.ACCTNO
AND LOG.MSGACCT = SEMAST.ACCTNO', 'SEMAST', '', '', '2256', NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;