SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('GLMAST','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('GLMAST', 'Quản lý tài khoản kế toán chi tiết', 'GL detail account management', 'SELECT SP_FORMAT_EBS_ACCOUTNO(ACCTNO) ORACLE_ACCTNO, ACCTNO,
(CASE WHEN BALANCE<0 THEN -BALANCE ELSE 0 END) DRBAL,(CASE WHEN BALANCE>0 THEN BALANCE ELSE 0 END) CRBAL,
GLBANK, SUBCD, ACNAME, CCYCD, BRID, A1.CDCONTENT MASTER, A2.CDCONTENT ACTYPE, A3.CDCONTENT BALTYPE, OPNDATE,
LSTDATE, A4.CDCONTENT RECONCILE, BALANCE, AVGBAL, YEARBAL, INTRATE, DDR, DCR, MDR, MCR, YDR, YCR,
DTXCOUNT, YTXCOUNT, MNEMONIC, A5.CDCONTENT DEPGRCD, SUBCD2, MAPID FROM GLMAST,
ALLCODE A1, ALLCODE A2, ALLCODE A3,ALLCODE A4, ALLCODE A5 WHERE
A1.CDTYPE = ''GL'' AND A1.CDNAME = ''MASTER'' AND A1.CDVAL=MASTER AND
A2.CDTYPE = ''GL'' AND A2.CDNAME = ''ACTYPE'' AND A2.CDVAL=ACTYPE AND
A3.CDTYPE = ''GL'' AND A3.CDNAME = ''BALTYPE'' AND A3.CDVAL=BALTYPE AND
A4.CDTYPE = ''SY'' AND A4.CDNAME = ''YESNO'' AND A4.CDVAL=RECONCILE AND
A5.CDTYPE = ''GL'' AND A5.CDNAME = ''DEPGRCD'' AND A5.CDVAL=DEPGRCD', 'GLMAST', 'frmGLMAST1', NULL, NULL, NULL, 5000, 'Y', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;