SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SA0094','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('SA0094', 'Điều chỉnh ICCF (0094)', 'Adjust ICCF (0094)', 'SELECT ICCF.AUTOID, TYP.TYPENAME, ICCF.EVENTNAME, ICCF.MODCODE, ICCF.ACTYPE, ICCF.EVENTCODE, ICCF.DESC_RULETYPE,
 (CASE WHEN ICCF.ICTYPE=''F'' THEN ICCF.DESC_ICTYPE ELSE ICCF.DESC_ICRATECD || ''.'' || ICCF.DESC_ICTYPE END) VALTYPE,
 (CASE WHEN ICCF.ICTYPE=''F'' THEN ICCF.ICFLAT WHEN (ICCF.ICTYPE=''P'' AND ICCF.ICRATECD=''S'') THEN ICCF.ICRATE ELSE IRRATEVAL+ICCF.ICRATE END) VALRATE,
 ICCF.MINVAL, ICCF.MAXVAL, ICCF.ICRATE ICCFRATE, ICCF.VARRATE, ICCF.ICFLAT, NVL(ICCF.IRRATEVAL,0) IRRATEVAL, ICCF.ICRATEID,
 ICCF.DESC_MONTHDAY, ICCF.DESC_YEARDAY, ICCF.DESC_ICTYPE, ICCF.DESC_ICRATECD, ICCF.DESC_PERIOD
FROM ((SELECT ''CI'' MODCODE, ACTYPE, TYPENAME FROM CITYPE TYP
      UNION ALL SELECT ''SE'' MODCODE, ACTYPE, DESCRIPTION TYPENAME FROM SETYPE TYP
      UNION ALL SELECT ''OD'' MODCODE, ACTYPE, TYPENAME FROM ODTYPE TYP) TYP JOIN
                (SELECT APPEVENTS.EVENTNAME, ICCF.*, CD1.CDCONTENT DESC_RULETYPE, CD2.CDCONTENT DESC_MONTHDAY,
                CD3.CDCONTENT DESC_YEARDAY, CD4.CDCONTENT DESC_PERIOD, CD5.CDCONTENT DESC_ICTYPE, CD6.CDCONTENT DESC_ICRATECD
                FROM APPEVENTS, (SELECT ICCFTYPEDEF.*, IRRATE.RATE IRRATEVAL FROM ICCFTYPEDEF LEFT JOIN IRRATE ON ICCFTYPEDEF.ICRATEID=IRRATE.RATEID) ICCF,
                ALLCODE CD1, ALLCODE CD2, ALLCODE CD3, ALLCODE CD4, ALLCODE CD5, ALLCODE CD6
                WHERE APPEVENTS.MODCODE=ICCF.MODCODE AND APPEVENTS.EVENTCODE=ICCF.EVENTCODE AND ICCF.DELTD<>''Y'' AND ICCF.ICCFSTATUS=''A''
                AND CD1.CDTYPE=''SA'' AND CD1.CDNAME=''RULETYPE'' AND CD1.CDVAL=ICCF.RULETYPE
                AND CD2.CDTYPE=''SA'' AND CD2.CDNAME=''MONTHDAY'' AND CD2.CDVAL=ICCF.MONTHDAY
                AND CD3.CDTYPE=''SA'' AND CD3.CDNAME=''YEARDAY'' AND CD3.CDVAL=ICCF.YEARDAY
                AND CD4.CDTYPE=''SA'' AND CD4.CDNAME=''PERIOD'' AND CD4.CDVAL=ICCF.PERIOD
                AND CD5.CDTYPE=''SA'' AND CD5.CDNAME=''ICTYPE'' AND CD5.CDVAL=ICCF.ICTYPE
                AND CD6.CDTYPE=''SA'' AND CD6.CDNAME=''ICRATECD'' AND CD6.CDVAL=ICCF.ICRATECD) ICCF
                ON TYP.MODCODE=ICCF.MODCODE AND TYP.ACTYPE=ICCF.ACTYPE) WHERE 0=0 ', 'ICCFTYPEDEF', NULL, NULL, '0094', NULL, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;