SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('BONDTYPEPAY','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('BONDTYPEPAY', 'Tạo lịch thanh toán lãi ', 'Create interest payment period', 'SELECT  BO.AUTOID, BO.ACTUALPAYDATE, BO.RECORDDATE,
        BO.BEGINDATE, BO.PAYMENTDATE,
        SB.CODEID BONDCODE, SB.SYMBOL BONDSYMBOL, A1.<@CDCONTENT> STATUS, A2.<@CDCONTENT> BONDEVENT
FROM BONDTYPEPAY BO, SBSECURITIES SB, ALLCODE A1, ALLCODE A2
WHERE BO.BONDCODE = SB.CODEID
AND A1.CDNAME =''STATUS''
AND A1.CDVAL = BO.STATUS
AND A1.CDTYPE =''SE''
AND A1.CDVAL IN (''A'',''C'')
AND A2.CDTYPE =''BA''
AND A2.CDNAME =''BONDEVENT''
AND A2.CDVAL = BO.BONDEVENT', 'BONDTYPEPAY', '', 'AUTOID', '', 0, 5000, 'Y', 1, '', 'Y', 'T', '', 'N', '');COMMIT;