SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SE0087A','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('SE0087A', 'Tra cứu lịch sử đối chiếu số dư chứng khoán (RSE0087)', 'Search the history of collating securities balance (RSE0087)', 'SELECT SE.*, A1.<@CDCONTENT> TRADEPLACE,
       (CASE WHEN SE.SY_CUSTODYCD = SE.VSD_CUSTODYCD AND SE.SY_SYMBOL = SE.VSD_SYMBOL AND SE.SY_QTTY = SE.VSD_QTTY THEN ''Match'' ELSE ''Mismatch'' END) STATUS
FROM LOG_SE0087 SE,
(
    SELECT A.*, SB.SYMBOL
    FROM ALLCODE A, SBSECURITIES SB
    WHERE SB.TRADEPLACE = A.CDVAL
    AND A.CDNAME = ''TRADEPLACE''
    AND A.CDTYPE = ''SA''
) A1
WHERE NVL(SE.VSD_SYMBOL, SE.SY_SYMBOL) = A1.SYMBOL(+)
AND 0 = 0', 'SE0087A', 'frmSEMAST', 'AUTOID DESC', NULL, NULL, 5000, 'N', 1, 'NNNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;