SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('GLMASTEX','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('GLMASTEX', 'Quản lý tài khoản kế toán chi tiết', 'GL account management', '
SELECT SP_FORMAT_EBS_ACCOUTNO(ACCTNO) ORACLE_ACCTNO,ACCTNO,
(CASE WHEN BALANCE<0 THEN -BALANCE ELSE 0 END) DRBAL,(CASE WHEN BALANCE>0 THEN BALANCE ELSE 0 END) CRBAL,
CCYCD, GLBANK, ACNAME,AVGBAL, YEARBAL, DDR, DCR, BALANCE,
MDR, MCR, YDR, YCR, A1.CDCONTENT MASTER, A2.CDCONTENT ACTYPE, A3.CDCONTENT BALTYPE,
BRID, DTXCOUNT, YTXCOUNT, OPNDATE, LSTDATE, INTRATE,A4.CDCONTENT RECONCILE FROM GLMAST,
ALLCODE A1, ALLCODE A2, ALLCODE A3,ALLCODE A4 WHERE
A1.CDTYPE = ''GL'' AND A1.CDNAME = ''MASTER'' AND A1.CDVAL=MASTER AND
A2.CDTYPE = ''GL'' AND A2.CDNAME = ''ACTYPE'' AND A2.CDVAL=ACTYPE AND
A3.CDTYPE = ''GL'' AND A3.CDNAME = ''BALTYPE'' AND A3.CDVAL=BALTYPE AND
A4.CDTYPE = ''SY'' AND A4.CDNAME = ''YESNO'' AND A4.CDVAL=RECONCILE AND GLBANK not like ''0%''', 'GLMASTEX', 'frmGLMAST', NULL, NULL, NULL, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;