SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SE8894','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('SE8894', 'Tra cứu giao dịch bán chứng khoán lô lẻ chờ thanh toán chứng khoán', 'View odd lot trading payment', 'SELECT CF.CUSTODYCD, B.DESACCTNO AFDDI , C.CODEID, C.SYMBOL, C.PARVALUE, A.AFACCTNO,
    B.TXDATE,B.TXNUM,B.ACCTNO,B.PRICE,B.QTTY,B.STATUS,B.DESACCTNO,B.FEEAMT,B.TAXAMT,B.SDATE,B.VDATE,
    CF.IDCODE ,A4.CDCONTENT TRADEPLACE,CASE WHEN AF.COREBANK=''Y'' THEN 0 ELSE 1 END ISCOREBANK,
    ROUND(DECODE(CF.VAT,''Y'',1,0)* B.QTTY*B.PRICE/100*(SELECT TO_NUMBER(VARVALUE) FROM SYSVAR WHERE VARNAME =''ADVSELLDUTY'')) TAX,
    '''' DEPOLASTDT,NVL(PIT.QTTY,0) PITQTTY,NVL(PIT.ARIGHT,0) PITAMT2,CF.FULLNAME,
    TO_CHAR(B.TXDATE,''DD/MM/YYYY'') || B.TXNUM ACCREF
FROM SEMAST A, SERETAIL B, SBSECURITIES C ,AFMAST AF , CFMAST CF ,ALLCODE A4,
(
    SELECT ORGORDERID ORDERID , SUM(QTTY) QTTY, SUM(ARIGHT) ARIGHT
    FROM SEPITALLOCATE
    GROUP BY ORGORDERID
) PIT
WHERE A.ACCTNO = B.ACCTNO AND A.CODEID = C.CODEID
      AND B.QTTY > 0 AND B.STATUS=''I''
      AND AF.ACCTNO =A.AFACCTNO AND AF.CUSTID =CF.CUSTID
    AND A4.CDTYPE = ''SE'' AND A4.CDNAME = ''TRADEPLACE''  AND A4.CDVAL = C.TRADEPLACE
    AND TO_CHAR(B.TXDATE,''DDMMRRRR'') || B.TXNUM= PIT.ORDERID(+)', 'SEMAST', '', '', '8894', NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;