SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('ISSUESHIST','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('ISSUESHIST', 'Quản lý đợt phát hành trái phiếu', 'Bond issue management ', 'SELECT ISS.*, A1.<@CDCONTENT> TYPERATE, A2.<@CDCONTENT> PURPOSE, A3.<@CDCONTENT> ROLE
FROM VW_ISSUES ISS,
(
    SELECT * FROM ALLCODE WHERE CDNAME = ''TYPERATE'' AND CDTYPE = ''CB''
) A1,
(
    SELECT * FROM ALLCODE WHERE CDNAME = ''BAPURPOSE'' AND CDTYPE = ''BA''
) A2,
(
    SELECT * FROM ALLCODE WHERE CDNAME = ''BAISSUESROLE'' AND CDTYPE = ''BA''
) A3
WHERE (ISS.EFFECTIVE = ''N'' OR NVL(ISS.MATURITYDATE, GETCURRDATE) < GETCURRDATE)
AND ISS.VTYPERATE = A1.CDVAL(+)
AND ISS.VPURPOSE = A2.CDVAL(+)
AND ISS.VROLE = A3.CDVAL(+)', 'ISSUES', NULL, 'ISS.AUTOID', NULL, NULL, 5000, 'Y', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;