SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('MT1720','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('MT1720', 'Foreign Exchange Order', 'Foreign Exchange Order', 'SELECT TBL.*,NVL(TBL.AMOUNT,TBL.FRAMOUNT) AMOUNTORG,DD1.REFCASAACCT DEBITAC,DD1.BALANCE, DD2.REFCASAACCT CREDITAC,CASE WHEN TBL.BORS = ''S'' THEN TBL.FRCCYCD ELSE TBL.CCYCD END CCYCDORG,
       NVL(RT.VND, 1) FXRATE,
       NVL( TBL.FRAMOUNT,DECODE(TBL.FXTYPE,''TTB'',ROUND(TBL.AMOUNT/RT.VND,2),ROUND(TBL.AMOUNT*RT.VND,2))) AMOUNTC,
       NVL(TBL.AMOUNT ,DECODE(TBL.FXTYPE,''TTS'',ROUND(TBL.FRAMOUNT/RT.VND,2),ROUND(TBL.FRAMOUNT*RT.VND,2))) EXAMOUNT
FROM (
    SELECT TBL.AUTOID, TBL.REQID, TBL.BORS, TBL.REQDT, TBL.EFFDT, TBL.AMOUNT,TBL.FRAMOUNT, DECODE(TBL.CCYCD,''VND'',TBL.FRCCYCD,TBL.CCYCD)EXCCYCD,TBL.FRCCYCD,TBL.CCYCD,
         TBL.CIFID, TBL.STATUS, TBL.CREATETIME, TBL.CFTXDATE, TBL.CFTXNUM,
         A1.<@CDCONTENT>  STATUSVAL, A2.<@CDCONTENT> BORSVAL, CF.CUSTODYCD,
         FN_GET_DEFACCTNO_1720(CF.CUSTID, TBL.FRCCYCD) DEBITACCTNO,
         FN_GET_DEFACCTNO_1720(CF.CUSTID, TBL.CCYCD) CREDITACCTNO,
         (CASE WHEN (TBL.BORS = ''B'' AND TBL.FRCCYCD = ''VND'') OR (TBL.BORS = ''S'' AND TBL.FRCCYCD = ''VND'') THEN ''TTS'' ELSE ''TTB'' END) FXTYPE
    FROM TBL_MT380_INF TBL, CFMAST CF,
    (SELECT * FROM ALLCODE WHERE CDNAME = ''MT380_STATUS'' AND CDTYPE = ''MT'') A1,
    (SELECT * FROM ALLCODE WHERE CDNAME = ''BORS'' AND CDTYPE = ''SA'') A2
    WHERE TBL.STATUS = A1.CDVAL(+)
    AND TBL.BORS = A2.CDVAL(+)
    AND TBL.CIFID = CF.CIFID
    AND TBL.STATUS IN (''P'')
) TBL
LEFT JOIN (SELECT * FROM DDMAST WHERE STATUS<>''C'') DD1 ON TBL.DEBITACCTNO = DD1.ACCTNO
LEFT JOIN (SELECT * FROM DDMAST WHERE STATUS<>''C'') DD2 ON TBL.CREDITACCTNO = DD2.ACCTNO
LEFT JOIN EXCHANGERATE RT ON RT.CURRENCY = TBL.EXCCYCD AND RT.RTYPE = TBL.FXTYPE AND RT.ITYPE = ''SHV''', '1720', NULL, 'tbl.autoid', '1720', 0, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;