SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('BONDSEMAST','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('BONDSEMAST', 'Tra cứu nhanh thông tin khách hàng', 'Customer information', 'SELECT BO.ACCTNO, BO.CUSTODYCD, CF.FULLNAME, CF.SHORTNAME ,BO.AFACCTNO, BO.BONDSYMBOL
     , BO.TRADE, BO.STATUS, A1.EN_CDCONTENT STATUSCONTENT
FROM BONDSEMAST BO, AFMAST AF, CFMAST CF, ALLCODE A1
WHERE AF.STATUS <> ''C''
AND A1.CDTYPE = ''SE'' AND A1.CDNAME = ''STATUS'' AND A1.CDVAL = BO.STATUS
AND BO.AFACCTNO = AF.ACCTNO
AND AF.CUSTID = CF.CUSTID
AND BO.STATUS <> ''C''', 'BONDSEMAST', '', '', '', 0, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;