SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SE2258','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('SE2258', 'DS yêu cầu tất toán TK(chuyển toàn bộ nhưng không đóng TK) chờ gửi VSD (GD 2258)', 'DS yêu cầu tất toán TK(chuyển toàn bộ nhưng không đóng TK) chờ gửi VSD (GD 2258)', 'SELECT DISTINCT TF.CUSTODYCD, CF.FULLNAME, TF.INWARD, TF.RCVCUSTODYCD, CF.IDCODE
FROM SEFULLTRANSFER_LOG TF, CFMAST CF
WHERE TF.CUSTODYCD = CF.CUSTODYCD
AND TF.DELTD = ''N''
AND TF.STATUS = ''P''
AND NOT EXISTS(
    SELECT * FROM V_SE2257 SE WHERE NVL(SE.MCUSTODYCD, SE.CUSTODYCD) = TF.CUSTODYCD
)', 'SEMAST', NULL, NULL, '2258', NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;