SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CBLOGNOTIFYDETAIL','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CBLOGNOTIFYDETAIL', 'Chi tiết đồng bộ CB và FA', 'Synchronization detail between CB and FA', 'SELECT VW.CTCK,CF.FULLNAME ,VW.CUSTODYCD,CF.CIFID ,A.<@CDCONTENT> EXECTYPE ,VW.SYMBOL,VW.AMT ,VW.FEE ,VW.TAX,VW.TXDATE,VW.SETLDATE,VW.ORDERID   
    FROM    VW_ODMAST_IMPORT VW,CFMAST CF , (SELECT * FROM VW_CBFA_FASFNOTICETX  WHERE TXNUM = ''<$KEYVAL>'' ) SYN,(SELECT *FROM ALLCODE WHERE CDNAME = ''EXECTYPE'' and CDTYPE = ''OD'' )A
    WHERE   VW.ORDERID = SYN.REFKEY
        AND VW.txdate = SYN.TXDATE
        AND VW.custodycd = CF.CUSTODYCD
        and vw.exectypeval = A.cdval(+)
        AND CF.status <> ''C''', 'CBLOGNOTIFYDETAIL', 'CBLOGNOTIFYDETAIL', '', '', NULL, 5000, 'N', 1, 'NNNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;