SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('TEMPLATES','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('TEMPLATES', 'Thông tin mẫu SMS/Email', 'SMS/Email templates', 'SELECT T.CODE, T.NAME, T.SUBJECT, A1.CDCONTENT TYPE, A2.CDCONTENT CYCLE,
       A3.CDCONTENT FORMAT, A4.CDCONTENT REQUIRE_REGISTER, T.EXPORT_PATH, A5.CDCONTENT ALLOW_ZIP, A6.CDCONTENT INTERNAL,
       T.ISACTIVE, A7.CDCONTENT ISCCBROKER, A8.CDCONTENT ISDISPLAY, emailcs
FROM TEMPLATES T
 INNER JOIN ALLCODE A1 ON T.TYPE = A1.CDVAL AND A1.CDTYPE = ''SY'' AND A1.CDNAME = ''TEMPLATE_TYPE''
 INNER JOIN ALLCODE A2 ON T.CYCLE = A2.CDVAL AND A2.CDTYPE = ''SY'' AND A2.CDNAME = ''TEMPLATE_CYCLE''
 INNER JOIN ALLCODE A3 ON T.FORMAT = A3.CDVAL AND A3.CDTYPE = ''SY'' AND A3.CDNAME = ''TEMPLATE_FORMAT''
 INNER JOIN ALLCODE A4 ON T.REQUIRE_REGISTER = A4.CDVAL AND A4.CDTYPE = ''SY'' AND A4.CDNAME = ''TEMPLATE_REQUIRED''
 INNER JOIN ALLCODE A6 ON T.INTERNAL = A6.CDVAL AND A6.CDTYPE = ''SY'' AND A6.CDNAME = ''YESNO''
 INNER JOIN ALLCODE A7 ON T.ISCCBROKER = A7.CDVAL AND A7.CDTYPE = ''SY'' AND A7.CDNAME = ''YESNO''
 INNER JOIN ALLCODE A8 ON T.ISDISPLAY = A8.CDVAL AND A8.CDTYPE = ''SY'' AND A8.CDNAME = ''YESNO''
 INNER JOIN ALLCODE A5 ON CASE WHEN T.TYPE = ''H'' THEN T.ALLOW_ZIP ELSE ''N'' END = A5.CDVAL AND A5.CDTYPE = ''SY''
   AND A5.CDNAME = ''YESNO''', 'TEMPLATES', NULL, 'NAME', NULL, NULL, 5000, 'N', 30, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;