SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('RMCMPBANKBALANCE','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('RMCMPBANKBALANCE', 'Đối chiếu số dư tiền CB và corebank', 'Compare cash balance from CB with corebank', 'SELECT ROWNUM RN,REFCASAACCT, CCYCD, FLEXREFCASAACCT, CIFID, FULLNAME, CUSTODYCD, ACCTNO, STATUS, MATCHSTS, BANKBALANCE, BALANCE, 
       BANKHOLDBALANCE, HOLDBALANCE, LASTREQBANK, OPNDATE, SUPEBANK
FROM (
    SELECT MST.*, NVL(A1.CDCONTENT,''-'') MATCHSTS, NVL(A2.CDCONTENT,''-'') SUPEBANK
    FROM (
        SELECT D.REFCASAACCT, D.ACCTNO, D.CCYCD,
            CASE WHEN NVL(RQ.STATUS,''R'') = ''C'' THEN D.BANKBALANCE ELSE 0 END BANKBALANCE,
            CASE WHEN NVL(RQ.STATUS,''R'') = ''C'' THEN D.BANKHOLDBALANCE ELSE 0 END BANKHOLDBALANCE,
            CASE WHEN NVL(RQ.STATUS,''-'') IN (''E'',''R'') THEN ''E''
                WHEN NVL(RQ.STATUS,''-'') = ''C'' THEN (CASE WHEN D.BANKBALANCE = D.BALANCE AND D.BANKHOLDBALANCE = D.HOLDBALANCE THEN ''Y'' ELSE ''N'' END)
                WHEN NVL(RQ.STATUS,''-'') = ''-'' THEN ''ZZ''
                ELSE ''P''
            END STATUS,
            D.REFCASAACCT FLEXREFCASAACCT, CF.CIFID, CF.FULLNAME, CF.CUSTODYCD, D.BALANCE, D.HOLDBALANCE, D.OPNDATE,
            NVL(TO_CHAR(RQ.CREATEDATE,''DD/MM/RRRR HH24:MI:SS''),'''') LASTREQBANK, CF.SUPEBANK SUPEBANKV
            --, '''' REQSTATUS
        FROM DDMAST D, CFMAST CF, 
        (
            SELECT * FROM CRBTXREQ WHERE REQCODE =''INQACCT''
        ) RQ,
        (
            SELECT VARVALUE  FROM SYSVAR WHERE VARNAME = ''DEALINGCUSTODYCD''
        )SYS
        WHERE CF.CUSTID = D.CUSTID 
        AND D.INQBANKREQID = RQ.REQTXNUM (+) 
        AND D.ACCTNO = RQ.AFACCTNO(+)
        AND D.STATUS NOT IN (''C'') 
        AND SUBSTR(CF.CUSTODYCD,0,4) NOT LIKE SYS.VARVALUE
        AND (NVL(D.PAYMENTFEE, ''N'') = ''N'' OR (D.PAYMENTFEE = ''Y'' AND D.ISDEFAULT = ''Y''))
    )MST,
    (
        SELECT * FROM ALLCODE WHERE CDTYPE LIKE ''RM'' AND CDNAME = ''RMCMPBANKBALANCESTS''
    ) A1,
    (
        SELECT * FROM ALLCODE WHERE CDTYPE LIKE ''SY'' AND CDNAME = ''YESNO'' 
    ) A2
    WHERE MST.STATUS = A1.CDVAL(+)
    AND MST.SUPEBANKV = A2.CDVAL(+)
    ORDER BY MST.STATUS, MST.CUSTODYCD, MST.REFCASAACCT
) WHERE 0=0', 'RMCMPBANKBALANCE', 'frmRMCMPBANKBALANCE', '', '6671', NULL, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;