SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SE2241','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('SE2241', 'Tra cứu các tài khoản đang chờ để gửi hồ sơ lưu ký (2241)', 'View pending to send depository center (2241)', 'SELECT  SEDEPOSIT.DEPODATE TXDATE,A4.CDCONTENT TRADEPLACE ,SEMAST.ACTYPE,
        SUBSTR(SEMAST.ACCTNO,1,4) || ''.'' || SUBSTR(SEMAST.ACCTNO,5,6) || ''.'' || SUBSTR(SEMAST.ACCTNO,11,6) ACCTNO,
        SYM.SYMBOL, SYM.PARVALUE, SEMAST.CODEID, SUBSTR(SEMAST.AFACCTNO,1,4) || ''.'' || SUBSTR(SEMAST.AFACCTNO,5,6) AFACCTNO,
        SUBSTR(CUSTODYCD,1,4) || ''.'' || SUBSTR(CUSTODYCD,5,6) CUSTODYCD, SEMAST.OPNDATE, SEMAST.CLSDATE, SEMAST.LASTDATE,
        A1.CDCONTENT STATUS, SEMAST.PSTATUS, A2.CDCONTENT IRTIED, A3.CDCONTENT ICCFTIED, IRCD, COSTPRICE,
        SEDEPOSIT.DEPOSITQTTY DEPOSIT,SEDEPOSIT.DEPOSITPRICE DEPOSITPRICE,SEDEPOSIT.AUTOID AUTOID,
        SEDEPOSIT.DESCRIPTION DESCRIPTION,SEDEPOSIT.DEPODATE PDATE,SEMAST.CUSTID CUSTID, COSTDT,
        CFMAST.FULLNAME CUSTNAME,CFMAST.ADDRESS  ADDRESS,(CASE WHEN SUBSTR( CFMAST.CUSTODYCD,4,1)=''F'' THEN CFMAST.tradingcode ELSE CFMAST.IDCODE END )  LICENSE,
         DEPOTRADE,DEPOBLOCK,SEDEPOSIT.WTRADE,A5.CDCONTENT  QTTYTYPE,RDATE,CFMAST.IDTYPE,   (CASE WHEN SUBSTR( CFMAST.CUSTODYCD,4,1)=''F'' THEN CFMAST.tradingcodedt ELSE CFMAST.IDDATE END )IDDATE,
ISSUERS.FULLNAME  NAMESYMBOL,SEDEPOSIT.VSDCODE,SEDEPOSIT.DESCRIPTION REFERENCEID,CFMAST.MCUSTODYCD
FROM SEMAST,CFMAST,SBSECURITIES SYM,ISSUERS, SBSECURITIES SYM2,
     (SELECT * FROM SEDEPOSIT WHERE STATUS=''D'' AND DELTD <> ''Y'') SEDEPOSIT,
     ALLCODE A1, ALLCODE A2, ALLCODE A3,ALLCODE A4,ALLCODE A5
WHERE SEMAST.DEPOSIT>0 AND A1.CDTYPE = ''SE'' AND A1.CDNAME = ''STATUS'' AND A1.CDVAL = SEMAST.STATUS
AND A2.CDTYPE = ''SY'' AND A2.CDNAME = ''YESNO''  AND A2.CDVAL = IRTIED AND ISSUERS.ISSUERID = SYM.ISSUERID
AND NVL(A5.CDTYPE,''SE'')  = ''SE'' AND NVL(A5.CDNAME,''QTTYTYPE'') = ''QTTYTYPE'' AND  SEDEPOSIT.TYPEDEPOBLOCK=A5.CDVAL (+)
AND SYM.CODEID = SEMAST.CODEID
and sym.refcodeid = sym2.codeid(+)
AND A3.CDTYPE = ''SY'' AND A3.CDNAME = ''YESNO''  AND A3.CDVAL = SEMAST.ICCFTIED
AND A4.CDTYPE = ''SE'' AND A4.CDNAME = ''TRADEPLACE''
AND A4.CDVAL = (case when sym.refcodeid is null then SYM.TRADEPLACE else SYM2.TRADEPLACE end)
AND CFMAST.CUSTID = SEMAST.CUSTID
AND SEDEPOSIT.ACCTNO=SEMAST.ACCTNO', 'SEMAST', '', '', '2241', 0, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;