SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3359','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CA3359', 'Danh sách phân bổ tiền chờ thực hiện', 'List of allocating pending', 'SELECT A.*,AMT-DUTYAMT NETAMT FROM (
SELECT CA.AUTOID, CA.CAMASTID, CA.AFACCTNO, SYM.SYMBOL, CA.CODEID, CA.EXCODEID, CAMAST.CATYPE, A0.<@CDCONTENT> CCATYPE, CAMAST.REPORTDATE, CAMAST.ACTIONDATE,
       (CASE WHEN CA.PITRATEMETHOD=''##'' THEN CAMAST.PITRATEMETHOD ELSE CA.PITRATEMETHOD END) SCHDVAT,
       (CASE WHEN CAMAST.CATYPE = ''017'' THEN CA.AFACCTNO || CA.EXCODEID ELSE CA.AFACCTNO || CA.CODEID END) SEACCTNO,
       (CASE WHEN CAMAST.CATYPE = ''017'' THEN CA.AFACCTNO || CA.CODEID ELSE CA.AFACCTNO || (CASE WHEN CAMAST.EXCODEID IS NULL THEN CAMAST.CODEID ELSE CAMAST.EXCODEID END) END) EXSEACCTNO,
       ROUND(CASE WHEN CF.VAT=''Y'' THEN NVL(CASE WHEN CAMAST.CATYPE = ''010'' THEN CA.AMTDTL ELSE CA.AMT END,0) - NVL(
                CASE WHEN CAMAST.PITRATEMETHOD=''IS'' THEN
                 (CASE WHEN CAMAST.CATYPE IN (''016'',''023'',''033'') THEN ROUND(CAMAST.PITRATE*CA.INTAMT/100)
                       WHEN CAMAST.CATYPE = ''024'' THEN ROUND(CA.BALANCE*CAMAST.EXPRICE*CAMAST.PITRATE/100/CAMAST.EXERCISERATIO)
                       WHEN CAMAST.CATYPE = ''010'' AND  CF.CUSTTYPE = ''I'' THEN ROUND(CAMAST.PITRATE*CA.AMTDTL/100)
                       WHEN CAMAST.CATYPE = ''010'' AND  CF.CUSTTYPE = ''B'' THEN 0
                       ELSE ROUND(CAMAST.PITRATE*CA.AMT/100)
                 END)
                    ELSE 0
                END,0)
                 ELSE NVL(CASE WHEN CAMAST.CATYPE = ''010'' THEN  CA.AMTDTL ELSE CA.AMT END, 0)
            END,0) AMT, ROUND(CA.AAMT) AAMT,
        SYM.PARVALUE PARVALUE, EXSYM.PARVALUE EXPARVALUE,
        CF.FULLNAME, CF.IDCODE, CF.CUSTODYCD, CF.CIFID,
        (CASE WHEN CF.VAT=''Y''
            THEN (CASE WHEN CAMAST.PITRATEMETHOD=''IS'' OR CAMAST.PITRATEMETHOD=''NO'' THEN 0 ELSE
                    (CASE WHEN CAMAST.CATYPE IN (''016'',''023'',''033'')  THEN ROUND(CAMAST.PITRATE*CA.INTAMT/100)
                       WHEN CAMAST.CATYPE = ''024'' THEN ROUND(CA.BALANCE*CAMAST.EXPRICE*CAMAST.PITRATE/100/CAMAST.EXERCISERATIO)
                        WHEN CAMAST.CATYPE = ''010'' AND CF.CUSTTYPE = ''I'' THEN ROUND(CAMAST.PITRATE*CA.AMTDTL/100)
                        WHEN CAMAST.CATYPE = ''010'' AND CF.CUSTTYPE = ''B'' THEN 0
                       ELSE ROUND(CAMAST.PITRATE*CA.AMT/100) END) END)
            ELSE 0 END
        ) DUTYAMT,
        CAMAST.DESCRIPTION,
        (CASE WHEN AF.COREBANK=''Y'' THEN 0 ELSE 1 END) ISCOREBANK,
        (CASE WHEN CAMAST.CATYPE IN (''027'') THEN 1 ELSE 0 END) ISDEBITSE,
        NVL(SE.TRADE,0) TRADE,
        ROUND(CA.INTAMT) INTAMT,
        NVL(CA.TRFEEAMT, CA.TRFFEE) TRFEEAMT,
        ROUND(CA.DFAMT) DFAMT,
        CAD.EXECRATE, CAMAST.ISINCODE,
        DD.ACCTNO DDACCTNO
FROM SBSECURITIES SYM, SBSECURITIES EXSYM, CFMAST CF, SEMAST SE,
(
    SELECT CA.*, (CASE WHEN CATYPE = ''024'' THEN TO_NUMBER(SUBSTR(EXRATE,0,INSTR(EXRATE,''/'') - 1))/TO_NUMBER(SUBSTR(EXRATE,INSTR(EXRATE,''/'')+1,LENGTH(EXRATE))) ELSE 0 END) EXERCISERATIO
    FROM CAMAST CA
) CAMAST, AFMAST AF,
(SELECT * FROM CAMASTDTL WHERE DELTD <> ''Y'' AND STATUS =''P'') CAD,
(
    SELECT CA1.*,  NVL(CSD.FEEAMT,0) TRFEEAMT, NVL(CSD.AMT, CA1.AMT) AMTDTL
    FROM CASCHD CA1, (SELECT CSD1.* FROM CASCHDDTL CSD1 WHERE CSD1.DELTD <> ''Y'' AND CSD1.STATUS =''P'') CSD
    WHERE CA1.DELTD <> ''Y''
    AND CA1.AUTOID = CSD.AUTOID_CASCHD (+)
    AND CA1.AFACCTNO = CSD.AFACCTNO (+)
) CA,
(
    SELECT * FROM DDMAST WHERE ISDEFAULT=''Y'' AND STATUS <> ''C''
) DD,
(SELECT * FROM ALLCODE WHERE CDTYPE = ''CA'' AND CDNAME = ''CATYPE'') A0
WHERE CA.CAMASTID = CAMAST.CAMASTID AND CAMAST.CODEID = SYM.CODEID
AND CAMAST.CAMASTID = CAD.CAMASTID (+)
AND NVL(CAMAST.EXCODEID,CAMAST.CODEID)  = EXSYM.CODEID
AND CA.AFACCTNO = AF.ACCTNO AND AF.CUSTID = CF.CUSTID
AND CA.DELTD = ''N'' AND CA.STATUS IN (''S'',''H'',''W'',''K'',''I'') AND CAMAST.STATUS  IN (''K'',''I'',''H'')
AND CA.AMT > 0 AND CA.ISEXEC=''Y''
AND SE.ACCTNO(+) = CA.AFACCTNO||CA.CODEID
AND CF.CUSTODYCD = DD.CUSTODYCD(+)
AND CAMAST.CATYPE = A0.CDVAL 
)A WHERE 0=0', 'CAMAST', NULL, 'CAMASTID DESC', '3359', 0, 5000, 'N', 30, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;