SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3343','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CA3343', 'Danh sách phân bổ tiền chờ thực hiện', 'List of allocating pending ', 'SELECT CA.AUTOID, CA.TRADE, CA.CAMASTID, CA.AFACCTNO,A0.CDCONTENT CATYPE, CA.CODEID, CA.EXCODEID, CA.QTTY,
       CASE WHEN CAMAST.CATYPE=''010'' THEN NVL(CSD.AMT,0) ELSE(CA.AMT-CA.INTAMT) END AMT,
       CA.AQTTY, CFMAST.ADDRESS ,CA.AAMT, SYM.SYMBOL, A1.CDCONTENT STATUS,CA.AFACCTNO || CA.CODEID  SEACCTNO,
       CA.AFACCTNO || (CASE WHEN CAMAST.EXCODEID IS NULL THEN CAMAST.CODEID ELSE CAMAST.EXCODEID END) EXSEACCTNO,
       SYM.PARVALUE PARVALUE, EXSYM.PARVALUE EXPARVALUE, CAMAST.REPORTDATE REPORTDATE, CAMAST.ACTIONDATE,
       CFMAST.FULLNAME, CFMAST.IDCODE, CFMAST.CUSTODYCD,CFMAST.CIFID,CASE WHEN CI.COREBANK=''Y'' THEN 1 ELSE 0 END COREBANK,
       CASE WHEN CI.COREBANK=''Y'' THEN ''YES'' ELSE ''NO'' END ISCOREBANK
       ,DECODE(PRICEACCOUNTING,0,EXSYM.PARVALUE,PRICEACCOUNTING) PRICEACCOUNTING, A0.CDVAL CATYPEVALUE,
       CA.INTAMT, CAMAST.ISINCODE
FROM CASCHD CA, SBSECURITIES SYM, SBSECURITIES EXSYM, ALLCODE A0, ALLCODE A1, CAMAST, AFMAST, CFMAST,DDMAST CI,
    (SELECT CSD1.* FROM CASCHDDTL CSD1 WHERE CSD1.DELTD <> ''Y'' AND CSD1.STATUS =''P'') CSD
WHERE A0.CDTYPE = ''CA'' AND A0.CDNAME = ''CATYPE'' AND A0.CDVAL = CAMAST.CATYPE
AND A1.CDTYPE = ''CA'' AND A1.CDNAME = ''CASTATUS'' AND A1.CDVAL = CA.STATUS
AND CA.CAMASTID = CAMAST.CAMASTID AND CAMAST.CODEID = SYM.CODEID
AND CA.DELTD = ''N'' AND CA.ISCI = ''N''
AND EXSYM.CODEID = (CASE WHEN CAMAST.EXCODEID IS NULL THEN CAMAST.CODEID ELSE CAMAST.EXCODEID END)
AND CA.AFACCTNO = AFMAST.ACCTNO AND CI.AFACCTNO=AFMAST.ACCTNO
AND AFMAST.CUSTID = CFMAST.CUSTID
AND CA.AUTOID = CSD.AUTOID_CASCHD (+)
AND CA.AFACCTNO = CSD.AFACCTNO (+)
AND CA.STATUS IN (''I'',''C'')
AND (CASE WHEN CAMAST.CATYPE=''010'' THEN NVL(CSD.AMT,0)
          WHEN CAMAST.CATYPE=''015'' THEN NVL(CA.INTAMT,0)
          ELSE(CA.AMT-CA.INTAMT) END) > 0
AND CI.ISDEFAULT = ''Y'' 
AND CI.STATUS <> ''C''', 'CAMAST', NULL, NULL, '3343', 0, 5000, 'N', 30, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;