SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('RETYPE','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('RETYPE', 'Loại hình quản lý đại lý/môi giới', 'Remiser product type', 'SELECT TYP.ACTYPE, SBC.CCYNAME CCYCD, TYP.TYPENAME, TYP.GLGRP,
A0.CDCONTENT STATUS, 
(CASE WHEN TYP.APPRV_STS=''P'' THEN ''Y'' ELSE ''N'' END) APRALLOW,
TYP.GLBANK, TYP.SUBCD, TYP.DESCRIPTION, A1.CDCONTENT RETYPE, --DECODE(TYP.RETYPE,''I'',''...'',A2.CDCONTENT)
A2.CDCONTENT REROLE
FROM RETYPE TYP, SBCURRENCY SBC, ALLCODE A0, ALLCODE A1, ALLCODE A2
WHERE A0.CDTYPE = ''SY'' AND A0.CDNAME = ''TYPESTS'' AND A0.CDVAL=TYP.APPRV_STS AND SBC.CCYCD=TYP.CCYCD
AND A1.CDTYPE = ''RE'' AND A1.CDNAME = ''RETYPE'' AND A1.CDVAL=TYP.RETYPE
AND A2.CDTYPE = ''RE'' AND A2.CDNAME = ''REROLE'' AND A2.CDVAL=TYP.REROLE', 'RETYPE', 'frmTDTYPE', 'ACTYPE', '', 0, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;