SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CFAUTH_DETAIL','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CFAUTH_DETAIL', 'Người ủy quyền', 'Authorize', 'SELECT   CF.CUSTODYCD AS AUTHORIZER_ACCOUNT
        ,CF.FULLNAME AS AUTHORIZER_NAME
        ,CF1.CUSTODYCD AS AUTHORIZED_ACCOUNT
      --,NVL(AU.CUSTID, AU.LICENSENO) CUSTID
        ,UPPER(AU.FULLNAME) AS AUTHORIZED_NAME
      --,AU.ADDRESS
      --,CF1.EMAIL
        ,AU.VALDATE
        ,CD1.<@CDCONTENT> DELTDCH
FROM CFAUTH AU, CFMAST CF, AFMAST AF, SYSVAR SYS,CFMAST CF1,ALLCODE CD1
WHERE CF.CUSTID = AU.CFCUSTID
      AND AF.CUSTID = CF.CUSTID
      AND NVL(AU.CUSTID, AU.LICENSENO) = CF1.CUSTID(+)
      AND CD1.CDVAL = AU.DELTD AND cd1.cdname = ''CANCELED''
      AND SYS.VARNAME = ''CURRDATE''
      AND TO_DATE(VARVALUE,''DD/MM/RRRR'') BETWEEN AU.VALDATE AND AU.EXPDATE
      AND AU.FULLNAME IS NOT NULL', 'CFAUTH', 'frmCFAUTH', 'AUTHORIZER_ACCOUNT', NULL, NULL, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;