SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('BROKER_CASHHOLD','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('BROKER_CASHHOLD', 'Tra cứu thông tin tài khoản thấu chi', 'Overdraft account information', 'SELECT MSGACCT, REQTXNUM, TXNUM, TXDESC, CCYCD, AMOUNT, TLNAME, TXTIME, SHORTNAME, BRNAME, BRPHONE, NOTE, STATUS, STATUSTEXT, UNHOLD, UNHOLDTEXT,
    (CASE WHEN UNHOLD = ''N'' THEN 4 ELSE 1 END) TXSTATUSCD,
    (CASE WHEN UNHOLD = ''N'' THEN ''Y'' ELSE ''N'' END) APRALLOW,
    ''N'' REFUSEALLOW, BANKACCTNO, PURPOSE
FROM (
    SELECT L.MSGACCT, R.REQTXNUM, L.TXNUM, X.EN_TXDESC TXDESC, F.BANKACCTNO, F.CCYCD, L.MSGAMT AMOUNT, P.TLNAME, L.TXTIME, M.SHORTNAME, MX1.EXTRAVAL BRNAME, MX2.EXTRAVAL BRPHONE, NOTE, L.CFCUSTODYCD CUSTODYCD, R.STATUS, R.UNHOLD, 
        A.<@CDCONTENT> STATUSTEXT, A1.<@CDCONTENT> UNHOLDTEXT, A2.<@CDCONTENT> PURPOSE
    FROM TLTX X, FAMEMBERSEXTRA MX1, FAMEMBERSEXTRA MX2, TLPROFILES P,
    (SELECT * FROM CRBTXREQ WHERE TRFCODE = ''HOLD'') R,
    (SELECT * FROM TLLOG WHERE TLTXCD = ''6690'') L,
    (SELECT * FROM FAMEMBERS WHERE ROLES = ''BRK'') M,
    (SELECT * FROM ALLCODE WHERE  CDNAME = ''RMSTATUS'' AND CDTYPE = ''CI'') A,
    (SELECT * FROM ALLCODE WHERE  CDNAME = ''UNHOLD'' AND CDTYPE = ''MT'') A1,
    (SELECT * FROM ALLCODE WHERE  CDNAME = ''HOLDPURPOSE'' AND CDTYPE = ''RM'') A2,
    (
        SELECT TXNUM,
        MAX (CASE WHEN F.FLDCD = ''05'' THEN F.CVALUE ELSE '''' END)  MEMBERID,
        MAX (CASE WHEN F.FLDCD = ''06'' THEN F.CVALUE ELSE '''' END)  BRNAME,
        MAX (CASE WHEN F.FLDCD = ''07'' THEN F.CVALUE ELSE '''' END)  BRPHONE,
        MAX (CASE WHEN F.FLDCD = ''20'' THEN F.CVALUE ELSE '''' END)  CCYCD,
        MAX (CASE WHEN F.FLDCD = ''93'' THEN F.CVALUE ELSE '''' END)  BANKACCTNO,
        MAX (CASE WHEN F.FLDCD = ''30'' THEN F.CVALUE ELSE '''' END)  NOTE
        FROM TLLOGFLD F
        WHERE FLDCD IN (''05'', ''06'', ''07'', ''20'', ''93'',''30'')
        GROUP BY TXNUM
    ) F
    WHERE L.TXNUM = F.TXNUM 
    AND L.TLID = P.TLID
    AND F.MEMBERID = M.AUTOID
    AND MX1.AUTOID = F.BRNAME
    AND MX2.AUTOID = F.BRPHONE
    AND R.OBJNAME = L.TLTXCD
    AND L.TLTXCD = X.TLTXCD
    AND R.OBJKEY = L.TXNUM
    AND R.TXDATE = L.TXDATE
    AND R.STATUS = A.CDVAL(+)
    AND R.UNHOLD = A1.CDVAL(+)
    AND R.REQCODE = A2.CDVAL(+)
    ORDER BY L.TXNUM DESC
) WHERE 0=0', 'CIMAST', NULL, NULL, NULL, 0, 5000, 'N', 30, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;