SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('ODER03','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('ODER03', 'Hoàn trả ứng trước tiền bán lệnh bán lỗi(8842)', 'Revert Advance Payment of error order (8842)', 'SELECT OD.TXDATE, OD.ORDERID, OD.CUSTODYCD, OD.AFACCTNO, OD.CIACCTNO, OD.RRTYPE, OD.CUSTBANK, OD.STAUTOID,
    OD.CODEID, OD.SYMBOL, OD.EXECTYPEVL, OD.EXECTYPE, OD.MATCHAMT, OD.CLEARDATE,
    OD.AAMT, OD.FEEAMT, OD.ADLAUTOID, OD.FULLNAME, OD.MBLOCK, GREATEST(CASE WHEN NVL(ODM.AAMT,0) > 0 AND OD.TXDATE = OD.ADTXDATE THEN OD.AAMT - OD.FEEAMT ELSE 0 end,0) VSDAMT
FROM
(
SELECT OD.TXDATE, OD.ORDERID, CF.CUSTODYCD, STS.AFACCTNO, STS.ACCTNO CIACCTNO, AD.RRTYPE, AD.CUSTBANK, AD.AUTOID STAUTOID,
    SB.CODEID, SB.SYMBOL, OD.EXECTYPE EXECTYPEVL, A.CDCONTENT EXECTYPE, OD.MATCHAMT, STS.CLEARDATE,
    ADL.AAMT, GREATEST(ROUND(ADL.AAMT * ADT.ADVRATE/36500 * (AD.CLEARDT - AD.TXDATE)), ADT.ADVMINFEE) FEEAMT,
    ADL.AUTOID ADLAUTOID, CF.FULLNAME, CI.MBLOCK, AD.TXDATE ADTXDATE
FROM STSCHD STS, ODMAST OD, CFMAST CF, AFMAST AF, SBSECURITIES SB, ALLCODE A, ADSCHD AD, ADSCHDDTL ADL, ADTYPE ADT, CIMAST CI
WHERE STS.AFACCTNO = AF.ACCTNO AND CF.CUSTID = AF.CUSTID
    AND STS.AFACCTNO = AD.ACCTNO AND AD.ADTYPE = ADT.ACTYPE
    AND AD.TXDATE = ADL.TXDATE AND AD.TXNUM = ADL.TXNUM
    AND ADL.ORDERID = OD.ORDERID AND CI.AFACCTNO = AF.ACCTNO
    AND STS.CODEID = SB.CODEID AND STS.ORGORDERID = OD.ORDERID
    AND STS.DUETYPE IN (''RM'') AND STS.DELTD = ''N''
    AND OD.ERROD = ''Y'' AND OD.ERRSTS = ''M''
    AND A.CDTYPE = ''OD'' AND A.CDNAME = ''EXECTYPE'' AND A.CDVAL = OD.EXECTYPE
    AND STS.AAMT >0 AND ADL.DELTD = ''N''
) OD
LEFT JOIN
(SELECT * FROM ODMAPEXT ODM WHERE ODM.ISVSD = ''Y'' AND ODM.AAMT > 0 UNION ALL SELECT * FROM ODMAPEXTHIST ODM WHERE ODM.ISVSD = ''Y'' AND ODM.AAMT > 0) ODM
ON OD.ORDERID = ODM.ORDERID
WHERE 0 = 0 ', 'OD.ODMAST', NULL, 'TXDATE DESC, CUSTODYCD, SYMBOL, ORDERID', '8842', NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;