SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3406','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CA3406', 'Hủy đăng ký bán lại TPRL', 'Cancle register PPBs redemption to issuer', 'SELECT V.*, REG.QTTY REGQTTY, REG.AUTOID REGAUTOID
FROM V_CA040REG V, 
(
    SELECT * FROM CA040REGISTER  WHERE MSGSTATUS IN (''P'',''R'') AND DELTD = ''N'' 
) REG
WHERE V.AUTOID = REG.CASCHDAUTOID', 'CA3406', NULL, 'REGAUTOID DESC', '3406', NULL, 5000, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;