SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CAMASTVSD_DE','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CAMASTVSD_DE', 'Quản lý thực hiện quyền gửi báo cáo VSD', 'Coporate action management', 'SELECT CA.CAMASTID,CA.VSDID,A2.CDCONTENT CATYPE,TOSYM.SYMBOL,SYM.SYMBOL TOSYMBOL,CA.REPORTDATE,CA.ACTIONDATE,CA.INACTIONDATE,CA.BEGINDATE,CA.DUEDATE,
CA.TRADEDATE,CA.FRDATETRANSFER,CA.TODATETRANSFER,CA.DESCRIPTION,CA.PITRATESE,CA.PITRATE,CA.PITRATEMETHOD,
CA.MAKERID,CA.APPRVID,A1.CDCONTENT STATUS,CA.VSDCAID,CA.VSDCAID || '','' || CA.ISINCODE || '','' || NVL(CA.VSDCATYPE, A3.CDCONTENT) DEVSDCAID
FROM CAMAST CA, SBSECURITIES TOSYM,SBSECURITIES SYM,
(SELECT * FROM ALLCODE WHERE CDNAME = ''CASTATUS'' AND CDTYPE = ''CA'' AND CDUSER = ''Y'') A1,
(SELECT * FROM ALLCODE WHERE CDNAME = ''CATYPE'' AND CDTYPE = ''CA'' AND CDUSER = ''Y'') A2,
(SELECT * FROM ALLCODE WHERE CDNAME = ''CATYPEVSD'' AND CDTYPE = ''CA'' AND CDUSER = ''Y'') A3
WHERE NVL(CA.TOCODEID, CA.CODEID) = TOSYM.CODEID
AND CA.CODEID=SYM.CODEID
AND CA.STATUS = A1.CDVAL(+)
AND CA.CATYPE = A2.CDVAL(+)
AND CA.CATYPE = A3.CDVAL(+)', 'CAMAST', 'frmCAMAST', 'CAMASTID DESC', NULL, 0, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;