SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SEALL','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('SEALL', 'Quản lý chứng khoán', 'Securities management', '
SELECT SEC.CODEID ,ISS.fullname FULLNAME,

       ISS.fullname DESCRIPTION, SEC.PARVALUE, SEINFO.BASICPRICE PRICE,
       SEC.SYMBOL, SEC.CODEID, SEC.INTPERIOD, SEC.INTRATE,
       SEC.SYMBOL OPTSYMBOL
  FROM SBSECURITIES SEC, SECURITIES_INFO SEINFO, ISSUERS ISS
 WHERE SEC.TRADEPLACE <> ''006''
   AND SEC.CODEID = SEINFO.CODEID
   AND SEC.SECTYPE <> ''004''
   AND SEC.issuerid = ISS.issuerid ', 'SEALL', '', '', '', NULL, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;