SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('TXCHKRULES','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('TXCHKRULES', 'Quy định kiểm tra giao dịch', 'Rule check transaction', 'SELECT MST.AUTOID, MST.RULENAME,
        MST.TORD, A1.CDCONTENT TORD_DESC,
        MST.LLEVEL, A2.CDCONTENT LLEVEL_DESC,
        MST.CHKTYPE, A3.CDCONTENT CHKTYPE_DESC,
        MST.KEYWORDS,
        MST.TLTXCD, MST.TLTXCD || '': '' || TL.TXDESC TXDESC, MST.TLTXCD || '': '' || TL.EN_TXDESC EN_TXDESC,
        MST.CCYCD, SB.SHORTCD,
        MST.AMT,
        MST.Effectivecd, A4.CDCONTENT EFFECTIVECD_DESC,
        MST.REFCUSTODYCD,
        MST.REFMEMBERID,
        A0.CDCONTENT STATUS,
        (CASE WHEN STATUS IN (''P'') THEN ''Y'' ELSE ''N'' END) APRALLOW
FROM TXCHKRULES MST, ALLCODE A0, ALLCODE A1, ALLCODE A2, ALLCODE A3, ALLCODE A4,
     TLTX TL, SBCURRENCY SB
WHERE MST.STATUS = A0.CDVAL AND A0.CDNAME =''APPRV_STS'' AND A0.CDTYPE=''SY''
    AND MST.TORD = A1.CDVAL AND A1.CDNAME =''TORD'' AND A2.CDTYPE=''SA''
    AND MST.LLEVEL = A2.CDVAL AND A2.CDNAME =''LLEVEL'' AND A2.CDTYPE=''SA''
    AND MST.CHKTYPE = A3.CDVAL AND A3.CDNAME =''CHKTYPE'' AND A3.CDTYPE=''SA''
    AND MST.EFFECTIVECD = A4.CDVAL AND A4.CDNAME =''EFFECTIVECD'' AND A4.CDTYPE=''SA''
    AND MST.TLTXCD = TL.TLTXCD AND MST.CCYCD = SB.CCYCD', 'TXCHKRULES', NULL, NULL, NULL, 0, 1000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;