SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SE2282','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('SE2282', 'Sinh chuyển chứng khoán lẻ giữa các tiểu khoản cùng tài khoản', 'Gen internal transferring odd lot quantity ', '
SELECT TRF.SYMBOL,SB.CODEID,TRF.AFACCTNO, TRF.AFACCTNO || SB.CODEID ACCTNO, AFACCTNO2, AFACCTNO2 || SB.CODEID ACCTNO2, 0 DEPOBLOCK, 0 PRICE, QTTY AMT, PARVALUE,
QTTY, 0 TRADEWTF, ''001'' QTTYTYPE,  0 CIDFPOFEEACR, 0 DEPOBLOCK_CHK, TRF.AUTOID, 0 ORGAMT, 0 ORGTRADEWTF, TRF.DESCRIPTION , ''001'' TRTYPE, CF1.FULLNAME CUSTNAME,
CF1.ADDRESS, CF1.IDCODE LICENSE,  CF2.FULLNAME CUSTNAME2, CF2.ADDRESS ADDRESS2, CF2.IDCODE LICENSE2, 0 NEEDQTTY, least(trade -NVL(od.secureamt,0)+NVL(od.sereceiving,0),GETAVLSEWITHDRAW(SE.ACCTNO)) AMT_CHK,
cf2.custodycd custodycd2,cf1.custodycd

FROM TBLTRFSTOCK TRF, SBSECURITIES SB, AFMAST AF1, AFMAST AF2,CFMAST CF1, CFMAST CF2,SEMAST SE,
(SELECT SEACCTNO, SUM(SECUREAMT) SECUREAMT, SUM(SECUREMTG) SECUREMTG, SUM(RECEIVING) SERECEIVING
    FROM (SELECT OD.SEACCTNO,
            CASE WHEN OD.EXECTYPE IN (''NS'', ''SS'') AND OD.TXDATE =to_date(SY.VARVALUE,''DD/MM/YYYY'') THEN REMAINQTTY + EXECQTTY ELSE 0 END SECUREAMT,
            CASE WHEN OD.EXECTYPE = ''MS''  AND OD.TXDATE =to_date(SY.VARVALUE,''DD/MM/YYYY'') THEN REMAINQTTY + EXECQTTY ELSE 0 END SECUREMTG,
            CASE WHEN OD.EXECTYPE = ''NB'' THEN ST.QTTY ELSE 0 END RECEIVING
        FROM ODMAST OD, STSCHD ST, ODTYPE TYP, SYSVAR SY
        WHERE OD.DELTD <> ''Y''  AND OD.EXECTYPE IN (''NS'', ''SS'',''MS'', ''NB'')
            AND OD.ORDERID = ST.ORGORDERID(+) AND ST.DUETYPE(+) = ''RS''
            And OD.ACTYPE = TYP.ACTYPE
            AND SY.GRNAME = ''SYSTEM'' AND SY.VARNAME = ''CURRDATE''
            AND ((TYP.TRANDAY <= (SELECT SUM(CASE WHEN CLDR.HOLIDAY = ''Y'' THEN 0 ELSE 1 END)
            FROM SBCLDR CLDR
            WHERE CLDR.CLDRTYPE = ''000'' AND CLDR.SBDATE >= ST.TXDATE AND CLDR.SBDATE <= (select to_date(VARVALUE,''DD/MM/YYYY'') from sysvar where grname=''SYSTEM'' and varname=''CURRDATE'')) AND OD.EXECTYPE = ''NB'')
            OR OD.EXECTYPE IN (''NS'',''SS'',''MS'')))
    GROUP BY SEACCTNO ) od

WHERE TRF.SYMBOL=SB.SYMBOL AND TRF.AFACCTNO=AF1.ACCTNO AND TRF.AFACCTNO2=AF2.ACCTNO AND CF1.CUSTID = AF1.CUSTID
AND CF2.CUSTID=AF2.CUSTID AND NVL(TRF.STATUS,''N'') <>''A'' AND NVL(TRF.DELTD,''N'')<>''Y'' AND NVL(TRF.DELTD,''N'')<>''Y'' AND NVL(TRF.DELTD,''N'')<>''Y''
AND TRF.AFACCTNO || SB.CODEID = SE.ACCTNO
and SE.ACCTNO = OD.SEACCTNO (+)', 'SEMAST', 'frmSEMAST', NULL, '2242', NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;