SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SE2235','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('SE2235', 'Hủy yêu cầu giải tỏa cầm cố chưa gửi VSD (2235)', 'View pending to cancel release mortage (wait for 2235)', 'SELECT SE.AUTOID, SE.BUSDATE, SE.TXDATE, SE.AFACCTNO, SE.ACCTNO, CF.FULLNAME CUSTNAME, CF.CUSTODYCD, SB.SYMBOL, SB.PARVALUE,
    SE.QTTY, SE.FEEAMT, SB.CODEID, CF.ADDRESS, CF.IDCODE LICENSE, CF.MCUSTODYCD
FROM SEMORTAGE SE, AFMAST AF ,CFMAST CF, SBSECURITIES SB
WHERE SE.AFACCTNO = AF.ACCTNO
AND AF.CUSTID = CF.CUSTID
AND SE.TLTXCD IN (''2233'',''2239'')
AND SE.STATUS IN (''N'')
AND SE.DELTD = ''N''
AND SE.SENDQTTY = 0
AND SE.RELEASED = 0
AND SE.CODEID = SB.CODEID', 'SEMAST', '', '', '2234', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;