SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('ISSUES','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('ISSUES', 'Quản lý đợt phát hành trái phiếu', 'Bond issue management ', 'SELECT ISS.*, A1.CDCONTENT TYPERATE, A2.CDCONTENT PURPOSE, A3.CDCONTENT ROLE
FROM VW_ISSUES ISS,
(
    SELECT * FROM ALLCODE WHERE CDNAME = ''TYPERATE'' AND CDTYPE = ''CB''
) A1,
(
    SELECT * FROM ALLCODE WHERE CDNAME = ''BAPURPOSE'' AND CDTYPE = ''BA''
) A2,
(
    SELECT * FROM ALLCODE WHERE CDNAME = ''BAISSUESROLE'' AND CDTYPE = ''BA''
) A3
WHERE ISS.EFFECTIVE = ''Y''
AND NVL(ISS.MATURITYDATE, GETCURRDATE) >= GETCURRDATE
AND ISS.VTYPERATE = A1.CDVAL(+)
AND ISS.VPURPOSE = A2.CDVAL(+)
AND ISS.VROLE = A3.CDVAL(+)', 'ISSUES', '', 'ISS.AUTOID', '', NULL, 5000, 'Y', 1, '', 'Y', 'T', '', 'N', '');COMMIT;