SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('V_LNMAST','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('V_LNMAST', 'Quản lý Deal DF của khách hàng', 'DF Deal Management', 'select DF.ACCTNO DFACCTNO,
DF.FULLNAME,DF.SYMBOL, CHD.ACCTNO, DF.DFTYPE,CHD.OVERDUEDATE,DF.AFACCTNO AFACCTNO, DF.CUSTODYCD, CHD.INTNMLACR, CHD.FEEINTNMLACR , ln.AUTOAPPLY, , ln.AUTOAPPLY OAUTOAPPLY  
from (select v_dfmast.*,(SELECT  varvalue FROM SYSVAR
WHERE GRNAME=''SYSTEM'' AND VARNAME=''CURRDATE'') CURRDATE
from v_dfmast) df, lnmast ln,
(SELECT ACCTNO,OVERDUEDATE , sum(INTNMLACR) INTNMLACR, sum(FEEINTNMLACR) FEEINTNMLACR 
    FROM LNSCHD 
    WHERE OVERDUEDATE IS NOT NULL
GROUP BY ACCTNO ,OVERDUEDATE
HAVING SUM(NML) + SUM(ovd) + SUM(intnmlacr) + SUM(fee) +
SUM(intdue) +
SUM(intovd) + SUM(intovdprin) + sum(feedue) +
sum(feeovd) >0 ) CHD
WHERE CHD.ACCTNO= DF.LNACCTNO and df.lnacctno = ln.acctno and
OVERDUEDATE >= to_date
(CURRDATE,''DD/MM/YYYY'')', 'V_LNMAST', 'frmV_LNMAST', 'ACCTNO DESC', '', NULL, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;