SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('RMCBFABANKPAYMENT','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('RMCBFABANKPAYMENT', 'Tra cứu trạng thái chỉ thị thanh toán (từ AMC)', 'Bank payment instruction status (from AMC)', 'SELECT C.GLOBALID,C.CUSTODYCD,C.ACCTNO,C.REFBANKACCT, A1.EN_CDCONTENT TXTYPE,A3.EN_CDCONTENT TRANSTYPE,
       C.TLTXCD,C.TXNUM,C.TXDATE,C.CITAD,C.BENEFICIARYACCOUNT BANKACCT,C.BANKNAME,C.CUSTNAME,C.TXAMT,C.REFCONTRACT,
       A2.EN_CDCONTENT FEETYPE,C.SUPERBANK,A4.EN_CDCONTENT ISAPPRSB ,A5.EN_CDCONTENT BANKSTATUS,
       C.RESPONSE,C.VALUEDATE, D.EN_ERRDESC ERRMSG
FROM CBFA_BANKPAYMENT C, ALLCODE A1, ALLCODE A2, ALLCODE A3, ALLCODE A4, ALLCODE A5, DEFERROR D
WHERE A1.CDNAME = ''CBTXTYPE''
      AND A1.CDVAL = C.TXTYPE
      AND A2.CDNAME = ''IOROFEE''
      AND A2.CDVAL = C.FEETYPE
      AND A2.CDTYPE = ''SA''
      AND A3.CDTYPE = ''FA''
      AND A3.CDNAME = ''TRANSTYPE''
      AND A3.CDVAL = C.TRANSTYPE
      AND A4.CDTYPE = ''SA''
      AND A4.CDNAME = ''ISAPPRSB''
      AND A4.CDVAL = C.ISAPPRSB
      AND A5.CDTYPE = ''SA''
      AND A5.CDNAME = ''SYNCBANKSTATUS''
      AND A5.CDVAL = C.BANKSTATUS
      AND D.ERRNUM(+) = C.ERR_CODE', 'RMCBFABANKPAYMENT', 'frmRMCBFABANKPAYMENT', 'GLOBALID DESC', NULL, 0, 100, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;