SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('RPTGENCFG','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('RPTGENCFG', 'Quản lý cài đặt gen báo cáo tự động', 'Set up automatically general reports', 'SELECT R.AUTOID     AUTOID,
       R.RPTID      RPTID,
       R.RPTNAME    RPTNAME,
       r.filetype FILETYPE,
       A2.CDCONTENT CYCLE_CRET
  FROM RPTGENCFG R, ALLCODE A2
 WHERE R.CYCLE_CRET = A2.CDVAL
   AND A2.CDNAME = ''TEMPLATE_CYCLE''
   AND A2.CDTYPE = ''SY'' ', 'RPTGENCFG', 'frmRPTGENCFG', '', '', 0, 5000, 'N', 1, 'YYYYYYYYYYN', 'Y', 'T', '', 'N', '');COMMIT;