SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CF0064','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CF0064', 'Tra cứu Tiểu khoản chờ duyệt', 'Contract pending to approve', 'SELECT AFMAST.ACTYPE, SUBSTR(AFMAST.CUSTID,1,4) || ''.'' || SUBSTR(AFMAST.CUSTID,5,6) CUSTID,CF.FULLNAME,  SUBSTR(AFMAST.ACCTNO,1,4) || ''.'' || SUBSTR(AFMAST.ACCTNO,5,6) ACCTNO, AFMAST.AFTYPE,A10.cdcontent TYPENAME, A1.CDCONTENT TRADEFLOOR,A2.CDCONTENT TRADETELEPHONE,A3.CDCONTENT TRADEONLINE,CF.PIN,CF.MOBILESMS TRADEPHONE,AFMAST.BANKACCTNO,AFMAST.SWIFTCODE,CF.EMAIL,CF.ADDRESS,CF.FAX,AFMAST.ACCTNO CIACCTNO,AFMAST.LASTDATE,A8.CDCONTENT STATUS,AFMAST.ADVANCELINE,AFMAST.BRATIO,A9.CDCONTENT TERMOFUSE,AFMAST.DESCRIPTION
FROM AFMAST AFMAST,CFMAST CF,AFTYPE AFT, ALLCODE A1, ALLCODE A2,ALLCODE A3,ALLCODE A8,ALLCODE A9 ,ALLCODE A10
WHERE AFMAST.STATUS=''T'' AND AFMAST.CUSTID=CF.CUSTID AND AFMAST.ACTYPE=AFT.ACTYPE AND
A1.CDTYPE = ''SY'' AND A1.CDNAME = ''YESNO'' AND
A1.CDVAL= CF.TRADEFLOOR AND
A2.CDTYPE = ''SY'' AND A2.CDNAME = ''YESNO'' AND
A2.CDVAL= CF.TRADETELEPHONE AND A3.CDTYPE = ''SY'' AND
A3.CDNAME = ''YESNO'' AND
A3.CDVAL= CF.TRADEONLINE AND
A8.CDTYPE = ''CF'' AND
A8.CDNAME = ''STATUS'' AND
A8.CDVAL = AFMAST.STATUS AND
A9.CDTYPE = ''CF'' AND
A9.CDNAME = ''TERMOFUSE'' AND
A9.CDVAL = AFMAST.TERMOFUSE AND
A10.CDTYPE = ''CF'' AND
A10.CDNAME = ''AFTYPE'' AND
A10.CDVAL = AFMAST.AFTYPE', 'AFMAST', '', '', '0064', NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;