SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3402','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CA3402', 'Yêu cầu đăng ký bán lại TPRL', 'Register PPBs redemption to issuer', 'SELECT V.*, V.QTTY + NVL(REG.QTTY, 0) REMAINQTTY_REG, (V.AQTTY - (V.QTTY + NVL(REG.QTTY, 0))) MAXQTTY_REG
FROM V_CA040REG V,
(
    SELECT CASCHDAUTOID, SUM(QTTY) QTTY
    FROM CA040REGISTER 
    WHERE MSGSTATUS IN (''P'', ''R'', ''S'')
    AND DELTD = ''N'' 
    GROUP BY CASCHDAUTOID
) REG
WHERE V.AUTOID = REG.CASCHDAUTOID(+)', 'CA3402', NULL, 'AUTOID DESC', '3402', NULL, 5000, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;