SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('BA0005','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('BA0005', 'CHUYỂN NHƯỢNG TP/ CHỨNG QUYỀN (BA)(1911)', 'BOND/ WARRANT TRANSFER (BA)(1911)', 'SELECT CF.CIFID, BON.CUSTODYCD, SB.CODEID, SB.SYMBOL, SB.SECTYPE, A1.CDCONTENT SECTYPE_NAME,
       BON.TRADE, BON.BLOCKED, CF.FULLNAME, BON.ACCTNO, AF.ACCTNO AFACCTNO,
       NVL(TL.MSGAMT,0) PENDING_AMT, BON.TRADE - NVL(TL.MSGAMT,0) ALLOWED_AMT
FROM BONDSEMAST BON,CFMAST CF,SBSECURITIES SB, ALLCODE A1, AFMAST AF,
     (
      SELECT MSGACCT, SUM(MSGAMT) MSGAMT
      FROM TLLOG
      WHERE TXSTATUS = ''4'' AND TLTXCD =''1911''
      GROUP BY MSGACCT
     )TL
WHERE BON.CUSTODYCD=CF.CUSTODYCD(+) AND
      BON.BONDCODE = SB.CODEID AND
      CF.CUSTID = AF.CUSTID AND
      A1.CDVAL = SB.SECTYPE AND A1.CDNAME =''SECTYPE'' AND A1.CDTYPE =''SA'' AND
      (BON.TRADE+ BON.BLOCKED) > 0 AND
      BON.ACCTNO = TL.MSGACCT (+)', 'BONDTYPE', NULL, NULL, '1911', 0, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;