SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CFLIMIT','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CFLIMIT', 'NH - Quản lý hạn mức tín dụng chung', 'Common credit limit of the bank', 'SELECT MST.AUTOID, MST.BANKID, MST.LMAMT, MST.LMAMTMAX, CF.FULLNAME,
A.CDCONTENT STATUS, A0.CDCONTENT DESC_LMTYP, A1.CDCONTENT DESC_LMSUBTYPE,
A2.CDCONTENT DESC_LMCHKTYP, MST.ODAMT, MST.LMAMTMAX-MST.ODAMT AVLLIMIT,
(CASE WHEN MST.STATUS=''P'' THEN ''Y'' ELSE ''N'' END) APRALLOW
FROM (select mst.*,cspks_cfproc.fn_get_bank_outstanding(mst.bankid,mst.lmsubtype) ODAMT from CFLIMIT MST) mst, CFMAST CF, ALLCODE A, ALLCODE A0, ALLCODE A1, ALLCODE A2
WHERE MST.BANKID=CF.CUSTID AND A.CDTYPE=''SY'' AND A.CDNAME=''APPRV_STS'' AND A.CDVAL=MST.STATUS
AND A0.CDTYPE=''CF'' AND A0.CDNAME=''LMTYP'' AND A0.CDVAL=MST.LMTYP
AND A1.CDTYPE=''CF'' AND A1.CDNAME=''LMSUBTYPE'' AND A1.CDVAL=MST.LMSUBTYPE
AND A2.CDTYPE=''CF'' AND A2.CDNAME=''LMCHKTYP'' AND A2.CDVAL=MST.LMCHKTYP', 'CFLIMIT', 'frmCFLIMIT', NULL, NULL, NULL, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;