SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('ISSUES_BA6030','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('ISSUES_BA6030', 'Quản lý đợt phát hành trái phiếu', 'Bond issue management ', 'SELECT * FROM (SELECT DISTINCT ISS.ISSUERID, ISR.SHORTNAME, ISR.FULLNAME 
FROM ISSUES ISS, ISSUERS ISR,ALLCODE A1 
WHERE ISS.ISSUERID = ISR.ISSUERID AND A1.CDTYPE = ''CB''  
AND A1.CDNAME = ''TYPERATE'' AND A1.CDUSER = ''Y'' 
AND A1.CDVAL = ISS.TYPERATE ) WHERE 0=0', 'ISSUES_BA6030', '', 'ISSUERID', '', NULL, 5000, 'Y', 1, '', 'Y', 'T', '', 'N', '');COMMIT;