SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('IMP6639_I078ONLINE','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('IMP6639_I078ONLINE', 'Tra cứu thông tin import 6639_I078', 'Tra cứu thông tin import 6639_I078', '  select t.FTYPE,t.TRADINGACCOUNT,t.VALUEDATE,
        t.AMOUNT,t.FEETYPE,t.DESCRIPTION,t.BANKTRANSFERS,t.beneficiaryaccount,
        t.BENEFICIARYBANK,t.BENERFICARYNAME,t.TLIDIMP MAKER,''TABLE'' TYPE from(
        select * from PAYMENTCASH_TEMP
        union all
        select * from PAYMENTCASH_TEMP_HIST) t
    where 1=1', 'IMP6639_I078ONLINE', '', '', '', NULL, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;