SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CUSTODYCD_MCF','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CUSTODYCD_MCF', 'Tra cứu nhanh thông tin khách hàng', 'Customer information', 'SELECT format_custid(CF1.CUSTID) CUSTID,
  case when CF.CUSTODYCD is null then '''' else CF.CUSTODYCD end CUSTODYCD,AF.ACCTNO
  , (CASE WHEN CF1.IDTYPE=''009'' THEN CF1.tradingcode ELSE CF1.IDCODE END ) tradingcode,
   (CASE WHEN CF1.IDTYPE=''009'' THEN CF1.tradingcodedt ELSE CF1.IDDATE END ) tradingcodedt,
  CF1.SHORTNAME,CF1.FULLNAME,CF1.DATEOFBIRTH,CF1.IDCODE,CF1.IDDATE , a2.cdcontent country, CF1.IDCODE || '' - ('' || TO_CHAR(CF1.IDDATE,''DD/MM/RRRR'') || '')'' IDCODE_DATE,
  CF1.IDPLACE,CF1.ADDRESS, CF1.mrloanlimit,CF1.t0loanlimit, AF.TLID OLDTLID, AF.CAREBY, CF.CUSTID T_CUSTID,
  CF1.MOBILESMS PHONE,CF1.FAX, NVL(CF.USERNAME, CF1.CUSTODYCD) USERNAME,
  A1.cdcontent AFSTATUS,
  (SELECT BANKACC FROM (SELECT * FROM CFOTHERACC ORDER BY AUTOID) CFO WHERE CFO.cfcustid LIKE CF.custid AND ROWNUM = 1  AND TYPE =1) BANKACC
  ,CF1.CIFID, CF1.CUSTATCOM, CF1.CIFID Margincontractno,CF1.COUNTRY COUNTTRYID,CF.MCUSTODYCD   
FROM CFMAST CF, TLGROUPS GRP, AFMAST AF, allcode a1, ALLCODE A2,CFMAST CF1
WHERE AF.CUSTID=CF.CUSTID
AND AF.CAREBY = GRP.GRPID
AND NVL(CF.MCUSTODYCD,CF.CUSTODYCD)=CF1.CUSTODYCD
AND A2.CDTYPE = ''CF'' AND A2.CDNAME = ''COUNTRY'' AND cf1.country = a2.cdval
and a1.cdtype=''RE'' and A1.cdname=''AFSTATUS'' AND A1.cdval= CF1.afstatus 
AND (SUBSTR(CF.CUSTID,1,4) = DECODE(''<$BRID>'', ''<$HO_BRID>'', SUBSTR(CF.CUSTID,1,4), ''<$BRID>'')
      OR AF.CAREBY IN (SELECT TLGRP.GRPID FROM TLGRPUSERS TLGRP WHERE TLID = ''<$TELLERID>'')
    )', 'CUSTODYCD_MCF', NULL, NULL, NULL, 0, 5000, 'N', 30, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;