SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3365','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CA3365', 'Đăng ký nhận cổ phiếu/tiền chuyển đổi từ trái phiếu gửi VSD', 'Register to receive stock/cash converted from bond send to VSD', 'SELECT V.*, V.REMAINBALANCE + NVL(REG.BALANCE, 0) REMAINBALANCE_REG, V.REMAINPBALANCE + NVL(REG.PBALANCE, 0) REMAINPBALANCE_REG,
    A1.<@CDCONTENT> CCONVERTTYPE
FROM V_CA3327 V,
(
    SELECT CASCHDAUTOID, 
        SUM(CASE WHEN CONVERTTYPE = ''SECU'' THEN QTTY ELSE 0 END) PBALANCE, 
        SUM(CASE WHEN CONVERTTYPE = ''CASH'' THEN QTTY ELSE 0 END) BALANCE
    FROM CA023REGISTER 
    WHERE MSGSTATUS = ''P''
    AND DELTD = ''N'' 
    GROUP BY CASCHDAUTOID
) REG,
(SELECT * FROM ALLCODE WHERE CDNAME = ''ACTIVETYPE'' AND CDTYPE = ''CA'') A1
WHERE V.AUTOID = REG.CASCHDAUTOID(+)
AND V.CONVERTTYPE = A1.CDVAL(+)
AND 0=0', 'CAMAST', NULL, NULL, '3365', NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;