SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3357','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CA3357', 'Gửi điện yêu cầu đăng kí đặt mua', 'Send a request to subscribe', 'SELECT CAS.AUTOID AUTOID, CAR.CAMASTID, CAR.CUSTODYCD CFCUSTODYCD, CAR.AFACCTNO, CA.TOCODEID CODEID, SB.SYMBOL, CA.VSDID, CAR.EXPRICE, CAR.PARVALUE, CAR.QTTY, CAR.BALANCE, CAR.AMT, CA.PURPOSEDESC, CAR.REFCODE REFCODE,
(CAR.AFACCTNO || (CASE WHEN CA.ISWFT = ''Y'' THEN (SELECT CODEID FROM SBSECURITIES WHERE REFCODEID = SB.CODEID) ELSE CA.TOCODEID END)) ACCTNO,
 A1.<@CDCONTENT> STATUS,
(CASE WHEN CAR.VSDSTOCKTYPE = ''1'' THEN CAR.QTTY ELSE 0 END) PTRADE,
(CASE WHEN CAR.VSDSTOCKTYPE <> ''1'' THEN CAR.QTTY ELSE 0 END) PBLOCKED, CF.CIFID, CF.MCUSTODYCD
FROM SBSECURITIES SB, CAMAST CA, CASCHD CAS, CFMAST CF,
(
    SELECT CAMASTID, CUSTODYCD, AFACCTNO, SEACCTNO, OPTSEACCTNO, CODEID, TRFACCTNO,
        '','' || LISTAGG(TO_CHAR(AUTOID), NULL,'') WITHIN GROUP(ORDER BY AUTOID) || '','' REFCODE,
        SUM(QTTY) QTTY,
        SUM(BALANCE) BALANCE,  
        SUM(QTTY * EXPRICE) AMT, 
        SUM(CANCELQTTY) CANCELQTTY,
        (CASE WHEN SUM(QTTY) = 0 THEN 0 ELSE ROUND(SUM(AMT)/SUM(QTTY), 2) END) EXPRICE,
        MAX(PARVALUE) PARVALUE, VSDSTOCKTYPE, MSGSTATUS, DELTD
    FROM CAREGISTER
    GROUP BY CAMASTID, CUSTODYCD, AFACCTNO, SEACCTNO, OPTSEACCTNO, CODEID, TRFACCTNO, VSDSTOCKTYPE, MSGSTATUS, DELTD
) CAR,
(SELECT * FROM ALLCODE WHERE CDTYPE = ''CA'' AND CDNAME = ''CASTATUS'') A1
WHERE NVL(CA.TOCODEID,CA.CODEID) = SB.CODEID
AND CA.CAMASTID = CAR.CAMASTID
AND CA.STATUS = A1.CDVAL(+)
AND CAR.DELTD = ''N''
AND CAR.MSGSTATUS IN (''P'',''N'',''R'')
AND CF.CUSTODYCD = CAR.CUSTODYCD
AND CA.CAMASTID = CAS.CAMASTID
AND CAS.AFACCTNO = CAR.AFACCTNO', 'CAMAST', NULL, NULL, '3357', NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;