SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('AP1001','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('AP1001', 'Cập nhật trạng thái chuyển tiền mua physical', 'Update Status Transfer Money to Buy Physical', 'SELECT A1.<@CDCONTENT> TYPE, T.TLTXCD, T.ID CRPHYSAGREEID, T.NO, CF.CUSTODYCD, T.CODEID, T.CITAD, T.BANKCODE, T.BANKACCTNO, T.CLVALUE, T.CLVALUE REMAMT
      , SB.SYMBOL, CUR.SHORTCD, CUR.CCYNAME, T.TAX, T.CLVALUE AMT, CF.FULLNAME
FROM
    (   SELECT ''1407'' TLTXCD, CR.CRPHYSAGREEID ID, CR.NO, CR.NAME, 0 TAX
            , CR.CUSTODYCD, CR.ACCTNO, CR.CODEID, CR.CITAD, CR.BANKCODE, CR.BANKACCTNO
            , CR.CLVALUE
            , CASE WHEN CRLOG.AAMT IS NULL THEN CR.CLVALUE ELSE (CR.CLVALUE - CRLOG.AAMT) END REMAMT
        FROM (SELECT *fROM CRPHYSAGREE WHERE DELTD <>''Y'') CR, CRBBANKLIST CRB,
             (SELECT CRL.CRPHYSAGREEID, SUM(CRL.AMT) AAMT FROM CRPHYSAGREE_LOG CRL WHERE CRL.TYPE = ''T'' AND CRL.DELTD <> ''Y'' GROUP BY CRL.CRPHYSAGREEID) CRLOG
        WHERE CR.CRPHYSAGREEID = CRLOG.CRPHYSAGREEID(+) AND
              CR.STATUS = ''A'' AND
              (CR.CLVALUE > CRLOG.AAMT or CRLOG.AAMT IS NULL) AND
              CR.CITAD = CRB.CITAD(+)
        UNION ALL
        SELECT ''1400'' TLTXCD, TO_CHAR(AP.AUTOID) ID, AP.NO, AP.NAME, CRS.TAX
            , CRS.BUYCUSTODYCD CUSTODYCD, AP.ACCTNO, AP.CODEID, '''' CITAD, AP.BANKCODE,  AP.BANKACCTNO
            , CRS.NETAMT CLVALUE
            , (CASE WHEN CRLOG.AAMT IS NULL THEN (CASE WHEN AP.taxableparty =''001'' AND AP.deductionplace =''001'' THEN CRS.NETAMT ELSE CRS.AMT END) ELSE ((CASE WHEN AP.taxableparty =''001'' AND AP.deductionplace =''001'' THEN CRS.NETAMT ELSE CRS.AMT END) - CRLOG.AAMT) END) REMAMT
        FROM APPENDIX AP, CRPHYSAGREE_SELL_LOG CRS,
        (SELECT CRL.APPENDIXID, SUM(CRL.AMT) AAMT FROM CRPHYSAGREE_LOG CRL WHERE CRL.TYPE = ''T'' AND CRL.DELTD <> ''Y'' GROUP BY CRL.APPENDIXID) CRLOG
        WHERE AP.AUTOID = CRS.APPENDIXID AND CRS.BUYMEMBER =''SHV'' AND
              AP.AUTOID = CRLOG.APPENDIXID(+) AND
              AP.STATUS = ''P'' AND
              (AP.CLVALUE > CRLOG.AAMT or CRLOG.AAMT IS NULL)
    ) T, SBSECURITIES SB, SBCURRENCY CUR, ALLCODE A1, CFMAST CF
WHERE  T.CODEID = SB.CODEID AND
       SB.CCYCD = CUR.CCYCD AND
       A1.CDTYPE = ''AP'' AND A1.CDNAME =''REFTYPE'' AND A1.CDVAL = T.TLTXCD AND
       T.ACCTNO = CF.CUSTID', 'AP1001', '', 'T.TLTXCD ASC, T.ID DESC', '1408', 0, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;