SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('VSDTXINFO','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('VSDTXINFO', 'Điện thông báo từ VSD', 'Manage the notification messages from VSD', 'SELECT L.AUTOID, L.SENDER, L.MSGTYPE, L.FUNCNAME, L.REFMSGID,
       L.REFERENCEID, UPPER(REPLACE(L.FINFILENAME,''.fin'','''')) FINFILENAME, TO_CHAR(L.TIMECREATED,''HH24:MI:SS'')TIMECREATED , L.TIMEPROCESS,
       L.STATUS, L.AUTOCONF, L.ERRDESC, L.RECLAS, L.REQTTY,
       L.REFCUSTODYCD, L.RECCUSTODYCD, L.VSDEFFDATE , C.CDCONTENT DESCRIPTION, L.TIMECREATED DATECREATED,
       NVL(A1.CDCONTENT,L.STATUS) MSGSTATUS,A1.CDVAL, SUBSTR(L.SYMBOL, 6) ISINCODE, SB.SYMBOL, L.VSDCAID
FROM VSDTRFLOG L,
(SELECT TRFCODE, MAX(DESCRIPTION) CDCONTENT, MAX(EN_DESCRIPTION) EN_CDCONTENT FROM VSDTRFCODE GROUP BY TRFCODE) C,
(SELECT * FROM ALLCODE WHERE CDNAME LIKE  ''VSDTRFLOGSTS'' AND CDTYPE = ''ST'') A1,
(SELECT * FROM SBSECURITIES WHERE REFCODEID IS NULL) SB
WHERE L.FUNCNAME = C.TRFCODE(+)
AND L.STATUS = A1.CDVAL(+)
AND L.FUNCNAME NOT LIKE ''%.ACK''
AND L.FUNCNAME NOT LIKE ''%.NAK''
AND SUBSTR(L.SYMBOL, 6) = SB.ISINCODE(+)', 'VSDTXINFO', 'frmVSDTXREQ', ' DATECREATED DESC, TIMECREATED DESC', NULL, 0, 5000, 'Y', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;