SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CF_IDCODE','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CF_IDCODE', 'TTKH', 'Customer information', 'select *  FROM (
        SELECT CF.CUSTID FILTERCD, CF.CUSTODYCD,
               NVL(AU.CUSTID, AU.LICENSENO) CUSTID, AU.FULLNAME , AU.ADDRESS, AU.licenseno IDCODE, AU.lnplace IDPLACE, AU.lniddate IDDATE
        FROM (SELECT *FROM CFAUTH WHERE DELTD <> ''Y'') AU, (select *From CFMAST where status = ''A'') CF, (SELECT *FROM AFMAST WHERE STATUS = ''A'') AF, SYSVAR SYS
        WHERE CF.CUSTID = AU.CFCUSTID
              AND AF.CUSTID = CF.CUSTID
              AND SYS.VARNAME = ''CURRDATE''
              AND TO_DATE(VARVALUE,''DD/MM/RRRR'') BETWEEN AU.valdate AND AU.expdate
        UNION ALL
        SELECT CUSTID FILTERCD, CUSTODYCD, CUSTID ,  FULLNAME  , ADDRESS, IDCODE, IDPLACE, IDDATE
        FROM CFMAST where status = ''A''  )
WHERE 0=0', 'CFMAST', 'frmCFMAST', 'FULLNAME', NULL, NULL, 1000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;