SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('DFBASKET','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('DFBASKET', 'Chứng khoán cầm cố/forward', 'Securities for mortgage/forward', 'SELECT TYP.AUTOID, TYP.SYMBOL,
A0.CDCONTENT CALLTYPE, TYP.DEALTYPE,A1.CDCONTENT, SEIF.BASICPRICE REFPRICE, TYP.TRIGGERPRICE , TYP.DFRATE, TYP.MRATE,
TYP.LRATE, TYP.DFPRICE, TYP.DEALTYPE,A1.CDCONTENT FROM DFBASKET TYP, ALLCODE A0, SECURITIES_INFO SEIF, ALLCODE A1
WHERE A0.CDTYPE=''DF'' AND A0.CDNAME=''CALLTYPE'' AND TYP.CALLTYPE=A0.CDVAL
AND A1.CDNAME=''DEALTYPE'' AND TYP.DEALTYPE=A1.CDVAL
AND TYP.SYMBOL = SEIF.SYMBOL
AND TYP.BASKETID=''<$KEYVAL>'' ORDER BY SYMBOL', 'SA.DFBASKET', 'frmDFBASKET', NULL, NULL, 0, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;