SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('BROKERS','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('BROKERS', 'Quản lý thành viên', 'Participant management', 'SELECT
        USERNAME, SHORTNAME,FULLNAME,ROLES,BICCODE,BANKACCTNO,
        BANKNAME,BANKCITADCODE,BANKBICCODE,
        TAXCODE, A0.<@CDCONTENT> STATUS, A2.<@CDCONTENT> ROLESMEMBER,
        fan.<@CDCONTENT> ROLESNAME, ENGLISHNAME, TAXCODEDATE,
        taxccy, cifno,A3.<@CDCONTENT> NATIONALITY,
        address, ceoname, email, telephone, faxno,
        incdate, incorporation, language, opendate,
        (CASE WHEN STATUS IN (''P'') THEN ''Y'' ELSE ''N''
        END) APRALLOW
FROM FAMEMBERS MST, ALLCODE A0, ALLCODE A2,ALLCODE A3,
    (select autoid CDVAL,fullname CDCONTENT, englishname EN_CDCONTENT from famembers) fan
WHERE   MST.STATUS = A0.CDVAL AND A0.CDNAME =''APPRV_STS''
    AND A0.CDTYPE=''SY''
    AND MST.ROLES = A2.CDVAL AND A2.CDNAME =''FAROLES''
    AND A2.CDTYPE=''FA''
    and fan.cdval = mst.autoid
    AND A3.CDNAME = ''COUNTRY'' AND A3.CDTYPE = ''CF'' AND A3.CDVAL = MST.nationality AND A3.CDVAL NOT IN(''0'')
    AND MST.ROLES=''BRK''', 'BROKERS', '', '', '', NULL, 1000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;