SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('BONDPAYMENTSCHEDULE','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('BONDPAYMENTSCHEDULE', 'Lịch trả lãi', 'Interest payment schedule', 'SELECT BO.*, SB.SYMBOL, SB.PARVALUE, SB.INTCOUPON, SB.INTERESTDATE, CA.CAMASTID, CA.CATYPE, CA.CASTATUS
FROM BOND_PAYMENT_SCHEDULE BO, SBSECURITIES SB,
(
    SELECT CA.CAMASTID, CA.CODEID, CAA1.<@CDCONTENT> CATYPE, CAA2.<@CDCONTENT> CASTATUS
    FROM CAMAST CA, 
    (SELECT * FROM ALLCODE WHERE CDNAME = ''CATYPE'' AND CDNAME = ''CA'') CAA1,
    (SELECT * FROM ALLCODE WHERE CDNAME = ''CASTATUS'' AND CDNAME = ''CA'') CAA2
    WHERE CA.CATYPE IN (''016'',''015'',''099'') 
    AND CA.STATUS NOT IN (''C'')
    AND CA.CATYPE = CAA1.CDVAL
) CA
WHERE BO.CODEID = SB.CODEID
AND BO.CODEID = CA.CODEID(+)
AND BO.CODEID =''<$KEYVAL>''', 'SA.BONDPAYMENTSCHEDULE', 'frmBONDPAYMENTSCHEDULE', '', '', NULL, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;