SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('AF_0042','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('AF_0042', 'Quản lý tiểu khoản', 'Contract management', 'SELECT BANKNAME,     
BANKACCTNO ,  
AUTOTRF  ,    
ALTERNATEACCT,
format_subac(ACCTNO)  ACCTNO      
FROM AFMAST 
WHERE 0=0', 'AF_0042', '', '', '', NULL, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;