SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CRBBANKREQUEST_2228','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CRBBANKREQUEST_2228', 'Tra cứu điện nhận từ ngân hàng', 'Bank request management', 'SELECT R.AUTOID REQID,R.AUTOID,R.TRANSACTIONNUMBER,R.TXDATE TXDATE,R.REFTXNUM REQTXNUM,T.<@CDCONTENT> TRFCODE,to_char(R.CREATEDT,''dd/MM/yyyy hh24:mi:ss'') CREATEDATE,
        D.CUSTODYCD, R.DESBANKACCOUNT BANKACCT,D.CCYCD CURRENCY,R.AMOUNT AMOUNT,R.ISCONFIRMED STATUS,A1.<@CDCONTENT> STATUSTEXT,R.ERRORDESC,
        R.CFSTATUS,A2.<@CDCONTENT> CFSTATUSTEXT,R.CBOBJ,R.BANKOBJ,R.TRANSACTIONDESCRIPTION
FROM CRBBANKREQUEST R, DDMAST D,(SELECT *FROM ALLCODE WHERE CDNAME = ''RMSTATUS'' AND CDTYPE = ''RM'')A1,(SELECT * FROM ALLCODE WHERE  CDNAME = ''RMSTATUS'' AND CDTYPE = ''CI'')A2,
        (SELECT TLTXCD CDVAL ,TXDESC CDCONTENT, EN_TXDESC EN_CDCONTENT FROM TLTX) T
WHERE   R.CBOBJ = T.CDVAL(+)
    AND R.DESBANKACCOUNT = D.REFCASAACCT(+)
    --AND R.MSGTYPE=''RQ''
    AND R.ISCONFIRMED = A1.CDVAL(+)
    AND R.CFSTATUS =A2.CDVAL(+)', 'CRBBANKREQUEST_2228', NULL, 'AUTOID DESC', NULL, NULL, 5000, 'N', 1, 'NNYNYYNNNNNY', 'Y', 'T', NULL, 'N', NULL);COMMIT;