SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CIMAST_ALL2','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CIMAST_ALL2', 'Quản lý tiểu khoản tiền đầu tư', 'CI account management', 'SELECT CF.CUSTODYCD,CF2.CUSTODYCD CUSTODYCDCFO, CI.CUSTID,CI.ACTYPE, CI.ACCTNO ACCTNO,
SB.SHORTCD, CI.AFACCTNO AFACCTNO, CF.FULLNAME OWNERNAME,
CF.FULLNAME, CF.ADDRESS, CF.IDCODE LICENSE, CF.IDDATE, CF.IDPLACE,AF.BANKACCTNO,AF.BANKNAME,
CI.OPNDATE, CI.CLSDATE,CI.LASTDATE, CI.DORMDATE,A0.CDCONTENT STATUS, CI.BALANCE,CI.CRAMT,CI.DRAMT,CI.MBLOCK ,
CI.CRINTACR,CI.CRINTDT,CI.ODINTACR,CI.ODINTDT,CI.AVRBAL,CI.MDEBIT,CI.MCREDIT,CI.AAMT,CI.RAMT,BAMT,
CI.EMKAMT,CI.MMARGINBAL, CI.MARGINBAL,CI.ODLIMIT ,CI.ICCFCD, A1.CDCONTENT ICCFTIED, AF.CAREBY CAREBY,
AFT.LNTYPE,
getbaldefovd(CI.AFACCTNO) BALDEFOVD,
GET_DFDEBTAMT_RELEASE(CI.AFACCTNO,''U'') AVLRELEASE, CI.CIDEPOFEEACR, CI.DEPOFEEAMT, CI.DEPOLASTDT, CI.HOLDBALANCE, CI.COREBANK,
(CASE WHEN CI.COREBANK=''Y'' THEN 1 ELSE 0 END) ISCOREBANK
FROM CIMAST CI, ALLCODE A0 ,ALLCODE A1,CFMAST CF,SBCURRENCY SB, AFMAST AF, AFTYPE AFT, cfotheracc CFO, CFMAST CF2
WHERE
CF.CUSTID = CI.CUSTID AND CI.CCYCD =SB.CCYCD AND
A0.CDTYPE = ''CI'' AND A0.CDNAME = ''STATUS'' AND A0.CDVAL=CI.STATUS
AND A1.CDTYPE = ''SY'' AND A1.CDNAME = ''YESNO'' AND A1.CDVAL=CI.ICCFTIED
AND CI.AFACCTNO = AF.ACCTNO AND AF.ACTYPE = AFT.ACTYPE
AND CI.AFACCTNO = CFO.CIACCOUNT(+)
AND CFO.CFCUSTID = CF2.CUSTID(+)', 'CIMAST_ALL2', 'frmCIMAST', '', '', NULL, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;