SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CF0063','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CF0063', 'Tra cứu Tiểu khoản đổi loại hình sang Core Bank', 'Account changing to corebank type', 'SELECT AF.ACTYPE , CF.CUSTID , CF.CUSTODYCD, CF.FULLNAME, CF.IDCODE, CF.ADDRESS , AF.ACCTNO,CI.BALANCE , CI.ODINTACR , CI.CRINTACR , CI.ODAMT
FROM  AFMAST AF , CFMAST CF ,CIMAST CI
WHERE CF.CUSTID = AF.CUSTID  AND  AF.ACCTNO = CI.ACCTNO
AND CI.STATUS not in (''T'',''N'')
AND CI.COREBANK =''N''
AND CI.BAMT<=1
AND CI.EMKAMT<=1
AND CI.RECEIVING<=1
AND CI.ODAMT<=1
AND CI.ODINTACR<=1
AND CI.MBLOCK<=1', 'AFMAST', NULL, NULL, '0063', NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;