SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CUSTODYCD_CF_1713','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CUSTODYCD_CF_1713', 'Tra cứu nhanh thông tin khách hàng', 'Customer information', 'SELECT * FROM
(
    SELECT FORMAT_CUSTID(CF.CUSTID) CUSTID, CF.CUSTODYCD, CF.CIFID, AF.ACCTNO, CF.FULLNAME, CF.SHORTNAME, CF.IDCODE, CF.IDPLACE, CF.IDDATE, CF.DATEOFBIRTH
    FROM CFMAST CF, TLGROUPS GRP, AFMAST AF
    WHERE AF.CUSTID=CF.CUSTID
    AND AF.CAREBY = GRP.GRPID
    AND TRIM(NVL(CF.SENDSWIFT,''N'')) = ''Y''
    AND NVL(CF.SWIFTCODE,''X'') <> ''X''
    AND CF.STATUS <> ''C''
    AND (
        SUBSTR(CF.CUSTID,1,4) = DECODE(''<$BRID>'', ''<$HO_BRID>'', SUBSTR(CF.CUSTID,1,4), ''<$BRID>'')
        OR
        AF.CAREBY IN (SELECT TLGRP.GRPID FROM TLGRPUSERS TLGRP WHERE TLID = ''<$TELLERID>'')
    )
    UNION ALL
    SELECT  ''ALL'' CUSTID, ''ALL'' CUSTODYCD, ''ALL'' CIFID, ''ALL'' ACCTNO, ''ALL'' FULLNAME, ''ALL'' SHORTNAME, ''ALL'' IDCODE, ''ALL'' IDPLACE, NULL IDDATE, NULL DATEOFBIRTH
    FROM DUAL
) WHERE 0 = 0', 'CUSTODYCD_CF_1713', NULL, NULL, NULL, 0, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;