SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SE2253','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('SE2253', 'Xác nhận giải tỏa cầm cố chứng khoán (2253)', 'Confirming releasing blocked stock (2253)', 'SELECT SE.AUTOID, SE.BUSDATE, SE.TXDATE, SE.AFACCTNO, SE.ACCTNO, CF.FULLNAME CUSTNAME, CF.CUSTODYCD, SB.SYMBOL, SB.PARVALUE, (SE.QTTY - SE.RELEASED) QTTY, SB.CODEID,
    CF.ADDRESS, CF.IDCODE LICENSE, CF.MCUSTODYCD
FROM SEMORTAGE SE, AFMAST AF, CFMAST CF, SBSECURITIES SB
WHERE SE.AFACCTNO = AF.ACCTNO
AND AF.CUSTID= CF.CUSTID
AND SE.TLTXCD = ''2233''
AND SE.STATUS IN (''N'')
AND SE.DELTD = ''N''
AND SE.QTTY - SE.RELEASED > 0
AND SE.CODEID = SB.CODEID', 'SEMAST', NULL, NULL, '2253', 0, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;