SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('RECFLNK_RF','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('RECFLNK_RF', 'Đại lý/môi giới', 'Broker/Remiser management', 'SELECT RF.TLID,CF.FULLNAME,BRGRP.BRNAME,RF.BRID,RF.AUTOID,
    A0.CDCONTENT DESC_STATUS, RF.CUSTID, RF.AFACCTNO, RF.EFFDATE, RF.EXPDATE, nvl(rg.mapcode,null) REGRPID,
    NVL(TL.TLNAME,'''') TLNAME
--AnTB them RG.REFRECFLNKID REGRPID nhom hien tai cua moi neu co
FROM RECFLNK RF, CFMAST CF, ALLCODE A0,BRGRP, tlprofiles tl,
(select rgl.*,substr(SP_FORMAT_REGRP_MAPCODE(rgl.refrecflnkid),-6) mapcode from REGRPLNK rgl where status=''A'') RG
WHERE A0.CDTYPE=''RE'' AND A0.CDNAME=''STATUS'' AND A0.CDVAL=RF.STATUS AND RF.CUSTID=CF.CUSTID
    AND RF.CUSTID=CF.CUSTID
    AND (RF.STATUS = ''A'' or RF.STATUS is null)
    and RF.BRID= BRGRP.brid(+)
    and RF.CUSTID = RG.CUSTID(+)
    AND RF.TLID=TL.TLID(+)', 'RECFLNK', 'frmRECFLNK', 'FULLNAME', '', 0, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;