SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('ONLREQUESTLOG','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('ONLREQUESTLOG', 'Tra cứu giao dịch online', 'Look up online transactions', 'SELECT *
FROM (
    SELECT OL.AUTOID, OL.TXDATE, OL.TXNUM, OL.CUSTODYCD, OL.QTTY, OLU.USER_CREATED, OLU.USER_APPR, OL.DESCRIPTION, TX.<@CDCONTENT> TXDESC, A1.<@CDCONTENT> TXSTATUS, CF.FULLNAME, SB.SYMBOL,A1.CDVAL TXSTATUSVAL,
    A2.<@CDCONTENT> SI,TO_CHAR(OL.EFFDATE,''DD/MM/RRRR'') EFFDATE,TO_CHAR(OL.EXPDATE,''DD/MM/RRRR'') EXPDATE,OL.NOTE NOTESI 
    FROM ONLREQUESTLOG OL
    LEFT JOIN ONLREQUESTLOG_USER OLU ON OL.TXDATE = OLU.TXDATE AND OL.TXNUM = OLU.TXNUM
    LEFT JOIN CFMAST CF ON CF.CUSTODYCD = OL.CUSTODYCD
    LEFT JOIN SBSECURITIES SB ON SB.CODEID = OL.CODEID
    LEFT JOIN ALLCODE A1 ON A1.CDVAL = OL.STATUS AND A1.CDNAME = ''STATUS'' AND A1.CDTYPE = ''OL''
    LEFT JOIN ALLCODE A2 ON A2.CDVAL = NVL(OL.SI,''N'') AND A2.CDNAME = ''YESNO'' AND A2.CDTYPE = ''SY''
    LEFT JOIN (
        SELECT TLTXCD, TXDESC CDCONTENT, EN_TXDESC EN_CDCONTENT FROM TLTX
    ) TX ON TX.TLTXCD = OL.TLTXCD
) WHERE 0 = 0', 'ONLREQUESTLOG', 'frmONLREQUESTLOG', 'AUTOID DESC', NULL, NULL, 1000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;