SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('ST9940','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('ST9940', 'Xử lý điện bị từ chối bởi VSD', 'Manage rejecting messages from VSD', 'SELECT reqdtl.cval, REQ.REQID,REQ.OBJNAME,REQ.TRFCODE,REQ.OBJKEY,to_date(REQ.TXDATE,''DD/MM/RRRR'')TXDATE ,REQ.Afacctno,REQ.MSGACCT,REQ.NOTES,
A5.CDCONTENT MSGSTATUS,
REQ.VSD_ERR_MSG ,to_char(req.CREATEDATE,''hh24:mi:ss.'') CREATEDATE ,req.tlid,tl.tlname,''NACK'' SWPROCESS
FROm VSDTXREQ REQ, ALLCODE A5,tlprofiles tl,
(select reqid,max(cval) cval from vsdtxreqdtl where fldname=''CUSTODYCD'' group by reqid) reqdtl
WHERE A5.CDTYPE=''SA'' AND A5.CDNAME=''VSDTXREQSTS'' AND A5.CDVAL=REQ.MSGSTATUS
and req.tlid=tl.tlid(+) And  req.MSGSTATUS=''N''
and req.reqid=reqdtl.reqid(+)', 'CFMAST', 'frmMMSG', 'REQID DESC', '9940', 0, 5000, 'Y', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;