SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CSVFILENAME_CA','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CSVFILENAME_CA', 'Danh sách file CSV', 'Danh sách file CSV', 'SELECT B.AUTOID, B.REFREQID, M.RPTID REPORTID, B.FILENAME, B.TXDATE, M.DESCRIPTION RPTNAME, M.RPTID, M.DESCRIPTION, TO_CHAR(B.TIMECREATED,''HH24:MI:SS.'') CREATEDATE,
    B.VSDCAID, CA.CCATYPE CATYPE
FROM CSVCOMPAREREPORT A, VSDCONTENTLOG B, RPTMASTER M,
(
    SELECT CA.*, A1.CDCONTENT CCATYPE
    FROM CAMAST CA,
    (SELECT * FROM ALLCODE WHERE CDNAME = ''CATYPE'' AND CDTYPE = ''CA'') A1
    WHERE CA.STATUS NOT IN (''C'')
    AND CA.CATYPE = A1.CDVAL(+)
) CA
WHERE B.RPTID = M.RPTID
AND M.RPTID = A.DESCRIPTION
AND UPPER(B.FILENAME) LIKE ''%.CSV''
AND A.CMPID = ''CA''
AND B.STATUS = ''C''
AND B.VSDCAID = CA.VSDCAID(+)', 'CSVFILENAME_CA', 'frmCAMAST', 'AUTOID DESC', '', 0, 50, 'N', 30, '', 'Y', 'T', '', 'N', '');COMMIT;