SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('RE0383','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('RE0383', 'Tra cứu môi giới của nhóm (Giao dịch 0383 để chuyển nhóm)', 'View remiser belong to group (0383 to move to other group)', 'select * from (
SELECT AUTOID,GRNAME,LEADERID, LEADTLNAME, LEADERNAME,CUSTID,RETLNAME,REFULLNAME,MAX(FRDATE) FRDATE,MAX(TODATE) TODATE
FROM (
SELECT substr(SP_FORMAT_REGRP_MAPCODE(REF.AUTOID),-6) AUTOID, CFLEADER.CUSTID LEADERID, NVL(TL.TLNAME,'''') LEADTLNAME, CFLEADER.FULLNAME LEADERNAME, LNK.AUTOID LNKAUTOID,
REF.custid||REF.ACTYPE LEADREACCTNO, LNK.REACCTNO,LNK.CUSTID, NVL(TL2.TLNAME,'''') RETLNAME, REF.ACTYPE, RE.FULLNAME REFULLNAME, LNK.FRDATE, LNK.TODATE,
REF.FULLNAME GRNAME, REF.GRPLEVEL, A0.CDCONTENT DESC_REROLE, A1.CDCONTENT DESC_RETYPE
FROM REGRPLNK LNK, REGRP REF, CFMAST CFLEADER, CFMAST RE, RETYPE TYP, ALLCODE A0, ALLCODE A1, RECFLNK RF, TLPROFILES TL, RECFLNK RF2, TLPROFILES TL2
WHERE REF.AUTOID=LNK.REFRECFLNKID AND REF.CUSTID=CFLEADER.CUSTID AND  SUBSTR(LNK.reacctno,11,4)=TYP.ACTYPE
AND RE.CUSTID=LNK.CUSTID  AND LNK.STATUS=''A''
AND A0.CDTYPE=''RE'' AND A0.CDNAME=''REROLE'' AND A0.CDVAL=TYP.REROLE
AND A1.CDTYPE=''RE'' AND A1.CDNAME=''RETYPE'' AND A1.CDVAL=TYP.RETYPE
AND REF.CUSTID = RF.CUSTID (+)
AND RF.TLID = TL.TLID(+)
--AND RF.STATUS = ''A''
AND LNK.CUSTID = RF2.CUSTID
AND RF2.TLID = TL2.TLID(+)
AND RF2.STATUS = ''A''
 AND (<$BRID> =''0001'' or RF.BRID = <$BRID>)
)
GROUP BY AUTOID,GRNAME,LEADERID,LEADTLNAME,LEADERNAME,CUSTID,RETLNAME,REFULLNAME) a
where 0=0', 'REMAST', NULL, NULL, '0383', NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;