SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('UNHOLDSEMAST','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('UNHOLDSEMAST', 'Unhold chứng khoán trong ngày', 'Unhold securities', 'SELECT TXNUM,TXDESC,CODEID,CFCUSTODYCD,CFFULLNAME,SYMBOL,QTTY,TLNAME,TXTIME,SHORTNAME,BRNAME,BRPHONE,NOTE,STATUS,STATUSTEXT,SEACCOUNT,MEMBERID,BRNAMEID,BRPHONEID,ASSETTYPE
    FROM (
    SELECT  '''' TXNUM, SE.CODEID, CF.CUSTODYCD CFCUSTODYCD, CF.FULLNAME CFFULLNAME, '''' TXDESC, SE.ACCTNO SEACCOUNT, SB.SYMBOL, SE.HOLD QTTY, '''' TLNAME, '''' TXTIME, '''' SHORTNAME, ''''  BRNAME,
    ''''  BRPHONE, ''''  NOTE, ''''  STATUS, '''' STATUSTEXT, '''' MEMBERID, ''''  BRNAMEID, '''' BRPHONEID,
    A1.CDVAL ASSETTYPEVAL, A1.<@CDCONTENT> ASSETTYPE
    FROM SEMAST SE, CFMAST CF, SBSECURITIES SB,
    (SELECT * FROM ALLCODE WHERE CDTYPE = ''OD'' AND CDNAME = ''ASSETTYPE'') A1
    WHERE SE.HOLD > 0
    AND SE.CODEID = SB.CODEID
    AND SE.AFACCTNO = CF.CUSTID
    AND (CASE WHEN SB.TRADEPLACE = ''099'' THEN ''TPRL'' ELSE ''CKNY'' END) = A1.CDVAL(+)
 ) A
 WHERE 0=0', 'UNHOLDSEMAST', NULL, NULL, '2216', 0, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;