SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('OD8889','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('OD8889', 'Tra cứu giao dịch ngoài Shinhan', 'View Trade outside Shinhan', 'SELECT DT.*, DD.REFCASAACCT || ''-'' || DD.CCYCD || ''-'' || DD.ACCOUNTTYPE DDACCOUNT FROM(
    SELECT LOG.TXDATE, LOG.BUSDATE ,LOG.TXNUM,
           MAX(CASE WHEN LOGF.FLDCD = ''88'' THEN LOGF.CVALUE ELSE '''' END) CUSTODYCD,
           MAX(CASE WHEN LOGF.FLDCD = ''19'' THEN LOGF.CVALUE ELSE '''' END) DDACCTNO,
           MAX(CASE WHEN LOGF.FLDCD = ''11'' THEN LOGF.NVALUE ELSE 0 END) IITOTAL,
           MAX(CASE WHEN LOGF.FLDCD = ''12'' THEN LOGF.NVALUE ELSE 0 END) TAXTOTAL,
           MAX(CASE WHEN LOGF.FLDCD = ''13'' THEN LOGF.NVALUE ELSE 0 END) OTHERTOTAL,
           MAX(CASE WHEN LOGF.FLDCD = ''14'' THEN LOGF.NVALUE ELSE 0 END) INCOMETOTAL,
           MAX(CASE WHEN LOGF.FLDCD = ''15'' THEN LOGF.NVALUE ELSE 0 END) PLTOTAL,
           MAX(CASE WHEN LOGF.FLDCD = ''30'' THEN LOGF.CVALUE ELSE '''' END) NOTE
    FROM VW_TLLOG_ALL LOG, VW_TLLOGFLD_ALL LOGF
    WHERE LOG.TXDATE = LOGF.TXDATE
    AND LOG.TXNUM = LOGF.TXNUM
    AND LOG.TLTXCD = ''8889''
    AND LOG.DELTD <> ''Y''
    AND LOG.TXSTATUS = ''1''
    GROUP BY LOG.TXDATE, LOG.BUSDATE, LOG.TXNUM
) DT, DDMAST DD
WHERE DT.DDACCTNO = DD.ACCTNO', 'OD8889', '', 'DT.TXDATE DESC, DT.TXNUM DESC', '8890', 0, 5000, 'N', 1, 'NYNNYYYNNN', 'N', 'T', '', 'N', '');COMMIT;