SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('VSDTXINFO_VSTP','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('VSDTXINFO_VSTP', 'Điện thông báo từ VSD (VSTP)', 'Manage the notification messages from VSD (VSTP)', 'SELECT L.AUTOID, L.SENDER, L.MSGTYPE, L.FUNCNAME, L.REFMSGID,
       L.REFERENCEID, L.FINFILENAME FINFILENAME, TO_CHAR(L.TIMECREATED,''HH24:MI:SS'')TIMECREATED , L.TIMEPROCESS,
       L.STATUS, L.AUTOCONF, L.ERRDESC, L.RECLAS, L.REQTTY,
       L.REFCUSTODYCD, L.RECCUSTODYCD, L.VSDEFFDATE , C.CDCONTENT DESCRIPTION, L.TIMECREATED DATECREATED,
       NVL(A1.CDCONTENT,L.STATUS) MSGSTATUS, A1.CDVAL, SUBSTR(L.SYMBOL, 6) ISINCODE, NVL(L.SYMBOL, LD.FLDVAL) SYMBOL
FROM VSDTRFLOG_VSTP L,
(SELECT * FROM VSDTRFLOGDTL_VSTP WHERE FLDNAME IN (''VSDSYMBOL'',''SYMBOL'')) LD,
(SELECT TRFCODE, MAX(DESCRIPTION) CDCONTENT, MAX(EN_DESCRIPTION) EN_CDCONTENT FROM VSDTRFCODE_VSTP GROUP BY TRFCODE) C,
(SELECT * FROM ALLCODE WHERE CDNAME LIKE  ''VSDTRFLOGSTS'' AND CDTYPE = ''ST'') A1
WHERE L.AUTOID = LD.REFAUTOID
AND L.FUNCNAME = C.TRFCODE(+)
AND L.STATUS = A1.CDVAL(+)
AND L.FUNCNAME NOT LIKE ''%.ACK''
AND L.FUNCNAME NOT LIKE ''%.NAK''', 'VSDTXINFO_VSTP', 'frmVSDTXINFO_VSTP', ' DATECREATED DESC, TIMECREATED DESC', '', 0, 5000, 'Y', 1, '', 'Y', 'T', '', 'N', '');COMMIT;