SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('V_CI1180','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('V_CI1180', 'Giao dịch thu phí lưu ký đến hạn (1180)', 'Collect maturity depository fee (1180)', 'SELECT TYP.TYPENAME, CF.CUSTODYCD, CF.CUSTID, CF.FULLNAME, MST.AFACCTNO, MST.TODATE, MST.AVL,
to_Char(to_Date(MST.TODATE,''DD/MM/RRRR''),''MM/RRRR'') FTODATE
FROM AFMAST AF, CFMAST CF, AFTYPE TYP, tblci1180 tb,
(SELECT AFACCTNO, TODATE, SUM(NMLAMT)-SUM(PAIDAMT)-SUM(FLOATAMT) AVL FROM CIFEESCHD WHERE DELTD<>''Y'' GROUP BY AFACCTNO, TODATE) MST
WHERE MST.AFACCTNO=AF.ACCTNO AND AF.CUSTID=CF.CUSTID AND AF.ACTYPE=TYP.ACTYPE AND MST.AVL>0
and cf.custodycd = tb.custodycd and af.acctno = tb.afacctno
AND TB.DELTD = ''N''
 AND TB.AUTOID NOT IN (SELECT REFKEY FROM TLLOGEXT WHERE TLTXCD=''1135'' AND DELTD=''N'' AND STATUS IN (''0'',''1'', ''3'',''4'') )', 'CI.CIMAST', NULL, NULL, '1180', NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;