SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SE2205','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('SE2205', 'Tra cứu chứng khoán khách tự giữ', 'View stock balance keep by client', 'SELECT CF.CUSTODYCD, CF.FULLNAME, CF.IDCODE, SB.SYMBOL, NVL(SE_TMP.TRADE, 0) TRADE
FROM SBSECURITIES SB, CFMAST CF,
(
    SELECT AFACCTNO, ACCTNO, CODEID, TRADE FROM SENOCUSTATCOM WHERE (ACCTNO,TXDATE) IN (SELECT ACCTNO, MAX(TXDATE) FROM SENOCUSTATCOM GROUP BY ACCTNO)
) SE_TMP 
WHERE SE_TMP.AFACCTNO = CF.CUSTID
AND SE_TMP.CODEID = SB.CODEID
AND CF.STATUS NOT IN (''C'')
AND NVL(SE_TMP.TRADE, 0) > 0', 'SE2205', '', 'CUSTODYCD', '', NULL, 5000, 'N', 1, 'NNNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;