SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('REGRP','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('REGRP', 'Quản lý nhóm đại lý/môi giới', 'Group of remiser account', 'SELECT GRP.AUTOID, PRGRP.FULLNAME PRNAME, GRP.FULLNAME,
CF.CUSTID, GRP.GRPLEVEL, GRP.MINDREVAMT+GRP.MINIREVAMT MINREVENUE, A0.CDCONTENT DESC_STATUS, CF.FULLNAME REFULLNAME,
SP_FORMAT_REGRP_MAPCODE(GRP.AUTOID) MAPCODE, SP_FORMAT_REGRP_GRPLEVEL(GRP.AUTOID) MAPLEVEL, TYP.TYPENAME,(CASE WHEN GRP.STATUS IN (''P'') THEN ''Y'' ELSE ''N'' END) APRALLOW
FROM REGRP GRP, ALLCODE A0, CFMAST CF, REGRP PRGRP, RETYPE TYP, RECFLNK RF
WHERE GRP.ACTYPE=TYP.ACTYPE AND CF.CUSTID=GRP.CUSTID AND A0.CDTYPE=''RE'' AND A0.CDNAME=''STATUS'' AND A0.CDVAL=GRP.STATUS
 AND GRP.PRGRPID = PRGRP.AUTOID (+) AND GRP.CUSTID=RF.CUSTID(+) --AND ( <$BRID> =''0001'' or RF.BRID = <$BRID>)
AND GRP.STATUS<>''C'' 
and (RF.STATUS <> ''C'' OR RF.STATUS IS NULL)
AND (CF.CAREBY IN (SELECT TLGRP.GRPID FROM TLGRPUSERS TLGRP WHERE TLID = ''<$TELLERID>'')
     OR EXISTS (
        SELECT AF.CUSTID FROM AFMAST AF,TLGRPUSERS TLG
        WHERE AF.CAREBY=TLG.GRPID AND TLG.TLID = ''<$TELLERID>''
        AND AF.CUSTID=CF.CUSTID
       )
  )', 'REGRP', 'frmREGRP', 'MAPCODE', NULL, 0, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;