SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3301','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('CA3301', 'Màn hình theo dõi lịch thực hiện quyền theo số lưu ký', 'View the CA scheduler by custody code', 'SELECT VW.CAMASTID,VW.CUSTODYCD,VW.ISINCODE,VW.CODEID,VW.EXCODEID,VW.SYMBOL,VW.SYMBOLDIS,
    VW.REPORTDATE,VW.ACTIONDATE,VW.DESCRIPTION,VW.FULLNAME,VW.IDCODE,VW.ADDRESS,VW.CASTATUS,VW.CIFID,VW.PITRATE,VW.TRADEDATE,
    VW.BALANCE,VW.RQTTY,VW.PBALANCE,VW.QTTY,VW.AMT,VW.NMQTTY,VW.AQTTY,VW.AAMT,VW.INQTTY,VW.REGISQTTY,VW.SENDQTTY,VW.SENDPBALANCE,
    VW.SENDRQTTY,VW.SENDAMT,VW.TRADE,VW.TAXAMT,VW.AMTAFTER,VW.PARVALUE,VW.EXPARVALUE,VW.STATUS_RECEIVED,VW.MCIFID,VW.MCUSTODYCD,
    A0.CDCONTENT CATYPE,A1.CDCONTENT STATUS,A2.CDCONTENT PITRATEMETHOD, A3.CDCONTENT ISRECEIVE
--FROM V_CA3301 VW,
FROM v_ca3301_DEL_N VW,     --THANGPV SHBVNEX-2774
    (SELECT * FROM ALLCODE WHERE CDNAME = ''CATYPE'' AND CDTYPE = ''CA'') A0,
    (SELECT * FROM ALLCODE WHERE CDNAME = ''CASTATUS'' AND CDTYPE = ''CA'') A1,
    (SELECT * FROM ALLCODE WHERE CDNAME = ''PITRATEMETHOD'' AND CDTYPE = ''CA'') A2,
    (SELECT * FROM ALLCODE WHERE CDNAME = ''YESNO'' AND CDTYPE = ''SY'') A3
WHERE VW.CATYPE = A0.CDVAL(+)
AND VW.CASTATUS = A1.CDVAL(+)
AND VW.ISRECEIVE = A3.CDVAL(+)
AND VW.PITRATEMETHOD = A2.CDVAL(+)', 'CAMAST', '', '', '', NULL, 500, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;