SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('RM6613','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('RM6613', 'Tra cứu yên cầu thu phí LK chờ xử lý (6613)', 'View pending collect depository fee to process  (6613)', 'SELECT MST.REQID, MST.BANKCODE, MST.BANKACCT, MST.REFCODE, MST.OBJTYPE, MST.OBJNAME, MST.TRFCODE, MST.TXDATE, MST.OBJKEY,
FN_CRB_GETVOUCHERNO(RF.TRFCODE, RF.TXDATE, RF.VERSION) VOUCHERNO, A1.CDCONTENT DESC_DTLSTS,
MST.NOTES, MST.AFACCTNO, MST.TXAMT, CF.CUSTODYCD, CF.FULLNAME, TYP.TYPENAME
FROM CRBTXREQ MST, AFMAST AF, CFMAST CF, AFTYPE TYP, CRBTRFLOG RF, CRBTRFLOGDTL DTL, ALLCODE A1
WHERE MST.STATUS IN (''A'',''S'') AND MST.TRFCODE=''TRFSEFEE''
AND MST.REQID=DTL.REFREQID AND DTL.VERSION=RF.AUTOID AND DTL.DONESTS=''P''
AND A1.CDTYPE=''RM'' AND A1.CDNAME=''TRFLOGDTLSTS'' AND A1.CDVAL=DTL.STATUS
AND MST.AFACCTNO=AF.ACCTNO AND AF.CUSTID=CF.CUSTID AND AF.ACTYPE=TYP.ACTYPE', 'BANKINFO', NULL, NULL, '6613', NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;