SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('RE0320','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('RE0320', 'Tra cứu tính hoa hồng (Giao dịch 0320 để chốt hoa hồng)', 'View calculating commission for remiser (0320)', 'SELECT MST.ACCTNO, MST.CUSTID RECUSTID, TYP.TYPENAME, CF.FULLNAME, TYP.RATEFEE, TYP.RATECOMM,
CF.FULLNAME || '' ['' || A0.CDCONTENT || ''] '' REFVALUE, MST.DIRECTACR, MST.INDIRECTACR,
MST.DIRECTACR+MST.INDIRECTACR REVENUE, TYP.RATEFEE/100*(MST.DIRECTACR+MST.INDIRECTACR) FEEAMT,
FN_RE_GETCOMMISION(MST.ACCTNO)-TYP.RATEFEE/100*(MST.DIRECTACR+MST.INDIRECTACR) NMLAMT,
MST.BALANCE, A0.CDCONTENT DESC_RETYPE, A2.CDCONTENT DESC_REROLE, A1.CDCONTENT DESC_STATUS
FROM RECFLNK RF, REMAST MST, CFMAST CF, RETYPE TYP, ALLCODE A0, ALLCODE A1, ALLCODE A2
WHERE MST.ACTYPE=TYP.ACTYPE AND MST.CUSTID=CF.CUSTID
AND A0.CDTYPE=''RE'' AND A0.CDNAME=''RETYPE'' AND TYP.RETYPE=A0.CDVAL
AND A2.CDTYPE=''RE'' AND A2.CDNAME=''REROLE'' AND TYP.REROLE=A2.CDVAL
AND A1.CDTYPE=''RE'' AND A1.CDNAME=''STATUS'' AND MST.STATUS=A1.CDVAL
AND RF.CUSTID=MST.CUSTID AND FN_RE_GETCOMMISION(MST.ACCTNO)>0', 'RE.REMAST', 'frmREMAST', NULL, '0320', 0, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', NULL, 'N', NULL);COMMIT;