SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('RE0381','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('RE0381', 'Tra cứu khách hàng của môi giới (Giao dịch 0381 để chuyển môi giới)', 'View customer belong to remiser (0381 to move to other remiser)', 'SELECT RF.CUSTID RECUSTID,CFAFREF.FULLNAME DESC_TYPE,A2.CDCONTENT AFSTATUS,RCF.ODRNUM,(LNK.REACCTNO) REACCT,TYP.typename,CFREREF.FULLNAME FULLNAME,RCF.EFFDATE, RCF.EXPDATE,
LNK.AUTOID, LNK.REACCTNO, LNK.FUREACCTNO, LNK.AFACCTNO, LNK.FRDATE, LNK.TODATE, MST.ACTYPE, LNK.AFACCTNO CUSTID, TYP.REROLE, TYP.RETYPE,
nvl(tl.tlname,'''') retlname,CFREREF.FULLNAME REFULLNAME, CFAFREF.FULLNAME AFFULLNAME, CFAFREF.CUSTODYCD, A0.CDCONTENT DESC_REROLE, A1.CDCONTENT DESC_RETYPE,
CFREREF.FULLNAME||''/''||TYP.typename RADESC, CFREREF.FULLNAME||''/''||FTYP.TYPENAME FRADESC ,LNK.futreacctno, LNK.furdays, LNK.todate FUTODATE
FROM ALLCODE A2,REMAST MST, RETYPE TYP, REAFLNK LNK, CFMAST CFREREF, CFMAST CFAFREF, ALLCODE A0, ALLCODE A1, RECFLNK RF, 
     RETYPE FTYP,RECFDEF RCF, tlprofiles tl
WHERE TYP.ACTYPE=MST.ACTYPE AND MST.ACCTNO=LNK.REACCTNO AND CFREREF.CUSTID=MST.CUSTID
AND LNK.AFACCTNO=CFAFREF.CUSTID AND LNK.STATUS=''A''
AND A0.CDTYPE=''RE'' AND A0.CDNAME=''REROLE'' AND A0.CDVAL=TYP.REROLE
AND A1.CDTYPE=''RE'' AND A1.CDNAME=''RETYPE'' AND A1.CDVAL=TYP.RETYPE
AND MST.CUSTID = RF.CUSTID --AND (<$BRID> =''0001'' or RF.BRID = <$BRID>)
AND SUBSTR(LNK.FUREACCTNO,11,4) = FTYP.actype(+)
AND RCF.REACTYPE=TYP.ACTYPE
AND RCF.REFRECFLNKID = RF.AUTOID
and rf.tlid = tl.tlid(+)
and rf.status=''A''
--and CFREREF.status=''A''
--AND CFAFREF.STATUS=''A''
AND A2.CDTYPE = ''RE'' AND A2.CDNAME = ''AFSTATUS'' AND A2.CDVAL = TYP.AFSTATUS
AND (CFREREF.CAREBY IN (SELECT TLGRP.GRPID FROM TLGRPUSERS TLGRP WHERE TLID = ''<$TELLERID>'')
     OR EXISTS (
        SELECT CF.CUSTID FROM CFMAST CF,TLGRPUSERS TLG
        WHERE CF.CAREBY=TLG.GRPID AND TLG.TLID = ''<$TELLERID>''
        AND CF.CUSTID=CFREREF.CUSTID
       )
  )', 'RE.REMAST', '', '', '0381', NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;