SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SE2230','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('SE2230', 'Tra cứu các tài khoản chờ hủy hồ sơ luu ký (2230)', 'View pending to revert depository (2230)', 'SELECT FN_GET_LOCATION(CFMAST.BRID) LOCATION, SEDEPOSIT.TXDATE TXDATE,A4.CDCONTENT TRADEPLACE ,SEMAST.ACTYPE, SUBSTR(SEMAST.ACCTNO,1,4) || ''.'' || SUBSTR(SEMAST.ACCTNO,5,6) || ''.'' || SUBSTR(SEMAST.ACCTNO,11,6) ACCTNO, SYM.SYMBOL, SYM.PARVALUE, SEMAST.CODEID, SUBSTR(AFACCTNO,1,4) || ''.'' || SUBSTR(AFACCTNO,5,6) AFACCTNO,SUBSTR(CUSTODYCD,1,4) || ''.'' || SUBSTR(CUSTODYCD,5,6) CUSTODYCD, SEMAST.OPNDATE, SEMAST.CLSDATE, SEMAST.LASTDATE,
A1.CDCONTENT STATUS, SEMAST.PSTATUS, A2.CDCONTENT IRTIED, A3.CDCONTENT ICCFTIED, IRCD, COSTPRICE,SEDEPOSIT.DEPOSITQTTY DEPOSIT,SEDEPOSIT.depotrade,SEDEPOSIT.depoblock,SEDEPOSIT.typedepoblock ,SEDEPOSIT.DEPOSITPRICE DEPOSITPRICE,SEDEPOSIT.AUTOID AUTOID,SEDEPOSIT.DESCRIPTION DESCRIPTION, SEDEPOSIT.TXDATE PDATE,SEMAST.CUSTID CUSTID, COSTDT,CFMAST.FULLNAME CUSTNAME,CFMAST.ADDRESS  ADDRESS, cfmast.idcode LICENSE,
BR.brid brname, null tlfullname, ISSU.fullname ISSFULLNAME
FROM SEMAST,CFMAST,SBSECURITIES SYM,
(SELECT * FROM SEDEPOSIT WHERE STATUS=''D'' AND DELTD <> ''Y'') SEDEPOSIT, ALLCODE A1, ALLCODE A2, ALLCODE A3,ALLCODE A4,
brgrp BR, ISSUERS ISSU
WHERE SEMAST.DEPOSIT>0 AND A1.CDTYPE = ''SE'' AND A1.CDNAME = ''STATUS'' AND A1.CDVAL = SEMAST.STATUS
AND BR.brid = ''<$BRID>''
AND SYM.ISSUERID = ISSU.ISSUERID(+)
AND A2.CDTYPE = ''SY'' AND A2.CDNAME = ''YESNO'' AND A2.CDVAL = IRTIED
AND SYM.CODEID = SEMAST.CODEID
AND A3.CDTYPE = ''SY'' AND A3.CDNAME = ''YESNO'' AND A3.CDVAL = SEMAST.ICCFTIED
AND A4.CDTYPE = ''SE'' AND A4.CDNAME = ''TRADEPLACE''  AND A4.CDVAL = SYM.TRADEPLACE
AND CFMAST.CUSTID = SEMAST.CUSTID
AND SEDEPOSIT.ACCTNO = SEMAST.ACCTNO ', 'SEMAST', '', '', '2230', NULL, 5000, 'N', 1, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '');COMMIT;