SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('RECFLNK_ALL','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('RECFLNK_ALL', 'Danh sách tổng hợp MG', 'Position review', 'SELECT A.AUTOID,A.CUSTID REACCTNO,
       tl.tlname TLNAME, CF.FULLNAME,A.COMPLETEDCOME CURRSALARY,(nvl(A.ADDSALARY,0)+A.COMPLETEDCOME)ADJSALARY,
       A.POSITION CURRPOSITION, A1.CDCONTENT CURRPOSTEXT
  FROM RECFLNK A, ALLCODE A1, CFMAST CF, tlprofiles tl
  WHERE A1.CDNAME=''POSITION'' AND A1.CDTYPE =''RE'' AND A1.CDVAL = A.POSITION
AND (A.STATUS = ''A'' OR A.STATUS IS NULL)
AND a.CUSTID = CF.CUSTID and a.tlid = tl.tlid', 'RECFLNK', 'frmRECFLNK', 'FULLNAME', '', 0, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;