SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('RERFEE','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('RERFEE', 'Phí giảm trừ', 'Fee deduct', 'SELECT RER.RERFID,RER.RERFTYPE,A1.CDCONTENT FEETYPE,RER.CALTYPE,
A2.CDCONTENT FEECALTYPE,RER.RERFRATE,RER. AFFECTDATE, A3.cdcontent SYMTYPE, A4.cdcontent TRADEPLACE
 FROM RERFEE RER,ALLCODE A1,ALLCODE A2, allcode A3, ALLCODE A4
 WHERE
 RER.RERFTYPE=A1.CDVAL AND A1.CDTYPE=''RE'' AND A1.CDNAME=''RERFTYPE'' AND
 RER.CALTYPE=A2.CDVAL AND A2.CDTYPE=''RE'' AND A2.CDNAME=''CALTYPE'' AND
 RER.symtype = A3.CDVAL AND A3.CDTYPE=''RE'' AND A3.CDNAME=''SYMTYPE'' AND
 RER.tradeplace = A4.CDVAL AND A4.CDTYPE=''RE'' AND A4.CDNAME=''TRADEPLACE'' AND
 RER.RERFOBJTYPE=''RE.RETYPE'' AND RER.REFOBJID=''<$KEYVAL>''', 'RE.RERFEE', 'frmRERFEE', '', '', 0, 1000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;