SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('V_USERLIMITRE','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('V_USERLIMITRE', 'Tra cuu cap han muc TLID/User', 'View allocate tlid/user limmit', 'SELECT TLID TLIDUSER,TL.idcode idcode, TL.TLNAME USERNAME ,TO_CHAR(TL.TLFULLNAME)  FULLNAME,NVL(ALLOCATELIMMIT,0) ALLOCATELIMMIT,NVL(USEDLIMMIT,0) USEDLIMMIT,
    NVL(T0,0) T0,NVL(T0MAX,0) T0MAX,(NVL(ALLOCATELIMMIT,0)-NVL(USEDLIMMIT,0)) REMAINISSUE,
    BRGRP.brname BRID,ACCTLIMIT, ''Flex'' USERTYPE,NVL(T0.T0USED,0) T0USED, NVL(T0,0) - NVL(T0.T0USED,0) T0REMAIN,
    NVL(TC.TCUSED,0) TCUSED,NVL(dplimit,0) - NVL(TC.TCUSED,0) TCREMAIN,nvl(DPLIMIT,0) DPLIMIT,
     nvl(DPLIMITMAX,0) DPLIMITMAX
    FROM BRGRP,userlimit u ,TLPROFILES TL,(Select sum(A.ACCLIMIT) T0USED ,A.TLIDUSER from useraflimit A where A.TYPERECEIVE =''T0'' Group by A.TLIDUSER) T0,
                                      (Select sum(B.acclimit) TCUSED ,B.TLIDUSER from useraflimit B where B.TYPERECEIVE =''DP'' Group by B.TLIDUSER) TC
    WHERE u.TLIDUSER(+) = TLID and T0.TLIDUSER(+) =TLID and TC.TLIDUSER(+) =TLID AND BRGRP.BRID=TL.BRID
    AND TLID NOT IN (SELECT NVL(TLID,0) TLID FROM RECFLNK WHERE STATUS=''A'' AND getcurrdate BETWEEN EFFDATE AND EXPDATE)', 'USERLIMIT', 'frmSATLID', 'TLIDUSER', NULL, NULL, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;