SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('AFEXTRALIMITSYMBOL','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('AFEXTRALIMITSYMBOL', 'Danh sách chứng khoán áp dụng', 'Stock list apply', 'SELECT AFS.*,SS.FULLNAME ,A0.cdcontent TRADEPLACE_TEXT,
(SELECT NVL(SUM(NVL(LN.ODAMT,0)),0) FROM LNPROBRKLOG LN
   WHERE LN.AFACCTNO=AF.ACCTNO  AND LN.SYMBOL 
=AFS.SYMBOL) DEPT,afs.effdate

FROM AFEXTRALIMITSYMBOL AFS,AFEXTRALIMIT AF , 
SBSECURITIES SB, issuers SS,
(select * from allcode where cdname =''TRADEPLACE'' and 
cdtype =''SE'') A0
WHERE   AF.AUTOID = AFS.REFID
AND A0.CDVAL = SB.TRADEPLACE
AND SB.SYMBOL = AFS.SYMBOL
AND SB.issuerid = SS.issuerid
AND AFS.REFID=''<$KEYVAL>''', 'MR.AFEXTRALIMITSYMBOL', 'frmAFEXTRALIMITSYMBOL', '', '', 0, 5000, 'N', 1, '', 'Y', 'T', '', 'N', '');COMMIT;