SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('DDMAST_1290','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT) Values   ('DDMAST_1290', 'Thông tin tài khoản thanh toán khách hàng', 'Customer payment account information', 'SELECT CF.CUSTODYCD,CF.FULLNAME,CF.CIFID,
    DD.AFACCTNO,DD.ACCTNO,DD.OPNDATE,DD.CCYCD,DD.REFCASAACCT,DD.BALANCE,DD.HOLDBALANCE, DD.RECEIVING,DD.NETTING, DD.PENDINGHOLD,DD.PENDINGUNHOLD,DD.ACCOUNTTYPE,
    (CASE WHEN DD.BRANCHDATE IS NOT NULL THEN TO_CHAR(DD.BRANCHDATE,''DD/MM/RRRR'') ELSE '''' END) BRANCHDATE,
    (CASE WHEN DD.CLSDATE IS NOT NULL THEN TO_CHAR(DD.CLSDATE,''DD/MM/RRRR'') ELSE '''' END) CLOSEDATE, 
    ALLCODE.<@CDCONTENT> STATUS,
    A2.<@CDCONTENT> ISDEFAULT,
    A3.<@CDCONTENT> AUTOTRANSFER,
    DD.REFCASAACCT ||'' - ''|| DD.CCYCD || '' - '' || A4.<@CDCONTENT> DISPLAY
FROM DDMAST DD, CFMAST CF,
(SELECT *FROM ALLCODE WHERE CDNAME = ''STATUS'' AND CDTYPE = ''CI'') ALLCODE,
(SELECT *FROM ALLCODE WHERE CDNAME = ''YESNO'' AND CDTYPE = ''SY'') A2,
(SELECT *FROM ALLCODE WHERE CDNAME = ''YESNO'' AND CDTYPE = ''SY'') A3,
(SELECT *FROM ALLCODE WHERE CDNAME = ''ACCOUNTTYPE'' AND CDTYPE = ''DD'') A4
WHERE CF.CUSTODYCD  = DD.CUSTODYCD
AND DD.STATUS = ALLCODE.CDVAL
AND DD.ISDEFAULT = A2.CDVAL
AND DD.AUTOTRANSFER = A3.CDVAL
AND DD.ACCOUNTTYPE = A4.CDVAL
AND CF.CUSTODYCD = ''<@KEYVALUE>''', 'DDMAST', NULL, NULL, NULL, NULL, 5000, 'N', 1, NULL, 'Y', 'T', NULL, 'N', NULL);COMMIT;