SET DEFINE OFF;
CREATE OR REPLACE TRIGGER TRG_CFMAST_BEFORE 
 BEFORE
  INSERT OR UPDATE
 ON cfmast
REFERENCING NEW AS NEWVAL OLD AS OLDVAL
 FOR EACH ROW
BEGIN
    IF :OLDVAL.LAST_MKID IS NULL THEN
        :NEWVAL.LAST_MKID:=:NEWVAL.TLID;
    END IF;
    if nvl(:oldval.custodycd,'0000000000') = '0000000000' and nvl(:newval.custodycd,'0000000000') <> '0000000000' then
        :newval.opndate:= GETCURRDATE;
    end if;
    IF NVL(:OLDVAL.PIN, 'XXXXXXXXXXX') <> NVL(:NEWVAL.PIN,'YYYYYYYYY') THEN
        :NEWVAL.PIN := GENENCRYPTPASSWORD(:NEWVAL.PIN);
    END IF;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
