SET DEFINE OFF;
CREATE OR REPLACE TRIGGER TRG_AFMAST_AFTER 
 AFTER
  INSERT OR UPDATE
 ON afmast
REFERENCING NEW AS NEWVAL OLD AS OLDVAL
 FOR EACH ROW
DISABLE
DECLARE
BEGIN
    IF FOPKS_API.FN_IS_HO_ACTIVE THEN
        --LOG TRIGGER FOR BUFFER IF MODIFY ADVANCEDLINE
        -- THENN, 04-FEB-2012
        IF :NEWVAL.ADVANCELINE <> :OLDVAL.ADVANCELINE
            OR :NEWVAL.AUTOADV <> :OLDVAL.AUTOADV
            OR :NEWVAL.MRCRLIMITMAX <> :OLDVAL.MRCRLIMITMAX
            OR :NEWVAL.DPCRLIMITMAX <> :OLDVAL.DPCRLIMITMAX
            OR :NEWVAL.MRCRLIMIT <> :OLDVAL.MRCRLIMIT THEN
            
            JBPKS_AUTO.PR_TRG_ACCOUNT_LOG(:NEWVAL.ACCTNO,'CI');
            
        END IF;
        --END LOG TRIGGER FOR BUFFER
    END IF;
END;
/
