SET DEFINE OFF;
CREATE OR REPLACE TRIGGER TRG_VSDTXREQ_BEFORE_INSERT 
 BEFORE
  INSERT
 ON vsdtxreq
REFERENCING NEW AS NEWVAL OLD AS OLDVAL
 FOR EACH ROW
DECLARE
    L_COUNT NUMBER;
BEGIN
    SELECT COUNT(1) INTO L_COUNT FROM SWIFT_OUT WHERE TXNUM = :NEWVAL.objkey AND TXDATE = :NEWVAL.TXDATE;
    IF L_COUNT > 0 THEN
        UPDATE SWIFT_OUT SET REQID = :NEWVAL.REQID WHERE TXNUM = :NEWVAL.objkey AND TXDATE = :NEWVAL.TXDATE;
    END IF;
END;
/
