SET DEFINE OFF;
CREATE OR REPLACE TRIGGER TRG_DDMAST_BEFORE 
 BEFORE
  INSERT OR UPDATE
 ON ddmast
REFERENCING NEW AS NEWVAL OLD AS OLDVAL
 FOR EACH ROW
BEGIN
    :NEWVAL.LASTCHANGE:= SYSTIMESTAMP;
END;
/
