SET DEFINE OFF;
CREATE OR REPLACE TRIGGER TRG_CFMAST_AFTER 
 AFTER
  INSERT OR UPDATE
 ON cfmast
REFERENCING NEW AS NEWVAL OLD AS OLDVAL
 FOR EACH ROW
DECLARE
BEGIN
    --15/12/2015, TruongLD Modified --> khong can kiem tra TT he khi khi cap nhat
    --IF FOPKS_API.FN_IS_HO_ACTIVE THEN
        --SONLT 20150128: Tu dong insert cac mau SMS email khong can dang ky.
        /*PR_ERROR('TRG_CFMAST_AFTER','CUSTID: ' || NVL(:NEWVAL.CUSTID,:OLDVAL.CUSTID));
        INSERT INTO AFTEMPLATES (AUTOID, CUSTID,TEMPLATE_CODE )
        SELECT SEQ_AFTEMPLATES.NEXTVAL,NVL(:NEWVAL.CUSTID,:OLDVAL.CUSTID) , CODE
        FROM TEMPLATES TP
        WHERE TP.REQUIRE_REGISTER = 'N'
            AND TP.CODE NOT IN (SELECT CODE FROM AFTEMPLATES WHERE NVL(:NEWVAL.CUSTID,:OLDVAL.CUSTID) = CUSTID) ;*/
        --LOG TRIGGER FOR BUFFER IF MODIFY ADVANCEDLINE
        IF :NEWVAL.STATUS ='A' OR :OLDVAL.STATUS = 'P' THEN
       --      UPDATE EMAILLOG SET STATUS ='A',EMAIL=:NEWVAL.MOBILESMS WHERE STATUS ='P' AND AFACCTNO = :NEWVAL.CUSTODYCD AND TEMPLATEID ='101S';
             UPDATE EMAILLOG SET STATUS ='A',EMAIL=:NEWVAL.EMAIL WHERE STATUS ='P' AND AFACCTNO = :NEWVAL.CUSTODYCD AND TEMPLATEID ='100E';
        END IF;
        
        --11/02/2015 TruongLD Add --> Neu doi careby tai khoan --> doi careby tieu khoan luon
        IF :NEWVAL.CAREBY <> :OLDVAL.CAREBY AND :OLDVAL.CUSTODYCD NOT LIKE '022P%' THEN
            Update afmast set CAREBY = :NEWVAL.CAREBY where custid = :NEWVAL.custid ;
        END IF;
        
        If :NEWVAL.IDCODE <> :OLDVAL.IDCODE Then
            Update CFOTHERACC set IDCODE = :NEWVAL.IDCODE where cfcustid = :NEWVAL.custid;
        End IF;
        
        If :NEWVAL.IDDATE <> :OLDVAL.IDDATE Then
            Update CFOTHERACC set IDDATE = :NEWVAL.IDDATE where cfcustid = :NEWVAL.custid;
        End IF;
        -- End TruongLD
        --END LOG TRIGGER FOR BUFFER
    -- END IF;
END;
/
