SET DEFINE OFF;
CREATE OR REPLACE TRIGGER TRG_GRMAST_BEFORE 
 BEFORE
  INSERT OR UPDATE
 ON grmast
REFERENCING NEW AS NEWVAL OLD AS OLDVAL
 FOR EACH ROW
DISABLE
begin
:NEWVAL.last_change:= SYSTIMESTAMP;
END;
/
