SET DEFINE OFF;
CREATE OR REPLACE TRIGGER TRG_AFMAST_BEFORE 
 BEFORE
  INSERT OR UPDATE
 ON afmast
REFERENCING NEW AS NEWVAL OLD AS OLDVAL
 FOR EACH ROW
DISABLE
BEGIN
:NEWVAL.LAST_CHANGE:= SYSTIMESTAMP;
END;
/
