SET DEFINE OFF;
CREATE OR REPLACE TRIGGER trg_tlprofiles_after
 AFTER
  INSERT OR UPDATE
 ON tlprofiles
REFERENCING NEW AS NEWVAL OLD AS OLDVAL
 FOR EACH ROW
DECLARE
    L_CLIENTID VARCHAR2(50);
BEGIN
    IF :NEWVAL.USERID IS NOT NULL AND :NEWVAL.ACCESSTOKEN IS NOT NULL AND :OLDVAL.ACCESSTOKEN <> :NEWVAL.ACCESSTOKEN THEN
        BEGIN
            SELECT VARVALUE INTO L_CLIENTID FROM SYSVAR WHERE VARNAME = 'ClientIdMicrosoft';
        EXCEPTION WHEN OTHERS THEN
            L_CLIENTID := 'ERROR_GET_CLIENTID';
        END;

        INSERT INTO TLPROFILES_REQ_EXCHANGETOKEN(AUTOID, CLIENTID, TLID, USERID, ACCESSTOKEN)
        VALUES (SEQ_TLPROFILES_REQ_EXCHANGETOKEN.NEXTVAL, L_CLIENTID, :NEWVAL.TLID, :NEWVAL.USERID, :NEWVAL.ACCESSTOKEN);
    END IF;
EXCEPTION WHEN OTHERS THEN
    PLOG.ERROR ('TRG_TLPROFILES_AFTER ERR:' || SQLERRM || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END;
/
