SET DEFINE OFF;
CREATE OR REPLACE TRIGGER TRG_CRBTXREQDTL_BEFORE 
 BEFORE
  INSERT
 ON crbtxreqdtl
REFERENCING NEW AS NEWVAL OLD AS OLD
 FOR EACH ROW
DECLARE
    V_AUTOID NUMBER(30);
BEGIN

    SELECT TO_NUMBER(TO_CHAR(SYSDATE,'RRRRMMDD') || '999999' || :NEWVAL.REQID)
    INTO V_AUTOID
    FROM DUAL;

    :NEWVAL.REQID := V_AUTOID;

END;
/
