SET DEFINE OFF;

DELETE FROM FLDVAL WHERE 1 = 1 AND NVL(OBJNAME,'NULL') = NVL('2245','NULL');

Insert into FLDVAL
   (FLDNAME, OBJNAME, ODRNUM, VALTYPE, OPERATOR, VALEXP, VALEXP2, ERRMSG, EN_ERRMSG, TAGFIELD, TAGVALUE, CHKLEV)
 Values
   ('12', '2245', 0, 'E', 'EX', '06++10', NULL, NULL, NULL, NULL, NULL, 0);
Insert into FLDVAL
   (FLDNAME, OBJNAME, ODRNUM, VALTYPE, OPERATOR, VALEXP, VALEXP2, ERRMSG, EN_ERRMSG, TAGFIELD, TAGVALUE, CHKLEV)
 Values
   ('05', '2245', 1, 'E', '&&', '04&&01', NULL, NULL, NULL, NULL, NULL, 0);
Insert into FLDVAL
   (FLDNAME, OBJNAME, ODRNUM, VALTYPE, OPERATOR, VALEXP, VALEXP2, ERRMSG, EN_ERRMSG, TAGFIELD, TAGVALUE, CHKLEV)
 Values
   ('15', '2245', 2, 'E', 'FX', 'FN_CIGETDEPOFEEAMT', '04##01##BD##TD##12', NULL, NULL, NULL, NULL, 0);
Insert into FLDVAL
   (FLDNAME, OBJNAME, ODRNUM, VALTYPE, OPERATOR, VALEXP, VALEXP2, ERRMSG, EN_ERRMSG, TAGFIELD, TAGVALUE, CHKLEV)
 Values
   ('13', '2245', 3, 'E', 'FX', 'FN_CIGETDEPOFEEACR', '04##01##BD##TD##12', NULL, NULL, NULL, NULL, 0);
Insert into FLDVAL
   (FLDNAME, OBJNAME, ODRNUM, VALTYPE, OPERATOR, VALEXP, VALEXP2, ERRMSG, EN_ERRMSG, TAGFIELD, TAGVALUE, CHKLEV)
 Values
   ('12', '2245', 6, 'V', '>>', '@0', NULL, 'Tổng số lượng phải lớn hơn 0', 'Total quantity must be greater than zero', NULL, NULL, 0);
Insert into FLDVAL
   (FLDNAME, OBJNAME, ODRNUM, VALTYPE, OPERATOR, VALEXP, VALEXP2, ERRMSG, EN_ERRMSG, TAGFIELD, TAGVALUE, CHKLEV)
 Values
   ('68', '2245', 11, 'E', 'FX', 'fn_get_SYMBOL', '01', NULL, NULL, NULL, NULL, 0);
Insert into FLDVAL
   (FLDNAME, OBJNAME, ODRNUM, VALTYPE, OPERATOR, VALEXP, VALEXP2, ERRMSG, EN_ERRMSG, TAGFIELD, TAGVALUE, CHKLEV)
 Values
   ('69', '2245', 11, 'E', 'FX', 'fn_get_FULLNAME_SYMBOL', '01', NULL, NULL, NULL, NULL, 0);
Insert into FLDVAL
   (FLDNAME, OBJNAME, ODRNUM, VALTYPE, OPERATOR, VALEXP, VALEXP2, ERRMSG, EN_ERRMSG, TAGFIELD, TAGVALUE, CHKLEV)
 Values
   ('10', '2245', 7, 'I', 'FX', 'fn_is_only_input_TDCN_or_HCCN', '10##06', 'Không thể nhập hai loại chứng khoán cùng lúc', 'Cannot input two types of securities at the same time', NULL, NULL, 0);
COMMIT;
